### ISSUE TITLE
grunt serve:dist produces unexpected (replicated) <i> artifacts in html

### ISSUE THREAD

**Issue by davehorton** [angular-fullstack/generator-angular-fullstack#1068]
This is very strange, and I don't know exactly what is going wrong.  I have a build that works fine when I run 'grunt serve' (i.e. development mode).  If I run grunt serve:dist (or do a grunt build and then run NODE_ENV=production node dist/server/app.js) I get strange issues where 'i' tags that I have within ng-repeat sections get replicated outside of the those sections (in addition to appearing where they are supposed to be).  I was using these 'i' elements to hold some glyphicon classes. 

Again, when I run 'grunt serve', no problems.  

For now I have simply eliminated my use of the 'i' tag and used 'span' instead, but wondering if this rings a bell with anyone

**Comment by Awk34** [comment]
Show code?

**Comment by sreevisakh** [comment]
The same problem happened to me once when I forgot to close my <i> tag. It
worked fine in serve but failed in dist

**Comment by Awk34** [comment]
Closed due to inactivity
