### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by peterwarbo** [angular-fullstack/generator-angular-fullstack#1088]
So right now in the generator the jwt is set to expire after 5 hours... this makes UX bad having to login every 5 hours.

There is an npm package (https://www.npmjs.com/package/passport-oauth2-refresh) that should refresh the token but I'm not sure on what way to use it best in conjuction with the generator.

I read on SO (http://stackoverflow.com/a/26834685/294661) that the best approach would be to set the token expiration to 1 week, refresh the token every time the user opens the web app, and every one hour. If a user doesn't open the application for more than a week, they will have to login again and this is acceptable web application UX. Great guidelines (I think) but I'm not sure on how to implement them together with passport-oauth2-refresh and generator-angular-fullstack.

What do you think of this? Has anyone done something similar?

**Comment by kingcody** [comment]
I agree, there could definitely be some improvements in this area.

**Comment by Toub** [comment]
+1 refresh support is required for this generator

If user checks a "reminder me" box while login, expiration date can be long (1 week), else it has to be short and renewed often.

**Comment by zack9433** [comment]
:+1:

**Comment by flaurian** [comment]
Maybe this can help? I have gathered from various sources my token management system. 
First approach (front side, very simple) to keep users logged in for a long period of time (6 months in this example).

In Auth.service change the lines
`$cookies.put('token', res.data.token);`
to
`var now = new $window.Date(),`
`exp = new $window.Date(now.getFullYear(), now.getMonth()+6, now.getDate());`
`$cookies.put('token', res.data.token, {expires: exp});`

This way the user can close the browser and it still remembers him.

Second approach (back & front side) to refresh the token when expired:

In auth.service edit the first block of the isAuthenticated function like this:
`...`
`if (req.query && req.query.hasOwnProperty('access_token')) {`
`req.headers.authorization = 'Bearer ' + req.query.access_token;`
`      }`
`      var token = _.clone(req.headers.authorization);`
`      if (token) {`
`        token = token.replace(new RegExp('Bearer ', 'g'), '');`
`        try {`
`          var profile = jwt.verify(token, config.secrets.session);`
`        } catch(err) {`
`          if (err.name == 'TokenExpiredError') {`
`            var decoded = jwt.decode(token, {complete: true});`
`              var refreshed_token = signToken(decoded._id, decoded.role);`
`              req.headers.authorization = 'Bearer ' + refreshed_token;`
`              res.cookie('token', refreshed_token);`
`          };`
`        };`
`      };`
`      validateJwt(req, res, next);`
`...`

Then in the interceptor.service.js file add a response function to the authInterceptor:

`response: function(response) {`
`        //if you get a token back in your response you can use `
`        //the response interceptor to update the token in the `
`        //stored in the cookie`
`        if (response.config.headers.Authorization) {`
`            //fetch token`
`            var token=response.config.headers.Authorization;`
`            token = token.replace(new RegExp('Bearer ', 'g'), '');`
`            var now = new $window.Date(),`
`            exp = new $window.Date(now.getFullYear(), now.getMonth()+6, now.getDate());`
`            $cookies.put('token', $cookies.get('token'), {expires: exp});`
`    }, `

I would be happy to have feedback on this. In my case I want my users to authenticate as less as possible. So I use the first approach which is a good compromise between logging in as rarely as possible, but still doing it from time to time.

PS sorry for the bad code indentation, I tried the 4 spaces but didn't get it to work.

**Comment by Toub** [comment]
Thanks for your feedback.

To format your code, use GitHub flavored markdown syntax:
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
