### ISSUE TITLE
Question: Guide for creating offline web apps

### ISSUE THREAD

**Issue by imcoddy** [angular-fullstack/generator-angular-fullstack#1101]
Hi

Maybe this is a bit dumb but I just want to ask if anyone knows.

Is there any generator for creating MANIFEST file for creating an offline webapp in this project?

I notice that when deploy to heroku, a folder named dest will be created and the static files will be renamed as well, which is a bit messy when trying to create the MANIFEST file for offline support.

I wonder if others also faced this same problem already and will appreciate if they share their solution, thanks in advance :)

**Comment by kingcody** [comment]
https://github.com/gunta/grunt-manifest
Basic config (`Gruntfile.js`):
```javascript
...
    manifest: {
      dist: {
        options: {
          basePath: 'dist/public'
        },
        src: ['app/*.{js,css}'],
        dest: 'dist/public/manifest.appcache'
      }
    },
...
```

Then you can add `manifest:dist` to the end of the [`build` task array](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/Gruntfile.js#L850-L869).

**Comment by imcoddy** [comment]
Thanks kingcody, I will have a look into it.

**Comment by kingcody** [comment]
@imcoddy if you don't mind, let us know how that works out for you.

**Comment by imcoddy** [comment]
Here is the update (in progress).
After installing the grunt-manifest, I added the following 

```javascript
    manifest: {
      dist: {
        options: {
          basePath: 'dist/public'
        },
        src: ['app/*.{js,css}', 'assets/images/*.{jpg,jpeg,png}'],
        dest: 'dist/public/manifest.appcache'
      }
    },
```
and then added ```manifest:dist``` to the end of the build task array as suggested.

The build task can run without problems, and the manifest file is generated as expected.

```sh
> cat manifest.appcache
CACHE MANIFEST
# This manifest was generated by grunt-manifest HTML5 Cache Manifest Generator
# Time: Mon Jul 27 2015 11:43:26 GMT+0900 (JST)

CACHE:
app/28a5c7d3.vendor.css
app/4b2244eb.vendor.js
app/7e6f893e.app.css
app/803edab3.app.js
assets/images/ad3b56bc.bitcoin.png
assets/images/d535427a.yeoman.png

NETWORK:
*
```

The problem is, I am not quite sure how to add the bower packages into the manifest file as well.

```sh
> tree -L 2
.
├── app
│   ├── 28a5c7d3.vendor.css
│   ├── 4b2244eb.vendor.js
│   ├── 7e6f893e.app.css
│   └── 803edab3.app.js
├── apple-touch-icon.png
├── assets
│   └── images
├── bower_components
│   ├── add-to-homescreen
│   ├── angular
│   ├── angular-bootstrap
│   ├── angular-cookies
│   ├── angular-dynamic-locale
│   ├── angular-gettext
│   ├── angular-i18n
│   ├── angular-mocks
│   ├── angular-qrcode
│   ├── angular-resource
│   ├── angular-sanitize
│   ├── angular-scenario
│   ├── angular-socket-io
│   ├── angular-translate
│   ├── angular-translate-handler-log
│   ├── angular-translate-loader-partial
│   ├── angular-translate-loader-static-files
│   ├── angular-translate-storage-cookie
│   ├── angular-translate-storage-local
│   ├── angular-ui-router
│   ├── bitcore
│   ├── bootstrap
│   ├── bootstrap-sass-official
│   ├── crypto-js
│   ├── es5-shim
│   ├── font-awesome
│   ├── jquery
│   ├── json3
│   ├── lodash
│   └── qrcode-generator
├── favicon.ico
├── index.html
├── manifest.appcache
└── robots.txt

34 directories, 9 files
```

For example, in the ```dist/public/bower_components/angular-bootstrap``` folder there is some min files I think we should include:
```sh
> ls
bower.json               ui-bootstrap-tpls.js     ui-bootstrap-tpls.min.js ui-bootstrap.js          ui-bootstrap.min.js
```

And there are some other bower packages which don't have the minified fils but the full source code.

So now the problem becomes: how to config to put the bower packages files into manifest as well?

**Comment by kingcody** [comment]
@imcoddy this will depend on the use case, but as far as the `bower_components` files you mentioned they have been minified and concatenated into `4b2244eb.vendor.js`. The reason we copy the `bower_components` folder over is that some components will include fonts, images, or other assets that aren't handled by `usemin`.

**Comment by imcoddy** [comment]
@kingcody Oh i see. So that means the js files provided by ```bower_components``` will already be in the ```vendor.js``` file right? Didn't know that.

Just another thing come up: files in the ```dist``` folder will be generated after the ```build``` task being executed, I think this is good when deploy, but when in the ```development``` mode and want to test to see if it works, this method won't help, unless you create a manifest file and include the ```bower_components``` manually, as there is no packed ```vendor.js``` files yet.

Did I miss something here?  Or is there any good practise to test offline feature in while developing it?

**Comment by kingcody** [comment]
Then perhaps add an additional target to your `manifest` config:
```diff
    manifest: {
+     dev: {
+       options: {
+         basePath: 'public'
+       },
+       src: [
+         '{app,components}/**/*.{js,css}',
+         'assets/images/*.{jpg,jpeg,png}',
+         'bower_components/**/*.js',
+       ],
+       dest: 'public/manifest.appcache'
+     },
      dist: {
        options: {
          basePath: 'dist/public'
        },
        src: [
          'app/*.{js,css}',
          'assets/images/*.{jpg,jpeg,png}'
        ],
        dest: 'dist/public/manifest.appcache'
      }
    },
```

**Comment by imcoddy** [comment]
Yeah I just think of that. Thanks for the help, and I will let you know if it works out as expected :)
