### ISSUE TITLE
Question: Session is short on mobile browsers

### ISSUE THREAD

**Issue by christiansakai** [angular-fullstack/generator-angular-fullstack#1107]
Hi,

I have a question.  When I login using a mobile browser, be it Safari iOS or Chrome Android, the session is pretty short, compared to desktop browser (Chrome).  I am wondering what is causing it? Because I made the session to live about 30 months on the backend side.

Thanks

**Comment by kingcody** [comment]
It shouldn't be any different... Are you running the server in development or production mode?

**Comment by Awk34** [comment]
Closed due to inactivity
