### ISSUE TITLE
Complying to style guide

### ISSUE THREAD

**Issue by remicastaing** [angular-fullstack/generator-angular-fullstack#1119]
Is there any need to modify the generator and the [component generator](https://github.com/DaftMonk/generator-ng-component) to comply to [John Papa Angular Style Guide](https://github.com/johnpapa/angular-styleguide)?

**Comment by Awk34** [comment]
It would probably be a good idea ;D

**Comment by remicastaing** [comment]
I started with the .js files of the component generator.

I leave the .coffee files to someone accustomed with coffescript.
