### ISSUE TITLE
Heroku Buildpack for Angular-Fullstack

### ISSUE THREAD

**Issue by austinkettner** [angular-fullstack/generator-angular-fullstack#1121]
I can't seem to find a suitable existing buildpack for Angular-Fullstack anywhere, as such I wanted to post here and see if anyone has made one or knows of one that can be used to seamlessly deploy Angular-Fullstack to Heroku from Github.

**Comment by austinkettner** [comment]
Still looking for something in this buildpack department. Anyone know of any on Github? Or would be willing to pay for one, if someone is interested on that front, let me know.

**Comment by Awk34** [comment]
Closed due to inactivity
