### ISSUE TITLE
Tutorial or Documentation

### ISSUE THREAD

**Issue by jjgonver** [angular-fullstack/generator-angular-fullstack#1137]
There is a tutorial or documentation to personalize the result of the generator-angular-fullstack?
Thanks

**Comment by Awk34** [comment]
No, but I've heard interest in it before from @maryampashmi . I'd like to get there eventually.

**Comment by teslaji** [comment]
It would be great if somebody do this ! thanks

**Comment by amejiarosario** [comment]
I'm writing a book "Building e-Commerce Apps with MEAN" and I'm using/explaining how to use most of the `generator-angular-fullstack` generated code...

**Comment by kingcody** [comment]
@amejiarosario that's awesome! Please keep us posted.

**Comment by amejiarosario** [comment]
@kingcody sure!

**Comment by jeffbuhrt** [comment]
@amejiarosario This isn't your book is it: https://www.safaribooksonline.com/library/view/building-an-e-commerce/9781785286551/ ?

**Comment by amejiarosario** [comment]
Yes @jeffbuhrt, that's my book. I forgot to update here, thanks :)

It explains in depth generator-angular-fullstack 3.x.x, it's components and more while a e-commerce app is built

It's also available on:

Amazon: http://www.amazon.com/Building-e-Commerce-Application-Adrian-Mejia/dp/1785286552/

And

https://www.packtpub.com/web-development/building-e-commerce-application-mean

**Comment by Awk34** [comment]
https://angular-fullstack.github.io
