### ISSUE TITLE
Protractor and tests database cleaner

### ISSUE THREAD

**Issue by amejiarosario** [angular-fullstack/generator-angular-fullstack#1146]
What's the best way to clean the database before each protractor test suite run?? Data in forms start to pile up from old tests and it makes recent tests to fail...

The same happens to my unit tests, I have to manually drop collections... I think this a very common problem, is there a way to automate this in the current workflow or is missing?

**Comment by Awk34** [comment]
`require('./config/seed');` will run `seed.js` to re-seed your dev database

**Comment by amejiarosario** [comment]
For the dev database seeds are fine. However, Protractor is running in the test database and it should be in blank (no seeds or leftovers from previous runs)

I ended up adding a new config called `cleanDB: true` use very similar `seedDB: true`. That way we can clean a database in a given environment (e.g. test).

Would you like a pull request with this feature?
https://github.com/amejiarosario/meanshop/commit/23cf2e29c3c9e5e93a5461a6a0435fe08250b4c1

**Comment by Awk34** [comment]
go for it :D

**Comment by Awk34** [comment]
Closed due to inactivity
