### ISSUE TITLE
Integration with Appcelerator/Titanium webview

### ISSUE THREAD

**Issue by ashishbajaj99** [angular-fullstack/generator-angular-fullstack#1183]
Not really an issue as much as a feature request. Just needed to ask if someone has experience on this forum integrating the output of this generator with Titanium and webview so that we can deploy an offline application on a cell phone?

If there folks with already some experience around this, I'd be happy to work with you and create a PR to extend on the deploy versions (similar to openshift/heroku). The added functionality is one where the client folder can be wrapped into a cell phone app using the titanium webview capability.

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by Awk34** [comment]
Closed due to inactivity
