### ISSUE TITLE
Passing Google's accessToken to the client

### ISSUE THREAD

**Issue by dutzi** [angular-fullstack/generator-angular-fullstack#1187]
Hey,

I am trying to make API calls to YouTube's data API and being the lazy bastard I am I just tried to guesswork a solution, burning way too much time on this.

The app I'm working on tries to make a POST request to Youtube API (you can see the code [here](https://github.com/dutzi/youtube-comment/blob/master/client/app/watch/watch.controller.js#L263)). Google requires I send the access token it provided passport when the user logged in. That token should be part of the "Authorization: Bearer &lt;token&gt;" header.

Doing some reverse engineering, I found that this access token is [here](https://github.com/dutzi/youtube-comment/blob/master/server/auth/google/passport.js#L11).

My questions are:

1. Am I getting something wrong here? If the user logs in using his Google account, shouldn't he be able to make requests to Google's API?
2. Is there any reason why I shouldn't expose that token to the client?
3. If there aren't any, how would I expose it? What would be the best way?

Thanks!

**Comment by Awk34** [comment]
Never provide your server secrets to a client, but you should be able to intercept the OAuth data for a client on the client-side
