### ISSUE TITLE
Query in Socket.io

### ISSUE THREAD

**Issue by andershagebakken** [angular-fullstack/generator-angular-fullstack#1195]
Hi. My question is simple. How can I for instance make a route called "/chat", and include socket.io in that  chatController? I know how to make the route, but how do I get socket implemented in that controller, and how to I add a query parameter to the connection? Thank you so much.

**Comment by kingcody** [comment]
[Here](https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/client/components/socket%28socketio%29/socket.service%28js%29.js#L10) is a commented out example of setting a query param for `socket.io`.

[Here](https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/app/templates/client/app/main/main.controller%28js%29.js#L9) is an example using the `socket` service to `syncUpdates` with the model.

**Comment by andershagebakken** [comment]
Thank you. Is there any way I can set the query string based on GET parameters? For instance /chat?roomID=11 will produce query: 'roomID' : 11?

**Comment by kingcody** [comment]
`query: 'roomID=11'`

**Comment by andershagebakken** [comment]
Yes, but is there a way of getting the roomID based on the GET parameter? For instance as :'roomID='getURLparameter?

**Comment by kingcody** [comment]
Depends, are you using `ng-route` or `ui-router`?

**Comment by andershagebakken** [comment]
ng-router. Thanks for your help.

**Comment by kingcody** [comment]
`query: 'roomID=' + $routeParams.roomID`

**Comment by andershagebakken** [comment]
There we go. Thank you very much!

**Comment by kingcody** [comment]
@andershagebakken sure thing (:

**Comment by andershagebakken** [comment]
I'll continue on this issue, rather than opening a new one. Is there any way I can add the currentUser._id to the query? I can get it asynchronously, but then the user_id is undefined when I do this: "query: 'user_id='+user_id". Thanks in advance.

**Comment by Awk34** [comment]
Closed due to inactivity
