### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by itrethan** [angular-fullstack/generator-angular-fullstack#1196]
One issue with angularjs is the initial load time, webpack helps module the application and loads scrips on demand.

Angular 2 will have build in support for module. However, it seems that the angular community is pretty upset about the up coming version. So webpack is still preferred is this project plans to stick to angularjs

**Comment by leonardoanalista** [comment]
Webpack support would be nice. You would have to run front and back end code in separate processes. Webpack in one terminal, grunt to start up node in another, which is fine in my opinion. 
I am using webpack in a large project and the re-compile in-memory time worths it.

**Comment by thinq4yourself** [comment]
Webpack/Browserfy would be amazing :+1:

**Comment by brownish** [comment]
+1

**Comment by Awk34** [comment]
I'm hoping to get initial support for Webpack in a 3.3.0 beta release

**Comment by gazzwi86** [comment]
+1

This would be awesome.  I was just reading up on Webpack 2 and feel that may be favoured - https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233#.yqcdl65p1

**Comment by itrethan** [comment]
Since angular2 will have lazy loading with native support. I am not sure if
it's still meaningful to have it.

**Comment by Awk34** [comment]
### Remaining Tasks
 - [ ] Make sure it works without CSS transpilers
 - [ ] Fix E2E tests in CI
 - [ ] 
 - [ ] 
 - [ ]
