### ISSUE TITLE
Bootstrap 4 is out!

### ISSUE THREAD

**Issue by amejiarosario** [angular-fullstack/generator-angular-fullstack#1216]
It will be nice to start migrating to the latest and shiniest Bootstrap.

http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha

**Comment by Awk34** [comment]
![1358477726878](https://cloud.githubusercontent.com/assets/5545474/9524984/ce4d0146-4caf-11e5-8ee4-2160015dec28.gif)

**Comment by Awk34** [comment]
I'm going to close this. Bootstrap 4 still isn't actually out. We'll wait for it to really get released before updating
