### ISSUE TITLE
Use Gulp for generator

### ISSUE THREAD

**Issue by Awk34** [angular-fullstack/generator-angular-fullstack#1269]
I'd like to investigate whether using Gulp for the generator build tool would be better than Grunt for our work flow

**Comment by kingcody** [comment]
As long as we can get task parity, I'm sure it would be a nice fit.

**Comment by loljoho** [comment]
+1

I am personally more than willing to contribute towards this endeavour, albeit a bit unexperienced with contributions in general.  Any additional resources or guidance would be great :)

**Comment by imcoddy** [comment]
Looking forward to see Gulp can be used as an option when init the app :)

**Comment by stefanKuijers** [comment]
Would be a great idea, especially if it means we can break this HUGE grunt file into multiple smaller gulp tasks. I usually store these tasks in a seperate '.gulp' folder, I'm not sure what the conventions are on that but it sure makes the task runner a lot more understandable.

**Comment by lbenie** [comment]
+1
This would be awesome !

**Comment by lvarayut** [comment]
I agree with @stefanKuijers . I would be really nice to support gulp. It's faster than grunt. Moreover, it would be great to break the grunt file into serval small chunks of tasks to be more understandable.

**Comment by gabovanlugo** [comment]
+1 as well.

Looking forward for this too. Would be awesome to have it as an option inside the generator.

**Comment by oriolpuig** [comment]
+1 
I love gulp and it would be a good option!!

**Comment by Kageetai** [comment]
+1
The missing Gulp support is kinda the only thing making me hesitating from using this amazing generator again for my next project :)

**Comment by Awk34** [comment]
@Kageetai This issue is for using Gulp for the generator itself, not the generated project itself, so this issue won't really affect end-users.

I have an incomplete Gulp branch with this PR: #1190 . If you'd like to try it out, check-out the `gulp` branch, `npm install` and `npm link`. You should then be able to run the generator with the ability to generate a semi-complete gulpfile.

**Comment by Kageetai** [comment]
Oh okay, I missunderstood the title then. Are there any other plans on using Gulp for the end user, too?

**Comment by Awk34** [comment]
@Kageetai yes, as I stated in my previous comment, look at #1190 .
