### ISSUE TITLE
"yeoman": "~0.9.6" now "yo": "~1.0.4" ??

### ISSUE THREAD

**Issue by chuckwilliams37** [angular-fullstack/generator-angular-fullstack#13]
I think there's some issues with some missing dependencies now with yeoman 0.9.6, although, yo 1.0.4 seems to work.  I'm still kinda new at this so maybe you could confirm?

from the npm install "npm WARN deprecated yeoman@0.9.6: The Yeoman CLI is deprecated. See http://yeoman.io/migrate.html for more info."

**Comment by funkytaco** [comment]
This happens if you run
`npm install -g yeoman`
instead of
`npm install -g yo`

**Comment by johndrach** [comment]
funkytaco is right. If you install "npm install -g yo" everything is good. If you do "npm install -g yeoman" you get a lot of depreciated errors
