### ISSUE TITLE
Sub-generator for creating modules

### ISSUE THREAD

**Issue by ksambhav** [angular-fullstack/generator-angular-fullstack#1310]
Having a sub-generator to create angular module in the client code will result in better structural code.
Each top level module resides in its own folder(client/app/module-x) and its related components (module-x/routes-xa,routes-xb, module-x/services, module-x/constants,module-x/factory)  inside the folder.

Currently, all components are created using the only top level module.

The existing sub-generators should prompt to choose which module to use for generating the component and place the files in correct folder/hierarchy.

Similar approach is is used in generator-cg-angular.

https://github.com/cgross/generator-cg-angular#directory-layout

**Comment by kingcody** [comment]
@ksambhav that's a great suggestion. This generator uses [`generator-ng-component`](https://github.com/DaftMonk/generator-ng-component) to scaffold all the client-side sub-gen calls. Feel free to submit an issue or PR there, thanks.

**Comment by Awk34** [comment]
I shouldn't try to read issues before I have my morning coffee

**Comment by VaibhavP17** [comment]
I personally like to keep the application modular, and have tried cg-angular generator and I enjoy it. It is a great suggestion. We definitely need to have this feature in this generator.

**Comment by kingcody** [comment]
We're currently working on this for the code generated by this project.

**Comment by verrol** [comment]
+1 Glad to hear this is being worked on. I tied g-angular for a project at my previous company and loved it.

**Comment by ksambhav** [comment]
Do we have a timeline for this change? I am willing to use the generator for my next project. How can I contribute - need guidance on where to start from ( example, blogs ,docs on how to create a generator)

**Comment by Awk34** [comment]
http://yeoman.io/authoring/index.html

**Comment by Awk34** [comment]
This would be for https://github.com/DaftMonk/generator-ng-component
