### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by jjgonver** [angular-fullstack/generator-angular-fullstack#1322]
I'm with versión 3.0.0-rc8.
I generated my app with Google and Facebook login. To configure it I've changed the parameters of ID and SECRET of both in server\config\local.env.js and server\config\environment\index.js.  The problem is that when I login with Google or Facebook account the name user that appear is 'Hello Test User'. Do I need to do something more to configure Social Account?
Thanks

**Comment by b4dtR1p** [comment]
something less...add you ID and your SECRET only in server/config/local.env.js and you'll see that it will work!

**Comment by jjgonver** [comment]
I just make this change and put the ID and SECRET only in the server/config/local.env.js and continue the same error: 'Hello Test User'

**Comment by jjgonver** [comment]
One question about this. Is this a problem of the version 3.0.0-rc8? or I'm making something wrong?

**Comment by Awk34** [comment]
There's nothing wrong with our Passport login for the latest pre-release AFAIK. Once you get your test credentials, all you need to do is add them to the relevant locations in `local.env.sample.js`.

**Comment by jjgonver** [comment]
I'm using local, google and FB account. I've created a Google and FB key. I've modify the server\config\environment\local.env.js to change the FACEBOOK_ID and GOOGLE_ID. And when I try to loging with Google and FB, I can log in the app but in the area where must appear the name of the user appear "Hello Test User". Which can be the problem? Thanks

**Comment by jjgonver** [comment]
Any news about this post?

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by Awk34** [comment]
Sorry about no replies. Have you tried the latest version of the generator?
