### ISSUE TITLE
Running one file for tests.

### ISSUE THREAD

**Issue by nschurmann** [angular-fullstack/generator-angular-fullstack#1340]
For developing would be much nicer to just run a single test file, so the output only display the messages of the current test that you are writing. Is there a tool for that implemented?

**Comment by kingcody** [comment]
You could prefix your testing task in grunt with `newer:`, which would cause only test files that had been changed to be loaded.

**Comment by nschurmann** [comment]
The testing task is grunt test:client or grunt test:server. So if i want to watch is IE:
`grunt test:client watch`

What you say is `grunt newer:test:client watch`?, or make a new grunt task?

**Comment by morganwu277** [comment]
Also having problem of this
