### ISSUE TITLE
grunt breaking some of my bower components

### ISSUE THREAD

**Issue by dolanmiu** [angular-fullstack/generator-angular-fullstack#1345]
I appreciate how grunt concats and minifys my bower_components, it works great......90% of the time.
Some of my bower components don't work when its became a vendor.js file.

Examples of bower components which are broken:
http://lipis.github.io/flag-icon-css/ 
https://github.com/vasyabigi/angular-slick

flag-icon-css cannot find the flag images because links are broken

**Comment by Awk34** [comment]
We solve this by installing the `bower_components` folder into the `dist/client` folder. Which generator version are you using?

**Comment by dolanmiu** [comment]
I'm using version 2.0.13

My bower_components folder is in:

dist/public

**Comment by Awk34** [comment]
I think I misunderstood your question. Do you have console output of where it fails?

**Comment by dolanmiu** [comment]
I drew some pictures to make it more clear:

![untitled3](https://cloud.githubusercontent.com/assets/2917613/10208085/9dcce480-67c8-11e5-88b1-1a204b9d97cb.png)
![untitled4](https://cloud.githubusercontent.com/assets/2917613/10208088/a40a4842-67c8-11e5-928e-3c1942105c69.png)

See? all the paths are all wrong. It ONLY happens when I build. When I am using grunt serve, its fine. 

I am guessing other libraries I use have a similar sort of issue.

**Comment by Awk34** [comment]
Bower will be removed in future versions of the generator
