### ISSUE TITLE
Update Whats New Wiki page

### ISSUE THREAD

**Issue by programming-kid** [angular-fullstack/generator-angular-fullstack#1377]
Hi 
    i have been a long term user of fullstack its been my go to framework, it has saved me countless hours of grunt work while starting new projects, today i returned to  ```generator-angular-fullstack``` after about 6 months and lot has changed we have 3.0.0RC out and it looks like lot of things have changed since ```v2.0.13```

Iit would be really nice to have Whats New Wiki Page list out all new changes in v 3.0.0

Thanks

**Comment by Awk34** [comment]
See #1215
