### ISSUE TITLE
How to avoid automatically changing state to '/login' when home page is opened?

### ISSUE THREAD

**Issue by chenweiyj** [angular-fullstack/generator-angular-fullstack#1379]
I have set `authenticate: false` in the `main` state, however it still goes to `login` state when the home page is opened by first time.

**Comment by mcpDESIGNS** [comment]
The only place I can think of is that there's a `$state.go('login');` in the `app.js` file (in Client).
Maybe do some debugging here, I believe something is taking it here and it's trying to log you in.

        if (next.authenticate) {
			Auth.isLoggedIn(function (loggedIn) {
				if (!loggedIn) {
					event.preventDefault();
					$state.go('login');              // <--- here
				}
			});
		}

**Comment by Awk34** [comment]
@chenweiyj which version of the generator did you scaffold from?

**Comment by chenweiyj** [comment]
@Awk34 the version of the generator I scaffolded from is `2.1.0`. @mcpDESIGNS  Since I added `authenticate: false` in the `main` state as follows, I think the code in `if (next.authenticate)` won't run. However, it does, which confused me.

```
angular.module('myApp')
  .config(function ($stateProvider) {
    $stateProvider
      .state('main', {
        url: '/',
        templateUrl: 'app/main/main.html',
        controller: 'MainCtrl',
        authenticate: false
      });
  });
```

**Comment by Awk34** [comment]
[This](https://github.com/DaftMonk/generator-angular-fullstack/blob/8b3c69f63a6d413deeb40d81183f54e3139c5e37/app/templates/client/app/app(js).js#L31-L42) code is probably what's getting you.
