### ISSUE TITLE
Updating angular-bootstrap to 0.14

### ISSUE THREAD

**Issue by yoshiokatsuneo** [angular-fullstack/generator-angular-fullstack#1393]
The latest angular-bootstrap is 0.14 that added prefix "uib-" to directives.
0.14 is also compatible with 0.13, so updating to 0.14 just works.

Now, because generator-angular-fullstack uses 0.13, we cannot refer the latest ui-bootstrap document but need to find out 0.13 document.

How about upgrading angular-bootstrap to 0.14 ?

**Comment by mcpDESIGNS** [comment]
This would be a good idea, I personally had to update my own because I ran into some strange issues with the modals and scrolling with .13

**Comment by lbenie** [comment]
I also updated my package locally to 0.14 and bootstrap 3.3.6

**Comment by Kageetai** [comment]
Oh mean, this took me a while to figure out why the ui-boostrap directives just wouldn't work. Now it works just fine X-)
