### ISSUE TITLE
OAuth fails when connected to local server from remote host.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [angular-fullstack/generator-angular-fullstack#1396]
OAuth fails when I run server by "grunt serve", and connect to the local node from remote host
(to debug using non-local browsers/OSs).
It is because callback url is set by "(process.env.DOMAIN || '') + '/auth/facebook/callback'" on "server/auth/{facebook,google,twitter}/passport.js", and "DOMAIN" is set to "http://localhost:9000" on server/config/local.env.js .

**Comment by yoshiokatsuneo** [comment]
From https://github.com/DaftMonk/generator-angular-fullstack/pull/1395

**Comment by Awk34** [comment]
I'd suggest using `grunt serve:dist` if you'd like to test the server from a different machine. Or you could just modify your local dev code
