### ISSUE TITLE
Routes doesn't work if they have the same name as a directory within /client

### ISSUE THREAD

**Issue by chillyistkult** [angular-fullstack/generator-angular-fullstack#1411]
I use grunt serve to preview my site and want to establish a state 'app' with the url '/app'. Note: app is also a folder within the client directory.

It does not work because the server somehow tries to access the directory instead of resolving the route. For example a route /assets also doesn't work because there is a assets directory in /client. Does anybody know where I have to look for to resolve this issue?

**Comment by Awk34** [comment]
Is this what you're looking for?
`server/routes.js`
```js
    // All undefined asset or api routes should return a 404
    app.route('/:url(api|auth|components|app|bower_components|assets)/*')
        .get(errors[404]);
```

**Comment by chillyistkult** [comment]
No that just disables the 404 error pages for that routes, but you still can't establish a route with that names.

**Comment by Awk34** [comment]
Closed due to inactivity
