### ISSUE TITLE
Heroku Pipelines

### ISSUE THREAD

**Issue by dolanmiu** [angular-fullstack/generator-angular-fullstack#1429]
I am trying to use the new Heroku Pipelines feature, but wondering how to have multiple 'dist' folders, so I could deploy to multiple targets/apps in the pipeline.

For example, I can have UAT1, UAT2, Dev, and finally a Live server.

Is there a way to use the command: ```yo angular-fullstack:heroku:dist_UAT``` or something? 

Learn more about it here:

https://devcenter.heroku.com/articles/pipelines

**Comment by mcpDESIGNS** [comment]
I'm not positive, but I believe in your case you'd need separate projects that maybe all build into the same `/dist` folder. I'll be looking into this myself shortly so if I figure it out I'll get back to you!

**Comment by dolanmiu** [comment]
I have learnt more about pipelines, you deploy to one development app, and you promote it to Staging/UAT, then promote it to production/live. So you don't need to deploy to multiple environments.

The problem arises when there are multiple developers. Apparently you can deploy to TWO development dynos, then merge them into one Staging/UAT, then promote that to live etc. I'm not too sure how that works

**Comment by bogini** [comment]
@MarkPieszak Did you figure it out? Is it possible to make this work using a single repo?
Maybe by using `postinstall` scripts...
```
"scripts": {
    "postinstall": "bower install; npm install; grunt build",
    "start": "node dist/server/app.js"
  }
```

**Comment by MarkPieszak** [comment]
Yeah basically, I do something along those lines that work. Specific webpack (in my case) bundles/tasks that run and create different dist folders for me to then be able to push live.
