### ISSUE TITLE
Using a controller with modal Service

### ISSUE THREAD

**Issue by Luidog** [angular-fullstack/generator-angular-fullstack#1439]
If this question should be asked in another way I apologize in advance and would appreciate learning how to properly ask a question here. I have followed two previous issues here regarding the modal service that is included in this generator. @kingcody referenced the https://angular-ui.github.io/bootstrap/#/modal in a previous issue and after reading how this modal works I have become a bit more familiar with it. However it seems that I can not add things such as an angular controller to the html in the body of the modal box. I am trying to add buttons and fields to the body of the modal box. It seems as though I can only add plain html. Can anyone point me in the right direction or explain how to do this? Thank You.

**Comment by lbenie** [comment]
@Luidog 
Hi,

A simple way to override the modal html/controller is to add arguments to the openModal function.
I've created a gist to show you : https://gist.github.com/lbenie/0bb722802ed7eb6b28f2.

You simply call the openModal function as so :
myModal = openModal({/*properties*/}, /*modal class*/, /*modal ctrl*/, /*modal template*/,/*modal size*/);

In the gist there's a custom modal that I use. Also if you take a closer look at the modal constructor -> openModal all the arguments have default values.

Cheers mate!
