### ISSUE TITLE
Socket IO Error in Azure Web App

### ISSUE THREAD

**Issue by showmethebitcoin** [angular-fullstack/generator-angular-fullstack#1444]
I'm not a contributor to this project but I wanted to bring this up in case anybody has a similar problem.
I was able to deploy to Azure but I was getting an error in socketio.js -

Socket.IO TypeError: Cannot read property 'address' of undefined 

on this line (48):

socket.address = socket.handshake.address !== null ?
      socket.handshake.address.address + ':' + socket.handshake.address.port :
        process.env.DOMAIN;

I fixed it by changing the line to this:

socket.address = socket.handshake.address ?
      socket.handshake.address.address + ':' + socket.handshake.address.port :
        process.env.DOMAIN;

The fix was to check to see if address is defined rather than null, then to add DOMAIN as a site value (in Azure Web App configuration.) Setting the IP or PORT site values break the entire site (since it's doing something I don't quite understand to hook into express.) The DOMAIN value had to be set to the url of my site, without the http://.

Was this fix correct? Thanks.

**Comment by afgallo** [comment]
I had the same issue and I simply commented out those 3 lines and had it working perfectly.

**Comment by Awk34** [comment]
`null` is falsy so that code change shouldn't change anything
