### ISSUE TITLE
livereload not working?

### ISSUE THREAD

**Issue by MohhamedRafi** [angular-fullstack/generator-angular-fullstack#1452]
So after a livereload the page reloads like it should but it pauses and give this error(warning maybe) in chrome:
 
```javascript
xhr.send(isUndefined(post) ? null : post);
```

I am guessing it from angular but wondering what causing it. I had no trouble with other projects using the generator.

**Comment by Awk34** [comment]
That doesn't look like an error. It looks like code.

**Comment by MohhamedRafi** [comment]
Well mean if it was code it pause my live reload. Chrome is saying that it "paused on that function".

**Comment by Awk34** [comment]
Can you post the full error output?

**Comment by Awk34** [comment]
Closed due to inactivity.
