### ISSUE TITLE
Enable gulp as a generation-time flag

### ISSUE THREAD

**Issue by Awk34** [angular-fullstack/generator-angular-fullstack#1454]
I want to get the gulpfile support in, but it just isn't complete enough yet. I thought of a good solution: Add a `--gulp` flag to the generator. That way users won't be asked if they want Gulp at generation-time, since I don't want to add a very less-than-complete feature to the prompts list, but a user can still use a flag if he/she really wants the gulpfile to be generated.

**Comment by tmundt** [comment]
If I may ask, is GULP support included as described? Could there be another using GULP instead of GRUNT?

**Comment by Awk34** [comment]
@tmundt yes, Gulp support was turned on as a flag in 3.1.0
