### ISSUE TITLE
Is there a way to modify the generator once already a project has been created?

### ISSUE THREAD

**Issue by miguelalche** [angular-fullstack/generator-angular-fullstack#1460]
Hey guys, amazing project! Thanks a lot! 
My question is this: 
I've chosen to use Sass but I've seen it takes to long and I want to change it to simple css. 

Is there a way to update this and the build process without reinstalling the generator?

Thanks in advance!

**Comment by mcpDESIGNS** [comment]
You would have to change multiple css files, as well as npm dev dependencies (remove sass / grunt-sass). Also you'd need to make edits to your grunt file.js to remove the grunt-sass rendering and bundling.

**Comment by Awk34** [comment]
https://stackoverflow.com/questions/18480316/how-to-upgrade-existing-project-scaffolded-with-yeoman
