### ISSUE TITLE
Can I select ES5 OR ES6/7 at the time of generating new project ?

### ISSUE THREAD

**Issue by hb-github** [angular-fullstack/generator-angular-fullstack#1468]
I am very new to ES6/7, so when I generated new project from Version 3 which is latest release all scaffolding code is in ES6. I want new project in ES5 where I can use below syntax:
```
var express= require('express');
````

**Comment by mcpDESIGNS** [comment]
I'm not positive, but I don't know if this is an option unless you use an older version of the generator.

**Comment by hb-github** [comment]
@mcpDESIGNS thanks for the reply. Yes that project is created using latest release version i.e 3.0.2, where its by default generates code in 3.0.2 and I was looking for Font-Awesome Css inside index.html or any where it can be.

But Now I realized that I should go with ES5 instead of ES6 code, so thats why I am looking for this option otherwise I have to use 2.1.1 version for scaffolding new project and may be I will miss those new enhancements which are made in last release.

**Comment by mcpDESIGNS** [comment]
I would honestly just stick with the ES6 and let Babel compile it into ES5 for you, etc.

There isn't *much* ES6 going on yet in the generator, mainly the basic stuff, imports etc

**Comment by Awk34** [comment]
3.0.0+ does not support ES5 syntax. This was not a light decision. You can view part of the public discussion [here](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1281). If you *need* to use ES5, your best bet would probably be to use 2.x.x. I do plan on supporting 2.x.x with fixes, but there will likely not be much new development with it.

The purpose of this generator is to scaffold out a **new** full-stack web application, and the vast majority of brand new full-stack apps will start out with using a transpiler like Babel or TypeScript.
