### ISSUE TITLE
Peer Dependencies

### ISSUE THREAD

**Issue by skstudios** [angular-fullstack/generator-angular-fullstack#1470]
I think that there has to be an added entry in a file somewhere - I saw another module make a change for this.. 

These are some dependency errors/warnings i get:

npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

I'm just too new with the technology to know what to add.

**Comment by Awk34** [comment]
That output is expected, there's currently nothing wrong there
