### ISSUE TITLE
Unit test fails after upgrade bluebird to 3.0.6

### ISSUE THREAD

**Issue by ndjordjevic** [angular-fullstack/generator-angular-fullstack#1471]
```javascript
User Model #password should remain the same hash unless the password is updated:
      TypeError: expecting an array or an iterable object but got [object Null]
      at apiRejection (node_modules/bluebird/js/release/promise.js:10:27)
      at PromiseArray.init [as _init] (node_modules/bluebird/js/release/promise_array.js:62:19)
```

No idea how to fix this test:
```javascript
it('should remain the same hash unless the password is updated', function() {
      user.name = 'Test User';
      return user.saveAsync()
        .spread(function(u) {
          return u.authenticate('password');
        }).should.eventually.be.true;
    });
```

**Comment by Awk34** [comment]
Yes, this has to do with how we `require('bluebird').promisifyAll(require('mongoose'))`. Look at the [Bluebird 3.0.0 Promisification](http://bluebirdjs.com/docs/new-in-bluebird-3.html#promisification-api-changes) changes. You *might* be able to get a quick fix for this by using `require('bluebird').promisifyAll(require('mongoose'), { multiArgs: true })` instead.

I do plan on upgrading the generator to use Bluebird 3.x.x sometime soon. The eventual solution will be to remove the promisification of Mongoose, since Mongoose 4.x.x returns promises now anyway. To fix some issues with the Mongoose promises though, I'll be shimming it with this: `mongoose.Promise = require('bluebird')`.

**Comment by ndjordjevic** [comment]
Doesn't work even with { multiArgs: true }. I removed bluebird promisification and now it's OK.

**Comment by Awk34** [comment]
Yeah, you'd probably also have to change the places that use multi-argument promisified-mongoose promises too.

The best solution is still to use `mongoose.Promise = require('bluebird')` and write proper code conforming to the Promise spec.

I'm going to leave this issue open as a reminder that I need to fix this stuff in the generator when I upgrade Bluebird to 3.x.x.

**Comment by ndjordjevic** [comment]
In my generated app I gave up of bluebird promises at all since mongoose async methods are now return promises. Is there a reason why we we should keep using bluebird with mongoose?

**Comment by Awk34** [comment]
Last time I checked, Mongoose didn't return [Promises/A+](https://promisesaplus.com/)/[ES6](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise-constructor) spec compliant promises. By replacing Mongoose's non-spec-compliant [mpromise](https://github.com/aheckmann/mpromise) with the spec-compliant Bluebird, we make sure that any promise-returning Mongoose functions give us what we expect.

**Comment by ndjordjevic** [comment]
Doc says that now mongoose returns Promises/A+ conformant promises

http://mongoosejs.com/docs/promises.html

**Comment by Awk34** [comment]
Okay, so they might have finally started returning spec-compliant mpromises in all the relevant locations, but I'm still going to keep the generator using Bluebird. mpromise hasn't been updated in over a year, and Bluebird is the best-supported promise implementation. Mongoose even has unit tests for using Bluebird.

**Comment by corporationsruleyourmom** [comment]
This Promisification stuff is a little confusing to get the hang of... Wish the docs were a little easier to understand... It would be nice to see some examples of typical promises, limited/extended promises, search result promises, etc...

**Comment by Awk34** [comment]
#1453

**Comment by volody** [comment]
as noted in bluebirdjs spread help 
> [Note that if using ES6, the above can be replaced with .then()](http://bluebirdjs.com/docs/api/spread.html)

this code should work:

    it('should remain the same hash unless the password is updated', function() {
      user.name = 'Test User';
      return user.saveAsync()
        .then(function(u) {
          return u.authenticate('password');
        }).should.eventually.be.true;
    });
