### ISSUE TITLE
Google Login OAuth fails

### ISSUE THREAD

**Issue by kcampion** [angular-fullstack/generator-angular-fullstack#1474]
After configuring the Google OAuth, when I try to login, I can view the google screen, but after accepting the conditions, I'm redirected to http://localhost:9000/auth/google/callback?code=xxx and this mistake appears: 
```
InternalOAuthError: failed to fetch user profile
   at /Users/me/Documents/Projects/my_project/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
   at passBackControl (/Users/me/Documents/Projects/my_project/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/Users/me/Documents/Projects/my_project/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickCallback (node.js:355:11)
```

Info: my mongo server is well configured because I can login with admin@admin.com
I use the last version of generator-angular-fullstack

**Comment by Awk34** [comment]
I believe this is relevant to your issue: https://github.com/jaredhanson/passport-google-oauth/issues/91

**Comment by kcampion** [comment]
Thank you @Awk34.
To fix this error, you need to enable Google+ Api in Developer Console.
