### ISSUE TITLE
on install app can't use arrow for select function

### ISSUE THREAD

**Issue by bluezip** [angular-fullstack/generator-angular-fullstack#1476]
![2015-12-10_7-39-57](https://cloud.githubusercontent.com/assets/3119129/11703357/454d6fac-9f11-11e5-9611-cc56ef75ead2.png)

i use windows system

**Comment by Awk34** [comment]
Refer to this issue: https://github.com/SBoudrias/Inquirer.js/issues/266

**Comment by bluezip** [comment]
thank you. bug from node.js
mine change node.js version from 4.2.2 --> 5.2.0

**Comment by Awk34** [comment]
Okay, so using Node 5.2.0 made it work for you?

**Comment by RonAlmog** [comment]
i updated to the latest, 5.7.0, and it's not working. i can't make the selection between babel and typescript. arrows not working.

![image](https://cloud.githubusercontent.com/assets/5527427/13417037/f7080022-df35-11e5-9c28-567cabd218b3.png)
