### ISSUE TITLE
imagemin:dist" (imagemin) task Error: spawn optipng.exe ENOENT in file client/assets/images/yeoman.png

### ISSUE THREAD

**Issue by aditya61085** [angular-fullstack/generator-angular-fullstack#1479]
Hi

I just installed angular fullstack latest version and grunt serve worked fine.
grunt build is failing with attached error:

Running "imagemin:dist" (imagemin) task
Warning: Error: spawn C:\00 ADITYA\programming\steptosteps3\node_modules\grunt-contrib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor\optipng.exe ENOENT in file client/assets/images/yeoman.png Use --force to continue.

When I use --force, it build but images are not copied.

Plz help to resolve this issue.

![delete](https://cloud.githubusercontent.com/assets/1188412/11735073/3a62cefa-9f8b-11e5-84fa-871d5c35d3aa.PNG)

**Comment by Awk34** [comment]
Try `npm uninstall grunt-contrib-imagemin` then `npm install grunt-contrib-imagemin`

**Comment by aditya61085** [comment]
Hi Thanks a lot for your reply. But still its failing in same step with different error:

Kindly help please.


![capture](https://cloud.githubusercontent.com/assets/1188412/11769295/06bea794-a1b2-11e5-9ddd-825f5633e716.PNG)

**Comment by Awk34** [comment]
#1382

**Comment by aditya61085** [comment]
Thanks a lot. That worked. 

Butt 1 major issue:
My image file client\assets\images\abc.png now got copied to dist\public\assets\images\04b26038.abc.png
I am able to view it as well from dist.

But when I deploy to heroku then it gives 404 for www.XYV.com/assets/images/abc.png
When I try www.XYV.com/assets/images/04b26038.abc.png, then it doesnt give 404 but doesnt even shows the image. Just an empty small box with border.

Also jpg load fine. Its only happening with pngs.

I know this issue is not related to angular fullstack but would appreciate if you can be of any help.

**Comment by aditya61085** [comment]
![production-capture](https://cloud.githubusercontent.com/assets/1188412/11771185/d8af4998-a1da-11e5-8c39-6499ecc04274.PNG)

**Comment by Awk34** [comment]
@aditya61085 is #802 the same as your issue? If so please continue the discussion there.
