### ISSUE TITLE
Need options to scaffold server only or client only 

### ISSUE THREAD

**Issue by manjeshpv** [angular-fullstack/generator-angular-fullstack#1480]
I love angular-fullstack, I need a small customization.

Sometimes I need only server side  or only client side code & components.

If there is option prompt ask for only server or only client or both

I also trying to do. 

![image](https://cloud.githubusercontent.com/assets/1999957/11736228/685bd106-9ff1-11e5-94d1-c2959cbb0bc1.png)

![image](https://cloud.githubusercontent.com/assets/1999957/11736235/8403a708-9ff1-11e5-9d67-ba5cd076a7bc.png)

```js
stackPrompts: function() {
        if (this.skipConfig) return;
        var cb = this.async();

        this.log('# Stack\n');
        this.prompt([{
          type: 'checkbox',
          name: 'stacks',
          message: 'Select your stack preference?',
          filter: function( val ) { console.log(val); return val },
          choices: [
            {
              value: 'server',
              name: 'Server',
              checked: true
            },
            {
              value: 'client',
              name: 'AngularJS Client',
              checked: false
            }
          ]
        }
        ], function (answer) {
          console.log("stacks answer",answer.stacks)
          if(answer.stacks && answer.stacks.length > 0) {
            answer.stacks.forEach(function(stack) {
              this.filters[stack] = true;
            }.bind(this));
          }
          cb();
        }.bind(this));
      },
```

Now I'm manually separating client and server by generating two projects and deleting the code not required.

**Comment by Awk34** [comment]
I don't think that's really in the scope of this project. It is the full-stack generator after all. There are plenty of other generators that you could use together, such as generator-angular and generator-express. The point of this generator is that both server and client share a single code base. This enables things like a single build tool, combined dev server, code sharing, etc.

**Comment by manjeshpv** [comment]
I understand your point but stability of angular-fullstack  is best among others.

**Comment by Awk34** [comment]
What do you mean by 'stability'? Like the generator itself not breaking, or the generated codebase producing a stable app, or something else?

I'm going to open this back up as I guess there could be more discussion here. One of my other main concerns with this is that it would just add more complexity to the generator, as we would need to support the cases of client only, server only, and full-stack. Excluding client/server folders wouldn't be too hard, but a lot of complexity would have to be added to the grunt/gulp files, and other files, to allow for all three cases.

**Comment by tmundt** [comment]
In my opinion, a fullstack generator should deliver for both client and server, not only one.

**Comment by Awk34** [comment]
closed due to inactivity

**Comment by alokrajiv** [comment]
A server only fork is available here: https://github.com/Liam-Williams/generator-node-express-mongo

But it is way behind in commits against angular-fullstack now.
