### ISSUE TITLE
jshint:all failed

### ISSUE THREAD

**Issue by ivegotwings** [angular-fullstack/generator-angular-fullstack#1485]
PS C:\Users\Shiv\Desktop\WebDev Adventures\PORTFOLIO\MeanApp> grunt
Running "newer:jshint" (newer) task

Running "newer:jshint:server" (newer) task
No newer files to process.

Running "newer:jshint:serverTest" (newer) task
No newer files to process.

Running "newer:jshint:all" (newer) task

Running "jshint:all" (jshint) task

client/components/navbar/navbar.controller.js
  line 14  col 22  '$location' is not defined.
  line 15  col 23  'Auth' is not defined.
  line 16  col 20  'Auth' is not defined.
  line 17  col 27  'Auth' is not defined.
  line 13  col 15  '$locationAuth' is defined but never used.

  ‼  5 warnings

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2015-12-11 14:43:08 UTC)
loading tasks                 669ms  █████████████████████████████ 39%
loading grunt-newer            33ms  ██ 2%
newer:jshint:server            34ms  ██ 2%
newer:jshint:serverTest        27ms  ██ 2%
newer:jshint:all               21ms  █ 1%
loading grunt-contrib-jshint  287ms  █████████████ 17%
jshint:all                    613ms  ███████████████████████████ 36%
Total 1.7s

PS C:\Users\Shiv\Desktop\WebDev Adventures\PORTFOLIO\MeanApp>

**Comment by ivegotwings** [comment]
Change navbar.controller.js to -
constructor($location, Auth) {

**Comment by Awk34** [comment]
This has been fixed in master already
