### ISSUE TITLE
Multiple connections to mongo

### ISSUE THREAD

**Issue by uiktiomasfeliz** [angular-fullstack/generator-angular-fullstack#1486]
What is the correct way to implement mongo multiple connection on angular-fullstack project, manteining structure.

i tried like in example: http://mongoosejs.com/docs/connections.html#multiple_connections

but without success.

Here full question:
http://stackoverflow.com/questions/34225655/multiple-connections-on-angular-fullstack

**Comment by Awk34** [comment]
As this isn't really a question specific to the generator, and more for mongoose, I'm going to close this. I hope you get an answer on your SO question.
