### ISSUE TITLE
Node.js version >4 compatibility issues

### ISSUE THREAD

**Issue by flexpert** [angular-fullstack/generator-angular-fullstack#1487]
Hi,
I'm facing lots of issues after upgrading my local node to v4 (later also to v5).

At the beginning I had issues with ```grunt-node-inspector```, so I bumped up it's version to latest and I had to install xCode 7 so ```node-gyp``` will work.

Now ```npm install``` run without any errors but I can't run grunt ```build``` nor ```serve``` because of this error:
```javascript
jit-grunt: Plugin for the "injector" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings
```

It seems like there isn't anything related to that in the relevant repositories's issues, or event in any other place, am I one of the first who got the chance to face it?

I'm working with OS X 10.11, node version 5.1.0, npm version 3.5.1.

I guess that downgrading node version to 0.12 will do the trick but I really don't want to do it.

Please advice.

**Comment by Awk34** [comment]
`npm install grunt-injector`

**Comment by flexpert** [comment]
thanks, 
yeah, that's work, but somehow the generator omit it from ```package.json```, maybe it was environment issue, still investigating

**Comment by Awk34** [comment]
@flexpert any more info?

**Comment by hb-github** [comment]
I got such type of error too 

```
jit-grunt: Plugin for the "imagemin" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "imagemin" failed. Used --force, continuing.

Done, but with warnings.
```

I have ``` "grunt-contrib-imagemin": "^1.0.0", ``` installed.
