### ISSUE TITLE
OAuth Issue

### ISSUE THREAD

**Issue by jaysig** [angular-fullstack/generator-angular-fullstack#1488]
I tried replacing the app-id & secret but when I press the signin with Facebook or Google+ button it is not being sent with the url. For example it just says client=id. Any suggestions? 

```
module.exports = {
  DOMAIN:           'http://localhost:9000',
  SESSION_SECRET:   'b-secret',
​
  FACEBOOK_ID:      'app-id',
  FACEBOOK_SECRET:  'secret',
​
  TWITTER_ID:       'app-id',
  TWITTER_SECRET:   'secret',
​
  GOOGLE_ID:        'app-id',
  GOOGLE_SECRET:    'secret',
​
  // Control debug level for modules using visionmedia/debug
  DEBUG: ''
};
```

**Comment by Awk34** [comment]
Which file are you adding these to? Hopefully you copied `local.env.sample.js` to `local.env.js`.

Also make sure you've restarted the server. It won't pick up these env vars without restarting. Also, the `local.env.js` file only helps out in dev mode, not production.

**Comment by Awk34** [comment]
Closed due to inactivity.
