### ISSUE TITLE
Launch multiple instances with Grunt

### ISSUE THREAD

**Issue by kcampion** [angular-fullstack/generator-angular-fullstack#1490]
It would be great to have this feature in the next version.

**Problem**
I had this error when I launched multiple instances of different webapps:
```
Running "watch" task
Waiting...
Fatal error: Port 35729 is already in use by another process.
```

**Solution**
The solution is to use a random port number for watch and express' debug. I have only tested it under dev zone. The port number for debug is random, it's possible to have an error because Grunt initializes the same.

Install grunt-openport (https://github.com/shama/grunt-openport)
```
# npm install grunt-openport --save-dev
```

Add "dev_port" and "opts" under dev into Gruntfile.js
```
grunt.initConfig({
    express: {
      options: {
        port: process.env.PORT || 9000
      },
      dev: {
        options: {
          script: 'server/app.js',
          debug: true,
          dev_port: true,
          opts: ['--debug=<%= express.dev.options.dev_port %>']
```

And add all "openport" into the "serve" task:
```
grunt.registerTask('serve', function (target) {
    if (target === 'dist') {
      [...]
    }

    if (target === 'debug') {
      [...]
    }

    grunt.task.run([
      'openport:express.dev.options.dev_port:5860:5960',
      'openport:watch.livereload.options.livereload:35729:36729',
      'openport:watch.express.options.livereload:35729:36729',
      'clean:server',
      [...]
```

Update the file server/config/local.env.js with:
```
module.exports = {
  DOMAIN: 'http://localhost:' + (process.env.PORT || 9000),
```

Now
```
# cd /my_project1 && PORT=9001 grunt serve
# cd /my_project2 && PORT=9002 grunt serve
```

**Comment by Awk34** [comment]
I think a better solution might be to just set the debug ports in the server's grunt config to a random port at generation-time. How does that sound?

**Comment by kcampion** [comment]
What do you mean @Awk34? This is what I do with these modifications.

**Comment by Awk34** [comment]
So the problems here are that the Express server always defaults to port 9000, and livereload uses the default 35729 port. Both of these ports can be set statically. We could randomize the livereload port and dev port when someone runs the generator. That way if you go and scaffold out two different projects, you can `grunt serve` them immediately without modifying anything. This solution would also prefent adding more cruft to the final project.

**Comment by kcampion** [comment]
As you want, I proposed this solution to avoid changing the server's grunt config.

**Comment by Awk34** [comment]
Closing in favor of #957
