### ISSUE TITLE
Can't run sass server

### ISSUE THREAD

**Issue by nelsonlho** [angular-fullstack/generator-angular-fullstack#1491]
Every time I am running grunt I get the following error:  

Running "sass:server" (sass) task
    Warning: Exited with error code 1 Used --force, continuing.

Also get the following messages (no, it's not because I forgot to install the gems)

Total 3.7s/Users/nho/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'sass' (>= 0) among 29 total gem(s) (Gem::LoadError)
    Checked in 'GEM_PATH=/Users/nho/.gem/ruby/2.2.0:/Users/nho/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0', execute `gem env` for more information
    	from /Users/nho/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    	from /Users/nho/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    	from /Users/nho/.rvm/gems/ruby-2.2.1/bin/sass:22:in `<main>'
    	from /Users/nho/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/nho/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

Anyone know what's wrong?

**Comment by Awk34** [comment]
I've never had an issue with Ruby not finding the sass gem. I'd try reinstalling ruby/sass. If that doesn't work, ask the Ruby folks.
