### ISSUE TITLE
 ui-router authentication not work

### ISSUE THREAD

**Issue by hirokoma** [angular-fullstack/generator-angular-fullstack#1492]
Authentication of ui-router doesn't work.

client/app/account/account.js
~~~
      .state('settings', {
        url: '/settings',
        templateUrl: 'app/account/settings/settings.html',
        controller: 'SettingsController',
        controllerAs: 'vm',
        authenticate: true
      });
~~~

When I access http://localhost:9000/settings without a login, the setting page is visible.
![2015-12-14 0 05 26](https://cloud.githubusercontent.com/assets/7194170/11767694/41be7a7c-a1f8-11e5-9819-38d4e84f073b.png)

angular-fullstack: 3.0.2
node: 5.2.0
npm: 3.5.2
OS X: 10.10.3
Chrome: 47.0

**Comment by Awk34** [comment]
*should* be fixed in next version
