### ISSUE TITLE
Setting up Login page as default

### ISSUE THREAD

**Issue by Abdizriel** [angular-fullstack/generator-angular-fullstack#1496]
Hello all,

I want the page login first and not the main, I play with the code and my solution is to add 'authenticate: true' in MainCtrl

I'm trying to set up login page as default when user is not logged. I saw that someone was trying to get the same result here: https://github.com/angular-fullstack/generator-angular-fullstack/issues/1446 but I couldn't find a way to do that with v3.1

I have tried this solutions:

```javascript
} else {
        Auth.isLoggedIn(_.noop).then(is => {
          if(is) {
            return;
          }

          event.preventDefault();
          $state.go('login');
        });
      }
```
with v3.1 but it didn't work.

How I can redirect someone loading my site fresh to login page and when is authorized to go to main page?

**Comment by donvadicastro** [comment]
But why adding 'authenticate: true' to main control is not an option in this case? Perfect way to declare access permission to any page without module customization.

**Comment by Awk34** [comment]
If your question is the same as the other issue, please refrain from opening duplicate questions, and keep the discussion to a single issue.

**Comment by Awk34** [comment]
But to answer your question, one way to detect if a person is loading fresh (with ui-router) is by checking `!fromState || !fromState.name`, as I commented in the other issue.
