### ISSUE TITLE
expiresInMinutes is deprecated for auth.service.js (server)

### ISSUE THREAD

**Issue by kcampion** [angular-fullstack/generator-angular-fullstack#1500]
When I try to login, this error appears in the logs:
```
jsonwebtoken: expiresInMinutes and expiresInSeconds is deprecated.
(/Users/me/Projects/server/auth/auth.service.js:61:16)
Use "expiresIn" expressed in seconds.
```

I suggest to update the file server/auth/auth.service.js at line 59:
```
function signToken(id) {
  return jwt.sign({ _id: id }, config.secrets.session, { expiresInMinutes: 60*5 });
}
```
by
```
function signToken(id) {
  return jwt.sign({ _id: id }, config.secrets.session, { expiresIn: 60*5*60 });
}
```

Just replace "expiresInMinutes" by "expiresIn" and add *60.

**Comment by Awk34** [comment]
Already fixed in 3.1.0: [ecf9014](https://github.com/angular-fullstack/generator-angular-fullstack/commit/ecf9014ee97187c2f091e469c9c4827041c077d0)
