### ISSUE TITLE
Angular-material CSS framework Support?

### ISSUE THREAD

**Issue by abibell** [angular-fullstack/generator-angular-fullstack#1506]
First of all, great job guys, really cool generator.

With Introduction of [Angular-material](https://material.angularjs.org/latest/) and popularity of Google's material design combined with the name of project **angular-fullstack**, what do you think of supporting Angular-material framework on top of Bootstrap?

I am trying to avoid a situation where there are so many combinations of yeoman generators when they should be extra options.

**Comment by Awk34** [comment]
#999
