### ISSUE TITLE
Full Gulp support

### ISSUE THREAD

**Issue by Awk34** [angular-fullstack/generator-angular-fullstack#1512]
Need to test gulpfile and eventually add it as a prompt instead of a flag

**Comment by tmundt** [comment]
Is gulp working? After a fresh generation with angular-fullstack, running "gulp" results in this error:
"Task 'default' is not in your gulpfile"

**Comment by Awk34** [comment]
@tmundt  Yes. It should be almost there. If you simply look at the gulpfile, there isn't a `'default'` task.

**Comment by itswadesh** [comment]
Need to know whether there is any similar command as `grunt:buildcontrol openshift` using gulp

**Comment by Awk34** [comment]
@itswadesh unfortunately not, since I don't know of any similar tool for Gulp. If you know of one, or would like to make one, feel free to submit a PR. If there is enough interest shown, I could possibly port over the tool to Gulp.
