### ISSUE TITLE
angular-fullstack:endpoint not generating Mongoose Model

### ISSUE THREAD

**Issue by bodagetta** [angular-fullstack/generator-angular-fullstack#1514]
I have a project I generated with < 3.0 angular-fullstack and it used Mongoose. I updated my generator and used angular-fullstack:endpoint to generate a new api endpoint.

It did not generate my endpointName.model.js file and there is only one entry in the endpointName.controller.js file for the Index. I'm used to see the typical CRUD in the scaffold. 

Why wasn't a Mongoose Model generated?

**Comment by Awk34** [comment]
There are breaking changes between 2.x.x and 3.0.0, which is entirely expected as we follow semver. If you wish to start using 3.x.x with an existing project, I suggest reading [this SO question](https://stackoverflow.com/questions/18480316/how-to-upgrade-existing-project-scaffolded-with-yeoman) on upgrading a Yeoman-generated project to a new version of the generator.

**Comment by bodagetta** [comment]
Thanks!
