### ISSUE TITLE
Installation issue on Node 5.0

### ISSUE THREAD

**Issue by samuelcastro** [angular-fullstack/generator-angular-fullstack#1515]
I'm getting this issue on Node 5:
```
npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-angular-fullstack/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-environment/package.json'
npm ERR! code 1
```

Any idea?

**Comment by Awk34** [comment]
Looks like it didn't install properly. Try `npm uninstall -g generator-angular-fullstack` and then re-`npm install -g generator-angular-fullstack`.

**Comment by samuelcastro** [comment]
Same thing.
I'm using sudo to install my global modules.

**Comment by samuelcastro** [comment]
Fixed following this:

```
npm config get prefix
sudo chown -R `whoami` <directory>
```

:)

**Comment by Awk34** [comment]
Okay, looks like an improper npm install. The generator doesn't throw the ENOENT error anymore? If so, please close the issue.

**Comment by samuelcastro** [comment]
Sorry my mistake, locally is working, but when I try to install globally (-g), I'm getting this issue.

**Comment by Awk34** [comment]
It might be a problem with npm 3.x.x. Try using npm 2.x.x.

**Comment by Awk34** [comment]
Any news on this?

**Comment by samuelcastro** [comment]
Hi @Awk34, I've fixed installing locally.

Let me try your solution to see what will happen.

**Comment by tylerdmace** [comment]
I've always had issues when not installing NPM/Node via `nvm`. I highly suggest you switch to it! You'll mitigate a lot of strange behavior including permission issues.
