### ISSUE TITLE
Gulp build attempts to run client/index.html through Jade resulting in failure

### ISSUE THREAD

**Issue by jjongsma** [angular-fullstack/generator-angular-fullstack#1517]
When using Jade as the template engine, the Gulp build processes index.html (mainView) with Jade, resulting in a syntax error and build failure. Removed .jade() from the pipeline allows the build to succeed.

**Comment by wangjiaji** [comment]
Simply removing the jade pipe doesn't work, anyone knows how to fix this?

**Comment by drmikeh** [comment]
I manually fixed my project by commenting out the pipe to jade in the build:client task:

return gulp.src(paths.client.mainView)
        /* .pipe(plugins.jade({pretty: true}))           comment out this line */
        .pipe(plugins.useref())

**Comment by gazzwi86** [comment]
I tried much the same, but simply commenting out the line results in the build not containing the index.html though.

**Comment by gazzwi86** [comment]
Ok, got some progress.  Looks like a filter wasn't closed correctly.  Removing
   ```.pipe(plugins.jade({pretty: true})) ```
line and also adding after
  ```.pipe(assetsFilter)```
the following
  ```.pipe(assetsFilter.restore())```

**Comment by gazzwi86** [comment]
I have for the moment gone with removing the build revision numbers on image assets in the copy:images task

**Comment by drmikeh** [comment]
After removing jade step from index.html and adding the ".pipe(assetsFilter.restore())" there are still errors with the partials (navbar.html, footer.html, etc.) not getting added to Angular's templateCache.

**Comment by Awk34** [comment]
This should be fixed with https://github.com/angular-fullstack/generator-angular-fullstack/commit/687cd09fdd9a66b9230b865083288b79e246ca86
