### ISSUE TITLE
Angular injection declaration

### ISSUE THREAD

**Issue by JosselinTD** [angular-fullstack/generator-angular-fullstack#1519]
Hi ! I use Angular Fullstack for 1 week now and I have a question :
Why the injection in controller, directive, service, etc... are declared without the "extended" version ?
# Example here :
## Current version :

    angular.module('app.admin')
    .controller('AdminController', AdminController);

## "Extended" version :

    angular.module('app.admin')
    .controller('AdminController', ["User", AdminController]);

I understand while learning Angular that the "extending" version was better, for example for minification.

**Comment by Awk34** [comment]
The generator uses [ng-annotate](https://github.com/olov/ng-annotate) to automatically provide the dependency array, so that *you* don't have to.
