### ISSUE TITLE
Heroku Error: ENOENT, open '/app/public/favicon.ico'

### ISSUE THREAD

**Issue by CodisRedding** [angular-fullstack/generator-angular-fullstack#152]
I've deployed my dist dir to heroku but the process log is showing me this error: Error: ENOENT, open '/app/public/favicon.ico'. Why would it be referencing app? 

I jumped on the heroku box, and poked around to make sure that the dist dir infact was deployed correctly but I cannot seem to see anything odd.  

Also if I run this locally with grunt serve:dist it works fine.

Any suggestions?

**Comment by ArdentKid** [comment]
+1
using grunt serve:dist works for me, but after deploying to heroku I get Error: ENOENT, open '/app/public/favicon.ico'

If I remove favicon dependency from server/config/express.js then I get Error: ENOENT, stat '/app/public/index.html'

**Comment by chinnichaitanya** [comment]
@ArdentKid Just replace the *favicon.ico* with some other *.ico* image and don't remove the dependency in config files. That worked for me.

**Comment by ibarrajo** [comment]
I feel the `config.root` variable is wrong, after printing out the variable, in Heroku as well as Dokku, the path to favicon.ico is different.

Local machine running as production:
`/home/josue/Projects/xxxxx/dist/public/favicon.ico`

On Dokku with `NODE_ENV=production`:
`/app/public/favicon.ico`

**Comment by kawashimaken** [comment]
Same here with @ArdentKid
