### ISSUE TITLE
Angular, lost of reference on update

### ISSUE THREAD

**Issue by JosselinTD** [angular-fullstack/generator-angular-fullstack#1520]
Hi ! In the socket component for the client app, here the code on an update :

    if (oldItem) {
        array.splice(index, 1, item);
        event = 'updated';
    }

Doesn't this imply a loss of reference on the item ?
Something like this isn't better ?

    if (oldItem) {
        _.extend(oldItem, newItem);
        event = 'updated';
    }

**Comment by Awk34** [comment]
Yes, if we find an item with the same ID as the one being inserted, the old one is removed and garbage collected. This would probably only be the case for an update event.
