### ISSUE TITLE
grunt serve:dist problem angularJs route already defined

### ISSUE THREAD

**Issue by aashish004** [angular-fullstack/generator-angular-fullstack#1527]
I am running version 3.1.1. When I try to serve the dist through grunt serve:dist I start getting console errors ```Error: State 'main'' is already defined.```

I am guessing It is because of the grunt uglify module which somehow messes the angular route definitions. I am using ui-router.

Is there a fix available for this ?

**Comment by Awk34** [comment]
I haven't been able to reproduce. Maybe your main route file got duplicated?
