### ISSUE TITLE
Error: Cannot find module 'mocha'

### ISSUE THREAD

**Issue by EliasJorgensen** [angular-fullstack/generator-angular-fullstack#1532]
Hi,

I'm using v3.2.0 of the generator for my project, but when i run ```grunt``` i get the following error:
```
Running "env:test" (env) task
Loading "mocha-test.js" tasks...ERROR
>> Error: Cannot find module 'mocha'
Warning: Task "mochaTest:unit" failed. Use --force to continue.

Aborted due to warnings.

```

I'm running the LTS version of node, and npm v2.14.7

**Comment by EliasJorgensen** [comment]
I don't know if it's any help, but i'm getting these error messages when the generator runs ```npm install```:
```
npm WARN peerDependencies The peer dependency mocha@>=1.20.0 included from grunt-mocha-test will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by JRhyne** [comment]
Try running 
`npm install mocha`

**Comment by EliasJorgensen** [comment]
That changed the error to this:
```
Running "mochaTest:unit" (mochaTest) task
Warning: Cannot find module './modules/es5' Use --force to continue.

Aborted due to warnings.
```

The weird part is that i chose Jasmine for testing, and not mocha...?

**Comment by EliasJorgensen** [comment]
I get the same error when running ```grunt serve```,  but with express instead of mocha:
```
Running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858
module.js:340
    throw err;
    ^

Error: Cannot find module './modules/es5'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/vagrant/node_modules/babel-core/node_modules/core-js/shim.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
Stopping Express server
```

**Comment by EliasJorgensen** [comment]
I'm only getting this error when choosing Jasmine.
Everything runs fine when choosing Mocha...

**Comment by JRhyne** [comment]
I'm not sure then =/  

What version of node.js and npm are you using?

**Comment by EliasJorgensen** [comment]
I'm running Node v4.2.4 and npm v2.14.7

**Comment by Awk34** [comment]
What OS are you on? I've seen the `Error: Cannot find module './modules/es5'` issue on TravisCI, but Codeship didn't have that problem. There must be some bug in the generator..

**Comment by EliasJorgensen** [comment]
I'm running an Ubuntu 14.04 vagrant box, so everything should be nice and stable on the OS side... =/

**Comment by Awk34** [comment]
It's probably not a stability thing, but more of an environment issue. Do you think you could copy your code to another OS and see if the issue is fixed? Trying to narrow down the issue..

**Comment by EliasJorgensen** [comment]
I have Arch running on my laptop.. I could try running it on that?

**Comment by Awk34** [comment]
Sure, worth a shot. I just want to see if it behaves the same on a different OS.

**Comment by EliasJorgensen** [comment]
Alrighty then. I'll reproduce my steps and post the results when i'm done :)

**Comment by EliasJorgensen** [comment]
I had no issues on Arch.
Here is my terminal output: http://pastebin.com/u5Rx6mxN

I was using a cleanly generated project on this AND in my previous posts.
So we can exclude that factor from the problems.

**Comment by vucalur** [comment]
same issue, but @JRhyne 's solution works for me.

`mocha` is not included as an dependency to any package in `package.json`.
Shouldn't it be listed in `package.json` ?

**Comment by Awk34** [comment]
@vucalur https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/_package.json#L154

**Comment by vucalur** [comment]
my bad.
Please check the surrounding `if`s then.
When jasmine is chosen, mocha is not included in generated `package.json`. I guess `mocha` package should be present for both jasmine and mocha choices.

As per different behaviour on different OSes: Check if you have mocha installed globally. That could be the reason why it's working.

**Comment by EliasJorgensen** [comment]
I don't have Mocha installed globablly, no.

**Comment by Awk34** [comment]
@vucalur ah, that's right, since we don't have the option for using Jasmine for server tests

**Comment by LuckyLin** [comment]
@EliasJorgensen  I also have the problem with "Cannot find module 'mocah'"

Maybe you can try
npm install --save-dev karma-mocha

Hope it helps

**Comment by EliasJorgensen** [comment]
This issue is a year old, so i do not have this issue anymore.
Thanks for trying to help out though, maybe someone in the future will find it helpful 😄

**Comment by eduardfrankford** [comment]
For me: `npm install -g  mocha` solved the issue
