### ISSUE TITLE
CDNs and Amazon CloudFront

### ISSUE THREAD

**Issue by dolanmiu** [angular-fullstack/generator-angular-fullstack#1533]
I hear that it is best practice to serve static files somewhere else to free up resources for the NodeJs server.

https://devcenter.heroku.com/articles/using-amazon-cloudfront-cdn

> Using a CDN optimises the delivery of static assets on your site. This allows us to offload all requests for these static assets off of your web dynos, which in turn will free those dynos to handle more requests for dynamic content.

> Amazon’s CloudFront service is designed as a content delivery network to serve static assets such as CSS or JavaScript files from edge cache locations.

I know ```generator-angular-fullstack``` has ```grunt-cdnify```, but does it support offloading my own static assets into CloudFront?

How should I go about doing it? Put all my images in CloudFront? Put the AngularJS Front-End in CloudFront? Surely the ```build``` task must be changed...

Is offloading requests to static even that important/significant?

**Comment by donvadicastro** [comment]
I think this can be achieved using grunt cdnify plugin, but you should create your cloudfront account before and move all static content here.

After this you can easy map your local content links to cloud links using this plugin.
https://github.com/callumlocke/grunt-cdnify

**Comment by dolanmiu** [comment]
What about moving the index.html? As you may know, ```generator-angular-fullstack``` creates this in the ```routes.js```:

```js
    // All other routes should redirect to the index.html
    app.route('/*').get(function (req, res) {
        res.sendFile(path.resolve(app.get('appPath') + '/index.html'));
    });
```

Is it fine that ```index.html``` is there? Or should it be served in CloudFront also?

**Comment by donvadicastro** [comment]
`index.html` is your application starting point. You can't move this file to another place (or other remote location) as you may have troubles with cross domain requests or virtual path mapping.

**Comment by Awk34** [comment]
In the interest of keeping the generator lightweight, I don't think adding a whole boilerplate for unloading static assets onto a CDN should be added into the template code. It is good to have the info, though.
