### ISSUE TITLE
Running grunt build, the name of images in the assets folder been changed, but the image name in the CSS not been updated.

### ISSUE THREAD

**Issue by dylannnn** [angular-fullstack/generator-angular-fullstack#1534]
When build the app, the task will add timestamp to the images in the assets > images folde. I understand this is to solve the browser cache issue. But somehow, the name of the images been used in the css hasn't been updated. so those images won't shows on the website.

Example:

I have an image (abc.jpg) in the assets/images folder
I use in the css:
background-image: url(./assets/images/abc.jpg);

After build task,
The image's name changed to  "abc.xxxxxxxxxx.jpg"  (xxxxxxxxxx is the timestamp)

==============================================================
I can comment that task in the Gruntfile.js

filerev: {
      dist: {
        src: [
          '<%= yeoman.dist %>/<%= yeoman.client %>/!(bower_components){,*/}*.{js,css}',
          // This ONE    '<%= yeoman.dist %>/<%= yeoman.client %>/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
          '<%= yeoman.dist %>/<%= yeoman.client %>/assets/fonts/*'
        ]
      }
    }

But, I would like to know if there is a way to make it works without comment that line out?

**Comment by JosselinTD** [comment]
+1 Same problem here, the css is not updated

**Comment by arkdelkaos** [comment]
Until is fixed, you can comment 'filerev' in the grunt task 'build' at the Gruntfile.js, and then the filenames will not be renamed :)  
The rename thing. as you may read at https://github.com/yeoman/grunt-filerev, is for browser caching purposes; IMHO you can live without it for a while :+1:

**Comment by Ilshidur** [comment]
Related to : https://github.com/angular-fullstack/generator-angular-fullstack/issues/802

**Comment by DanMMX** [comment]
@Awk34 which was the solution for this? Saw you closed this on March 7th, but couldn't find the fix

**Comment by DanMMX** [comment]
found on the updated code the fix, for anyone still having troubles with this [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/Gruntfile(grunt).js#L313) it is

**Comment by Awk34** [comment]
@DanMMX closed because it was a duplicate

**Comment by DanMMX** [comment]
yeah, but didn't found the duplicate anywhere
