### ISSUE TITLE
xdg-open command not found error on Ubuntu

### ISSUE THREAD

**Issue by sojharo** [angular-fullstack/generator-angular-fullstack#1538]
I have used this boilerplate on windows and it works fine.

However, I recently switched to Ubuntu and my same project is not working there.

When I give command : grunt serve

It fails on following message:

    Running "open:server" (open) task
    Warning: Command failed: /bin/sh -c sudo -u sojharo /media/sojharo/Data/blood-donations/node_modules/open/vendor/xdg-open "http://localhost:9000"
    sudo: /media/sojharo/Data/blood-donations/node_modules/open/vendor/xdg-open: command not found
     Use --force to continue.

**Comment by kawashimaken** [comment]
What is your Ubuntu version?
I dont have exact the same issue, but I encounter some errors in Ubuntu 15.04, while in Ubuntu 14.04.3 LTS everything works just fine and smooth. 

How about run the following command in your terminal
```
which xdg-open
```
to confirm if your xdg-open is installed in your ubuntu system
mine shows 
```
/usr/bin/xdg-open
```
if not installed, you can try
```
sudo apt-get install xdg-utils --fix-missing
```
Please let me know if this solves your problem. Have a nice day! :)

**Comment by kawashimaken** [comment]
What is your Ubuntu version?
I dont have exact the same issue, but I encounter some errors in Ubuntu 15.04, while in Ubuntu 14.04.3 LTS everything works just fine and smooth. 

How about run the following command in your terminal
```
which xdg-open
```
to confirm if your xdg-open is installed in your ubuntu system
mine shows 
```
/usr/bin/xdg-open
```
if not installed, you can try
```
sudo apt-get install xdg-utils --fix-missing
```
Please let me know if this solves your problem. Have a nice day! :)

**Comment by sojharo** [comment]
Thank you for nice response

My Ubuntu version is 14.04.3 LTS. I just installed it 10 days back.

I ran the command `which xdg-open` and it exactly showed me `/usr/bin/xdg-open`

I ran the command 'sudo apt-get install xdg-utils --fix-missing'

It showed 

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    xdg-utils is already the newest version.
    xdg-utils set to manually installed.
    The following packages were automatically installed and are no longer required:
      linux-headers-3.19.0-25 linux-headers-3.19.0-25-generic
      linux-image-3.19.0-25-generic linux-image-extra-3.19.0-25-generic
    Use 'apt-get autoremove' to remove them.
    0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.

The problem is still not resolved for me. However, I start the server using this command now : `grunt serve --force`. It doesn't crash but shows the problem. However, after this I am successfully able to go to the localhost:9000 in my browser

**Comment by Awk34** [comment]
Until you figure this out, I'd suggest removing the 'open' task from `grunt serve` instead of using `--force`

**Comment by kawashimaken** [comment]
Nice to know you can access your app now!

However it is strange that the error occurs even your xdg-open is installed.
my next guess is:
Are you using sudo to run
```
grunt serve
```
or did you use command like
```
sudo npm install
```
in the installation process at any point?

**Comment by sojharo** [comment]
When I use 

    grunt serve

I get permission denied error.

When I use

    sudo grunt serve

I get the error xdg-open command not found for which I have opened this issue.

I remember `npm install` also gave me some permission issues, therefore I had to use command:

    sudo npm install

Should I clone my project again and then try with `npm install`?

**Comment by kawashimaken** [comment]
Yes, I highly recommend you to do it again without ```sudo```
The things you need to sudo install are the packages supposed to be used globally (everywhere in your machine):
npm itself, grunt-cli, bower, yo, generator-angular-fullstack etc. using 
```
sudo npm install -g packagename
```
Please try again with a clean generation use
```
mkdir yourapp
cd yourapp
yo angular-fullstack
```
Good luck :)

**Comment by sojharo** [comment]
I created a new and clean application using `yo angular-fullstack`. I did not use sudo anywhere. Still, I got the same Permission denied error.

And when I used `sudo grunt serve`, I got command not found error.

Thanks @Awk34 for suggestion to remove the 'open'.

**Comment by kawashimaken** [comment]
Could you please show us your permission error messages?
and can you confirm by:
```
sudo npm list -g --depth=0
```
to find out what has been installed globally
and show us the result please?
I am thinking that you might be installing your ```grunt``` globally which might caused the error.
If it is the case the following command might solve your problem:
```
sudo npm uninstall -g grunt
cd yourapp
npm install grunt
```

**Comment by sojharo** [comment]
On `sudo npm list -g --depth=0` I got:

/usr/local/n/versions/node/5.2.0/lib
└── npm@3.3.12


On `sudo npm list -g --depth=1`, I got:

/usr/local/n/versions/node/5.2.0/lib
└─┬ npm@3.3.12
  ├── abbrev@1.0.7
  ├── ansi-regex@2.0.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── aproba@1.0.1
  ├── archy@1.0.0
  ├── async-some@1.0.2
  ├── chownr@1.0.1
  ├── cmd-shim@2.0.1
  ├── columnify@1.5.2
  ├── config-chain@1.1.9
  ├── debuglog@1.0.1
  ├── dezalgo@1.0.3
  ├── editor@1.0.0
  ├── fs-vacuum@1.2.7
  ├── fs-write-stream-atomic@1.0.4
  ├── fstream@1.0.8
  ├── fstream-npm@1.0.5
  ├── glob@5.0.15
  ├── graceful-fs@4.1.2
  ├── has-unicode@1.0.1
  ├── hosted-git-info@2.1.4
  ├── iferr@0.1.5
  ├── inflight@1.0.4
  ├── inherits@2.0.1
  ├── ini@1.3.4
  ├── init-package-json@1.9.1
  ├── lockfile@1.0.1
  ├── lodash._baseindexof@3.1.0
  ├── lodash._baseuniq@3.0.3
  ├── lodash._bindcallback@3.0.1
  ├── lodash._cacheindexof@3.0.2
  ├── lodash._createcache@3.1.2
  ├── lodash._getnative@3.9.1
  ├── lodash.clonedeep@3.0.2
  ├── lodash.isarguments@3.0.4
  ├── lodash.isarray@3.0.4
  ├── lodash.keys@3.1.2
  ├── lodash.restparam@3.6.1
  ├── lodash.union@3.1.0
  ├── lodash.uniq@3.2.2
  ├── lodash.without@3.2.1
  ├── mkdirp@0.5.1
  ├── node-gyp@3.0.3
  ├── nopt@3.0.4
  ├── normalize-git-url@3.0.1
  ├── normalize-package-data@2.3.4
  ├── npm-cache-filename@1.0.2
  ├── npm-install-checks@2.0.1
  ├── npm-package-arg@4.0.2
  ├── npm-registry-client@7.0.7
  ├── npm-user-validate@0.1.2
  ├── npmlog@1.2.1
  ├── once@1.3.2
  ├── opener@1.4.1
  ├── osenv@0.1.3
  ├── path-is-inside@1.0.1
  ├── read@1.0.7
  ├── read-cmd-shim@1.0.1
  ├── read-installed@4.0.3
  ├── read-package-json@2.0.1
  ├── read-package-tree@5.1.2
  ├── readdir-scoped-modules@1.0.2
  ├── realize-package-specifier@3.0.1
  ├── request@2.65.0
  ├── retry@0.8.0
  ├── rimraf@2.4.3
  ├── semver@5.0.3
  ├── sha@2.0.1
  ├── slide@1.1.6
  ├── sorted-object@1.0.0
  ├── strip-ansi@3.0.0
  ├── tar@2.2.1
  ├── text-table@0.2.0
  ├── uid-number@0.0.6
  ├── umask@1.1.0
  ├── unique-filename@1.0.0
  ├── unpipe@1.0.0
  ├── validate-npm-package-license@3.0.1
  ├── validate-npm-package-name@2.2.2
  ├── which@1.2.0
  ├── wrappy@1.0.1
  └── write-file-atomic@1.1.3

This is the permission error I get when I run without `sudo`:

    Running "open:server" (open) task
    Warning: Command failed: /bin/sh -c /media/sojharo/Data/blood-donations/node_modules/open/vendor/xdg-open "http://localhost:9000"
    /bin/sh: 1: /media/sojharo/Data/blood-donations/node_modules/open/vendor/xdg-open: Permission denied
     Use --force to continue.

    Aborted due to warnings.

**Comment by kawashimaken** [comment]
I notice you are using n to manage your node version.
Things might be, you have install some global package to version A, when you switch to version B, you have to install global package again for that version, 

On ```sudo npm list -g --depth=0```
only npm is shown, means you did not install others for this node version
try
```
sudo npm install -g yo grunt-cli bower generator-angular-fullstack
```
Also I suggest you use node 4.2.4(don't forget to check installed global packaged again, if you switch node version)

**Comment by sojharo** [comment]
While running this command I also noticed warning which said, 

    wanted: {"node":"^4.2.3","npm":"^2.14.7"} (current: {"node":"5.2.0","npm":"3.3.12"})

I think I am now beginning to understand the problem. I would test with reinstalling the packages again. If failed, I would remove current nodejs and then would go for 4.2.4.

Thanks. I would let know here about results.

**Comment by sojharo** [comment]
Still getting permission denied error. I think I should move towards nodejs 4.2.4. I would do this tomorrow and would let you know here. Thanks for your help :)

**Comment by sojharo** [comment]
I installed 4.2.4 but still no luck. :(

**Comment by Awk34** [comment]
The short term hack if `'open'` doesn't work is to just delete that task in your Grunt/Gulp config. All it does is open your browser to your project (localhost:9000). It's not necessary.

**Comment by VismayaSathyan** [comment]
> What is your Ubuntu version? I dont have exact the same issue, but I encounter some errors in Ubuntu 15.04, while in Ubuntu 14.04.3 LTS everything works just fine and smooth.
> 
> How about run the following command in your terminal
> 
> ```
> which xdg-open
> ```
> 
> to confirm if your xdg-open is installed in your ubuntu system mine shows
> 
> ```
> /usr/bin/xdg-open
> ```
> 
> if not installed, you can try
> 
> ```
> sudo apt-get install xdg-utils --fix-missing
> ```
> 
> Please let me know if this solves your problem. Have a nice day! :)

Hey, it worked for me. I Was facing a similar issue with xdg-open command. It's solved. Thank you! :')
