### ISSUE TITLE
angular-fullstack vs mean.io

### ISSUE THREAD

**Issue by programming-kid** [angular-fullstack/generator-angular-fullstack#154]
hi i know this is not the place for this type of question i apologize for that  , but then there is no other place to ask this 
i am starting a new project which is MEAN stack project after searching for a while and eliminating many other options i am stuck at two 
angular-fullstack and [mean.io](http://www.mean.io/)

i just want to know which one to choose, both seem to be very similar am i missing something ??
i am confused 
pls help

**Comment by LillaEli** [comment]
As I tried it today, looks like ui-router is now available as an option in angular-fullstack. Thanks for adding it!
