### ISSUE TITLE
Adding more passport authentications for social networks

### ISSUE THREAD

**Issue by georgeportillo** [angular-fullstack/generator-angular-fullstack#1540]
Hey all,

I was wondering if I could contribute on adding [Yammer](http://yammer.com) as a social network auth onto the existing ones. I already got some code working in another project of mine.

This project has helped me a lot on from getting started with node to learning angular. I'd be happy to contribute.

**Comment by Awk34** [comment]
Sure, you'd just have to add [passport-yammer](https://github.com/jaredhanson/passport-yammer) alongside the other passport plugins that we're using (google, twitter, facebook)

**Comment by kawashimaken** [comment]
Wow, glad to hear that!

**Comment by Awk34** [comment]
Closed due to inactivity
