### ISSUE TITLE
Generated route is not working

### ISSUE THREAD

**Issue by andershagebakken** [angular-fullstack/generator-angular-fullstack#1542]
Hi. I did what I always do to create routes, which is "yo angular-fullstack:route myroute". It creates the 5 files it always creates. The problem is that my app redirects me back to main no matter what I do when trying to access /myroute .The files are injected into index.html as well. I have always done it like this for all my angular-fullstack projects. I've previously done it on the current project, just a few days ago, but suddenly, it will not let me route to it. It is ngRoute by the way. I have no idea why this is not working. Any tips? Thanks.

**Comment by donvadicastro** [comment]
Maybe your route is auth protected by default. Try to login or allow anonim access to your route in route config file.

**Comment by andershagebakken** [comment]
Thanks for feedback, but it does not work even though I am logged in as admin or as any of the other users.

**Comment by andershagebakken** [comment]
For some reason, it suddenly worked to create a new controller and access it, so I guess this was just something that went by all by it self?

**Comment by donvadicastro** [comment]
Check your "server/routes.js" file also. Maybe your route is not registeted: app.use('/api/route', require('./api/your_route')

**Comment by gardner** [comment]
I had to add ``app.use('/api/things', require('./api/thing'));`` to my ``server/routes.js`` file for ``grunt test`` to pass.

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by tgwhite** [comment]
I think this issue is a [duplicate ](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1015).
