### ISSUE TITLE
Dev & Test works fine, PROD Fails

### ISSUE THREAD

**Issue by dicer2000** [angular-fullstack/generator-angular-fullstack#1547]
Great generator, but when I deploy with NODE_ENV=production, I get this error:
```
.../testproject/server/app.js:7
import express from 'express';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/SecondaryDrive/Users/dicer2000/Documents/Summertime/Clients/StarterData/Projects/iAbstract/testproject/server/index.js:12:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```
Do I have the wrong version of babel or something?  Any help you can give me would be great.

**Comment by Awk34** [comment]
If you look [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/server/index.js#L6), you'll see that in dev and test mode we use the babel require hook. In production, though, you are expected to have run `grunt build/gulp build` and to be running `node dist/server`, since the build command will transpile the server code. Babel doesn't suggest using the require hook in production, but to transpile and use the runtime. We use the require hook to save ourselves from waiting for transpilation in dev and test.

**Comment by dicer2000** [comment]
I'm still having problems - I could sure use help.  I'm building with grunt and get no errors.

Then I run: **NODE_ENV='production' nodemon server/index.js**

and it errors out with:

**testproject/server/app.js:7**
**import express from 'express';**
**^^^^^^**

**SyntaxError: Unexpected token import**
    **at exports.runInThisContext (vm.js:53:16)**
    **at Module._compile (module.js:374:25)**
    **at Object.Module._extensions..js (module.js:405:10)**
    **at Module.load (module.js:344:32)**
    **at Function.Module._load (module.js:301:12)**
    **at Module.require (module.js:354:17)**
    **at require (internal/module.js:12:17)**
    **at Object.<anonymous> **(/testproject/server/index.js:12:28)**
    **at Module._compile (module.js:398:26)**
    **at Object.Module._extensions..js (module.js:405:10)**

**Comment by Awk34** [comment]
The built server code is in `dist/server`, not `server`

**Comment by dicer2000** [comment]
Oh, I see what you are saying.  Thanks for the quick help. I owe you a big steak dinner!

**Comment by dicer2000** [comment]
Then let me ask you this...  Do you just distribute that "dist" folder to your final server?  Or do you copy the whole project.  I was just using git to pull down the entire thing.

Thanks again.

**Comment by chinnichaitanya** [comment]
@dicer2000 It is better to do `grunt build` in the server itself instead of copying them. Size will be huge.

**Comment by Awk34** [comment]
You could either just distribute the dist folder (make sure to install node dependencies), or copy the git repo, run a build, and serve out of `dist`.

**Comment by dicer2000** [comment]
Thanks guys.  That worked really well.

**Comment by saeidalidadi** [comment]
For `v3.7.5` I used `NODE_ENV=production grunt serve:dist`
