### ISSUE TITLE
`gulp styles` not producing anything

### ISSUE THREAD

**Issue by Kageetai** [angular-fullstack/generator-angular-fullstack#1549]
Hi there,
I just wanted to try out the latest version of the generator with `gulp` option. Generating worked fine bu t running `gulp serve` or even `gulp styles` do not produce any CSS files.
By testing and running `stylus` manually shows up that the injector injected `account/login/login` falsely. I removed that line and stylus now runs correctly but `gulp serve` is still not producing any stylesheets.

**Comment by Kageetai** [comment]
Okay, it seems like the stylus port of the generator is just not finished yet. There is also something `bootstrap-stylus` missing and the `app.styl` is quite different from its counterparts. Too bad but maybe I'll stick with less for now :)

**Comment by javidrashid** [comment]
From where did you run the gulp serve or anything like that because the scaffold-ed app doesn't come with a gulpfile.js. I only see gruntfile.
