### ISSUE TITLE
 yo angular-fullstack:endpoint isn't working for me.

### ISSUE THREAD

**Issue by swateek** [angular-fullstack/generator-angular-fullstack#1550]
I upgraded my yo and yeoman today, and this stopped producing an output.

The error shown is:

events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'sequelizeModels' of undefined
    at Generator.prompting (/home/swateek/Documents/codebase/project1/node_modules/generator-angular-fullstack/endpoint/generator.js:88:28)
    at /home/swateek/Documents/codebase/project1/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Any problem because of the upgrade?

**Comment by Awk34** [comment]
Did you also upgrade from generator-angular-fullstack < 3.0.0 to 3.0.0+? This is a major release bump, and there have been breaking changes.

**Comment by swateek** [comment]
Yes, I did. Anyway I can undo this?

Regards,
Swateek

**Comment by Awk34** [comment]
`npm install --global generator-angular-fullstack@^2.1.1`

**Comment by swateek** [comment]
Thank you, it worked.


Swateek Jena
about.me/swateek
[image: Swateek Jena on about.me]
  <http://about.me/swateek>Ph:+91-9900056958

**Comment by Climax777** [comment]
This is happening to me with `generator-angular-fullstack@4.0.1`:
```
yo angular-fullstack:endpoint atm
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'sequelizeModels' of undefined
    at Generator.prompting (/home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/generators/endpoint/index.js:118:30)
    at Object.<anonymous> (/home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:439:23)
    at /home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/run-async/index.js:26:25
    at /home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/run-async/index.js:25:19
    at /home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)

```

**Comment by swateek** [comment]
@Climax777 just downgrade your version as suggested above. It works, not sure why the upgrades are so buggy.

**Comment by Climax777** [comment]
Sorry I ran the generator in the wrong folder. Works now
