### ISSUE TITLE
Any plan on mongoDB 3.2.x support?

### ISSUE THREAD

**Issue by kawashimaken** [angular-fullstack/generator-angular-fullstack#1553]
I noticed in the latest generated package.json
mongoose version is:
"mongoose": "^4.1.2",
According to [mongoose mongoDB compatibility doc](http://mongoosejs.com/docs/compatibility.html)
>MongoDB Server 2.4.x: mongoose ~3.8, 4.x
>MongoDB Server 2.6.x: mongoose ~3.8.8, 4.x
>MongoDB Server 3.0.x: mongoose ~3.8.22, 4.x
>MongoDB Server 3.2.x: mongoose >=4.3.0

This means generated app will not able to use mongoDB 3.2.x accordingly.
I myself also experimented to switch my mongoDB to 3.2.x, expectedly the interaction with mongoDB is not functional due to the mongoose version (my working-fine version is mongoDB 3.0.8).

My question is, are there any plan to make the generated app compatible with mongoDB 3.2.x in future?

**Comment by Awk34** [comment]
We will always try to keep packages up to date.

**Comment by kawashimaken** [comment]
Great! looking forward to see the update soon! 
:-)
I am still learning this generator, but I will too try my best to contribute.
