### ISSUE TITLE
The "newer" prefix is not supported for aliases

### ISSUE THREAD

**Issue by vgiacchina** [angular-fullstack/generator-angular-fullstack#1554]
Hi, 
I have just installed generator, but the command grunt gives me this error:
Running "newer:tslint" (newer) task
Fatal error: The "newer" prefix is not supported for aliases

The dependencies are installed.
What do I do ?
Tnx.

**Comment by pharindoko** [comment]
same for 3.3 beta.
Install the released 3.2.0 version of the generator

**Comment by Awk34** [comment]
Does replacing `newer:tslint` with `newer:tslint:all` fix the problem? Is this for running `grunt`/`grunt default`?

**Comment by boxhead201** [comment]
I am having the same issue.  Replacing with newer:tslint:all does not fix the issue.

Node 4.2.4, NPM 3.5.3, Yo 1.6.0

**Comment by Awk34** [comment]
Did you scaffold for Babel or TypeScript? It should `tslint` for TypeScript, `jshint` for Babel.

**Comment by N0bl3** [comment]
This was corrected in last commit.

**Comment by Awk34** [comment]
If you're referring to https://github.com/angular-fullstack/generator-angular-fullstack/commit/15f60db1773eeb77e3fc7f09b01d7e1e0cd52c0c then yeah, I mixed up tslint and jshint in that one spot.
