### ISSUE TITLE
SocketIO is not wired with the gulp setup

### ISSUE THREAD

**Issue by asirko** [angular-fullstack/generator-angular-fullstack#1558]
I have just created an application with gulp (cf: the configuration bellow) and the socketIO sample (the `Thing` module). The resulting app does not work straight out of the box.

First, for routes, I had to add `app.use('/api/things', require('./api/thing'));` with others routes definition.

Then, for web socket, I have not seen how is `socketIO` wired. The socketIO is initiated in the `app.js` file where the config is called but I did not find any reference of the `thing.socket.js` in the whole project.

Where is the best place, considering the global architecture, to init socketIO with the `Thing` module ?

```
> yo angular-fullstack --gulp

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I create an AngularJS app with an Express server.

# Client

? What would you like to write markup with? HTML
? What would you like to write stylesheets with? Less
? What Angular router would you like to use? uiRouter
? Would you like to include Bootstrap? Yes
? Would you like to include UI Bootstrap? Yes

# Server

? What would you like to use for data modeling? Mongoose (MongoDB)
? Would you scaffold out an authentication boilerplate? Yes
? Would you like to include additional oAuth strategies? Google, Facebook, Twitter
? Would you like to use socket.io? Yes

# Project

? What would you like to write tests with? Mocha + Chai + Sinon
? What would you like to write Chai assertions with? Expect
```
My tool's versions are :
node@5.4.0
npm@3.3.12
bower@1.7.2
generator-angular-fullstack@3.2.0
gulp@3.9.0
yo@1.6.0

**Comment by Awk34** [comment]
If the server route wasn't automatically injected, the socket route probably wasn't injected either.

See if you need to add `require('../api/thing/thing.socket').register(socket);` [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.2.0/app/templates/server/config/socketio(socketio).js#L20)

**Comment by asirko** [comment]
It seems that adding `app.use('/api/things', require('./api/thing'));` into `server/routes.js` and `require('../api/thing/thing.socket').register(socket);` into `server/config/socketio.js` solve all issues related to the Thing module.

Thanks for all !
