### ISSUE TITLE
Generate Code in ES6

### ISSUE THREAD

**Issue by fabio-rigato** [angular-fullstack/generator-angular-fullstack#1560]
Hello everybody!

First of all my compliments about this project!.. It's very useful!

I'm wandering where can I set up yo or generator-angular to auto generate code in ES6.

Someone could help me please?

P.S: I apologize for my bad English

Best Regards
-----
Fabio Rigato

**Comment by Awk34** [comment]
Versions 3.0.0+ generate ES6 code by default

**Comment by fabio-rigato** [comment]
Thank you so much for your fast reply!
Just to be sure, when i generate a route, the controller auto-generated is this one:

```javascript
'use strict';

angular.module('myApp')
  .controller('MainAdminCtrl', function ($scope) {
    $scope.message = 'Hello';
  });
```

In my opinion this is ES5 instead of ES6 like this one:

```javascript
  'use strict';

  class MainAdminCtrl {

    constructor() {
      this.messsage = 'Hello';
    }
  }

  angular.module('bandyercorpApp')
    .controller('MainAdminCtrl', MainAdminCtrl);
```

Could you tell em where is the configuration file for auto-generate code in ES6 please?

Best Regards
--
Fabio Rigato

**Comment by Awk34** [comment]
The only generators part of this project are `yo angular fullstack` and `yo angular-fullstack:endpoint`. All the other ones are from [generator-ng-component](https://github.com/DaftMonk/generator-ng-component). I have been working on adding an ES6 option to that generator, but it is not complete yet. For the time being, you'll just have to convert manually after using the subgenerator.
