### ISSUE TITLE
grunt build tries to transpile .json files

### ISSUE THREAD

**Issue by carragom** [angular-fullstack/generator-angular-fullstack#1561]
Hi there,

I added a `server/log4js.json` file to my project generated with version `3.1.1`. And now `grunt build` breaks with the following error:

```
Running "babel:server" (babel) task
Warning: server/log4js.json: Unexpected token (2:19) Use --force to continue.

Aborted due to warnings.
```

I fixed the issue by removing `.json` files from the `babel:server` task. I don't see why `grunt build` would try to transpile `.json` files. Am I missing something here or is this a bug?

Thanks for the great generator by the way.

**Comment by Awk34** [comment]
[This line](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.1.1/app/templates/Gruntfile(grunt).js#L612) is what you're probably talking about. It should just be `.js`.

**Comment by rohita77** [comment]
same issue exist with gulp also. Unfortunately removing "paths.server.json" also skip copying of the file to the dist and does not get deployed. I am using the .json files as stubs
