### ISSUE TITLE
how to include scripts not in bower package?

### ISSUE THREAD

**Issue by macliems** [angular-fullstack/generator-angular-fullstack#1562]
I want to include minified scripts that are not in a bower package. I don't know where to place them or how to instruct the Gruntfile for serve and/or serve:dist.

Your help will be very much appreciated!!

**Comment by Awk34** [comment]
They'd probably be best put in `client/assets/js`

**Comment by dariospadoni** [comment]
I tried this way, it works fine on local development but assets/js is not copied into the dist folder and js files are not referenced from index.html. Can you provide some example on how to make serve:dist work?
