### ISSUE TITLE
Unable to create route files due to error on base.js

### ISSUE THREAD

**Issue by jchukwum** [angular-fullstack/generator-angular-fullstack#1564]
Can someone please help?

I see the following error when trying to create the route files (other generators are fine):

➜  zefi git:(develop) ✗ yo angular-fullstack:route job
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.instantiate is not a function
    at composeWith (/home/jchukwum/projects/zefi/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:620:26)
    at yeoman.generators.Base.extend.compose (/home/jchukwum/projects/zefi/node_modules/generator-angular-fullstack/route/index.js:6:10)
    at /home/jchukwum/projects/zefi/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by Awk34** [comment]
generator version?
node version?
npm version?
OS?
etc?

**Comment by jchukwum** [comment]
Apologies, I'm doing what I don't like done to me:

generator version? 3.2.0
node version? v5.4.1
npm version? 3.3.12
OS? Ubuntu 12.04.5 LTS
yo version? 1.1.2

**Comment by jchukwum** [comment]
Alright, in process of giving you the versions I realised that I was using an old version of yo. I've just upgraded it from 1.1.2 to 1.6.0 and that resolved the problem.

Thanks for indirectly helping me out.

**Comment by jchukwum** [comment]
I'm closing the issue since it's been resolved...
