### ISSUE TITLE
angular is not defined

### ISSUE THREAD

**Issue by radjivC** [angular-fullstack/generator-angular-fullstack#1565]
![screen shot 2016-01-17 at 8 01 20 pm](https://cloud.githubusercontent.com/assets/5714138/12376683/2379931c-bd55-11e5-8414-a51dfa8be888.png)

Just use npm start for the first time and I got this error from the browser,

Any idea?

**Comment by COMMODORE-256** [comment]
Did you run "npm install" and "bower install"?

**Comment by radjivC** [comment]
Yes I run bower and npm and mongodb is running

**Comment by lommaj** [comment]
@radjivC I typically use the grunt serve task to run, if npm start is running the production build, its going to replace script references with CDN urls, so if you dont happen to be connected to the internet, its going to be missing scripts.

**Comment by Awk34** [comment]
generator version?
node version?
npm version?
OS?
etc?

**Comment by Awk34** [comment]
Closed due to inactivity
