### ISSUE TITLE
Unexpected token trying to load underscore

### ISSUE THREAD

**Issue by arkdelkaos** [angular-fullstack/generator-angular-fullstack#1566]
*(Question)*  

After I have installed, via bower, Underscore, I've restarted grunt:serve and tried to use it, getting this error:  

````
(...)
Running "babel:client" (babel) task
Warning: client/app/deck/deck.controller.js: Unexpected token (43:13) Use --force to continue.
Aborted due to warnings.
(...)
````

That line correspond, on this code, with the underscore :  
````
(...)
this.deck.push({
            _.findWhere(this.cartas, {_id: response.data[i]});
          });
(...)
````

This is a controller, and this is the start of the constructor snippet:  
````
'use strict';

(function() {

  class DeckController {
    constructor(Auth, $scope, $http, socket, _, $log) {
(...)
````
...but I had tried with 'underscore' instead of '_', too.  

app.js:  
````
angular.module('eecrApp', [
(...)
(...)
  'validation.match',
  'underscore'
])
````

index.html:  
````
(...)
<script src="bower_components/underscore/underscore.js"></script>
      <!-- endbower -->
````

**I think that I just don't know how to load the library**, as simple as that; but I've been done some research, and I can't make it work. **What I'm doing wrong?**  
The project is here, if you want to look a it yourself :): https://github.com/arkdelkaos/EECR

**Comment by arkdelkaos** [comment]
BTW, Thank you for this great generator :) I'm learning A LOT with it, and thanks to how fine it works I have been advancing like crazy!  
May I ask you some questions about the github issues *forum*? I would like to contribute, but I don't know for sure how I could do it:
  - The tags, are applied only by te staff, or I could send a question...well, 'question' tagged?
  - Some constructors seems outdated. Well, I don't know for sure if they are; maybe they are like that for a reason. But I think it's unlikely that some controllers use one structure, and then when you use angular-fullstack:route you get another kind (for example, it do not use name.route.js and name.module.js, as with the admin module). In the end is more or less the same, but when you're not so sure about what you're doing, sometimes you copy the structure of what you know for sure that works (the 'default' modules, for example). Is easy to copy the structure of them and apply to your new route...but it feels strange...I don't know if I'm explaining myself here :) I think it could be better if all the routes have the same structure from scratch.
  - What I know for sure is that **ui.bootstrap is outdated**, and if you follow the api doc you get all kind of crazy errors. The problem is really easy to fix, updating a few code here and there. **Is better to send a issue, or I could just clone the repository, fix it, and commit it?**

**Comment by Awk34** [comment]
Objects need keys
```js
this.deck.push({
  key: _.findWhere(this.cartas, {_id: response.data[i]})
});
```

**Comment by Awk34** [comment]
* Only collaborators can tag issues
* The main generator and endpoint sub-generator are part of this project. The angular component sub-generators are part of the [generator-ng-component](https://github.com/DaftMonk/generator-ng-component) project.
* Feel free to submit a pull request, conforming to our Contributing Guidelines found in `CONTRIBUTING.md`

**Comment by arkdelkaos** [comment]
Ok...thanks for responding :)

I tried that snippet...at it is (adding 'key:' before the _.), and I still have the same problem (I think...)
But, where *'that'* comes from? I had look at the underscore docs and didn't saw anything. Where I could find info about the 'key:' part? I don't even know where to start looking for :?

**Comment by Awk34** [comment]
In your code here:
```js
{
  _.findWhere(this.cartas, {_id: response.data[i]});
}
```
you have declared a JSON Object with `{}`. JSON Objects are key-value stores. The way you declared it, you don't have a key, so that code is invalid. The following code *has* a key, and is thus valid:
```js
{
  someKey: _.findWhere(this.cartas, {_id: response.data[i]});
}
```
