### ISSUE TITLE
Where can I define Sequelize associations?

### ISSUE THREAD

**Issue by ketysek** [angular-fullstack/generator-angular-fullstack#1567]
Hello,
I've just started with using this full-stack to create my new project. I've set up PostgreSQL as my main database, but here comes the problem: I am a little bit confused with model associations...where should I put them? Here is for example my product.model.js file ... is it possible to add a rule belongsTo(Something) here or not?

    export default function(sequelize, DataTypes) {
      return sequelize.define('Product', {
        timestamps: true,
        _id: {
          type: DataTypes.INTEGER,
          allowNull: false,
          primaryKey: true,
          autoIncrement: true
        },
        buyUrl: DataTypes.STRING,
        createdAt: 'dateAdded',
        updatedAt: false,
        ean: {
          type: DataTypes.STRING,
          unique: true,
          validate: {
            isNumeric: true,
          },
        }
    }

**Comment by ketysek** [comment]
Ah, I'll found it :-D

**Comment by amoussard** [comment]
Hi @ketysek ,
How have you done ?

**Comment by ThiagoMiranda** [comment]
@ketysek where did you put it?

**Comment by ketysek** [comment]
it can be put in file `server\sqldb\index.js` (I am using postgress)

**Comment by ThiagoMiranda** [comment]
Thanks @ketysek . I've putted in there too.
Just a quick question: where do you put a model that not necessarily have an api ( like a through table )?

**Comment by andrewl913** [comment]
I think updating  `server\sqldb\index.js` with a helpful comment to let those know where to define relationships. It would be easy and effective :)

**Comment by AlexisNichel** [comment]
help me, where did you put it?
