### ISSUE TITLE
start-non-standard

### ISSUE THREAD

**Issue by tylerdmace** [angular-fullstack/generator-angular-fullstack#1573]
Just curious what this means. Found in controller files above the constructor function.

**Comment by Awk34** [comment]
It tells JSHint to ignore something. JSHint doesn't understand the ES7 proposed class properties.

**Comment by paulwithap** [comment]
What is the benefit of declaring the properties that way versus in the constructor method, i.e. `this.menu = ...`?

**Comment by Awk34** [comment]
For transpilation, they result in the same thing:

source
```js
class Foo {
  foo = 1;
  
  constructor() {
    this.bar = 2;
  }
}
```
babel
```js
var Foo = function Foo() {
  _classCallCheck(this, Foo);

  this.foo = 1;

  this.bar = 2;
};
```
typescript
```js
var Foo = (function () {
    function Foo() {
        this.foo = 1;
        this.bar = 2;
    }
    return Foo;
}());
```

For things like this it just makes for better separation of concerns. When the generator transitions to using ESLint with babel as its parser, we won't need the jank JSHint disable section
