### ISSUE TITLE
Best way to redirect root domain to www on Heroku.

### ISSUE THREAD

**Issue by samuelrutherford** [angular-fullstack/generator-angular-fullstack#1575]
I have an angular fullstack app running on Heroku and am wanting to redirect all http://example.com url's to http://www.example.com but am unclear as to the best way to be doing this.

eg:
http://example.com  ->  http://www.example.com
http://example.com/foo/bar  ->  http://www.example.com/foo/bar

I see that there is something in the .htaccess that looks like it should be doing what I need but isn't.

I also have a PointDNS add-on running on the Heroku app and am wondering if I should be trying to achieve it through this.

Any help or pointers in the right direction would be much appreciated.
Cheers.

**Comment by gazzwi86** [comment]
Could you not do this by adding a rule in the server/routes.js file?  Something like the following ahead of the catch all rule:

```
app.all(/.*/, function(req, res, next) {
  var host = req.header("host");
  if (host.match(/^www\..*/i)) {
    next();
  } else {
    res.redirect(301, "http://www." + host);
  }
});
```

**Comment by samuelrutherford** [comment]
Thanks @gazzwi86 
That seems to have done the trick but I did have to add a path so it ended up like this
```
  app.all(/.*/, function(req, res, next) {
    var host = req.header("host"),
        path = req.originalUrl;
    if (host.match(/^www\..*/i)) {
      next();
    } else {
      res.redirect(301, "http://www." + host + path);
    }
  });
```

**Comment by samuelrutherford** [comment]
I should have picked this up before but have now noticed that home page doesn't redirect.

As in:
http://example.com/foo/bar -> http://www.example.com/foo/bar (WORKS)
http://example.com -> http://www.example.com (DOESN'T WORK)

I'm also curious if this method is best practice or most efficient way of doing this?

**Comment by gazzwi86** [comment]
Well angular-fullstack uses express for its server, so I would suggest looking up on the documentation for that.  This is the way express handles routes and therefore is how its done.  As for a best practise or some form of pattern you could use, I'm afraid you're looking at further research as I don't know, this has always served my purposes.
