### ISSUE TITLE
Asset Pipeline

### ISSUE THREAD

**Issue by rightisleft** [angular-fullstack/generator-angular-fullstack#1577]
Context: I'm using the yo generator for generator-angular-fullstack

I've scaffolded my project using the gulp flag

I have gulp / express / angular running in development mode correctly

When i test gulp serve:dist i see the build process complete successfully

The build process seems to be implementing some type of asset caching logic for my images. When it optimizes the png images, it appends a suffix to the image name taking foo.png and changing it to foo-4324hju2.png. It does this for all assets in my project.

Resuling in:

foo-4324hju2.png
bar-5435fsgf.png
etc

Problem: When the browser loads the html file, its attempting to load assets from - /assets/images/foo.png - /assets/images/bar.png - This results in a 404 error.

Question: What is the correct way to integrate with the asset pipeline for generator-angular-fullstack ? Is there a library or a best practices document? I dont see anything in the readme

**Comment by Awk34** [comment]
I think that's a bug. Does it work fine if you run `gulp build` and then run the server from `/dist`?

**Comment by Awk34** [comment]
I haven't been able to reproduce this with the latest version of the generator. Do you have any more information as to why this might be happening for you?
