### ISSUE TITLE
Node 4.2.3 compatability issues

### ISSUE THREAD

**Issue by Nogbit** [angular-fullstack/generator-angular-fullstack#1579]
After the project is generated within a brand new install of node itself and using npm 3.5.3, and your install steps in the readme, I then try to run ``grunt``.  I get the following (maybe some additional steps are needed in your readme?).

```
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

So I then do ``npm install --save-dev grunt``, and then ``grunt`` again.  I then end up with one missing module after another (jit-grunt, time-grunt, jshint-stylish, autoprefixer).  Then once all of those are installed, I finally get the following when running ``grunt``.

```
jit-grunt: Plugin for the "newer" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "newer:tslint" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2016-01-24 02:01:40 UTC)
loading tasks  184ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 184ms

```

It would be great if you provided an option to simply use good old npm build scripts and no grunt or gulp.  But, for now, any advice on fixing this issue would be great.

**Comment by cupofnestor** [comment]
From the [npm docs](https://docs.npmjs.com/cli/install):
>With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.

This may or may not be your issue, but it is a common one.  Either way, you can install the devDependencies via 
`npm install --only=dev`

**Comment by Nogbit** [comment]
So I started fresh, on my dev box in an empty directory and not setting a production flag (which I hadn't done previously anyway) here is what I did.

``yo angular-fullstack`` with the following options

    Babel
    HTML
    CSS
    ngroute
    bootstrap
    ui bootstrap
    sequelize (no mongo)
    google/fb/twitter
    no socket io
    jasmine.

It creates the site, then does the npm install && bower install.  The problem I'm seeing is the ``node_modules`` directory is empty. The following is what is shown after a manual npm install (note the ``killed``)

```
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
extract:escape-html → gen ▌ ╢███████████████████████████████████████░░░░░░░░░░░░░░░░╟
Killed
```

**It turns out, my Manjaro VM had only 1GB of RAM and is not enough, I gave it two GB.  Then ``npm install`` finishes and I can successfully do a ``grunt serve`` now**, but, a regular ``grunt`` gives me the following ```Fatal error: The "newer" prefix is not supported for aliases``.

```
Running "newer:tslint" (newer) task
Fatal error: The "newer" prefix is not supported for aliases

Execution Time (2016-01-27 00:02:12 UTC)
loading tasks        227ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 93%
loading grunt-newer   13ms  ▇▇▇ 5%
newer:tslint           5ms  ▇ 2%
Total 245ms
```

**Comment by Nogbit** [comment]
As an FYI, I also had to do ``npm install mocha --seve-dev`` in order to get ``grunt test`` to work.

**Comment by Awk34** [comment]
The `newer:tslint` thing was a bug that has been fixed on master. Just replace it with `newer:jshint`.

Also the mocha thing is a bug that has not been fixed yet.

**Comment by Nogbit** [comment]
Thanks!  All set!

**Comment by danvitoriano** [comment]
I'm with the same problem, the error message is the same, but the scaffold from yeoman already came with `newer:jshint`. 

Do I have to install any other module? Tks!
