### ISSUE TITLE
How to generate endpoint for a specified model?

### ISSUE THREAD

**Issue by milansegedinac** [angular-fullstack/generator-angular-fullstack#1581]
Could someone please provide me an example of generating endpoint code for a given model? The readme says:
  
yo angular-fullstack:endpoint [options] <name>
  --models             # Specify which model(s) to use

How should the model be specified?

**Comment by Awk34** [comment]
The options for `--models` are either `sequelize` or `mongoose`

**Comment by milansegedinac** [comment]
Thank you for the answer.

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/commit/d3b4c541decd92d6ab878dd5d7451a9cddc92ec5
