### ISSUE TITLE
CSRF Token? 403 Forbidden

### ISSUE THREAD

**Issue by kaungmyatlwin** [angular-fullstack/generator-angular-fullstack#1582]
Hello. I was trying to POST on my API, and it returned an error 
`403 Error: CSRF token missing`

Note that I'm very new to MEAN Stack, and would like a help of how do I POST on the API?

**Comment by Awk34** [comment]
If you don't want to use CSRF tokens, disable [Lusca](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.2.0/app/templates/server/config/express.js#L55-L72)

**Comment by luisfusim** [comment]
please anyone know how can i disable Lucsa only for one route im using webhooks from OpenPay (Like PayPal) ... 

Thanks

**Comment by Awk34** [comment]
@luisfusim that's a question for the [Lusca](https://github.com/krakenjs/lusca) people

**Comment by nmarcetic** [comment]
Lusca does not support CSRF routes exclude if you don't use krakenjs on the top of it. There is a clean and easy way to disable CSRF for some routes. I followed the suggestion from lusca guys https://github.com/krakenjs/lusca/issues/58 last comment is a fix. 
In short :
1. Disable it by default , false here https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.2.0/app/templates/server/config/express.js#L61
2. In your routes.js file on the top define the routes you want to be CSRF free
3. In your routes.js file add  app.use(lusca.csrf({angular:true})); below the CSRF free routes
4. All routes after that line will be CSRF protected 
Easy, working like a charm.
