### ISSUE TITLE
POST /api/things returns 404

### ISSUE THREAD

**Issue by davehorton** [angular-fullstack/generator-angular-fullstack#1583]
I just built the stock / starting project, ran 'grunt serve' and noticed when I enter "things" and press the Add New button they just disappear.  Looking at the server-side logging I see this:

Running "watch" task
Waiting...
SocketIO / [127.0.0.1:61933] CONNECTED
GET /api/things 404 5.739 ms - -
POST /api/things 404 1.548 ms - 24
POST /api/things 404 1.748 ms - 24

**Comment by davehorton** [comment]
Tried rerunning npm install && bower install but no joy.

Interestingly, the endpoint API tests work but the mocha integration tests fail (for 'thing' only, tests pass for 'user').

```
Running "mochaTest:integration" (mochaTest) task


  Thing API:
    GET /api/things
GET /api/things 404 6.631 ms - -
      1) "before each" hook for "should respond with JSON array"
    POST /api/things
POST /api/things 404 1.037 ms - 24
      2) "before each" hook for "should respond with the newly created thing"
    GET /api/things/:id
      3) "before each" hook for "should respond with the requested thing"
    PUT /api/things/:id
      4) "before each" hook for "should respond with the updated thing"
    DELETE /api/things/:id
      5) should respond with 204 on successful removal
      6) should respond with 404 when thing does not exist

  User API:
    GET /api/users/me
POST /auth/local 200 30.941 ms - 203
GET /api/users/me 200 7.053 ms - 102
      ✓ should respond with a user profile when authenticated
GET /api/users/me 401 7.944 ms - -
      ✓ should respond with a 401 when not authenticated


  2 passing (163ms)
  6 failing
```

**Comment by Awk34** [comment]
Please make sure that [here](/generator-angular-fullstack/blob/3.2.0/app/templates/server/routes.js#L11) you have a line reading `app.use('/api/things', require('./api/things'));`.

**Comment by davehorton** [comment]
Thanks!  To make it work, I need to make a variant of the change you suggested:

```
  app.use('/api/things', require('./api/thing'));
```
i.e. the directory name is not plural.

I then saw that it was retrieving 'things' ok but not displaying my updates.  To fix that, I needed to add the line below in config/socketio.js

```
  require('../api/thing/thing.socket').register(socket);
```
This is all with the stock generated app, so it would probably be nice if the generator was updated.  Would you like me to send a PR?

Thanks again for the help!

**Comment by Awk34** [comment]
The generator should have added those. Did you quit the scaffolding early?

**Comment by davehorton** [comment]
Not to my knowledge, but perhaps something went wrong.  I'll run it fresh and see....

**Comment by davehorton** [comment]
OK, you are right - I re-installed the generator and re-ran to generate the stock app and all is ok.  Not sure what I did but we can chalk this one up to user error I think.

**Comment by jeffbuhrt** [comment]
One possible reason you saw the failure is it doesn't add it if you pick sequelize. #1477 I added a pull request (fix) for it along with four other sequelize fixes. [So I don't have to keep hand fixing them when generating.]
