### ISSUE TITLE
After fresh generation Auth and Admin modules are missing.

### ISSUE THREAD

**Issue by gabrielkunkel** [angular-fullstack/generator-angular-fullstack#1593]
So, I generated a fresh angular-fullstack with

- TypeScript
- MongoDB
- Bootstrap
- Bootstrap UI
- Authentication Boilerplate
- Twitter and Google OAuth
- Grunt
- Jasmine
- HTML
- CSS
- UI-Router

for the settings. 

After I ran npm install and bower install. There were some unmet dependencies, so I installed

- TypeScript, locally
- Mocha, locally
- Tslint, locally

Also, I was getting an error during build that was resolved by installing
- grunt-babel@5.0.0, locally

Now, when I run "grunt serve" It all works just fine, except when I go to the Admin page at http://localhost:9000/admin. There is no list of users. Instead it says, "The delete user and user index api routes are restricted to users with the 'admin' role." All of the links on the navigation bar are dead, except for the app title.

<img width="1260" alt="screen shot 2016-01-29 at 3 05 13 pm" src="https://cloud.githubusercontent.com/assets/2916773/12697473/4ed529e8-c739-11e5-967a-7440e6cf7b63.png">

When I check the console I get these two errors:

> Uncaught Error: [$injector:nomod] Module 'perfectAlgorithmDrillsApp.auth' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
> 
> Uncaught Error: [$injector:nomod] Module 'perfectAlgorithmDrillsApp.admin' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Further errors arise because the module isn't loaded. Obviously, it can't find the controllers, since those modules aren't loaded.

**At this point, I have not added or changed any code.**

I've tried a few things to resolve the situation:

- updating yo and angular-fullstack and then recreating the project from scratch.
- wrapping those "missing" modules in IFFE's.

More Details:
- I am running everything on OSX El Capitan 10.11.2
- I'm running node version 4.2.2, npm version 3.5.3, yo 1.6.0
- in the yo.rc file it says the generator version is "3.3.0-beta.0"
- I have mongod running.
- I'm doing my work in WebStorm, but I haven't used anything that's built in. It's all been command line.
- The TypeScript is being compiled correctly, as the .tmp directory looks good.

Thanks so much for the help. Let me know if you need anymore details.

**Comment by DanielTibbing** [comment]
I think you might have the same problem I had, someone solved it here: [Link](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1552) @gabrielkunkel
