### ISSUE TITLE
grunt build problem with Babel

### ISSUE THREAD

**Issue by joshkopecek** [angular-fullstack/generator-angular-fullstack#1595]
On a (nearly) vanilla install I get a problem with Babel on `grunt serve:dist` and `grunt build`:

`Warning: [BABEL] server/api/collection/collection.controller.js: Unknown option: base.optional Use --force to continue.`

this is corrected by removing the `options: optional: …` sections under babel in the Gruntfile. Then it builds without errors. But I get a serve error:

```SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/josh/Sites/echoes-fullstack/dist/server/index.js:13:28)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
Stopping Express server```

Which I'm guessing is due to the lack of the ES6 compatibility?

**Comment by Awk34** [comment]
Did you try upgrading to Babel 6 without chaning the config?

**Comment by joshkopecek** [comment]
I am running babel@6.3.26 global, just upgraded babel-runtime, babel-core and grunt-babel to the latest versions (all ^6.0.0). Still the same error.

**Comment by Awk34** [comment]
Yeah, make sure you read release notes before upgrading packages by major versions, as there will almost always be breaking changes (5.x.x -> 6.0.0).

**Comment by joshkopecek** [comment]
But this happened with vanilla install. I did not upgrade Babel, it
happened with both 5.x and 6.x

On Mon, 1 Feb 2016, 17:57 Andrew Koroluk <notifications@github.com> wrote:

> Closed #1595
> <https://github.com/angular-fullstack/generator-angular-fullstack/issues/1595>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-fullstack/generator-angular-fullstack/issues/1595#event-534561798>
> .
>
-- 
https://echoes.xyz

**Comment by Awk34** [comment]
Make sure all the node deps installed properly. You might even try wiping `node_modules` and running  `npm install` again.

**Comment by joshkopecek** [comment]
Solved - the problem was with `grunt-babel`. I downgraded to v5.0.3 and it runs fine. Thanks for all your help.

**Comment by Awk34** [comment]
Yeah, that would do it. grunt-babel 5 uses babel 5, and 6 uses babel 6.

**Comment by joshkopecek** [comment]
I don't know whether I changed this manually or it was like this after
generation. I will check.

On Tue, 2 Feb 2016, 13:21 Andrew Koroluk <notifications@github.com> wrote:

> Yeah, that would do it. grunt-babel 5 uses babel 5, and 6 uses babel 6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-fullstack/generator-angular-fullstack/issues/1595#issuecomment-178572259>
> .
>
-- 
https://echoes.xyz
