### ISSUE TITLE
Injector only picks up a few files (yes i have tried changing line endings) 

### ISSUE THREAD

**Issue by MaximilianLloyd** [angular-fullstack/generator-angular-fullstack#1596]
No matter what i do it only picks up a few files.

**Comment by MaximilianLloyd** [comment]
Ok so i am working on a windows 10 machine. I recently setup a project with this generator. Now it will only inject a few select files in the index.html. This is leading to things like the navbar vanishing because the directive is not being created, The socket service and a host of other things are not being created as well.
![skjermbilde](https://cloud.githubusercontent.com/assets/10583205/12754812/0a1ca57e-c9cd-11e5-9e35-0d6aad30e118.PNG)
![skjermbilde1](https://cloud.githubusercontent.com/assets/10583205/12754820/0f318804-c9cd-11e5-98e4-871517c80e7d.PNG)

**Comment by MaximilianLloyd** [comment]
Managed to solve the issue by generating another project with the same options as this one instead i chose gulp instead of grunt. Though this is not the first time it has happend so it is worth to investigate, cheers :smile:

**Comment by Awk34** [comment]
I can't investigate if I can't reproduce the issue (which I can't). If you'd like to investigate further, that would be great. I know you said you made sure you checked line endings, but I'd make super-sure that your're not using CRLF. The injector **really** doesn't like them XD. Do a recursive `dos2unix` if you haven't already, and maybe a recursive permissions check
