### ISSUE TITLE
session rows

### ISSUE THREAD

**Issue by ehijzen** [angular-fullstack/generator-angular-fullstack#1597]
Hi,

I'm running angular-fullstack with postgres and no socket.io on openshift. I notificed that a new row is being added to the Session table every 1 or 2 seconds. No other users are logged in. Does anybody know what's going on? Can I stop this from somehow?

Grtz
Eric

**Comment by andershagebakken** [comment]
Can it be that a new session is saved with every request made to the server?

**Comment by Awk34** [comment]
closed in favor of #1668
