### ISSUE TITLE
user.$save doesn't save changes

### ISSUE THREAD

**Issue by arkdelkaos** [angular-fullstack/generator-angular-fullstack#1601]
````
setClan(user,clan) {
    user.clan = clan;
    this.$log.info(user);
    this.$log.info(this.users);
    user.$save();
  }
````
So, I was expecting to get it working fine this time...but somehow It doesn't.  
When I do that `this.$log.info(user);`, even on `this.$log.info(this.users);` from the original `this.users = User.query();`, I can see that the change is done.  
But then if I look at the request, at the api, `req.user` doesn't have my change. Is like it's saving '"the original version".  
I always thought that when you are doing the changes on the $resource object, and execute $save on the same object, it "save" that object...so I'm completely lost here :?  
It may be the cache?

**Comment by arkdelkaos** [comment]
````
setClan(user,clan) {
    user.clan = clan;
    this.$log.info(user);
    this.$log.info(this.users);
    user.$save()
    .then(res =>  {
      console.log("ok: ");
      console.log(res);
    })
    .catch(req => console.log("err: "+req))
    .finally(() => console.log("always called"));
  }
````
So...the console looks right:
````
ok: 
admin.controller.js:47
Resource {_id: "56b10a3c6e5dc3a410930788", provider: "local", name: "Test User", email: "test@example.com", __v: 0…}$
    $hashKey: "object:132"
    $resolved: true
    __v: 0
    _id: "56b10a3c6e5dc3a410930788"
    clan: "EE2"
    (...)
   always called
````
But then on the api, the `req.user`still doesn't have the change done:
````
{ clan: 'none',
  (...)
 }
POST /api/users/56b10a3c6e5dc3a410930788 204 9.231 ms - -
````
I don't have a clue XD

**Comment by arkdelkaos** [comment]
Ok...it always send "admin" to the api, not the user i'm changing...but why?  
I mean, I'm doing the `$save` on that user, and the $promise shows that user log! Why it's sending always admin (current user)?

**Comment by arkdelkaos** [comment]
I know somewhere, something, is 'sending' the current user (in this case, admin) instead of the user i'm working with. But I haven't found where is that code. It has to be somewhere client-side, and it should be on 'client/components/auth/user.service.js' or 'client/components/auth/auth.service.js'.
I know that on 'client/components/auth/auth.service.js', for example, this function change the current user:  
````
createUser(user, callback) {
      return User.save(user,
        function(data) {
          $cookies.put('token', data.token);
          currentUser = User.get();
          return safeCb(callback)(null, user);
        },
        function(err) {
          Auth.logout();
          return safeCb(callback)(err);
        }).$promise;
    }
````
But I don't see why it should affect my update :?  
I even tried changing to PUT and making a $update on the 'user.service.js' service, and even then I still get the current user on API request :?  
This is driving me nuts...and I cannot find info about it anywhere (weird, or its very easy and I'm blind, or very difficult, and I think that's less likely)

**Comment by arkdelkaos** [comment]
Ok, I found the solution...2 days lost with such a easy problem!  
So frustrating :( But, well, I'l never make the same mistake again xD

**Comment by HectorAnadon** [comment]
And how did you solve the problem?
I am having sort of the same...

**Comment by arkdelkaos** [comment]
Well, I didn't update te solution because I was kind of ashamed of myself for not being able of see it before xD
...but now that I'm not the only one, I should post it xD

The user you are sending is on the body, not on the 'user'; on `req.body` but not o `req.user`.  
The user on `req.body` is the one who is sending the query, then the one 'logged in' at the front-end.  
I didn't saw it until I printed all req on console xD The teaching of the story is to sleep well and look again xD

**Comment by HectorAnadon** [comment]
It wasn't that. I had seedDB: false so I couldn't save new users in the DB

**Comment by Awk34** [comment]
@arkdelkaos all JSON data sent to the server will be in `req.body`. We attach the logged-in-user object to `req` in `auth.service.js`, for example, here: https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/server/auth(auth)/auth.service.js#L41
