### ISSUE TITLE
Returning an array when saving moongose model in passport.js

### ISSUE THREAD

**Issue by roboli** [angular-fullstack/generator-angular-fullstack#1605]
Hi guys,

I just wonder why are we returning an array after saving a mongoose model in google passport?

https://gist.github.com/roboli/027b97f4cdf1d242dc8a

To work properly, I had to change to code in order to return just the first item (the model) of the array into the callback. But maybe I'm missing something...

Thanks.

**Comment by Awk34** [comment]
`user` shouldn't be an array in this case. It should just be the user object. the `.then` should only get passed one parameter, not `numAffected`. I believe it depends on whether you're using a spec-conformant Promise implementation or not.
