### ISSUE TITLE
Gulp serve does not properly reload jade changes.

### ISSUE THREAD

**Issue by BenDiuguid** [angular-fullstack/generator-angular-fullstack#1606]
I tested this by creating a fresh app with the yo angular-fullstack (running v 3.3.0) command choosing gulp and jade.

Reproduction steps.
after the npm i and bower install finishes.
gulp serve (works correctly)
change main.jade
save the file
console logs that the file is reloaded
Finally the page does not change like it is supposed to.

P.S. I have tested the same process with HTML instead of Jade and the HTML scaffolded app works correctly.

**Comment by Awk34** [comment]
Can you test changing [these lines](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/gulpfile.babel(gulp).js#L380-L382) to the following?

```js
    plugins.watch(paths.client.views)
        .pipe(plugins.plumber())
        .pipe(plugins.jade())
        .pipe(gulp.dest('.tmp'))
        .pipe(plugins.livereload());
```

**Comment by BenDiuguid** [comment]
That worked perfectly! Thanks!
