### ISSUE TITLE
Question: How server images from node/express to angular with authori

### ISSUE THREAD

**Issue by ajmarmar** [angular-fullstack/generator-angular-fullstack#1607]
Hi,

How do I serve images from nodejs / Express to angularjs with permission?

In my router controller I've have the following lines:

```
export function getLogo(req, res) {
    fs.exists(config.repoLogos+'/'+req.params.file, (exists) => {
      if (exists){
        res.sendFile(config.repoLogos+'/'+req.params.file);
      } else {
        res.sendFile(config.repoLogos+'/logodefault.png');
      }
    });
```

And I get image in controller of angular with:

```
funciton getLogo(){
    return '/api/resources/logo/' + (this.client.logo || 'default';
}

```

And the template:

`<img ng-src="{{cdc.getLogo()}}" class="img-responsive img-thumbnail img-logo center-block" title="Logo">`

Any idea??

PD: I'm sorry for my english. :-P

**Comment by ajmarmar** [comment]
I tryed with 

```
function getLogoRaw()
$http.get('/api/resources/logo/' + (this.client.logo || 'default')).then(response => {
        this.logo = response.data;
        //console.log(this.logo);
      }, response => {
    
      });
}
```

`<img ng-src="{{cdc.getLogoRaw()}}" class="img-responsive img-thumbnail img-logo center-block" title="Logo">`

but write the bytes in the html but don't show the image.

**Comment by Awk34** [comment]
It would probably be easiest for you to set `ng-src` to a URL. Try something like `<img ng-src="{{'/api/resources/logo/' vm.client.logo}}">`

**Comment by ajmarmar** [comment]
Hi,

Yes, I did its, but in the route of express I did 2 options:

1.- with Authenticate 
`router.get('/logo/:file', auth.isAuthenticated(), controller.getLogo);`

this is than I want, but not run

2.- Without Authenticate
`router.get('/logo/:file', controller.getLogo);`

This run fine, but I want the 1st option.

Thx.

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by Awk34** [comment]
Your \#1 looks like it *should* work. It's not returning the image?
