### ISSUE TITLE
injector not injecting newly created services

### ISSUE THREAD

**Issue by joshkopecek** [angular-fullstack/generator-angular-fullstack#1608]
after making a new service using `yo angular-fullstack:service myService` the new scripts don't inject into index.html.

The problem is with the Gruntfile template defaulting to TypeScript extensions using `<%= scriptExt %>`, and the newly created services are javascript.

I corrected this by replacing my injector files selector with this:
`'<%= yeoman.client %>/{app,components}/**/!(*.spec|*.mock).{ts,js}',`

Is this a mistake or is there another way to inject newly created services?

**Comment by Awk34** [comment]
The issue is that the subgenerators we pull in from generator-ng-component don't support TypeScript yet. You can track it here: https://github.com/DaftMonk/generator-ng-component/issues/27
