### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by studentIvan** [angular-fullstack/generator-angular-fullstack#1610]
What about this feature?

**Comment by gaboAcosta** [comment]
Please at least wait for Angular 2 to be out of beta, many of us use this generator specifically for Angular and forcing Angular 2 would be a deal breaker for us.

**Comment by Awk34** [comment]
I'm working on moving the generator towards a more Angular 2 friendly state, and plan on **eventually** fully supporting Angular 2, but that's a ways off.

**Comment by amejiarosario** [comment]
Angular 2 migration tracked here: https://github.com/angular-fullstack/generator-angular-fullstack/issues/1869
