### ISSUE TITLE
npm WARN EPEERINVALID

### ISSUE THREAD

**Issue by khwerhahn** [angular-fullstack/generator-angular-fullstack#1612]
Just updated angular-fullstack to 3.0.0 and tried to create a fresh project with gulp. Got this error message:
 ```npm WARN EPEERINVALID gulp-tslint@4.2.2 requires a peer of tslint@^3 || >=3.1.0-dev || >=3.2.0-dev but none was installed.```

**Comment by khwerhahn** [comment]
It works if I manually install tslint and typescript manually... they were missing in the package.json....

**Comment by Awk34** [comment]
You're probably using npm 3.0.0+, yes?

We just need to include this in the readme, since npm 3.0.0+ doesn't install peer dependencies for you anymore. We could also change the automated `npm install` to also install tslint automatically.

**Comment by khwerhahn** [comment]
ah ok that explains a lot. thx for the help!

Shouldn't there be support for the newsest npm?

**Comment by Awk34** [comment]
Yeah, but it's less of a priority at the moment. The npm error/warning messages are pretty self-explanatory IMO, also.
