### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by findjonmos** [angular-fullstack/generator-angular-fullstack#1613]
http://fullstack-demo.herokuapp.com/

Currently appears to have an application error.

Wondering if this is why the version of angular-fullstack that I am trying to use might have this same bug as the demo.

**Comment by javidrashid** [comment]
The bug you are describing has nothing to do with the generator. This problem is specific to heroku deployment and not the generator. I think something wrong with how the dynos are scaled for heroku.

**Comment by Awk34** [comment]
That demo isn't maintained anymore, and was removed from the readme a while ago.
