### ISSUE TITLE
Running server in production mode

### ISSUE THREAD

**Issue by tonillo** [angular-fullstack/generator-angular-fullstack#1618]
I'm running: 
- Generator version 3.3.0-beta.0
- [Node.js and npm](nodejs.org) Node ^4.2.3, npm ^2.14.7 on OSX 10.11
- Grunt as task runner  

After build we have index.js in dist/server look like so:

```
'use strict';

// Set default node environment to development
var env = process.env.NODE_ENV = process.env.NODE_ENV || 'development';

if (env === 'development' || env === 'test') {
  // Register the Babel require hook
  require('babel-core/register');
}

// Export the application
exports = module.exports = require('./app');
```

if i set env to 'production' the server ran with the following error: 
```
import express from 'express';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/daton/WebStormProjects/CWA-PACKLY/dist/server/index.js:12:28)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```
it's ok because node 4 not support es2015 import then how can we solve this?

running also in production the babel-core/register? I may encounter problems running babel-core / register in production?
or adding a grunt task that transpile the server code to es5?
what is the best practice?

**Comment by Awk34** [comment]
The server source code doesn't support using the Babel require hook. It assumes that you've run `grunt build` and are running the build code in production: out of the `/dist` folder, with the `NODE_ENV` environment variable set to `production`.

**Comment by elmeerr** [comment]
@Awk34 question about what you've said: to get the enviroment variables on a specific server, the build folder should be named 'dist'? if I change it...it doesn't work? I asking this because I manage to deploy on a EC2 instance but I'm not able to make it facebook_id, etc works...even setting the enviroment variable.

**Comment by Awk34** [comment]
Changing the `dist` folder to another name shouldn't change anything

**Comment by elmeerr** [comment]
@Awk34 thanks for answering...I just want to make sure. I'm trying to figure out why the variables are not working. At least I don't need to worry about the folder's name =)
