### ISSUE TITLE
angular 2 support?

### ISSUE THREAD

**Issue by itrethan** [angular-fullstack/generator-angular-fullstack#1623]
angular 2 will be in beta very soon, any plan to support that?

**Comment by Awk34** [comment]
This has been asked and answered already. Please search issues before creating new ones.

**Comment by Koslun** [comment]
@itrethan angular 2 also already is in Beta since december. See [angular 2 beta blog post announcement](http://angularjs.blogspot.se/2015/12/angular-2-beta.html).

**Comment by itrethan** [comment]
Yes, haven't check for a while, but do we have plan for angular 2 support?
