### ISSUE TITLE
Generator not found after installation with npm

### ISSUE THREAD

**Issue by oshingc** [angular-fullstack/generator-angular-fullstack#1626]
After the installation with the following commands:
npm install -g generator-angular-fullstack 
I tried to create my app but for some reason this don't recognize the generator...
![demo](https://cloud.githubusercontent.com/assets/3100819/12953438/75ac9ab2-cfe8-11e5-8789-8752a1732b7c.jpg)

Any advice?
Thanks!

**Comment by Awk34** [comment]
What does `yo --help` show?

**Comment by oshingc** [comment]
![errors](https://cloud.githubusercontent.com/assets/3100819/12954852/55eaec50-cfee-11e5-91d8-12d530e28bea.jpg)

**Comment by oshingc** [comment]
![erro](https://cloud.githubusercontent.com/assets/3100819/12954907/95aeaa3e-cfee-11e5-86ba-97dbf41f3d1f.jpg)

**Comment by Awk34** [comment]
looks like it's an issue with your node/npm setup. where is the `generator-angular` located?

**Comment by oshingc** [comment]
Is located at C:\usr\local\node_modules\generator-angular-fullstack

**Comment by oshingc** [comment]
![folder](https://cloud.githubusercontent.com/assets/3100819/12958925/077132d2-d002-11e5-8e68-92bf49bf5382.jpg)

**Comment by oshingc** [comment]
![folds](https://cloud.githubusercontent.com/assets/3100819/12959026/93772f7a-d002-11e5-8f43-62057fcd26ec.jpg)

**Comment by Awk34** [comment]
not `generator-angular-fullstack`, but just `generator-angular`. When you run `yo --help`, it shows you all the generators that Yeoman can see. It can see `generator-angular`, but not `generator-angular-fullstack`.

**Comment by Awk34** [comment]
I'm closing as I don't believe this to be an issue with this generator, but your specific setup / installation. Feel free to respond here if you feel otherwise, or check out our Gitter.im chat room.

**Comment by preciousgeorge** [comment]
I still have this issue. still not resolved yet. Been beating my head all day.
