### ISSUE TITLE
"angular-bootstrap": "~0.13.0"-->"angular-bootstrap": "~0.14.3" please

### ISSUE THREAD

**Issue by sindrek** [angular-fullstack/generator-angular-fullstack#1629]
Hi,

angular-bootstrap 0.13.0 does not work with "angular-animate": "~1.4.9", but 0.14.3 does. I found it when using UI bootstrap collapse. So a little tip for you to bump the dependency.

Beside that a fantastic builder!

This project was generated with the [Angular Full-Stack Generator](https://github.com/DaftMonk/generator-angular-fullstack) version 3.3.0.

/BR
Sindre

**Comment by Awk34** [comment]
Might as well update to 1.x.x
