### ISSUE TITLE
ui-sref with generated route not working

### ISSUE THREAD

**Issue by andrewmcewen** [angular-fullstack/generator-angular-fullstack#1633]
I generate a route using `yo angular-fullstack:route about` and then attempted to add the generated route to the navbar. I added the following code to navbar/navbar.controller.ts 

`  menu = [{
    'title': 'Home',
    'state': 'main'
  },{
    'title': 'About',
    'state': 'about'
  }];`

After opening in the browser and clicking on About in the navbar I get the error

`Error: Could not resolve 'contact' from state ''`

**Comment by Yording** [comment]
hi, you can show your link you press

**Comment by andrewmcewen** [comment]
It is the navbar links in navbar/navbar.html

        <li ng-repeat="item in nav.menu" ui-sref-active="active">
            <a ui-sref="{{item.state}}">{{item.title}}</a>
        </li>

**Comment by Yording** [comment]
I see you have a contact link is not navbar.controller.js, 
Any contact state defined ?

**Comment by andrewmcewen** [comment]
Sorry that was the wrong error, the error was actually `Error: Could not resolve 'about' from state ''`.

**Comment by Yording** [comment]
You review client/app/about/about.js i revise the state the about or you show me

**Comment by Yording** [comment]
I review client/app/about/about.js you revise or show me

**Comment by andrewmcewen** [comment]
My client/app/about/about.js looks like this

```javascript
angular.module('fullstackwebsiteApp')
    .config(function($stateProvider) {
        $stateProvider
            .state('about', {
                url: '/about',
                templateUrl: 'app/about/about.html',
                controller: 'AboutCtrl',
                authenticate: true,
                controllerAs: 'about'
            });
    });
```

It looks like `app/about/about.js` and `app/about/about.controller.js` are not being injected into `index.html`. However even when I manually add them the link is still not working.

**Comment by andrewmcewen** [comment]
The issue was that for some reason the js injector in the gruntfile only injects *.ts files, and the generated route had *.js files so they weren't being injected into index.html

**Comment by pedro-ramos** [comment]
Same here, changing the file extension to ".ts" did the trick.
I'm not sure what's the right way though. Should it inject ".js" files as well?
Either way, since we're using _Typescript_ I think it should be generating those files with ".ts" extension.

**Comment by Awk34** [comment]
This relates to https://github.com/DaftMonk/generator-ng-component/issues/27 . I have updated generator-ng-component to generate .ts files instead of .js, but still need to release a new version. For now, you'll just have to change the extension from .js to .ts.
