### ISSUE TITLE
Binary files are corrupted in dev mode

### ISSUE THREAD

**Issue by Toub** [angular-fullstack/generator-angular-fullstack#1636]
Binary files dynamically generated and downloaded from the api are corrupted, due to connect-livereload trying to inject code into the binary.

The issue is discussed here: https://github.com/intesso/connect-livereload/issues/39

This can be fixed by configuring connect-livereload to ignore /api path in server/config/express.js:
``` js
if ('development' === env) {
        app.use(require('connect-livereload')({
            ignore: [/^\/api\/(.*)/,
                /\.js(\?.*)?$/, /\.css(\?.*)?$/, /\.svg(\?.*)?$/, /\.ico(\?.*)?$/, /\.woff(\?.*)?$/,
                /\.png(\?.*)?$/, /\.jpg(\?.*)?$/, /\.jpeg(\?.*)?$/, /\.gif(\?.*)?$/, /\.pdf(\?.*)?$/
              ]
        }));
    }
```

To reproduce, simply download a binary from the api using [res.download](http://expressjs.com/en/api.html#res.download).

**Comment by jchukwum** [comment]
@Toub,

This was quite helpful. Thank you so much. 

John
