### ISSUE TITLE
Failed to load external module babel-register

### ISSUE THREAD

**Issue by wangjiaji** [angular-fullstack/generator-angular-fullstack#1638]
If you initiate a new app with gulp, after `gulp serve`, the first line is an error saying: 

> Failed to load external module babel-register

Then the app starts up fine, will it have any further effects?
The options I made during the setup are:

- Babel
- Jade
- Sass
- ngRoute
- Include Bootstrap
- Include UI Bootstrap
- Data Modeler: None
- Gulp
- Jasmine

I'm on Mac, El Capitan

**Comment by timothystewart6** [comment]
I am experiencing the same thing.

**Comment by Awk34** [comment]
Do you guys have babel 6 installed globally? I think that's what causes it. I still haven't upgraded to Babel 6 because of issues I had with the first initial versions of it, but those are probably fixed by now.

**Comment by timothystewart6** [comment]
➜  project git:(develop) npm list -g --depth=0
/Users/user/.nvm/versions/node/v5.6.0/lib
├── bower@1.7.7
├── generator-angular-fullstack@3.3.0
├── grunt-cli@0.1.13
├── gulp@3.9.1
├── npm@3.6.0
└── yo@1.6.0



➜  project git:(develop) node --version
v5.6.0
➜  project git:(develop) npm -v
3.6.0


➜  project git:(develop) gulp build
[18:37:14] Failed to load external module babel-register
[18:37:14] Requiring external module babel-core/register
[18:37:15] Using gulpfile ~/Documents/projects/project/gulpfile.babel.js

**Comment by Awk34** [comment]
IIRC babel-register is the new way to run a Node.js require hook, and babel-core/register is the old way

**Comment by timothystewart6** [comment]
Thanks.  Should this just be ignored?

**Comment by Awk34** [comment]
@timothystewart6 yeah, if it can't register with one method, but can with another, yeah it's fine.

**Comment by codeofsumit** [comment]
I have the same issue although I did not select babel during setup.
This is my config:

Typescript
HTML
Sass
ngRoute
Don't Include Bootstrap
Don't Include UI Bootstrap
Gulp
Jasmine

This is the error:
```
gulp serve
[19:16:55] Failed to load external module babel-register
[19:16:55] Requiring external module babel-core/register
```

What can I do about it?
