### ISSUE TITLE
Module 'generatorApp.constants' is not available

### ISSUE THREAD

**Issue by dciccale** [angular-fullstack/generator-angular-fullstack#1642]
It fails loading the constants module when `serve:dist` is run **for the first time**

node: v4.3.0
npm: 3.7.2
grunt-cli v0.1.13
yo: 1.6.0

```sh
$ npm install -g yo grunt-cli bower generator-angular-fullstack
$ mkdir generator && cd $_
$ yo angular-fullstack [app-name]
```

```sh
Out of the box I create an AngularJS app with an Express server.

# Client

? What would you like to write scripts with? Babel
? What would you like to write markup with? HTML
? What would you like to write stylesheets with? Sass
? What Angular router would you like to use? uiRouter
? Would you like to include Bootstrap? Yes
? Would you like to include UI Bootstrap? Yes

# Server

? What would you like to use for data modeling? Mongoose (MongoDB)
? Would you scaffold out an authentication boilerplate? Yes
? Would you like to include additional oAuth strategies? 
? Would you like to use socket.io? Yes

# Project

? Would you like to use Gulp or Grunt? Gulp
? What would you like to write tests with? Mocha + Chai + Sinon
? What would you like to write Chai assertions with? Expect
You're using the fantastic NgComponent generator.
```

```sh
$ gulp serve:dist
```

`http://localhost:8080/` 

`DevTools output`
![screen shot 2016-02-18 at 11 02 20](https://cloud.githubusercontent.com/assets/539546/13139887/24fd9042-d62f-11e5-936b-a0937b0d7e09.png)

the file `app.constants.js` is there, but it just fails.

If I run `serve:dist` a second time it works.

You can reproduce this as many times as you want by running:
`rm client/app/app.constants.js && rm -rf dist && rm -rf .tmp && gulp serve:dist `

**Comment by Awk34** [comment]
I can't reproduce this with the latest version of the generator. If you believe it's still a bug, feel free to re-open

**Comment by dciccale** [comment]
did you followed exact command to reproduce?

I can reproduce it all the time.

I am using:
- OS X 10.11.3
- Node v4.3.0
- npm 2.14.12
- yo 1.7.0

**Comment by dciccale** [comment]
maybe.. but I'm not sure what to try, maybe if someone else could try this would be interesting to know the result

**Comment by Awk34** [comment]
Can you try it using a fresh generator 3.4.0 version?

**Comment by dciccale** [comment]
I was using `3.4.0`

**Comment by Stalso** [comment]
I also have this bug on Windows
