### ISSUE TITLE
Error: Could not find the following rules specified in the configuration: no-trailing-comma

### ISSUE THREAD

**Issue by lydemeister** [angular-fullstack/generator-angular-fullstack#1652]
After doing yo angular-fullstack for gulp + ts, "npm install" and running gulp serve I get the error:

> Error: Could not find the following rules specified in the configuration: no-trailing-comma

The error comes from tslint.

Btw tslint needs to be added to --save-dev.

**Comment by Awk34** [comment]
This has been fixed on master with https://github.com/angular-fullstack/generator-angular-fullstack/commit/d7cd347ce32c546dcbcdfcfbabc440bef2eecd36 .

tslint doesn't follow semver (no breaking changes in minor release versions) which is why this happened
