### ISSUE TITLE
tooltip flickering?

### ISSUE THREAD

**Issue by khchong** [angular-fullstack/generator-angular-fullstack#1659]
I just tried out this generator since I'm looking to try out MEAN stack in developing a little side project. 

I noticed some weird flickering where hovering between different "things" causes the tooltip to flicker, where it will for a split second show up from the bottom, then show up at the top normally.

Not sure what causes it and if it's supposed to be like that? I'm assuming this is bootstrap's tooltip (I installed bootstrap ui with sass).

**Comment by Awk34** [comment]
I've never seen it. Look through the angular-ui bootstrap issues.
