### ISSUE TITLE
Grunt serve error: unexpected reserved word.

### ISSUE THREAD

**Issue by mokargas** [angular-fullstack/generator-angular-fullstack#1664]
Variations on this error have been discussed before, but I'm not sure I comprehend them.

 I'm hoping someone can shed some light on what I'm missing here (In particular why the server doesn't run)

Using "grunt serve" or "grunt serve:debug", I get the following

`running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858
/Users/mkargas/Projects/swhe/server/app.js:7
import express from 'express';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mkargas/Projects/swhe/server/index.js:12:28)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
Stopping Express server
`

I get this is something to do with babel on the server side, because "grunt serve:dist" will run the server fine. How do I get dev or debug mode to serve on localhost?

Versions (Mac Yosemite 10.10.5):

Node: v4.2.2
Generator: 3.3.0
grunt-babel: 5.0.0
Babel runtime: 5.8.20

**Comment by Shinobi881** [comment]
+1 on `gulp`

**Comment by Shinobi881** [comment]
Rather `Unexpexted token import`

**Comment by Awk34** [comment]
@mokargas @Shinobi881 can you confirm that this is the same in your project? https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.3.0/app/templates/server/index.js#L6

**Comment by mokargas** [comment]
@Awk34 The file is identical on my end

**Comment by Awk34** [comment]
What does `npm list -g --depth=0` show?

**Comment by mokargas** [comment]
@Awk34 Quite a few missing deps, I've placed them here https://gist.github.com/mokargas/6bf40b9fe2fb389809c9

**Comment by Shinobi881** [comment]
**Global Dependcies: ** https://gist.github.com/Shinobi881/55976c9dd2ec7eafc23c

Error:

```
$ => gulp
[21:34:22] Requiring external module babel-register
/Users/Martial-One/Desktop/Coding/yongfull/gulpfile.babel.js:5
import _ from 'lodash';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at loader (/Users/Martial-One/Desktop/Coding/yongfull/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Martial-One/Desktop/Coding/yongfull/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at execute (/Users/Martial-One/.npm-packages/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/Users/Martial-One/.npm-packages/lib/node_modules/gulp-cli/index.js:150:63)```

**Comment by mokargas** [comment]
Some more information:

Tested on a colleagues Windows 7 x64 environment, works fine. Unfortunately, my development machine isn't Windows.

**Comment by mokargas** [comment]
Hi @Awk34 Right, I figured this out. Rather simple actually, and nothing at all wrong with the project.

Simply put, my process.env was returning "dev" (set for previous node projects), not the fully qualified "development". This means it was looking for "dev.js" not "development.js". 

Because I need to keep "dev", I simply duplicated development.js to dev.js, and added it to index.js

**Comment by Awk34** [comment]
@mokargas ah sounds good

**Comment by Awk34** [comment]
@Shinobi881 It looks like you're using Babel 6. You need so set the right config with Babel 6 for it to resolve the import/export syntax to CommonJS, in a `.babelrc` file.

**Comment by jpaaso** [comment]
I'm getting the same error with grunt. 

> It looks like you're using Babel 6.

What's the correct version or configuration for Babel?

**Comment by jpaaso** [comment]
I think the problem was that my NODE_ENV was "dev". It seems to work with an empty value (=development) and "production".

**Comment by Cdvalencia** [comment]
@Awk34 
i am having this same problem on version dist.
import express from 'express';
^^^^^^
SyntaxError: Unexpected token import


this is my versions:
node v6.11.1
npm 3.10.10
+-- bower@1.8.0
+-- grunt@1.0.1
`-- grunt-cli@1.2.0

**Comment by Awk34** [comment]
Make sure you're setting `NODE_ENV` to `'production'`. Ex:
```bash
$ NODE_ENV=production node ./server
```

**Comment by Cdvalencia** [comment]
@Awk34 
node say that --"NODE_ENV" is Not recognized as an internal or external command'--

**Comment by Cdvalencia** [comment]
@Awk34 
i´ve used. 
- cmd Windows 8
- Node.js Command promt
- ConEmu64

**Comment by Awk34** [comment]
For Windows command prompt: https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt

**Comment by Cdvalencia** [comment]
@Awk34 , the command on windos is: set NODE_ENV=production && node dist/server/app.js. 

And error persist, it is show _import express from 'express';_. 

the same error.

**Comment by Cdvalencia** [comment]
this is my solution --> [Solution](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1282#issuecomment-139658845)

thanks @Awk34
