### ISSUE TITLE
import fs from 'fs' error with v. 3.3.0 

### ISSUE THREAD

**Issue by ericmontreal** [angular-fullstack/generator-angular-fullstack#1667]
Using Node v.5.6.0, npm v.3.6.0, babel-core:5.8.35, generator-angular-fullstack v 3.3.0 ( with index.js files already fixed) I get:
____________________________
$ sudo yo angular-fullstack myapp
/usr/local/lib/node_modules/generator-angular-fullstack/app/generator.js:3
import fs from 'fs';
^^^^^^

SyntaxError: **Unexpected token import**
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:387:25)
at loader (/usr/local/lib/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
at Object.require.extensions.(anonymous function) as .js
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object. (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:9:28)
at Module._compile (module.js:413:34)
_________________

Any clue ?
Thx for your help

**Comment by Awk34** [comment]
Hmmm, do you maybe have a `.babelrc` somewhere that's overriding the `import` to CommonJS behavior?

**Comment by ericmontreal** [comment]
Thank's for giving an help,Awk34
Not a wiz with bash but
sudo find . -name ".babelrc" -ls 
from /
found nothing :(

**Comment by Awk34** [comment]
Oh, I'm pretty sure I know what the issue here is. It looks like you have `babel-core` @6.0.0+ installed globally, and the generator is picking that version up instead of the one installed with the generator. Try `npm uninstall -g babel-core` and running the generator again.

**Comment by ericmontreal** [comment]
Sorry for the delay..
I  globally uninstalled babel-core but the command gives me now:
module.js:341
    throw err;
    ^

Error: Cannot find module 'babel-core/register'

**Comment by Awk34** [comment]
Try `npm uninstall -g generator-angular fullstack` and then `npm install -g generator-angular fullstack`

**Comment by ericmontreal** [comment]
It just gave me the following warnings:

npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

**Comment by ericmontreal** [comment]
the yo command gives me the same err msg:
Error: Cannot find module 'babel-core/register'
I try to be helpful in any way.
:(

**Comment by ericmontreal** [comment]
Being stuck,  reinstalled my node environment and everything finally worked well.
Thx again Awk34.

**Comment by HECTORkaizen** [comment]
How you do that?
I have the same promblem (import fs from 'fs'...)
this is the message "Everything looks all right!" in the console when `$yo doctor`
I re-installed all but the problem persist, how you do reinstalled "node environment" ? I have Windows 8.1 [[I Know, I know... =(... but I hope son install and configure linux jajja ]]
