### ISSUE TITLE
EJS variables not rendered 

### ISSUE THREAD

**Issue by mokargas** [angular-fullstack/generator-angular-fullstack#1672]
This is more a question on approach. Classically the following approach has worked for me, but not with this stack.

I'm currently trying to pass some variables to the front-end template. For some reason they don't render. My assumption is some other magic is going on, I just can't find out where. In routes.js: 

```
var strings = require('./config/strings');

  // All other routes should redirect to the index.html
  app.route('/*')
    .get((req, res) => {
      res.render(path.resolve(app.get('appPath') + '/index'), {
        strings: strings
      });
    });
}

```
Where ./config/strings is a JSON file of external strings. 

Using 'grunt serve', I only see the EJS tokens. If I pass a general string:

`strings: "A string"`

The same thing happens. Any ideas or guidance on how to load strings with this stack would be appreciated.

**Comment by Awk34** [comment]
I don't think Express by itself supports EJS. You'll have to `require('ejs')`

**Comment by mokargas** [comment]
Isn't that already done in Express.js or am I missing something?

**Comment by Awk34** [comment]
oh hmm yeah EJS *is* in there by default, but set like this:

```js
app.engine('html', require('ejs').renderFile);
app.set('view engine', 'html');
```

try just this
```js
app.set('view engine', 'ejs');
```

**Comment by mokargas** [comment]
Thanks @Awk34 I had that as well, what I was missing was renaming the html files to .ejs. Don't really understand why that is required but there you go.

**Comment by Awk34** [comment]
Ah okay. You *should* be able to get it to work with `.html`, but I haven't fiddled with it any. Thanks for the info.

**Comment by mokargas** [comment]
Just revisited this. It works for index.html/index.ejs, but not for html/ejs files under /components or /app. I've tried creating another route in routes.js but no go. Any ideas on how to make directive templates go through EJS before returning to the browser?
