### ISSUE TITLE
Arrows not working

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1675]
when using the generator, the arrows are not working and i cannot make any selection.
i updated node to the latest (5.7.0) as some user suggested, no luck.
![image](https://cloud.githubusercontent.com/assets/5527427/13417074/5b63fa76-df36-11e5-8199-744baa63a67d.png)

**Comment by RonAlmog** [comment]
i have found that you can type 1 or 2 for babel or typescript, and it works.
(and after that even the arrows work)
so it's not a show stopper, but annoying, and i would like to know what's causing it.

**Comment by RonAlmog** [comment]
why close? it is a bug, i can replicate on other machines, so it is definitely a bug, and needs to be resolved. the arrows are not responding, so the user cannot actually use the generator.

**Comment by Awk34** [comment]
Whoops, I forgot to link the duplicated issue: #1476 . There's nothing *I* can do about it.
