### ISSUE TITLE
How to set the app name?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1682]
when creating a new app with the generator, it uses the folder name for the application name, and not the param.
here is what i tried:
- yo angular-fullstack app
- yo angular-fullstack 'app'
- yo angular-fullstack [app]
- yo angular-fullstack:app app

no luck. in all cases it ignores the param and uses the folder name. any advice?

**Comment by taotau** [comment]
The last one, as per instructions 

Usage:
  yo angular-fullstack:app [options] [<name>]

Options:
  -h,   --help          # Print the generator's options and usage
        --skip-cache    # Do not remember prompt answers                        Default: false
        --skip-install  # Do not install dependencies                           Default: false
        --app-suffix    # Allow a custom suffix to be added to the module name  Default: App

Arguments:
  name    Type: String  Required: false

**Comment by RonAlmog** [comment]
example of usage?
custom suffix: nothing.
app name: app

thanks

**Comment by RonAlmog** [comment]
looks like a bug to me. no matter what you do, it takes the folder name, and adds the suffix (App).
if you know any way to give the app any specific name without a suffix, please let me know.

**Comment by Awk34** [comment]
should be fixed in next patch
