### ISSUE TITLE
Facebook login works but no additional permissions

### ISSUE THREAD

**Issue by bitflower** [angular-fullstack/generator-angular-fullstack#1683]
Hi,

the Facebook login works like a charm straight outta the box.

However when trying to access the list of friends of the user for a certain app with the "user_friends" permission I get an error 440 with this response:
```
{
   "error": {
      "message": "Bad signature",
      "type": "OAuthException",
      "code": 1,
      "fbtrace_id": "Foedq4uUQhf"
   }
}
```

The Facebook app is set up as basic as possible and the 3 basic review-free permissions are: email, public_profile & user_friends. As the login works I believe that this was all done right up to this point.

I have added the "user_friends" permission to the scope in the file auth/facebook/index.js.

My call to the endpoint looks like this (in main.controller):
```
  getFBFriends() {
      this.$http.get('https://graph.facebook.com/me/friends?access_token=' + this.Auth.getToken());
  }
```

Do I have to set the passport Facebook strategy differently to be able to use additional permission that go beyond the login?

Would be grateful for some pointers.

Thanks

**Comment by Awk34** [comment]
Sorry for the late response. Here's a list of possible FB permissions you can add: https://developers.facebook.com/docs/facebook-login/permissions
