### ISSUE TITLE
App.constant.js wiped out by Grunt ng-constants task

### ISSUE THREAD

**Issue by mokargas** [angular-fullstack/generator-angular-fullstack#1684]
A task runs on grunt serve or when building, called ngconstant.  It copies the content from shared.js in /server/config/environment into app.constants.js under client/app. This task will completely empty app.constant.js of any other constants added to that file.

I need to add custom constants to my app. What is the recommended way to do this within this boilerplate?

**Comment by Abdizriel** [comment]
You have to add every constant /server/config/environment/shared.js
Not to client/app/app.constant.js

**Comment by mokargas** [comment]
Wait, even though my front-end constants may have nothing to do with the server? What if I have multiple front-end clients? 

This would mean their constants are buried in the server, who's architecture I may want to change or remove entirely?

**Comment by smirciat** [comment]
Its a convention that was used in this generator's design.  Put the constants in that file, during the build grunt (or gulp) copies them to a usable area of the client side, therefore you only have to update your constants in one place.  Server and client code will have access to the same constants.

**Comment by Awk34** [comment]
Yeah as @smirciat said it's by design. Any variables in the `shared.js` are available to the server, and then the ngConstant task creates an Angular module for the shared constants on every build. This provided for convenience, as this is a full-stack generator.
