### ISSUE TITLE
How to get the current user?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1685]
I would like to create a user setting page, where she can set her preferences, address, etc.
all in her User schema.  How to do that? I actually need 2 methods:
one to read user info, one to save user info.
i thought Auth.getCurrentUser()  will help me get the current user, but i can't make it work.
i get "getCurrentUser is not a function...." 
Any tip, example, link for further reading?  
Thank you!

**Comment by smirciat** [comment]
I have struggled with this concept as well, but I think I'm finally getting it.  If you look at the Auth factory, you will see that getCurrentUser returns either a result or a promise.  This allows it to be called either right as a login is being completed, or at another time when the login status is fixed.  In general terms, I get a promise when the function is evaluated immediately after the user logins, and a fixed result during any user fired functions that are called later. So far, my best usage has been to set in the controller's constructor section:
```
this.user = Auth.getCurrentUser;
```
Then, whatever function I need the user for, I use this.user() which will resolve to the current user.  When referencing if from the html view, I use things like ng-show="controllerName.isLoggedIn()" (a function from the same factory). Just keep in mind that whenever referencing this, you may get a promise or a result back, so you need to be ready to handle either.

**Comment by AmirGilboa** [comment]
@smirciat , thank you so much!
with your help i was able to grab the user data. a bit awkward, but hey, it's working.

    $scope.init = function(){
      this.getCurrentUser = Auth.getCurrentUser;
        this.getCurrentUser(function(data){
          console.log('data: ', data); 
          vm.authuser= data;
        });
    }

so again, big thank you.

**Comment by KhizarSH** [comment]
For the above solutions we will get vm undefined in-order to use this function in an onit u can refer the below one some update has made to above one thankyou @AmirGilboa 

 $onInit() {
  var vm = this;
   this.getCurrentUser =this.Auth.getCurrentUser;
    this.getCurrentUser(function(data){
      vm.currentuser = data;
      alert(JSON.stringify(vm.currentuser))
      alert(vm.currentuser._id)
    });
   
  }
