### ISSUE TITLE
Waiter, there's a class in my javascript!

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1686]
Forgive me for this very "newbee" question, but it's important for me to understand.
I used the generator to create the skeleton for my app, and i'm changing and adding to suit my needs. Now i'm looking at this file, **admin.controller.js**  , and i'm confused: what is this? class? constructor? hey, this is a javascript file, at least by it's filename, no?  there are no classes in javascript.
if it would be typescript/babel or any of those, the extension would be different, and there would be a conversion to javascript on every save. but here this does not happen, and this code seems to be working without any conversion. How?

`'use strict';

(function() {

class AdminController { 
  constructor(User) {
    // Use the User $resource to fetch all users
    this.users = User.query();
  }

  delete(user) {
    user.$remove();
    this.users.splice(this.users.indexOf(user), 1);
  }
}

angular.module('trApp.admin')
  .controller('AdminController', AdminController);

})();
`

**Comment by arg20** [comment]
Ecmascript 6 added syntactic sugar to support "classes".

**Comment by Awk34** [comment]
#1281
