### ISSUE TITLE
Extra user details: in user schema, or a different schema?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1689]
Users are important part of my app. they have tons of information.
address, phones, location, bio, etc.
Should i add all this to the user schema, or create a separate schema/table for that, and reference back to user schema?

as always, any link to discussion, blog, example, tutorial,  is much appreciated.

**Comment by smirciat** [comment]
I've done it both ways, they both work fine.  The generator is definitely set up to include additional user attributes in the schema, then add then to the User and Auth services for manipulation.  My problem was I tried it a few times, made a mistake, then I couldn't authenticate my users at all.  But certainly if you do it carefully, I think using the user schema would be preferred.

**Comment by AmirGilboa** [comment]
i have found this interesting project, Drywall, http://jedireza.github.io/drywall/
and they used a separate account schema too. so i guess that's the right way to go.
thanks!

**Comment by AmirGilboa** [comment]
but how to connect these 2? 
should they have the same _id ? 
or each have their own _id, and the schema has like a "foreign key" to the user?
how to seed the user with the account? i need to know the _id that has been created...

**Comment by smirciat** [comment]
When I set up the separate model, I had a field for user id, which is self explanatory.  Then I looked it up based on this.getCurrentUser()._id.  The danger here is ending up with duplicate entries for the same user, so you'll either have to check for that, or place a unique index on your database for the user id field.

**Comment by remicastaing** [comment]
Having two separate model, one for the account and another for the user could be an answer to the multiple social account issue (https://github.com/angular-fullstack/generator-angular-fullstack/issues/1681 or https://github.com/angular-fullstack/generator-angular-fullstack/issues/359). 
After checking that the email is the same and also verified, you could link several accounts to the same user. To simplify the process I wouldn't allow to fill additional infos in the user model before the email is verified (local strategy and tw strategy).
With two separate models, the complete registration logic would be hold in the account model and users of this generator would only focus on specific logic in a custom user model.
The generator could also provide some hooks to automatically fill some user infos according to the provided social data (first name, last name, etc.)
