### ISSUE TITLE
Invalid call to lazypipe().pipe() 

### ISSUE THREAD

**Issue by MaximilianLloyd** [angular-fullstack/generator-angular-fullstack#1693]
Why is this happening?
![skjermbilde](https://cloud.githubusercontent.com/assets/10583205/13594585/c1061574-e505-11e5-8a07-5860d5dc6277.PNG)

**Comment by Awk34** [comment]
You're trying to use a lazypipe chain without giving it an input stream. I haven't seen this happen anywhere in the generated app. It must have come from your own code. Read more on lazypipe here: https://github.com/OverZealous/lazypipe
