### ISSUE TITLE
Error Failed to load resource: Couldn't locate the fonts files being used while serving the from the dist directory

### ISSUE THREAD

**Issue by kunal12422** [angular-fullstack/generator-angular-fullstack#1694]
Hi there, 
I noticed that filerev is renaming the **font** files in **assets** directory under **dist** but these changes are not reflected back in **dist** version of app.css file causing the server to return 404 Not found.

![screenshot from 2016-03-09 02 30 46](https://cloud.githubusercontent.com/assets/9267351/13618827/282a6a7e-e5ac-11e5-88dd-a4dbaf978b57.png)
![screenshot from 2016-03-09 02 30 19](https://cloud.githubusercontent.com/assets/9267351/13618833/2ec99bde-e5ac-11e5-8e22-7a63e9cad193.png)

Here is config in gruntfile.js 

 // Renames files for browser caching purposes
    filerev: {
      dist: {
        src: [
          '<%= yeoman.dist %>/<%= yeoman.client %>/!(bower_components){,*/}*.{js,css}',
          '<%= yeoman.dist %>/<%= yeoman.client %>/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}'
          ,'<%= yeoman.dist %>/<%= yeoman.client %>/assets/fonts/*'   
        ]
      }
    },

    // Reads HTML for usemin blocks to enable smart builds that automatically
    // concat, minify and revision files. Creates configurations in memory so
    // additional tasks can operate on them
    useminPrepare: {
      html: ['<%= yeoman.client %>/index.html'],
      options: {
        dest: '<%= yeoman.dist %>/<%= yeoman.client %>'
      }
    },

    // Performs rewrites based on rev and the useminPrepare configuration
    usemin: {
      html: ['<%= yeoman.dist %>/<%= yeoman.client %>/{,!(bower_components)/**/}*.html'],
      css: ['<%= yeoman.dist %>/<%= yeoman.client %>/!(bower_components){,*/}*.css'],
      js: ['<%= yeoman.dist %>/<%= yeoman.client %>/!(bower_components){,*/}*.js'],
      options: {
        assetsDirs: [
          '<%= yeoman.dist %>/<%= yeoman.client %>',
          '<%= yeoman.dist %>/<%= yeoman.client %>/assets/images',
          '<%= yeoman.dist %>/<%= yeoman.client %>/assets/'
        ],
        // This is so we update image references in our ng-templates
        patterns: {
          js: [
            [/(assets\/images\/.*?\.(?:gif|jpeg|jpg|png|webp|svg))/gm, 'Update the JS to reference our revved images']
          ]
        }
      }
    }

**Comment by Awk34** [comment]
Hmmm, not quite sure why `assets/fonts/` is included in filerev. Font files won't really be changed. Just excluding fonts from filerev fixes things, right?

**Comment by kunal12422** [comment]
yes, excluding fonts from filerev fixes things.

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/commit/522853670e8e635d67ad35fd8154e2a7bd9b99b3

**Comment by kunal12422** [comment]
:+1:  Also, I uninstalled and reinstalled  **grunt-contrib-imagemin**  and this resolved my problem.
