### ISSUE TITLE
POST/PUT stops server, but without crash

### ISSUE THREAD

**Issue by andershagebakken** [angular-fullstack/generator-angular-fullstack#1695]
Hi. When I try to do a POST or a PUT, from time to time, the server stops without crashing. The console does not show the request URL like it does with every request that is made, but it does not crash or give any errors. When I reload the page, nothing wants to load, so I have to do a restart of the server. This is something that just started happening without changing anything on the server at all. And it kinda happens random places, sometimes it happens when I try to log in, and sometimes the login works. Again, no error or crash on server, it appears idling. 

What I have noticed, is that when I now try to add an endpoint to my app, the controller is basically empty, just the index with a res.json([]) response. It usually sets up the entire model with all CRUD options. 

Edit: It seems like this only happens when running "grunt serve", when I do grunt build, and run it in production environment, it seems to be working. I have not been able to produce the same issue on production env, yet, at least.

Any idea on how I can solve the POST/PUT issue? Thanks so much in advance.

**Comment by Awk34** [comment]
No idea, never seen anything like that

**Comment by Awk34** [comment]
Closed due to inactivity
