### ISSUE TITLE
How about using a config file for the generator?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1696]
This is more of a suggestion. because i spend lots of time running the generator over and over again with different selections, it would be very helpful if the generator could use a json config file.
all those question like babel/typescript, html/jade, etc.  if there is a config file located in the current folder, then take the selections from the file. otherwise, go on with your questions...
so you can have your carefully selected options in a file, (or more then one, for different preferences),
and use them quickly when needed. your thoughts?

**Comment by remicastaing** [comment]
You could use the `.yo-rc.json` as a config file, @AmirGilboa, couldn't you?

**Comment by Awk34** [comment]
Yeah, that's exactly what the `.yo-rc.json` file does.

**Comment by AmirGilboa** [comment]
how do i use it?
it has many more options than the wizard questions.
but anyways, take it as is, put in a new folder, and run the generator?
is there any doc/instructions on this?

and this is true in general: this is a very mighty machine, but with close to zero documentation or user guides, or anything like this. I always feel that this thing is very powerful, but i don't have the keys to the castle. people know things that i don't know. like this yo-rc thing. 
if there was a book, or user guide, (beyond the very brief in the github page), that could be a great help, and would bring many more people.

**Comment by Awk34** [comment]
Documentation is here: http://yeoman.io/authoring/storage.html

There is more work being done to add more documentation around this generator
