### ISSUE TITLE
Question on dependencies

### ISSUE THREAD

**Issue by bobby77** [angular-fullstack/generator-angular-fullstack#1697]
Dear all,
Sorry if my question is not relevant. 
I am surprised on the dependencies behaviour with the last version, as it didn't do that before.

I started an empty angular-fullstack app & launched npm install.

In the node_modules, there are 885 directories with packages... I find it to be huge... (and package.json is only 95 lines). The list is attached. 
In previous applications, I have around 90 directories in node_modules directory.

Does it look OK for you? 
Is it due to a change in this repository or in how npm manages packages?
Node & npm versions should be up to date, as I had troubles and updated them recently.
node version: v5.7.1 - npm version: v3.8.0

Thanks a lot.

[node_module directory list.txt](https://github.com/angular-fullstack/generator-angular-fullstack/files/165579/node_module.directory.list.txt)

**Comment by bobby77** [comment]
Sorry, actually this is due to the new npm way of working since 3.3.3

"npm 3.3.3 installs submodule dependencies in the root node_modules folder"
-> https://github.com/npm/npm/issues/9675

Still, 885 packages used for a "blank" application. It seems quite huge...
Best regards.

**Comment by Awk34** [comment]
Yep, that's due to your updated npm version. All those deps were there before, probably even more, just buried in subdirectories. That's the nature of a Node.js application.
