### ISSUE TITLE
FYI: Practical articles how to use generator-angular-fullstack

### ISSUE THREAD

**Issue by yoshiokatsuneo** [angular-fullstack/generator-angular-fullstack#1698]
FYI: I'm writing a series of articles how to build web applications using generator-angular-fullstack.
Hopefully, it helps for people using generator-angular-fullstack.

- [Building full-stack web service - MEAN stack development(1)](http://engineering.paiza.io/entry/2015/07/08/153011)
- [Building Twitter-like full-stack web service in 1 hour - MEAN stack development (2)](http://engineering.paiza.io/entry/2015/07/09/154028)
- [Building a QA web service in an hour - MEAN stack development(3)](http://engineering.paiza.io/entry/2016/03/10/115345)

**Comment by Awk34** [comment]
Thanks

(Closing so I know that this isn't something I have to follow up on; feel free to continue discussion in here.)

**Comment by AmirGilboa** [comment]
good stuff! i love those articles, and think they are great!  please keep on doing this!
