### ISSUE TITLE
Question: how does the Auth.isLoggedIn function work?

### ISSUE THREAD

**Issue by dieguezz** [angular-fullstack/generator-angular-fullstack#1699]
Hi, i am sure this is an stupid question but i am a bit stuck here, so any help would be appreciated.

In Auth service we got the following function:

    isLoggedIn: function(callback) {
      if (arguments.length === 0) {
        return currentUser.hasOwnProperty('role');
      }

      return Auth.getCurrentUser(null)
        .then(function(user) {
          var is = user.hasOwnProperty('role');
          safeCb(callback)(is);
          return is;
        });
      }

As far as i understand, there is a function that returns a boolean (if called without arguments) or a promise called with a callback. So, if you call it with a callback, why would you need a promise?

I don't really understand it because onRouteChangeStart there is the following:

`          Auth.isLoggedIn().then(is => {
            $location.path(is ? '/' : '/login');
          });`

If its called without params, why does return a promise?

**Comment by Awk34** [comment]
The auth functions are called without params for example, in the [navbar template](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.4.0/app/templates/client/components/navbar/navbar(html).html#L21). Angular doesn't know how to deal with promises or callbacks, so we need a synchronous method in that case.
