### ISSUE TITLE
Generated app with sequelize => notes

### ISSUE THREAD

**Issue by khwerhahn** [angular-fullstack/generator-angular-fullstack#1707]
Hi,

I just generated a new app with sequelize with auth boilerplate. Really nice work. Really like it! I went through the app and have some questions.

Shouldn't the generator ask what database is used (mysql/pg/sqlite), as it has some implications? First, of course, dependencies and secondly also coding styles. For example: I'm not sure if I'm right or wrong here, but I have never seen in a pg/mysql environment the "_id" style used. Best practise? This is used in the ```auth.service.js``` etc. . I know, that this style is used in a Mongo environment. So maybe the generator needs to make a better distinction about the different databases used.

**Comment by smirciat** [comment]
I have been using the _id convention in a postgres database model, and it works for me.  Even if someone unfamiliar with mongo/node looked at it, it would be obvious what it was.  It minimizes the differences between sequelize/mongoose generations, and is easily overridden by editing the model, which you have to do for every single generated endpoint anyway.  Just my opinion, but I have not used sequelize/postgres/mysql often before.

**Comment by Awk34** [comment]
It's set up to use sqlite by default because it's easy to set up and we know it works. It shouldn't be **too** diffucult from the Sequelize side to switch to a different SQL DB. I think @smirciat did a good job at answering your other questions.
