### ISSUE TITLE
script tag not added to index.html

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1710]
i installed angular-google-maps directive using bower, and it looks like installed correctly,
the folder with all the files are in bower_compoents.
but for some reason, the build process is not inserting a script tag into index.html.
i expected to see a line like this where it says ... app/vendor.js  -->

script src="bower_components/angular-google-maps/dist/angular-google-maps.min.js" ...

but it doesn't happen. (all other lines are there. bootstrap, lodash...) what can be the reason? 
how is that process work, so i can debug it?
thanks.

**Comment by Awk34** [comment]
Did you run the proper injection task?

**Comment by AmirGilboa** [comment]
i run grunt serve.
is there a specific task i should run for this to happen?

**Comment by Awk34** [comment]
If it's a *proper* Bower package, `grunt wiredep:client` should inject it

**Comment by AmirGilboa** [comment]
it is angular-google-maps, i can see it under bower_components, and in the package.json.
grunt wiredep:client  recreates the index.html, but the angular-google-maps is not there.
anything else to look for?
thanks.

**Comment by Awk34** [comment]
Is it also listed in your `bower.json`?

**Comment by AmirGilboa** [comment]
no! maybe that's the problem? should i add it manually, or otherwise?

**Comment by AmirGilboa** [comment]
yes, that solved the problem. i have added the line manually to bower.json, and then when running gulp serve, the script line was added to index.html.  thanks so much for your help!

**Comment by Awk34** [comment]
Yep, wiredep uses the dependencies in your bower.json file.
