### ISSUE TITLE
cannot build the project

### ISSUE THREAD

**Issue by Fattouh92** [angular-fullstack/generator-angular-fullstack#1713]
I updated to node v 5.x to run the generator then after genrating the app running gulp build resulted in unexpected token import. After searching online i created a .babelrc file and the content is 
{
  "presets": ["es2015"]
}
and installed npm babel-presets-es2015 and running gulp serve results in unknow option, removing .babelrc I get unexpected token import. I tried updating babel to 6.x but still same error

**Comment by Awk34** [comment]
Do you have Babel 6 installed globally? As of right now the generator still uses Babel 5.

**Comment by AmirGilboa** [comment]
what is this babel doing? 
and more specifically, what is babel-preset-es2015  doing?
is there a link with instructions on how to install it for this project?
which version do we need? 
thanks, and sorry for the silly questions, but i guess it's better to ask.

**Comment by Awk34** [comment]
@AmirGilboa Babel is a JavaScript transpiler: babeljs.io

`babel-preset-es2015` includes a large subset of Babel plugins that support transpiling ES2015 syntax.

Generator version 3.4.2 will install Babel 5 locally, but running gulp will have issues if you have Babel 6 installed globally.

**Comment by AmirGilboa** [comment]
Thanks!
are the gulp and grunt versions producing the same output, so it's only a matter of preference?
or is one of them more advance, capable, etc' ?

**Comment by Awk34** [comment]
@AmirGilboa there are subtle differences, but they mostly do the same thing.

**Comment by Fattouh92** [comment]
@Awk34 i will check this and reply later but probably babel 6 was just a try and it was local to the app. but even before upgrading to babel 6 it was not working

**Comment by Fattouh92** [comment]
@Awk34 babel 6 was not global, just updating g++ to 4.9 fixed everything and no .babelrc neither babel-presets-2015 were needed.

**Comment by HECTORkaizen** [comment]
@Fattouh92 did you solve the problem? how did you do that?
I have the same issue. And I need solve it, because I'm late...
Thanks

**Comment by Fattouh92** [comment]
@HECTORkaizen yes i did. i didnt change any packages from this generator. it is probably something wrong in your env. for me it was updating g++ or gcc. if you can show any of the error trace we can help
