### ISSUE TITLE
Lots of requests for express-sequelize-session

### ISSUE THREAD

**Issue by DanMMX** [angular-fullstack/generator-angular-fullstack#1714]
Not sure if the setup is wrong or this is absolutely normal but every time the page loads the session is required a lot of times to MySQL having this 44 times

```
Executing (default): SELECT `data` FROM `Sessions` AS `Session` WHERE `Session`.`sid` = 'ZFzNz0Aw7u7llU4eeNdHSF1lzhyHnqtr' LIMIT 1;
``` 

I'm wondering if a big application still handles so many requests to the DB

Am I getting something wrong in the setup? Just to notice, this happens on a brand new generated app

**Comment by Awk34** [comment]
#1668
