### ISSUE TITLE
Deploying Angular-fullstack app on Apache

### ISSUE THREAD

**Issue by Emidomenge** [angular-fullstack/generator-angular-fullstack#1715]
Hello everybody,

I'm very sorry, I'm a new beginner discovering angular-fullstack environnement.

I tried to find some information about my stupid question but I'm still not convince.

I want to deploy an angular fullstack project but I have to do it on Apache, is that possible without any problem ?

I'll be really thankful if you guys can enlighten me on this stuff.

**Comment by sg6** [comment]
Hello,

you actually do not need Apache, but you can use it. The server requires Node.js and NPM.
But I am not sure what your goal is, exactly. What is your set up? Which server (Windows, Unix?), what node version (node -v in command line), what npm version (npm -v). Will it be for a development site, or should it also run productive?

**Comment by Emidomenge** [comment]
Server >> Unix (Red Hat Linux)
Node >> 5.7.1
NPM >> 3.6.0

Yes it's a development site which must run productive also.

I think my solution is to use Apache as a reverse proxy and from there, access to a node server. Am i right ?

**Comment by sg6** [comment]
Yes exactly. On the development site, the page runs on e.g. domain.com:9000 and with Apache you can proxy it throught, e.g.

`                ProxyPreserveHost On
                ProxyPass /app http://localhost:9000
                ProxyPassReverse /app http://localhost:9000`

**Comment by Emidomenge** [comment]
Thank you
