### ISSUE TITLE
bootstrap.js not injected :(

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1716]
no matter what i do, bootstrap.js is not injected to index.html.
bootstrap is installed, under bower_comonents, 
in bower.json, it's says:  "bootstrap": "~3.3.6",

i googled about the issue that wiredep has with bootstrap, so i entered the bootstrap folder, 
found the bower.json and updated the "main" section to:
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js",
    "dist/js/bootstrap.css",
    "dist/js/bootstrap-theme.css"
  ],

still no luck. bootstrap.js is not being injected.  css file does. (compiled into app.css);
any ideas?

**Comment by Awk34** [comment]
It's excluded [here (Grunt)](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/Gruntfile(grunt).js#L260-L280) and [here (Gulp)](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/gulpfile.babel(gulp).js#L475-L505)

**Comment by AmirGilboa** [comment]
you are so right. thanks!
but why? maybe there is a reason?
why would anybody exclude bootstrap from being injected?

**Comment by Awk34** [comment]
We don't want the regular bootstrap JS because we include https://github.com/angular-ui/bootstrap instead
