### ISSUE TITLE
Q: How to update the project?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1718]
I would like to understand the best practice with this kind of project.
Let's say i'm creating a project with this generator, and happily work on it for 6 months.
Now the generator keeps progressing, bugs are fixed, features added, versions of libs updated,  and so forth.
Is there a way to merge those new things into my existing project?
Or is it more of a convenient way to bootstrap your app, and once the project has been created, no future updates?

**Comment by Awk34** [comment]
This has been asked many times in the past:
https://github.com/angular-fullstack/generator-angular-fullstack/issues/1188
https://github.com/angular-fullstack/generator-angular-fullstack/issues/1048
https://github.com/angular-fullstack/generator-angular-fullstack/issues/772
https://github.com/angular-fullstack/generator-angular-fullstack/issues/521

**Comment by taotau** [comment]
I havent seen this mentioned in previous comments, but I've had reasonable success using git to manage the upgrade process.

Just make sure all your changes are commited and simply run 'yo angular-fullstack' again.  This should pick up the fact that this is an existing app based on the presence of the .yo-rc.json file.  Tell it to overwrite all updated files and use git diff to see whats changed.  Revert any changes you don't want.

I've gone through several versions over the last few months with this technique.  You just have to be aware of the changes you have made.

**Comment by Awk34** [comment]
@taotau Sindre talks about this in a SO answer: http://stackoverflow.com/questions/18480316/how-to-upgrade-existing-project-scaffolded-with-yeoman
