### ISSUE TITLE
Lacking a lot of docs for Heroku deploy using gulp

### ISSUE THREAD

**Issue by mrmayfield** [angular-fullstack/generator-angular-fullstack#1720]
I just got deployed to Heroku after using Gulp as the build tool, and it was quite an ordeal that was lacking lots of docs. Would be happy to write out the docs, but where should we put them, in the wiki?

**Comment by mrmayfield** [comment]
Actually, it didn't even work. I got grunt up in 1 minute, I wasted a good 90 minutes on trying to get gulp up. A warning should definitely be in the readme. :)

**Comment by Awk34** [comment]
I have added a warning to the readme. Do you have any info that could help fix Gulp + Heroku?

**Comment by mrmayfield** [comment]
Hm, it's been a couple months so I don't really remember by now. If I fire up my project again and run into this I will let you know but I tried with grunt and it worked out of the box so I doubt I'll try and get gulp working again.

**Comment by Awk34** [comment]
Okay, I understand. I'd like to encourage more people to use Gulp, though, as it's faster, easier to use, and easier to maintain.

**Comment by skrichten** [comment]
For what its worth, I just did this with the latest version of the generator and had not trouble at all. I used gulp to do the build but I did not use the gulp command for deployment as I don't see any need for it.  Once you finish the initial setup you just ... `git push heroku master` from your dist folder.  I don't see the need for gulp/grunt for something that is already a one liner.
