### ISSUE TITLE
Question: how to create endpoint with only part of the data?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1728]
I have a product entity, and a webapi endpoint that works well.
but i need another endpoint, that returns the products in a different way. not all the fields, only subset of them, and one field has to be calculated, not straight from the database. how to do that?
i know this is not exactly a generator related question, so if any of you will only give me some keywords to search for, or how is this process called, i can search by myself. any tutorial or discussion of course would be great. Thanks!

**Comment by Awk34** [comment]
Take a look through the [User API files](https://github.com/angular-fullstack/generator-angular-fullstack/tree/3.4.0/app/templates/server/api/user(auth)). It includes excluding properties and creating virtual properties.
