### ISSUE TITLE
requiredProcessEnv

### ISSUE THREAD

**Issue by darryl-snow** [angular-fullstack/generator-angular-fullstack#1733]
in `/app/templates/server/config/environment/index.js` there is a function `requiredProcessEnv`

...just wondering what this is for, as it never appears to be used? is it just legacy code?

**Comment by Awk34** [comment]
It's just a helper that isn't used by default by the generated code. If you have an environment variable that you need to have defined, just wrap it with  that function.

Ex.

normally we just include `NODE_ENV`:
```js
env: process.env.NODE_ENV,
```

if you need it to be defined, else your app will crash:
```js
env: requiredProcessEnv('NODE_ENV'),
```
