### ISSUE TITLE
Not possible to generate without MongoDB

### ISSUE THREAD

**Issue by rubenvereecken** [angular-fullstack/generator-angular-fullstack#1737]
Just pointing out that it states in the readme that scaffolding works without a database. However, it doesn't.

**Comment by AmirGilboa** [comment]
what do you mean by "scuffolding won't work" ? the creation fails? or it does not work? error msg?

**Comment by rubenvereecken** [comment]
Ugh I just messed up. It's been ages since I've worked with Yeoman. So far this is looking great, let me close this without further ado.
