### ISSUE TITLE
Babel or TypeScript?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1738]
A small quick "survey": 
which one do you use with the angular-fullstack generator:  Babel or TypeScript?

would you prefer to stick with plain js?

**Comment by Awk34** [comment]
![screenshot-analytics google com 2016-03-23 14-38-46](https://cloud.githubusercontent.com/assets/5545474/13996625/03e922ea-f105-11e5-8534-18445fd4d10e.jpg)

**Comment by AmirGilboa** [comment]
where is this from?

**Comment by AmirGilboa** [comment]
and what's your recommendation?

**Comment by Awk34** [comment]
From the latest version of the generator, it will report which options a user chooses.

For the current state of the generator and the tools it uses, I'd recommend Babel.
