### ISSUE TITLE
Run Grunt without the Server dir

### ISSUE THREAD

**Issue by nevyen** [angular-fullstack/generator-angular-fullstack#1742]
Item | Version
----- | -----
generator-angular-fullstack | 3.3.0
Node | 5.0.0
npm | 3.5.3
Operating System | OS X 10 | Ubuntu 14:04

Grunt / Gulp | 

Hi guys, I love this generator but I only need the client because I am working with another api. Is it possible to run grunt serve without the server dir? And what do I have to change for this? 

Thanks in advance

**Comment by Awk34** [comment]
Sure, it's possible. Look at how things are done in [generator-angular](https://github.com/yeoman/generator-angular)
