### ISSUE TITLE
Showing SyntaxError: Unexpected reserved word for "import"

### ISSUE THREAD

**Issue by narayand4** [angular-fullstack/generator-angular-fullstack#1745]
Hi,

Showing SyntaxError: Unexpected reserved word for "import" when i'm executing "grunt serve:dist". Please suggest me what i'm doing wrong. 

Thanks.

**Comment by lwensveen** [comment]
Same issue, it has something to do with Babel, I got that far[]

**Comment by michaelpurnell** [comment]
+1

**Comment by xggaxlc** [comment]
+1

**Comment by michahell** [comment]
I got this error too after using: ```yo angular-fullstack:endpoint <name>```. is Babel part of the full-stack install? We didn't use Babel before when starting with this generator... Kind of backwards breaking if the generator functions just get modified to use ES6 while the project does not use Babel ?

**Comment by Awk34** [comment]
I just tested this on the latest version of the generator and didn't get any errors. If you still think this is an issue, please open an issue and provide details.

**Comment by narayand4** [comment]
Thanks @Awk34. Let me try with new version.
