### ISSUE TITLE
Fresh install: "app crashed"

### ISSUE THREAD

**Issue by maciej-gurban** [angular-fullstack/generator-angular-fullstack#1746]
After a fresh install and running gulp serve or gulp serve:dist, will generate error below. Running gulp start:server results in the same error, so I assume the problem lays there.

```
[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /dev/pr/dist/server/**/*
[nodemon] starting `node dist/server`
Express server listening on 8080, in production mode
MongoDB connection error: MongoError: connect ECONNREFUSED 127.0.0.1:27017
[nodemon] app crashed - waiting for file changes before starting..
```

I wanted to use the generator for entirely front end app, no mongo or sql required. Can I somehow run the project without it? I tried gulp start:client but it resulted in

```
/dev/pr/gulpfile.babel.js:95
        port: config.port
                    ^

TypeError: Cannot read property 'port' of undefined
    at checkAppReady (gulpfile.babel.js:69:15)
    at [object Object]._repeat (gulpfile.babel.js:80:9)
    at [object Object].wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

Thanks a lot in advance!

Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 5.8.0
npm | 3.7.3
Operating System | OS X 10
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y

**Comment by Awk34** [comment]
The purpose of the generator is to create a full-stack web app. If you're looking for front end only, try something like generator-angular.

If you selected to use MongoDB, you need to have a MongoDB daemon running. This is explained in the readme.

The `config` variable is populated by running `gulp start:server`

**Comment by agungsb** [comment]
I manage to solve the problem by change the following script:

`nodemon --watch 'server/data/**/*.js' --exec 'npm run update && babel-node server/index.js'`

with

`"nodemon --watch server/data/**/*.js --exec \"npm run update && babel-node server/index.js\""`

It is located inside `package.json`. I hope this will help somoeone out there who face the same problem as I had.

**Comment by guipsamora** [comment]
@agungsb I couldn't find the script you are referring to in the package.json file
