### ISSUE TITLE
[question] What is the recommended way of deploying applications generated with generator-angular-fullstack? 

### ISSUE THREAD

**Issue by ElderOrb** [angular-fullstack/generator-angular-fullstack#1749]
First of all I beg pardon for asking here, but I didn't find anything like forum or mail list or whatever, so.. 

I've reviewed a bit the way 'angular-fullstack:openshift' works, and noticed it just creates separate repo inside 'dist' folder. Is it recommended way of deploying production builds? If yes, should I use the same approach for deploying to other services not supported at the moment? 

Recently I also had a chance to read briefly about 'git subtree' approach, which looks like a bit more flexible. Is there any reason why wasn't it used but instead separate repo created? Sorry for stupid questions, I'm just searching for 'the best' way of deploying production builds.

**Comment by AmirGilboa** [comment]
just a bit of background: openshift and heroku are two hosting providers that supports a unique way of automated deployment to production through git. you can use either of them, or just take the dist folder and copy it however you want (ftp, etc) to your hosting server.
i think heroku provides a very easy (and free to begin with) way to deploy your app.
read more in their website about it. you need to download some package that is called Toolbelt.
read more here:
https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by jpaaso** [comment]
Atm, I think Google App Engine would be the most cost effective PaaS to deploy services with.

Has anyone managed to deploy an Angular Fullstack project with GAE? I didn't get this to work:
https://www.youtube.com/watch?v=thlFWQ15Z-0
