### ISSUE TITLE
import fs from 'fs';

### ISSUE THREAD

**Issue by HECTORkaizen** [angular-fullstack/generator-angular-fullstack#1750]
I want to start a new angular-fullstack app using this conmand is it in console ` $ yo angular-fullstack nameapp` the console send me this message:
```
C:\Users\Héctor\AppData\Roaming\npm\node_modules\generator-angular-fullstack\app\generator.js:3
import fs from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] 	(C:\Users\Héctor\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\babel-register\lib\node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Héctor\AppData\Roaming\npm\node_modules\generator-angular-fullstack\app\index.js:9:18)
    at Module._compile (module.js:413:34)
```
when I ussing this command in console: `$ yo doctor` The console sendme the next message:
```
Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version

Everything looks all right!
```
This is strange because before I can use perfectly angular-fullstack generator. And I don't know the reason to this new issue.
I saw this issue in other git post but no one resolve my problem. Please, any ideas?

Item | Version
----- | -----
generator-angular-fullstack | v3.5.0
Node | v5.9.1
npm | v3.7.3
Operating System | Windows 8.1
yo | v1.7.0
babel-core - 6.7.4

**Comment by AmirGilboa** [comment]
do you have babel installed?

**Comment by Awk34** [comment]
what is your `NODE_ENV`?

**Comment by HECTORkaizen** [comment]
@AmirGilboa 
do you have babel installed?
----------------------------------------------
Yea, last version!

**Comment by HECTORkaizen** [comment]
Hello everyone, the problem is a bug, Babel and the new way to do apps. I cant solve the problem, but I reinstalled generator-angular-fullstack version 2.1.1 and, yo version 1.2.0 and. I need finish my work, maybe is better wait to all bugs be will resolved. Anyway everything looks that all will go to Babel formats
Thanks all. The issus keeps open if someone have the solution

**Comment by Abdizriel** [comment]
@Awk34 I have the same issue with latest version.
My `NODE_ENV` is empty

**Comment by alwinn1977** [comment]
I had the same problem with this generator at Windows 10! For me it helped to install generator-angular-fullstack not globally and then run it:

```
$cd project_folder
$npm install generator-angular-fullstack
$yo angular-fullstack
```

maybe it's not very convenient, but it works!

**Comment by Awk34** [comment]
@alwinn1977 this should not be a problem anymore, try `3.7.0-beta.2`
