### ISSUE TITLE
Why are primary key columns prefixed with underscore in Sequelize template?

### ISSUE THREAD

**Issue by mjy78** [angular-fullstack/generator-angular-fullstack#1751]
Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 4.4.0
npm | 3.5.2
Operating System | Ubuntu 15.10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB | SQL (Postgres)
Auth | Y

The default naming convention for primary key fields with Sequelize is simply "id". 

Is there a reason why the [Sequelize model template](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/endpoint/templates/basename.model(sequelizeModels).js) in the angular-fullstack generator explicitly overrides this and specifies "_id"?

**Comment by Awk34** [comment]
To keep consistency with the Mongoose setup
