### ISSUE TITLE
Gulp inject:css shows nothing to inject

### ISSUE THREAD

**Issue by vikramthyagarajan** [angular-fullstack/generator-angular-fullstack#1752]
Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 5.9.0
npm | 3.7.3
gulp-cli | 1.2.1
gulp local version | 3.9.1
Operating System | OS X 10.11

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y

While running gulp serve, the css files that I have within the client folder do not get injected into the index.html file. 
I think the issue seems to be here
``` javascript
    return gulp.src(paths.client.mainView)
        .pipe(plugins.inject(
            gulp.src(`/${clientPath}/{app,components}/**/*.css`, {read: false})
                .pipe(plugins.sort()),
            {
                starttag: '<!-- injector:css -->',
                endtag: '<!-- endinjector -->',
                transform: (filepath) => '<link rel="stylesheet" href="' + filepath.replace(`/${clientPath}/`, '').replace('/.tmp/', '') + '">'
            }))
        .pipe(gulp.dest(clientPath));
```

Making this change seems to solve it temporarily
``` javascript
gulp.src(`${clientPath}/{app,components}/**/*.css`, {read: false})
```
However, removing the / seems to solve the issue temporarily, but I'm not sure if anything will break because of it

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/commit/6de62726846b310832704b0e01d297697da3a9c5 removes the extra `/`

This *should* be working in the next release
