### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by rjkunde** [angular-fullstack/generator-angular-fullstack#1755]
Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by chinnichaitanya** [comment]
@rjkunde I don't understand this issue. What does **ar** mean?

**Comment by rjkunde** [comment]
This isn't actually an issue, was having problems with angular-fullstack and google maps integration.  Ignore, sorry!
