### ISSUE TITLE
Project not generating typescript routes

### ISSUE THREAD

**Issue by andershagebakken** [angular-fullstack/generator-angular-fullstack#1757]
Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 5.10
npm | 3.8.3
OS | OS X El Capitan

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router | ngRoute
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB
Auth | Y

Hi. My issue is that when I do yo angular-fullstack:route myroute, it does not generate .ts files, but the old .js  I started a new project in order to port my old javascript-client project to typescript-client. How can generate .ts files instead? 

Edit: This turned out to be a three-part question. The generated project creates a main.controller.js and main.ts etc, but in index.html it says <script src="app/main/main.controller.js"></script>, it includes .js, but if I change it to .ts, the page stops working. Is this correct behavior? 

New routes are not injected into index.html either, how can I fix this as well?

Thanks in advance.

**Comment by Awk34** [comment]
As of 3.4.0, `generator-ng-component` was updated to the latest version, which should support .ts files. I'll have to look into if this is broken.

Adding `.ts` files to `index.html` wouldn't make sense, since browsers don't understand TypeScript code.

As for new routes not being injected, I'll probably have to investigate this too.

**Comment by Awk34** [comment]
Which OS are you using?

**Comment by andershagebakken** [comment]
OS X El Capitan

**Comment by andershagebakken** [comment]
I tried something my self just now. I removed the angular-fullstack generator completely, and reinstalled it, and now it is generating ts files properly. I guess the update function in yeoman was not updating the ng-component. I guess we can close this issue. Sorry about waisting your time.
