### ISSUE TITLE
Debugging server side.

### ISSUE THREAD

**Issue by gviligvili** [angular-fullstack/generator-angular-fullstack#1758]
Hey, 
Me and my friend are trying for 2 days to debug the server side correctly. 
We've tried gulp AND grunt.
node inspector is working terribly, randomly crash on start,  ** I can't even put any breakpoints any where besides index**. (both in gulp and grunt:debug)

I don't know why, and I've done so much research on Stack and here none of them helped.

Does it happen for anyone else? is there a solution?
I really want to use this generator but it seems impossible doing so without being able to debug.

What I'm trying to do is to make the nodemon instance to hit the Webstorm breakpoints I have. 
(I prefer using webstorm if possible, If not, then any other good debuggers would be great..)

What I've tried so far :

-- Regular debugging. (trivial..) But it seems node sends excpections when he meet ECMA6 syntax. (Still.. I rather run the gulp instance than run it from webstorm.)
-- Using --debug
-- Using 'remote debug' in webstorm.
-- Setting up node inspector in gulp task and set him to listen 5353
-- Using --debug-brk and debug on port 5353 (for example)
-- Everything mention have been tried in both gulp and grunt.

I could really appreciate it if someone could help me.

**Comment by Paca-Vaca** [comment]
Hi - have the same problem and tried more or less the same steps. Help with this will be much appreciated.

**Comment by rudolph2907** [comment]
Got the same problem.

**Comment by Awk34** [comment]
This is my setup with Gulp:

```js
gulp.task('start:inspector', function() {
    gulp.src([])
        .pipe(plugins.nodeInspector());
});

gulp.task('start:server:debug', () => {
    process.env.NODE_ENV = process.env.NODE_ENV || 'development';
    config = require(`./${serverPath}/config/environment`);

    return nodemon(`-w ${serverPath} --debug-brk ${serverPath}`)
        .on('log', onServerLog);
});

gulp.task('serve:debug', cb => {
    runSequence(
        [
            'clean:tmp',
            'lint:scripts',
            'env:all',
            'copy:fonts:dev'
        ],
        'webpack:dev',
        'start:inspector',
        ['start:server:debug', 'start:client'],
        'watch',
        cb
    );
});
```

**Comment by Paca-Vaca** [comment]
I'm getting no data of the server structure with this configuration unfortunately in the inspector( Maybe some additional configuration is needed, but I can't find which one, yet.

**Comment by Awk34** [comment]
Please try the latest version with Gulp

**Comment by Tauqeer1** [comment]
@Awk34  My gulp file configuration is same as yours and i am also using latest angular-fullstack generator but still I am unable to debug the application

**Comment by Awk34** [comment]
@Tauqeer1 please open a separate issue with details
