### ISSUE TITLE
`gulp serve` broken out of the box with CSS option

### ISSUE THREAD

**Issue by ggallo** [angular-fullstack/generator-angular-fullstack#1760]
Item | Version
----- | -----
generator-angular-fullstack | 3.3.0
Node | 5.3.0
npm | 3.8.5
yo | 1.7.0
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS | CSS 
Router | ui-router
Build Tool | Gulp
Client Tests |  Mocha
DB | MongoDB
Auth | Y

To recreate: 

1. `yo angular-fullstack` with the options above
2. `gulp serve` and you receive this error: `Error: Task inject:css is listed more than once. This is probably a typo.` Easily fixable, I suspect the second `inject:css` is meant as a placeholder in case a preprocessor was selected in step 1
3. Run `gulp serve` after removing the duplicate command, and `localhost:9000` is clearly missing style resources. I suspect that bootstrap and font awesome are not being loaded.

If you generate a second app that's exactly the same, except you select Less as a preprocessor, `gulp serve` works out of the box, and the demo app appears as expected. (This may hold for other preprocessors, I didn't check.) Could be related to #1466 and #1752

**Comment by Awk34** [comment]
Try the latest version of the generator

**Comment by ggallo** [comment]
Same problem with generator-angular-fullstack@3.5.0 after following the exact same steps.

I think it's because with the preprocessor, you get bootstrap and font awesome injected into client/app/app.less, but not with CSS. Just a guess, I'm a bit 🆕 to this stuff.

Here's a reference image for what I'm seeing with CSS:

<img width="632" alt="screen shot 2016-04-08 at 12 07 16 pm" src="https://cloud.githubusercontent.com/assets/3633936/14389960/dfcce948-fd82-11e5-96b7-3a4f100c4d4a.png">

And again, using Less looks great:

<img width="705" alt="screen shot 2016-04-08 at 12 11 18 pm" src="https://cloud.githubusercontent.com/assets/3633936/14390006/090c754e-fd83-11e5-8a17-55bf4aa0e77e.png">

**Comment by ggallo** [comment]
In fact, the `inject:css` task seems completely broken across all preprocessor options. Run a `gulp serve` and in `client/index.js`, there's nothing inside the `injector:css` tags. Compare that to the `injector:js` tags, which contain the necessary scrips after the task.

**Comment by dsschnau** [comment]
Hey, just another data point for this issue:

I set up an app to use css (no sass/less/styl), and there was indeed a `gulp` task that did `inject:css` twice which caused the error in this report. I didn't look further but I guessed that one of the `inject:css` tasks would have been for a css preprocessor. I deleted it and moved on but just wanted to let y'all know.

**Comment by Awk34** [comment]
I believe this has been fixed
