### ISSUE TITLE
Is the Canary branch even being used anymore?

### ISSUE THREAD

**Issue by programmerdave** [angular-fullstack/generator-angular-fullstack#1762]
I submitted a PR to the canary branch and it got merged into that branch but it seems that no one is paying attention to merge that into master. Why does the canary branch even exist if all the PRs are being merged directly into master. The contribution guidelines state "Please submit PRs to the canary branch, it is the main development branch for this generator." Is this no longer true?

**Comment by Awk34** [comment]
`canary` is typically the branch to submit 'new' stuff to, while fixes typically go directly to `master`. 

I have been quite busy lately, and haven't had much time to work on this project, but will be working on it more in the next week.
