### ISSUE TITLE
Is the Issue #1552 solved?

### ISSUE THREAD

**Issue by aabm00** [angular-fullstack/generator-angular-fullstack#1766]
Item | Version
----- | -----
generator-angular-fullstack | 3.5
Node | 4.2.3
npm | 3.7.5
Operating System | Windows 7 

Option | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router | ui-router
Build Tool | Grunt 
Client Tests | Jasmine
DB | MongoDB
Auth | Y

I still have the issue #1552 (closed, So I understood that was fixed) generating a project with the configuration bellow. The problem is that I can't delete users when login as an admin. 
Because the canary version of angular 1.5 has become master I believed that the known problems, were solved. Are the problems fixed?  

Thanks

**Comment by Awk34** [comment]
The issue referenced is that angular module creation files weren't being placed directly after `app.js` in `index.html`, thus the app wouldn't load. Not being able to delete users sounds completely unrelated.

**Comment by aabm00** [comment]
So then there are something  wrong when the project  is generated because
when login as admin and go to the admin tab I can see the users but I cant
see the delete button.

El 15/04/2016 04:48, "Andrew Koroluk" <notifications@github.com> escribió:
>
> The issue referenced is that angular module creation files weren't being
placed directly after app.js in index.html, thus the app wouldn't load. Not
being able to delete users sounds completely unrelated.

**Comment by mhheise** [comment]
If I understand correctly, you are trying to delete a user but you see a mouse-over instead of an actual link to delete the user. If that's the case, try changing the following line in your `client/app/admin/admin.html` file from this:

```html
<a ng-click="admin.delete(user)" class="trash"><span class="fa fa-trash fa-2x"></span></a>
```

to this:

```html
<a ng-click="admin.delete(user)" class="trash" href=""><span class="fa fa-trash fa-2x"></span></a>
```

**Comment by aabm00** [comment]
Thanks you both

I finally changed client/app/admin/admin.html file from this:

<a ng-click="admin.delete(user)" class="trash"><span class="fa fa-trash fa-2x"></span></a>

 to this:

<a ng-click="admin.delete(user)" class="trash"><span class="glyphicon glyphicon-trash pull-right"></span></a>

As it was in a previous versions of the generator.
