### ISSUE TITLE
ENHANCEMENT || To add E6 & angular-material for client side

### ISSUE THREAD

**Issue by siva3378** [angular-fullstack/generator-angular-fullstack#1767]
Requesting you to please add the E6 & angular-material for client side as generator  https://github.com/swiip/generator-gulp-angular

**Comment by siva3378** [comment]
+ Browserfy & webpack :)

**Comment by Awk34** [comment]
The project is already written in ES6/TS. See #999 for Angular Material and #1196 for webpack
