### ISSUE TITLE
"Resolve" issue

### ISSUE THREAD

**Issue by saurabhverma2892** [angular-fullstack/generator-angular-fullstack#1768]
Hi,

I am trying to add a resolve . I tried adding the resolve to $stateprovider.state once and also to the module.component, and then using the same variable and passing it to the constructor. I end up with an error everytime
angular.js:13424 Error: [$injector:unpr] Unknown provider. 

possible workarounds?

**Comment by DracoPL** [comment]
Hey,
I have exactly the same issue right now. Can someone help?

**Comment by Awk34** [comment]
Closed due to inactivity
