### ISSUE TITLE
Facebook oAuth showing Incalid App ID: app-id 

### ISSUE THREAD

**Issue by theklausster** [angular-fullstack/generator-angular-fullstack#1769]
Hi guys.

I'm stuck and i was hoping for a little help.

The app id and app secret from Facebook developer is set here. I made the callback url on Facebook like this: http://localhost:9000/auth/facebook/callback

server\config\environment\index.js
server\config\local.env.js
server\config\local.env.sample.js

Here's what I get when clicking on
![image](https://cloud.githubusercontent.com/assets/14737788/14470966/90726b12-00ec-11e6-9268-1d002de0e07d.png)

gives this error 

![image](https://cloud.githubusercontent.com/assets/14737788/14470990/acacbde6-00ec-11e6-8414-5e9abc70d053.png)

ohh and I tripled checked if the App id and secret key was the same - copy paste actually

Can you guys point me in some direction? 

Best regards
Klaus

Specs
generator-angular-fullstack | newsest
Node | newsest
npm | newsest
Operating System | win 7

Babel
HTML
CSS
ui-router
Grunt
Jasmine
MongoDB 
Auth | Y 
Facebook oAuth enabled

**Comment by theklausster** [comment]
If this doesn't belong here, let me know :)

**Comment by Awk34** [comment]
How are you starting your server?

**Comment by theklausster** [comment]
Hi Awk34,

 I've forgot to "whitelist" my urls in developer/facebook.
That solved it for me.

Thanks anyway.
