### ISSUE TITLE
Problem Using Babel.

### ISSUE THREAD

**Issue by rufogongora** [angular-fullstack/generator-angular-fullstack#1770]
So I've been used to write my scripts with plain AngularJS, no Babel or typescript, so right now I'm basically forced to choose from either or, so I'm having trouble understanding dependency injection here.

In this script I'm trying to call the $state dependency so I can use it inside a callback function after a $resource updates. Here's the code:

```

'use strict';
(function(){

class NewItemComponent {
  constructor(Category) {
  	this.category = Category.get({'id' : $stateParams.categoryid})

  }
  
  addItem(){
    this.category.items.push(this.newItem);
    this.category.$update(function (data, $state){
    	console.log($state);
    	$state.go('category-detail', {'id' : data._id});
    });
  }

}

angular.module('thePowerToGiveApp')
  .component('newItem', {
    templateUrl: 'app/new-item/new-item.html',
    controller: NewItemComponent,
    controllerAs: 'ctrl'
  });

})();
```

As you can see in the addItem function I'm trying to update a resource and after it's done change to another state, what's the proper way to achieve this?

Thanks.

**Comment by mihaipocorschi** [comment]
Did you try like this?
- first assign $state to $this.$state
- use fat arrow function in order to preserve this

class NewItemComponent {
  constructor(Category, $state) {
    this.$state = $state;
    this.category = Category.get({'id' : $stateParams.categoryid})
  }

  addItem(){
    this.category.items.push(this.newItem);
    this.category.$update( (data) => {
      this.$state.go('category-detail', {'id' : data._id});
    });
  }
}

**Comment by rufogongora** [comment]
Well what i've learned from the last couple of days of reading is that in order to access stuff from the class into callback functions, you have to do it with arrow functions the way you're doing it.

**Comment by mihaipocorschi** [comment]
great then problem solved i guess :)

**Comment by Awk34** [comment]
If it's easier for you, you don't have to use JavaScript Classes. What @mihaipocorschi looks like it is correct, though.
