### ISSUE TITLE
Question about the sessions collection

### ISSUE THREAD

**Issue by andershagebakken** [angular-fullstack/generator-angular-fullstack#1772]
I was wondering about the sessions collection in my MongoDB database, it is just growing and growing and more and more documents are added. In a few minutes, about 100 new session documents are added. Are these not supposed to be deleted? Is it safe for me to delete them?

**Comment by Awk34** [comment]
It *should* be safe to delete sessions (seeing the obvious consequences of doing so), especially expired ones.

Your sessions should not be growing and growing without any new users actually creating new sessions.

**Comment by andershagebakken** [comment]
I have not altered anything in relations to users in a new generated project, but this happens. How can I fix it?

**Comment by Awk34** [comment]
Let's track it there
