### ISSUE TITLE
Why gulpfile.babel.js ?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1773]
Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 5.10.1
npm | x.x.x
Operating System | OS X 10 
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | CSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y 
etc | etc

When i run the generator, i choose Typescript, Gulp.
the generated gulp file is called  gulpfile.babel.js
why is that? is this a bug?
is there a way to run this file without babel?
i'm obviously running the gulp file locally on my node server, so i need the file to be simple js.

it only happens with the gulp option. when i choose Typescript + Grunt,
the gruntfile is regular js.

pls help!

**Comment by Awk34** [comment]
When I created the Gulp file, the generator didn't support TypeScript. 

Feel free to port it over to TypeScript

**Comment by AmirGilboa** [comment]
i see. 
but... i would be happy with the js. do you still have that? before porting. no need any porting to ts.
if i get you correctly, you're telling me to translate the babel to typescript? so it will then be translated to javascript in order to run? why are we doing all this? let's just use the original js.

you see, the code in the application is mine. i spend time on it, it will go to production.  i want to take advantage of advance features etc. but this gulpfile is only a utility. it is not even meant to be changed. i will use it as is. so i don't need any cool or advanced featured language. js is perfect. pleeese.

**Comment by Awk34** [comment]
As of 3.5.0, the Gulpfile is only available in JavaScript. The Gruntfile is only available in JS as well. I thought you wanted the Gulpfile available in TypeScript: "When i run the generator, i choose Typescript, Gulp. The generated gulp file is called gulpfile.babel.js". It is perfectly fine to run the Gulpfile with Babel for a TypeScript project.

**Comment by AmirGilboa** [comment]
so can i take the gulpfile that has been created for the babel project, and use it in the typescript project?

**Comment by Awk34** [comment]
Just generating a project with TS & Gulp options will generate a `gulpfile.babel.js` which contains code for compiling your front-end TS files.
