### ISSUE TITLE
App name takes the folder name, like it or not.

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1774]
Item | Version
-----|-----
generator-angular-fullstack | 3.5.0
Node | 5.10.1
npm | x.x.x
Operating System | OS X 10
etc | etc

Item | Answer
-----|-----
Transpiler	 | TypeScript
Markup | HTML
CSS | CSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y

i reported that some months back, and it's still happening.
when you run the generator without param, it takes the folder name. that's by design.
but when you specify an app name, it takes the folder anyways, and adds your name to it.
so if the folder is Test3, and you run 
yo angular-fullstack app
your app name in the code will be Test3app.

the only way to call you app 'app', is to create it in a folder named app.

**Comment by Awk34** [comment]
I just tried this and it seems to be working fine: `yo angular-fullstack:app asdf`

**Comment by AmirGilboa** [comment]
i have just repeated that, but with a small change:
yo angular-fullstack:app app

the result in app.js:
angular.module('appApp', [ ....

i was hoping to see just:
angular.module('app', [

thanks so much for your help!

**Comment by AmirGilboa** [comment]
looking at the main page, maybe i should play with the --app-suffix ? 
but how to define no suffix at all?
probably it's working fine, only i need to learn how to use it...

**Comment by Awk34** [comment]
I believe `yo angular-fullstack:app app --app-suffix ""` is what you're looking for

**Comment by AmirGilboa** [comment]
Yes, it works! great, thank you!!
