### ISSUE TITLE
Facebook Authentication | MySql Syntax Error

### ISSUE THREAD

**Issue by saurabhverma2892** [angular-fullstack/generator-angular-fullstack#1778]
I am using the yeoman angular fullstack with sequelize and have configured mysql as my db.
I get an error when i try to login through facebook which is mysql syntax error when the following is trying to get executed in /server/auth/facebook/passport.js

    User.find({where:{'facebook.id': profile.id}}).then(user => {
        if (user) {
          return done(null, user);
        }

during this authentication mysql gives the following error:

Executing (default): SELECT `_id`, `name`, `email`, `role`, `password`, `provider`, `salt`, `facebook`, `twitter`, `google`, `github`, `createdAt`, `updatedAt` FROM `users` AS `User` WHERE (`User`.`facebook`#>>'{id}') = '1239871587612' LIMIT 1;
SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

I guess the error is at the syntax used at { 'facebook.id': profile.id}.

my mysql version is : 5.7.11

**Comment by saurabhverma2892** [comment]
Posting the same on sequelize issues i realised the sequelize supports JSON only on postgress. A possible work around for people using mysql as their db is : (As learnt from https://github.com/sequelize/sequelize/issues/5760)

User.find({where:sequelize.where(
                sequelize.literal('facebook->"$.id"'),
                profile.id
              )
    })
      .then.....

Cheers!

**Comment by Demonium** [comment]
@saurabhverma2892 could you please provide the complete you have done, it's not working for me

**Comment by saurabhverma2892** [comment]
server/auth/facebook/passport.js 

`User.find({
      where: {
        $or: [sequelize.where(
                      sequelize.literal('facebook->"$.id"'),
                      profile.id
          ),
            sequelize.where(
                      sequelize.literal('email'),
                      profile.emails[0].value
          )
          
        ]
      }
    }).then(user => {
        if (user) {
          return done(null, user);
        }
        user = User.build({
          name: profile.displayName,
          email: profile.emails[0].value,
          role: 'user',
          provider: 'facebook',
          facebook: profile._json,
          profile_complete:false
        });
        user.save()
          .then(user => done(null, user))
          .catch(err => done(err));
      })
      .catch(err => done(err));
  }));
}`

$or is used to check if either the facebook id or the email id is registered, since users can register by either on my platform.

hope this helps @Demonium

**Comment by Demonium** [comment]
Work perfectly!! Thanks very much @saurabhverma2892

**Comment by saurabhverma2892** [comment]
Cheers! :) @Demonium
