### ISSUE TITLE
Task 'buildcontrol:heroku' is not in your gulpfile

### ISSUE THREAD

**Issue by MaximilianLloyd** [angular-fullstack/generator-angular-fullstack#1787]
Item | Version
----- | -----
generator-angular-fullstack | not sure
Node | 4.2.4
npm | 3.5.3
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS | SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | JMocha
DB | SQL
Auth | Y 

For some reason when i try to update it so i can update the remote heroku server by using gulp buildcontrol:heroku it says the task does not exists? any help would be much appreciated
![capture](https://cloud.githubusercontent.com/assets/10583205/14649522/c5ad4510-0667-11e6-853e-33261824760c.PNG)

**Comment by raosushant** [comment]
I'm not sure buildcontrol is a task in the gulpfile. After running gulp build, I just push directly to heroku using git. 

`git subtree push --prefix dist heroku master
`

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/pull/1795/commits/3221678eb9f9d1599afdf62f5ba60a37f95cc0e3
