### ISSUE TITLE
Just hope. haha :) . not issues

### ISSUE THREAD

**Issue by YoungsoonLee** [angular-fullstack/generator-angular-fullstack#1788]
I really hope to generator-react-fullstack.
that is same structure with generator-angular-fullstack.
and same function and same flow......   haha

Is there someone with same think. :)

**Comment by Awk34** [comment]
(Closed as not an issue)

If anyone would like to copy the structure of this project and port it to a React-based architecture, it would be neat.

**Comment by raza2022** [comment]
> If anyone would like to copy the structure of this project and port it to a React-based architecture, it would be neat.
if some one do so please let me know@raza2022
