### ISSUE TITLE
gulp serve command modifying client/app/app.constant.js file

### ISSUE THREAD

**Issue by siva3378** [angular-fullstack/generator-angular-fullstack#1796]
When ever i'm executing gulp serve, it is modifiying app.constant.js file

Item | Version
----- | -----
generator-angular-fullstack |1.6.0
Node | v5.5.0
npm | 3.3.12
Operating System | Windows 7

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS / LESS / SCSS / Stylus
Router | ui-router
Build Tool |  Gulp
Client Tests | Jasmine
DB | MongoDB 
Auth | Y

**Comment by siva3378** [comment]
duplicate of https://github.com/angular-fullstack/generator-angular-fullstack/issues/1587

**Comment by siva3378** [comment]
I think even-though it is excluded, still this problem exists

    gulp.task('lint:scripts:client', () => {
        return gulp.src(_.union(
        paths.client.scripts,
        _.map(paths.client.test, blob => '!' + blob),
        [`!${clientPath}/app/app.constant.js`]
    )).pipe(lintClientScripts());
    });

**Comment by Awk34** [comment]
Is there a reason that you think the `app.constant.js` file shouldn't be changed when running `gulp serve`?

**Comment by siva3378** [comment]
Yes, for some js global objects like d3, moment it better to register in constants right. So I will be putting in this app.constant.js file as follows

    .constant('d3', d3);

**Comment by Awk34** [comment]
That's not the purpose of that file. Look at the relevant Gulp code https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/gulpfile.babel(gulp).js#L610-L623 . It takes all the variables in `server/config/environment/shared.js` and writes them to a file. Anything in the file will be overwritten when you run the `constant` task again.

**Comment by siva3378** [comment]
ok Thank you Andrew. Its really great work.
