### ISSUE TITLE
bower install doesn't automatically add the dependency to index.html

### ISSUE THREAD

**Issue by Pradeet** [angular-fullstack/generator-angular-fullstack#1798]
Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 5.10.1
npm | 3.8.3
Operating System | Ubuntu 14.04

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Awk34** [comment]
That's right. `bower install` just installs the dependencies listed in your `bower.json`. `grunt wiredep:client`/`gulp wiredep:client` are the commands to inject their tags into `index.html`.

**Comment by Pradeet** [comment]
Yeah it worked, then it would be better to mention it in the readme, because it is very useful.
Thank You.
