### ISSUE TITLE
Jade -> Pug

### ISSUE THREAD

**Issue by Awk34** [angular-fullstack/generator-angular-fullstack#1802]
Jade | Pug
----- | -----
jade | [pug](https://github.com/pugjs/pug)
gulp-jade | [gulp-pug](https://github.com/jamen/gulp-pug)
grunt-contrib-jade | [grunt-contrib-pug](https://github.com/gruntjs/grunt-contrib-pug)

**Comment by seetpalsingh** [comment]
Dude , since april 22 its you working on it.

what happened?

**Comment by Awk34** [comment]
Pug is still in Beta, you know
