### ISSUE TITLE
'grunt serve' and 'gulp serve' broken right out of the box.

### ISSUE THREAD

**Issue by jagzviruz** [angular-fullstack/generator-angular-fullstack#1805]
Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 5.9.0
npm | 3.7.3
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS |  LESS 
Router | ui-router
Build Tool | Grunt
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | N

I generated a fresh project with the above configuration. When I tried to run it with 'grunt serve' , the browser window opened 'http://localhost:9000' but I am getting an empty response error .
<img width="386" alt="screen shot 2016-04-21 at 8 25 34 am" src="https://cloud.githubusercontent.com/assets/390423/14696719/0e9e1cf2-079b-11e6-9c88-93ebcffdc7e8.png">

I tried with a fresh generate with Gulp as well, but had the same result. Am I doing something wrong ?

**Comment by Koslun** [comment]
No error in the console? That would probably say a lot more to detect the error if it's in the grunt/gulp, server or MongoDB part. If it's in the client part you could the Chrome developer console or something equivalent to it.  Additionally you should be able to see errors with MongoDB when you're starting it.

So you could be doing something wrong, need more information.

**Comment by AmirGilboa** [comment]
i have just created a new system last night with the latest version and it worked, so must be something in your environment. i would run
npm install
bower install
just in case stuff wasn't installed properly. watch for errors, put them here, and we'll try to help.

**Comment by jagzviruz** [comment]
Tried creating yet another project, with the same setup as above. Still no errors.
<img width="1677" alt="screen shot 2016-04-22 at 9 14 08 am" src="https://cloud.githubusercontent.com/assets/390423/14731102/d6a283b2-086a-11e6-9cb1-21cfa3b3a1bf.png">

**Comment by Koslun** [comment]
Try also running tests and showing the result. Either way does seem like some problem on the server part rather than the client.

What about MongoDB? Is it up and running? Should be able to reach it by writing `mongo` in a separate terminal window.

The biggest outlier in your setup I think is saying no to Auth and possible LESS over SASS. If it works using grunt with those it's less likely to be something with your setup.

**Comment by Awk34** [comment]
I would imagine it's something with your computer. Can you try it on another computer?

**Comment by jagzviruz** [comment]
Ran 'grunt test', got an all OK . Yes mongodb is up and running. Have to try running on another computer. Is thee any known issue if I have 'generator-angular' installed as well ?

**Comment by jagzviruz** [comment]
OK !! now I am confused.. I changed the running port for all my different configuration versions from 9000 to 3001, and all of them worked without a hitch.. 
Strangely enough, I have no process running on 9000.

Solves my problem for now.
