### ISSUE TITLE
Warning a promise was created in a handler but was not returned

### ISSUE THREAD

**Issue by whittssg** [angular-fullstack/generator-angular-fullstack#1810]
Item | Version
----- | -----
generator-angular-fullstack | 3.50
Node | 4.2.3

Operating System | Windows 7 64

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS 
Router | ui-router
Build Tool | Grunt 
Client Tests | Jasmine
DB | MongoDB 
Auth | Y

When saving a user inside the local passport.js file i receive the following error:

Warning: a promise was created in a handler but was not returned from it at model.wrappedPointCut [as save]

I just changed the if user does not exist section to :

```
 if (!user) {
                /*return done(null, false, {
                    message: 'This email is not registered.'
                });*/
                user = new User({
                    name: 'test',
                    email: 'test@test.com',
                    role: 'user',
                    username: 'testing',
                    provider: 'local'
                });
                user.save()
                    .then(user => done(null, user))
                    .catch(err => done(err));
            }
```
This is the exact same code that i was using in 3.1 and it worked fine - i just upgraded my project today and now get this error. The user is saved though and the user logs in.

Thanks,

**Comment by Awk34** [comment]
Yeah, it's just a warning, so you can ignore it for now. Bluebird doesn't like that we're creating a new promise and not returning that promise (since we're just using callbacks here anyway).

**Comment by whittssg** [comment]
Ah OK.  Il ignore it then.  Thabks

**Comment by chovy** [comment]
I'm still getting this.
