### ISSUE TITLE
build app in Gulp listening in port 8080

### ISSUE THREAD

**Issue by aabm00** [angular-fullstack/generator-angular-fullstack#1814]
Item | Version
----- | -----
generator-angular-fullstack | 3.6
Node | 4.2.3
npm | 3.7.5
Operating System | Windows 7

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router | ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
socket.io | Y

Hi 

I have been trying the new version 3.6 with tthe two build tools Grunt and Gulp. 

**GRUNT**
With Grunt everything is fine
- The local app preview --> **OK**
- The build app preview --> **OK**

**GULP**
- The local app preview --> **OK**
- The build app preview --> **NO OK**

In the preview of the build app I got the next error:

> .........
> [10:47:01] Finished 'start:client' after 168 ms
> [10:47:01] Finished 'serve:dist' after 1 min

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE 0.0.0.0:8080
>     at Object.exports._errnoException (util.js:874:11)
>     at exports._exceptionWithHostPort (util.js:897:20)
>     at Server._listen2 (net.js:1234 :14)
>     at listen (net.js:1270:10)
>     at net.js:1379:9
>     at doNTCallback3 (node.js:452:9)
>     at process._tickCallback (node.js:358:17)
>  [nodemon] app crashed - waiting for file changes before starting...

The app normally listen in the port 9000 but with the build app in Gulp listen in 8080. The EADDRINUSE error says that the port was in use, but it wasn't. 

![captura](https://cloud.githubusercontent.com/assets/2041161/14736919/c1fea058-0879-11e6-8600-1e9281e92aea.PNG)

**Comment by aabm00** [comment]
Hi
There was a process taking the port 8080. Killing it the build app worked fine.

The **locals app** use the port **9000 **in both, _Gulp _and **Grunt **but the **build app** in _Grunt _uses the **9000 **port and **Gulp **the _8080_. What is the reason to use different ports?

Thanks

**Comment by Awk34** [comment]
Personally I prefer Gulp, but it's up to you. The port we use for the `serve:dist` setup should be the same in both files, though. I'll make sure to change it.

**Comment by aabm00** [comment]
Thanks.  your are doing a great job !!!!
