### ISSUE TITLE
The version of grunt is too old to install some grunt-plugins by npm

### ISSUE THREAD

**Issue by dcalsky** [angular-fullstack/generator-angular-fullstack#1815]
Item | Version
----- | -----
generator-angular-fullstack | 3.6.0
Node | 4.2.1
npm | 2.14.7
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | Jade
CSS |  Stylus
Router |  ui-router
Build Tool | Grunt
Client Tests |  Mocha
DB | MongoDB 
Auth | Y 
etc | etc

---

grunt version is too old to install some grunt-plugins by npm ...
```
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-express-server@0.5.3 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-mocha-istanbul@4.0.2 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-tslint@3.1.0 wants grunt@>=0.4.5
npm ERR! peerinvalid Peer jit-grunt@0.10.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-build-control@0.7.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-karma@0.12.2 wants grunt@>=0.4.x
npm ERR! peerinvalid Peer grunt-ng-constant@2.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-postcss@0.8.0 wants grunt@>=0.4.5
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-filerev@2.3.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-usemin@3.1.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-ng-annotate@2.0.2 wants grunt@>=0.4.5
npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
npm ERR! peerinvalid Peer grunt-injector@0.6.1 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-newer@1.2.0 wants grunt@>=0.4.1
npm ERR! peerinvalid Peer grunt-dom-munger@3.4.0 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-wiredep@2.0.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-tsd@0.1.0 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-protractor-runner@2.1.2 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-ts@5.4.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-concurrent@2.3.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-nodemon@0.4.2 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-node-inspector@0.4.1 wants grunt@^0.4.5
npm ERR! peerinvalid Peer grunt-contrib-imagemin@1.0.0 wants grunt@>=0.4.0
```

### So, I think it's important to update the version of grunt in the package.json

Like this 
```
"grunt": "^0.4.5"
```

**Comment by Awk34** [comment]
This will fail on npm 2, but only warn on npm 3. If you can only install with npm 2, just change down to grunt 0.4.5

**Comment by dcalsky** [comment]
For compatibility, I think it's better to fix this problem on npm 2. Users who use npm 2 will meet the same problem like me.

**Comment by Awk34** [comment]
Ugh, annoying. I wonder if there's a way to force-install on npm 2.. There's one feature I recently added that depends on Grunt 1.0.0...

**Comment by dcalsky** [comment]
That's sounded like a sad story. 
Thanks for your hardworking anyway.

**Comment by Awk34** [comment]
I'll just have to revert the Grunt 1.0.0 change and put a note next to the feature that requires Grunt 1.0.0. We can't have everyone on npm 2 broken from the get-go!

**Comment by Awk34** [comment]
Now that I look at it, I should be able to keep the new feature. If the user chooses Gulp, we install Grunt 1 & grunt-build-control (with proper `peerDependency` allowing Grunt 1.0.0). This allows us to have `gulp buildcontrol` tasks by proxying to Grunt, which requires Grunt ^1.0.0. Reverting to using Grunt 0.4.5 when a user chooses Grunt should still be fine though.

**Comment by Awk34** [comment]
npm shouldn't be warning that grunt ^1.0.0 is `PEERINVALID` for `grunt@>=0.4.5`, though, since `1 >= 0.4.5` is definitely true..
