### ISSUE TITLE
default login page

### ISSUE THREAD

**Issue by texas697** [angular-fullstack/generator-angular-fullstack#1825]
I have found similar posts looking to set the login state as the default route and if user is not logged in. Some of the solutions are from December which have already been implemented in the newer releases. I have a default scaffold app that uses authentication. I can see the isLoggedIn check is working, it is returning false. but it does not reroute to the login view.  I even did a check with own code inside the main.js  The state still goes to the main.

```
angular.module('tesApp')
  .config(function($stateProvider) {
    $stateProvider
      .state('main', {
        url: '/',
        template: '<main></main>',
        //authenticate: true,
        resolve: {
          auth: function (Auth,$state) {
           if(!Auth.isLoggedIn()){
             console.log(Auth.isLoggedIn());
             $state.go('login');
           }
          }
        }
      });
  });
```

Item | Version
----- | -----
generator-angular-fullstack | latest version
Node | v5.9.1
npm | 3.7.3
Operating System | OS X 10.11.4
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | SCSS 
Router |  ui-router
Build Tool | Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB
Auth | Y 
etc | etc

**Comment by saurabhverma2892** [comment]
you can do this check in your main.controller.js. 

if islogged is returning false then just do
$state.go('login)

Make sure you are passing $state inside the constructor.

**Comment by Awk34** [comment]
Closed due to inactivity
