### ISSUE TITLE
Error in plugin 'gulp-tslint'

### ISSUE THREAD

**Issue by gr8rizwan** [angular-fullstack/generator-angular-fullstack#1826]
gulp-tslint | 4.3.0
generator-angular-fullstack | 3.6.1 
Node | v5.10.1
npm | 3.8.3
Operating System | Ubuntu 14.04 

Transpiler |  TypeScript
Markup | Jade
CSS |  SCSS
Router |  ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y

-----------------------

[11:40:13] [gulp-tslint] error (no-empty) components/navbar/navbar.controller.ts[13, 17]: block is empty
[11:40:13] 'lint:scripts:client' errored after 841 ms
[11:40:13] Error in plugin 'gulp-tslint'
Message:
    Failed to lint: components/navbar/navbar.controller.ts[13, 17]: block is empty.
[11:40:13] 'serve' errored after 5.15 s
[11:40:13] Error in plugin 'run-sequence'
Message:
    An error occured in task 'lint:scripts:client'.
[11:40:13] 'lint:scripts' errored after 842 ms
[11:40:13] Error in plugin 'run-sequence'
Message:
    An error occured in task 'serve'.
[11:40:13] 'lint:scripts' errored after 842 ms
[11:40:13] Error in plugin 'run-sequence'
Message:
    An error occured in task 'lint:scripts:client'.

---------------------------------------------

**Comment by mhheise** [comment]
Could you please check your `components/navbar/navbar.controller.ts` to see if there is an empty function block? The `tslint.json` file in the `client` folder has a rule [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/client/tslint.json(ts)#L24). This will throw an error in the `lint:scripts` task if the linter encounters an empty function block.

**Comment by gr8rizwan** [comment]
@mhheise yes, there is an empty constructor, its working now by just removing that empty constructor.

also I believe should work if rule is changed from 'tslint.json'

Thanks a lot ....
