### ISSUE TITLE
Problem with url which is automatically redirect to index.html

### ISSUE THREAD

**Issue by Emidomenge** [angular-fullstack/generator-angular-fullstack#1832]
Sorry for my beginner/stupid question but I really need your help. ^^

Here my problem :
 I generated a new route `yo angular-fullstack:route mainPage`

> ? Where would you like to create this route? client/app/
> ? What will the url of your route be? /mainPage

If I type on my browser, `http://localhost:9000/mainPage` it works.
Now, I want to create a subpage which is accessible by this url `http://localhost:9000/mainPage/subPage`

So  I generated a new route `yo angular-fullstack:route subPage`

> ? Where would you like to create this route? client/app/mainPage/
> ? What will the url of your route be? /subPage
(Also tried)  > ? What will the url of your route be? /mainPage/subPage

But when I type `http://localhost:9000/mainPage/subPage` I'm automatically redirected to the default url `http://localhost:9000/`. 

Thanks in advance.

Item | Version
----- | -----
generator-angular-fullstack | 3.0.0-rc8
Node | 5.7.1
npm | 3.6.0
Operating System |  Windows 7
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML
CSS | CSS 
Router | ngRoute 
Build Tool | Grunt
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
etc | etc

**Comment by elfouad** [comment]
hi,
how does your route config look like after you create the route ?
Look at https://docs.angularjs.org/api/ngRoute/directive/ngView for examples.
Mayme you change your Router to ui-router instead ngRoute.

**Comment by Emidomenge** [comment]
Hey, thanks for your reply ! :+1: 

Well, I change nothing yet in the route config but since you gave me a good example, I might deal with it now. (I'm using ui-router and I will certainly use [angular-breadcrumb](https://github.com/ncuillery/angular-breadcrumb) also !)

Can you just tell me in which path exactly, I should do the `yo angular-fullstack:route subPage` ?
In my above example, is it correct to do it in  `client/app/mainPage/` or should I put it just in ` client/app/` like others ?

**Comment by elfouad** [comment]
Hey,
this is my test config:

> fullstack_test yo angular-fullstack:route mainPage
> ? What module name would you like to use? fullstacktestApp
> ? Where would you like to create this route? client/app/
> ? What will the url of your route be? /mainPage

and 

> fullstack_test yo angular-fullstack:route subPage
> ? What module name would you like to use? fullstacktestApp
> ? Where would you like to create this route? client/app/mainPage/
> ? What will the url of your route be? /mainPage/subPage

this create in mainPage.js

> state('mainPage', {
>         url: '/mainPage',...

and in subPage.js

> .state('subPage', {
>         url: '/mainPage/subPage',

**Comment by Emidomenge** [comment]
Problem solved. Thanks a lot !
