### ISSUE TITLE
Ubuntu 14.04 installation creates no scaffolding for basic setup

### ISSUE THREAD

**Issue by dthompson-mio** [angular-fullstack/generator-angular-fullstack#1837]
running 
npm -v 3.8.7
node -v 0.10.25

run:
$ sudo npm install -g yo grunt-cli gulp-cli bower generator-angular-fullstack
$ mkdir project && cd $_
$ yo angular-fullstack app

select yes for everything (i.e. defaults but I've tried other configurations)

yo outputs:
you're using the fantastic NgComponent generator.
Initializating yo.rc.json configuration.

Then retuns.  The directory is empty.  

I have checked my home directory for hidden .yo-rc.json files and other subdirectories.  
I have updated spawn-sync.
I have uninstalled and re-installed everything.

It does not work.

Item | Version
----- | -----
generator-angular-fullstack | 2.14.20
Node | 0.10.25
npm | 3.8.7
Operating System Ubuntu 14.04 

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Koslun** [comment]
Currently on version 3.6.1 of this generator. If you're generating a new version of the project I'd suggest using that. Not sure that there is necessarily any maintenance for older versions.

Would with that also move to latest LTS version of node, 4.4.3.

**Comment by dthompson-mio** [comment]
apologies I went back and checked my angular-fullstack version.  it is 3.6.1.  So that being said, angular-fullstack 3.6.1 under Ubuntu 14.04 with the most up-to-date npm and stock nodejs package creates an empty directory.

**Comment by Koslun** [comment]
So you are using the latest LTS version of node 4.4.3? Because I can imagine something in the generator breaking between version 0.10 and 4+.

Might be a Yeoman issue as well, which Yeoman version are you using?

**Comment by dthompson-mio** [comment]
I'm running yo 1.7.0 and the the stock nodejs version provided by canonical is v0.10.25.  I'd recommend checking your support for that node version as the generator simply dies.  As built this version of the generator won't work for anyone but a node professional which I don't imagine is the intention.  I was trialing generators this week for suitability for a project coming up and this was the only generator that completely failed.

**Comment by Awk34** [comment]
I would suggest updating Node. Ubuntu hasn't updated their node package in forever. You can find how to do so here: https://nodejs.org/en/

**Comment by Koslun** [comment]
Completely agree on updating to Node 4+. There are breaking changes both from 0.10 to 0.12 and 0.12 to 4+, along with some performance improvements. Where I think a decent amount of packages just don't really even test against 0.10 or even 0.12 anymore.

Just downloading node from the homepage is probably the easiest way but I would also recommend [nvm](https://github.com/creationix/nvm) for installing and updating your node version continuously. Seeing as there are quite a few updates a year, including security related ones.

**Comment by Koslun** [comment]
Should probably also be mentioned that the `package.json` generated does require node ^4.4.0 or higher but less than 5. But maybe this should be explicitly stated in the prerequisites section of the readme of the generator that it only supports version 4.4.0+ and might fail on both 5+ and less than 4.4.0?

**Comment by Awk34** [comment]
Closed due to inactivity
