### ISSUE TITLE
Generating boilerplate stopped working

### ISSUE THREAD

**Issue by sherizan** [angular-fullstack/generator-angular-fullstack#1839]
Hi guys, I've been able to create new routes, directives, etc before without any problems. Only recently I noticed the new files were not injecting into index.html and not creating the new files automatically when I tried "**yo angular-fullstack:directive myDirective**" for example.

Appreciate the help.

Item | Version
----- | -----
generator-angular-fullstack | 3.6.1
Node | 4.2.6
npm | 3.6.0
Operating System | OS X 10.11.3

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ngRoute
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB
Auth | N

**Comment by Awk34** [comment]
@sherizan what was your problem/solution?
