### ISSUE TITLE
ReactJS for the client

### ISSUE THREAD

**Issue by nschurmann** [angular-fullstack/generator-angular-fullstack#1842]
Is there a way to keep all the goodies of the generator but instead of using angular, use ReactJS?

**Comment by Awk34** [comment]
We would have to rename the generator at that point, since the idea is that it's based around Angular..

**Comment by RonAlmog** [comment]
@nschurmann : why, is react that great?
have you looked at angular 2?  
I guess this generator will upgrade to 2.0 in the near future. 
changing to a whole different technology sounds to me like a bit too much to ask.

**Comment by nschurmann** [comment]
@RonAlmog @Awk34 i'm not thinking about replacing angular, but more like to have the option to choose between frontend libs/framework.

**Comment by Koslun** [comment]
@nschurmann: If you want to go for some flux + React thing I think it'd be just plain easier to create a new client that can work against backend in the generator. Maybe most easily done with sub-generators with a bunch of sub-generators with different client integrations being made at https://github.com/FountainJS, though still in pre-alpha I think. With both React, Angular 1 and Angular 2.

Even that would be a huge change and commitment though. And I plainly don't think we want to put our resources in a React alternative. Think we'd rather spend that time improving the current options and at some point moving to Angular 2. That alone is already quite a lot.

And yeah, would basically have to rename the generator at the point where we're also supporting React.

I would just choose another generator that was made with React in mind. Take a look at (react-starter-kit)[https://github.com/kriasoft/react-starter-kit], seems to have a lot of resources committed to it and be quite popular.

**Comment by Awk34** [comment]
We *could* add React alongside Angular, but that's down the road.

**Comment by rvillanueva** [comment]
If anyone's interested, I've started an experimental combination of the angular-fullstack generator (using MongoDB/HTML/SASS) and [react-slingshot](https://github.com/coryhouse/react-slingshot) here:
https://github.com/rvillanueva/react-fullstack-starter

It has a few significant changes, like losing the yeoman generator integration for now and the gulp/grunt pipelines in favor of simpler npm commands.

My main goal is to use it as a boilerplate for my own projects, but might be useful for others in saving time dealing with correctly setting up webpack and basic authentication actions.
