### ISSUE TITLE
bumping connect-mongo broke openshift deploy

### ISSUE THREAD

**Issue by unsalted** [angular-fullstack/generator-angular-fullstack#1844]
Bumping the version of connect-mongo creates an error on fresh deployment to openshift.
Bringing the version back fixed the problem.

Here is potential issue  #1782 

Openshift Log:
````
/var/lib/openshift/XXXXXXXXXXXX/app-root/runtime/repo/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
````

Item | Version
----- | -----
generator-angular-fullstack | 3.6.1
Node | 0.10
Operating System | RHEL Openshift

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | LESS 
Router | ui-router
Build Tool | Grunt
Client Tests | Mocha
DB | MongoDB
Auth | Y

**Comment by Awk34** [comment]
Mmm, this is because of the quite old Node version you & Openshift are using. For now I'd suggest re-installing the latest connect-mongo and importing `connect-mongo/es5` instead of `connect-mongo`, or updating to Node 4.x.x+

**Comment by unsalted** [comment]
Ideally openshift would have a more up to date version of Node, I run 4.x locally but alas community managed deployments are a ways behind.  Thanks for the advice.

**Comment by Awk34** [comment]
@unsalted would adding something to the readme about updating the node version in Openshift help? I found this article: https://blog.openshift.com/any-version-of-nodejs-you-want-in-the-cloud-openshift-does-it-paas-style/

**Comment by unsalted** [comment]
@Awk34 I suppose it would be, I will have to look into how that would work with the app deployment, as you know when using buildcontrol it decides the node module it deploys as. Prior to this change I quite literally didn't need to think at all about openshift deployments using angular-fullstack, just let my fingers do the walking and trust that it was configured to work.  I'm also not certain that custom build has scaling enabled (not essential but certainly ideal).

**Comment by Awk34** [comment]
@unsalted I think what I might do for now is include `connect-mongo/es5` if an older Node version is detected.
