### ISSUE TITLE
My project restarts after every grunt serve stop

### ISSUE THREAD

**Issue by deniz946** [angular-fullstack/generator-angular-fullstack#1857]
Hello, I've installed some libraries with bower like semanticui etc and i use them fine, but when i stop grunt serve and start it again those libraries are deleted from my index.html file and bower folder... how i can make it stop doing that? thanks

Edit: I've commented this in Gruntfile but still not working and it makes me use grunt serve with --force flag

```
 // Empties folders to start fresh
    // clean: {
    //   dist: {
    //     files: [{
    //       dot: true,
    //       src: [
    //         '.tmp',
    //         '<%= yeoman.dist %>/!(.git*|.openshift|Procfile)**'
    //       ]
    //     }]
    //   },
    //   server: '.tmp'
    // },
```

**Comment by deniz946** [comment]
I've figured out that if I install bower dependencies with --save it injects them into index.html and don't deletes theme, but it injects only the .js file, not the css file...

**Comment by Awk34** [comment]
I believe that that's either an issue with the project you're trying to include not having the CSS properly in its `bower.json`, or with [wiredep](https://github.com/taptapship/wiredep) itself
