### ISSUE TITLE
error in new Sequelize instance

### ISSUE THREAD

**Issue by Demonium** [angular-fullstack/generator-angular-fullstack#1859]
Sequelize | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 6.0.0
npm | 3.8.8
Operating System | Debian

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS 
Router | ngRoute 
Build Tool | Grunt 
Client Tests | Jasmine 
DB | SQL
Auth | Y / N
etc | etc
They are a problem in file server/sqldb/index.js
The declaration of the instance Sequelize does not correspond to the signature defined in the below link:
https://github.com/sequelize/sequelize/blob/3e5b8772ef75169685fc96024366bca9958fee63/lib/sequelize.js#L91

So when we define the configuration of the sql statement it does not take the username/password and cannot connect to the database.
Could you please confirm and correct?

**Comment by Awk34** [comment]
`username` and `password` parameters to sequelize are optional. Most local databases for development don't have a username and password, since they don't hold real data and don't expose anything to the web.

**Comment by Demonium** [comment]
I'm agree with you, but in a production environnement the problem will persist and the script to instiate Sequelize is the same for a production environment and a developement environment...

**Comment by Awk34** [comment]
The default case is no credentials. It should be easy enough for you to add them with a few changes.

**Comment by Demonium** [comment]
Yes it is!! But I prefer to talk about it I'm novice on this and if a newbee have the same question now he has the response ☺
