### ISSUE TITLE
Error when generating Users table in MySql

### ISSUE THREAD

**Issue by Demonium** [angular-fullstack/generator-angular-fullstack#1860]
I have connected NodeJs to my MySql Database, the script to create the table Users fail with the below error:

> ==== C stack trace ===============================
> 
>  1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
>  2: init(v8::Local<v8::Object>)
>  3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
>  4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
>  5: 0x98b90b
>  6: 0x98beb1
>  7: 0x124f4c80961b
> Executing (default): CREATE TABLE IF NOT EXISTS `Things` (`_id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `info` VARCHAR(255), `active` TINYINT(1), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`_id`)) ENGINE=InnoDB;
> Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`_id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `email` VARCHAR(255), `role` VARCHAR(255) DEFAULT 'user', `password` VARCHAR(255), `provider` VARCHAR(255), `salt` VARCHAR(255), `facebook` JSON, `twitter` JSON, `google` JSON, `github` JSON, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, UNIQUE `Users_email_unique` (`email`), PRIMARY KEY (`_id`)) ENGINE=InnoDB;
> Unhandled rejection SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON, `twitter` JSON, `google` JSON, `github` JSON, `createdAt` DATETIME NOT NUL' at line 1
>     at Query.formatError (/home/djo/apps/pensieve/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
>     at Query._callback (/home/djo/apps/pensieve/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
>     at Query.Sequence.end (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
>     at Query.ErrorPacket (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
>     at Protocol._parsePacket (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/Protocol.js:280:23)
>     at Parser.write (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/Parser.js:73:12)
>     at Protocol.write (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/Protocol.js:39:16)
>     at Socket.<anonymous> (/home/djo/apps/pensieve/node_modules/mysql/lib/Connection.js:96:28)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:172:18)
>     at Socket.Readable.push (_stream_readable.js:130:10)
>     at TCP.onread (net.js:535:20)
> From previous event:
>     at Query.run (/home/djo/apps/pensieve/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
>     at /home/djo/apps/pensieve/node_modules/sequelize/lib/sequelize.js:844:20
>     at /home/djo/apps/pensieve/node_modules/retry-as-promised/index.js:38:21
> From previous event:
>     at retryAsPromised (/home/djo/apps/pensieve/node_modules/retry-as-promised/index.js:27:10)
>     at .<anonymous> (/home/djo/apps/pensieve/node_modules/sequelize/lib/sequelize.js:843:12)
> From previous event:
>     at Promise.then (/home/djo/apps/pensieve/node_modules/sequelize/lib/promise.js:21:17)
>     at Model.sync (/home/djo/apps/pensieve/node_modules/sequelize/lib/model.js:1008:6)
>     at Object.<anonymous> (seed.js:46:6)
>     at Module._compile (module.js:541:32)
>     at loader (/home/djo/apps/pensieve/node_modules/babel-register/lib/node.js:126:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/djo/apps/pensieve/node_modules/babel-register/lib/node.js:136:7)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12)
>     at Function.Module._load (module.js:407:3)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (app.js:13:22)
>     at Module._compile (module.js:541:32)
>     at loader (/home/djo/apps/pensieve/node_modules/babel-register/lib/node.js:126:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/djo/apps/pensieve/node_modules/babel-register/lib/node.js:136:7)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12)
>     at Function.Module._load (module.js:407:3)
>     at Module.require (module.js:466:17)
> 

Could you please fix it

**Comment by Demonium** [comment]
Can Close find the solution, in the declaration of the Users model the line below must be changed with 
    facebook: DataTypes.STRING,
    twitter: DataTypes.STRING,
    google: DataTypes.STRING,
    github: DataTypes.STRING

**Comment by kcampion** [comment]
If you change "google: DataTypes.JSON," to "google: DataTypes.STRING," this error appears during the Google login:
`SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'User.google.id' in 'where clause'`

**Comment by okcjosh** [comment]
Reopen the issue. kcampion has a valid issue, and i have the same one. Changing dataType to STRING only quiets the error but breaks the OAuth/Passport functionality.

**Comment by shaharyar123** [comment]
i am facing the OAUTH issue when i assign datatype JSON to facebook and google. my database is mysql, getting this error :

`Server failed to start due to error: SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON,twitterJSON,googleJSON,providerVARCHAR(255),saltVARCHAR(255' at line 1`

if i set datatype : text or string then it works but i cant query on them. How to store in JSON datatype in MySql ?
