### ISSUE TITLE
factory module not avaible

### ISSUE THREAD

**Issue by deniz946** [angular-fullstack/generator-angular-fullstack#1863]
I've created a factory module with angular-fullstack:factory myfactory 

and it looks like 

```
'use strict';

angular.module('librostradingApp.Books')
  .factory('Books', function () {
    // Service logic
    // ...

    var meaningOfLife = 42;

    // Public API here
    return {
      someMethod: function () {
        return meaningOfLife;
      }
    };
  });

```

but when I try to inject Books in some another controller I get this erros and it doesnt work... 

```
angular.js:68 Uncaught Error: [$injector:nomod] Module 'librostradingApp.Books' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=librostradingApp.Books(anonymous function) @ angular.js:68(anonymous function) @ angular.js:2070ensure @ angular.js:1994module @ angular.js:2068(anonymous function) @ Books.service.ts:3
angular.js:68 Uncaught Error: [$injector:nomod] Module 'librostradingApp.testctrl' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=librostradingApp.testctrl(anonymous function) @ angular.js:68(anonymous function) @ angular.js:2070ensure @ angular.js:1994module @ angular.js:2068(anonymous function) @ testctrl.controller.ts:3
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module librostradingApp due to:
Error: [$injector:modulerr] Failed to instantiate module librostradingApp.Books due to:
Error: [$injector:nomod] Module 'librostradingApp.Books' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=librostradingApp.Books
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:2070:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:1994:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:2068:14)
    at http://localhost:9000/bower_components/angular/angular.js:4564:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at http://localhost:9000/bower_components/angular/angular.js:4565:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=librostradingApp.Bo…2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4548%3A5)
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:4587:15
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at http://localhost:9000/bower_components/angular/angular.js:4565:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4470:19)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1746:20)
    at bootstrap (http://localhost:9000/bower_components/angular/angular.js:1767:12)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=librostradingApp&p1…F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1767%3A12)(anonymous function) @ angular.js:68(anonymous function) @ angular.js:4587forEach @ angular.js:322loadModules @ angular.js:4548createInjector @ angular.js:4470doBootstrap @ angular.js:1746bootstrap @ angular.js:1767angularInit @ angular.js:1652(anonymous function) @ angular.js:30863fire @ jquery.js:3187self.fireWith @ jquery.js:3317jQuery.extend.ready @ jquery.js:3536completed @ jquery.js:3552
inject.js:56 Capturing clicks
```

If i change the name of module from librostradingApp.Books to librostradingApp it works... but i want to know why it doesnt work with the first one... Thanks you

**Comment by Awk34** [comment]
Is it properly loading the `librostradingApp.Books` angular module file?

**Comment by deniz946** [comment]
```
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <base href="/">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="bower_components/semantic/dist/semantic.min.css">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!-- build:css(client) app/vendor.css -->
      <!-- bower:css -->
      <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="bower_components/bootstrap-social/bootstrap-social.css" />
      <!-- endbower -->
    <!-- endbuild -->
    <!-- build:css({.tmp,client}) app/app.css -->
      <link rel="stylesheet" href="app/app.css">
      <!-- injector:css -->
      <link rel="stylesheet" href="app/admin/admin.css">
      <link rel="stylesheet" href="app/app.css">
      <link rel="stylesheet" href="app/books/books.css">
      <link rel="stylesheet" href="app/main/main.css">
      <link rel="stylesheet" href="components/footer/footer.css">
      <link rel="stylesheet" href="components/oauth-buttons/oauth-buttons.css">
      <!-- endinjector -->
    <!-- endbuild -->
  </head>
  <body ng-app="librostradingApp">
    <!--[if lt IE 7]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Add your site or application content here -->
    <navbar></navbar>
    <div ui-view=""></div>
    <footer></footer>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-XXXXX-X');
      ga('send', 'pageview');
    </script>

    <!--[if lt IE 9]>
    <script src="bower_components/es5-shim/es5-shim.js"></script>
    <script src="bower_components/json3/lib/json3.min.js"></script>
    <![endif]-->
    <!-- build:js({client,node_modules}) app/vendor.js -->
      <!-- bower:js -->
      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
      <script src="bower_components/angular-validation-match/dist/angular-validation-match.min.js"></script>
      <script src="bower_components/semantic/dist/semantic.js"></script>
      <!-- endbower -->
    <!-- endbuild -->
    <!-- build:js({.tmp,client}) app/app.js -->
      <script src="app/app.js"></script>
      <!-- injector:js -->
      <script src="components/auth/auth.module.js"></script>
      <script src="app/admin/admin.module.js"></script>
      <script src="components/util/util.module.js"></script>
      <script src="app/account/signup/signup.controller.js"></script>
      <script src="app/admin/admin.controller.js"></script>
      <script src="app/account/account.js"></script>
      <script src="app/admin/admin.router.js"></script>
      <script src="app/books/books.controller.js"></script>
      <script src="app/books/books.js"></script>
      <script src="app/factories/Books/Books.service.js"></script>
      <script src="app/main/main.controller.js"></script>
      <script src="app/main/main.js"></script>
      <script src="app/testctrl/testctrl.controller.js"></script>
      <script src="app/account/login/login.controller.js"></script>
      <script src="components/auth/auth.service.js"></script>
      <script src="components/auth/interceptor.service.js"></script>
      <script src="components/auth/router.decorator.js"></script>
      <script src="components/auth/user.service.js"></script>
      <script src="components/footer/footer.directive.js"></script>
      <script src="components/mongoose-error/mongoose-error.directive.js"></script>
      <script src="components/navbar/navbar.controller.js"></script>
      <script src="components/navbar/navbar.directive.js"></script>
      <script src="components/oauth-buttons/oauth-buttons.controller.js"></script>
      <script src="components/oauth-buttons/oauth-buttons.directive.js"></script>
      <script src="app/account/settings/settings.controller.js"></script>
      <script src="components/util/util.service.js"></script>
      <script src="app/app.constant.js"></script>
      <!-- endinjector -->
    <!-- endbuild -->
  </body>
</html>
```

Looks like this

**Comment by Awk34** [comment]
are you including the `librostradingApp.Books` dependency in your `app.js`?

**Comment by deniz946** [comment]
Nop, but if I include, it, I get bigger error message :(

```
'use strict';

angular.module('librostradingApp', [
  'librostradingApp.auth',
  'librostradingApp.admin',
  'librostradingApp.constants',
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'ui.router',
  'validation.match',
  'librostradingApp.Books'

  ])
  .config(function($urlRouterProvider, $locationProvider) {
    $urlRouterProvider
      .otherwise('/');

    $locationProvider.html5Mode(true);
  });
```
Uncaught Error: [$injector:nomod] Module 'librostradingApp.testctrl' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=librostradingApp.testctrl
angular.js:4587 Uncaught Error: [$injector:modulerr] Failed to instantiate module librostradingApp due to:
Error: [$injector:modulerr] Failed to instantiate module librostradingApp.Books due to:
Error: [$injector:nomod] Module 'librostradingApp.Books' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=librostradingApp.Books
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:2070:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:1994:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:2068:14)
    at http://localhost:9000/bower_components/angular/angular.js:4564:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at http://localhost:9000/bower_components/angular/angular.js:4565:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=librostradingApp.Bo…2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4548%3A5)
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:4587:15
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at http://localhost:9000/bower_components/angular/angular.js:4565:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4470:19)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1746:20)
    at bootstrap (http://localhost:9000/bower_components/angular/angular.js:1767:12)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=librostradingApp&p1…F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1767%3A12)
```


```
Uncaught Error: [$injector:nomod] Module 'librostradingApp.testctrl' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=librostradingApp.testctrl
angular.js:4587 Uncaught Error: [$injector:modulerr] Failed to instantiate module librostradingApp due to:
Error: [$injector:modulerr] Failed to instantiate module librostradingApp.Books due to:
Error: [$injector:nomod] Module 'librostradingApp.Books' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=librostradingApp.Books
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:2070:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:1994:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:2068:14)
    at http://localhost:9000/bower_components/angular/angular.js:4564:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at http://localhost:9000/bower_components/angular/angular.js:4565:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=librostradingApp.Bo…2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4548%3A5)
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:4587:15
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at http://localhost:9000/bower_components/angular/angular.js:4565:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:322:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4548:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4470:19)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1746:20)
    at bootstrap (http://localhost:9000/bower_components/angular/angular.js:1767:12)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=librostradingApp&p1…F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1767%3A12)
```

**Comment by Awk34** [comment]
It looks like you might have some modules loading out-of-order. If you want to get things running for now, I'd just not create submodules and add your Books service to your `librostradingApp` module. A lot of this stuff will be re-written in the generator soon anyway.

**Comment by Emidomenge** [comment]
I have the same problem with my service.

Even if i change the name of module from myApp.myService to myApp it still doesn't work
