### ISSUE TITLE
Stop regenerating default files

### ISSUE THREAD

**Issue by deniz946** [angular-fullstack/generator-angular-fullstack#1865]
Hello, I want to start my own project and I dont want to grunt regenerate all default files and things with each restart, how i can disable it? Thanks you?

i.e: i delete main folder, and it comes back automatically after grun restart

**Comment by Awk34** [comment]
When you re-run `grunt serve`, it's re-adding the `client/app/main` folder that you deleted??

**Comment by deniz946** [comment]
Yes

**Comment by Awk34** [comment]
I can't think of any reason off the top of my head why that would be happening

**Comment by Awk34** [comment]
I can't reproduce any of this
