### ISSUE TITLE
Updating an application to the new version of the generator

### ISSUE THREAD

**Issue by aabm00** [angular-fullstack/generator-angular-fullstack#1876]
Item | Version
----- | -----
generator-angular-fullstack | 3.6.1
Node | 4.2.3
npm | 3.7.5
Operating System | Windows 7
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | CSS 
Router | / ui-router
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB
Auth | Y 
socket.io | etc

Hi.
Lately there frequently updates the generator, and I wanted to know if there are an easy  way to update an application generated for example with the version 3.6 with the upgrades of the version 3.7.

Thanks

**Comment by Awk34** [comment]
#185
