### ISSUE TITLE
app.constants Issue

### ISSUE THREAD

**Issue by Stalso** [angular-fullstack/generator-angular-fullstack#1879]
Item | Version
----- | -----
generator-angular-fullstack | 3.6.1
Node | 5.10.1
npm | 3.8.3
Operating System | Windows 8.1 

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | Jade
CSS | LESS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB 
Auth | Y

Hello. I have some issue with `app.constants`. When I call `gulp serve` this file is empty in .tmp folder and I get blank page with angular error, which says that angular cannot find `app.constants` module.

**Comment by elfouad** [comment]
hey,
in the gruntfile.js, there is a task called ngconstant. This task puts the content of server/config/environment/shared.js in your app/app.constant.js.
Maybe you delete the shared file ?

**Comment by Awk34** [comment]
Well, he scaffolded with Gulp, so it'd be the gulp `constant` and `copy:constant` tasks to look at. Make sure they're doing what they're supposed to.

**Comment by Stalso** [comment]
No, I have not modified anything. I have generated project and fired `gulp serve`. By the way, sometimes it works. I can not figure out when it overwrites the file.

**Comment by yan-chen** [comment]
Mine too. Sometimes it shows the error, but it shows fine after re-starting gulp serve or refreshing the page.

**Comment by HugoPoi** [comment]
I have the same issue with 3.6.1 generator, gulp/typescript/sass/ngRouter under Linux/node 6.1

**Comment by HugoPoi** [comment]
I think the task `copy:constant` cannot be launch // with the task `constant`

**Comment by Koslun** [comment]
I think this relates to issue #1830, which was fixed and merged with version 3.7.0. See fix here: https://github.com/angular-fullstack/generator-angular-fullstack/commit/f07b451. It was part of this PR: #1836

**Comment by HugoPoi** [comment]
We can close this issue  because commit https://github.com/angular-fullstack/generator-angular-fullstack/commit/f07b451 resolve the problem :-)

**Comment by Koslun** [comment]
Just closing for now then.
