### ISSUE TITLE
"Warning: a promise was created in a handler but was not returned from it" when running after generating new app.

### ISSUE THREAD

**Issue by lydemeister** [angular-fullstack/generator-angular-fullstack#1882]
"Warning: a promise was created in a handler but was not returned from it" when running after generating new app and running "gulp serve".

Item | Version
----- | -----
generator-angular-fullstack | 3.6.1
Node | 5.1.0
npm | 3.3.12
Operating System Windows

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS |  SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y

**Comment by Awk34** [comment]
#1721

**Comment by chovy** [comment]
I'm still getting this.
