### ISSUE TITLE
Users are  not persisted

### ISSUE THREAD

**Issue by nelsonlho** [angular-fullstack/generator-angular-fullstack#1885]
It seems like every time I restarted the server, the _id of User of test@example.com is different.
So I tried to register as another user, and after a refresh I need to register again.

Just need some reasoning behind this, and how I can persist the user info. 

- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by RonAlmog** [comment]
The registration does not involve the id. only email and password. so there should be no problem.
on my machine the users are being regenerated (from seed) every time i do any change (every 10 min...) and the users registration is saved in the browser. let's think what's different in your case?

**Comment by mhheise** [comment]
You should take a look at [this](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/server/api/user(auth)/user.model(sequelizeModels).js#L17) and [this](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/server/config/environment/development.js#L25) for your issue. If `seedDB` is set to `true`, then the database will be reseeded when you run `gulp serve`. Combined with `autoIncrement` set to `true` for this column in this model, this means that every new user that populates this table when the server is restarted will have an automatically generated new `_id`. If this is not desired, you can simply set `seedDB` to `false` in your development environment configuration.

**Comment by RonAlmog** [comment]
After reading your q again, maybe this is your problem: you need another user(s)? 
just add them to the seed function. they will be recreated again every time, and you will not have to register with that user again. let me know if you need code sample.

**Comment by Awk34** [comment]
@mhheise 's answer is correct: When running the dev server, every time the server is restarted, we re-seed the database. You're going to want fresh data every time you change something server side, so that your current DB won't be affected by anything you could have done previously. This is disabled for production, of course.
