### ISSUE TITLE
node-inspector on Openshift

### ISSUE THREAD

**Issue by Coder2012** [angular-fullstack/generator-angular-fullstack#1887]
I don't know if this problem is with the generator or Openshift, but as this is the recommended framework to use, here goes. I want to use node-inspector for debugging, I rhc into my openshift app to debug:

```
node --debug app.js
debugger listening on port 5858
Failed to open socket on port 5858, waiting 1000 ms before retrying
```

I have been all over the internet, I've tried doing port forwarding but don't see 5858 listed, please can someone help me to get node-inspector working with this generator on Openshift

**Comment by Awk34** [comment]
Have you tried changing the debug port?

**Comment by Coder2012** [comment]
Thanks for the response man, I tried many ports, always same result

```
> node --debug=8888 app.js
debugger listening on port 8888
Failed to open socket on port 8888, waiting 1000 ms before retrying
```

**Comment by Awk34** [comment]
I'm not really familiar with Openshift. Does it not allow you to open your own ports?

**Comment by Coder2012** [comment]
I'm not sure if I can open specific ports or not, they do allow port forwarding but that just maps services that are already running and node-inspector doesn't run because it can't use any ports.

**Comment by Awk34** [comment]
¯\\\_(ツ)\_/¯ well, I doubt it's an issue with this generator. More of an Openshift thing. You should still be able to run node-inspector locally without a hitch.

**Comment by riclf** [comment]
"You should still be able to run node-inspector locally without a hitch."
That completely ignores the subject. Coder2012 does not want to run node-inspector locally because his node.js app is running on Redhat's Openshift in the cloud!  Running n-i locally does not address the issue being discussed.

**Comment by Awk34** [comment]
@riclf I wouldn't describe this as being a bug with the generator, but rather an issue with Openshift ports. That's why the issue was closed and tagged as 'upstream'.

**Comment by riclf** [comment]
@Awk34 I do agree. It seems to be an Openshift issue, not with the generator. I wish someone had found the way to circumvent the issue, availing use of n-i on Openshift. Running a test bed on a local network can have subtle but meaningful differences from its operation in the remote cloud.

**Comment by Awk34** [comment]
@riclf yes, but for the most part using a debugger on your Node server locally vs running on your server should not have many differences; I'd imagine mostly in just performance. I don't use Openshift so I have no idea what the port situation is there.
