### ISSUE TITLE
Dependencies 'bluebird' missing

### ISSUE THREAD

**Issue by HugoPoi** [angular-fullstack/generator-angular-fullstack#1888]
Package.json doesn't contains 'bluebird' dependency.
Introduce here https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/src/generators/util.js#L6

Version 3.7.0

**Comment by hitchan** [comment]
I am also running into this issue when scaffolding a new project.

**Comment by Awk34** [comment]
Thanks, fixed in 3.7.1
