### ISSUE TITLE
yo angular-fullstack does not work

### ISSUE THREAD

**Issue by codingmaven** [angular-fullstack/generator-angular-fullstack#1889]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Need Help.

dreamsoft@localhost:~/Gits/node-java$ yo angular-fullstack

events.js:154
      throw er; // Unhandled 'error' event
      ^

ReferenceError: cb is not defined
    at Generator.init (/home/dreamsoft/.nvm/versions/node/v5.10.1/lib/node_modules/generator-angular-fullstack/generators/app/index.js:110:55)
    at Object.<anonymous> (/home/dreamsoft/.nvm/versions/node/v5.10.1/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:431:23)
    at /home/dreamsoft/.nvm/versions/node/v5.10.1/lib/node_modules/generator-angular-fullstack/node_modules/run-async/index.js:26:25
    at /home/dreamsoft/.nvm/versions/node/v5.10.1/lib/node_modules/generator-angular-fullstack/node_modules/run-async/index.js:25:19
    at /home/dreamsoft/.nvm/versions/node/v5.10.1/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:432:9
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

Item | Version
----- | -----
generator-angular-fullstack | ???
Node | 6.1.0
npm | 3.8.3
Operating System | ubuntu 14
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Awk34** [comment]
Which version of the generator? Also, you say you're using node 6.1.0, but your stack trace says you're on 5.10.1

**Comment by Awk34** [comment]
Please try generator version 3.7.2

**Comment by codingmaven** [comment]
It works like a magic. Thanks.
