### ISSUE TITLE
How to add js lib to only one page?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1891]
What's the best way to use a js library (local or cdn) only in one page?

just to add it to the index.html would not be good, as i don't want to load it with every page.
maybe add it to the view?   but then it will not be minified with the others, right?
is there any common way to handle this?

What if i need to inject that library in the html head? (again, only in one or 2 pages).

**Comment by Awk34** [comment]
This isn't really easy to do without a module loader like Webpack, SystemJS, or Browserify.

The next major release of the generator will use Webpack
