### ISSUE TITLE
ERROR: Can't find config file: server/.jshintrc

### ISSUE THREAD

**Issue by Stalso** [angular-fullstack/generator-angular-fullstack#1893]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.0
Node | 5.10.1
npm | 3.8.3
Operating System | Windows 8.1 

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | Jade
CSS | LESS
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB | MongoDB 
Auth | Y

Hello. I am getting such error, when I have generated project and fired `gulp:serve`

**Comment by fercreek** [comment]
@Stalso  I had the same problem, i used grunt and i dont have problems anymore. For now..

**Comment by Koslun** [comment]
Probably want to actually show what the error is.

**Comment by elimence** [comment]
Getting the same error:

`ERROR: Can't find config file: server/.jshintrc`

**Comment by elimence** [comment]
Ok, this error goes away after I manually add the .jshintrc file

**Comment by Awk34** [comment]
Here's the problem: https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/.npmignore#L11

the `.jshintrc` in `.npmignore` is ignoring the project's as well as the one in `templates/app/server`

**Comment by Awk34** [comment]
Can you confirm that 3.7.3 works?

**Comment by elimence** [comment]
Tried reinstalling, but still got 3.7.2
How can I get 3.7.3?

**Comment by Awk34** [comment]
oh, hmmm, looks like my npm publish didn't go through

**Comment by Awk34** [comment]
@elimence should be published now

**Comment by elimence** [comment]
@Awk34 Yes, this fixes the issue.
Thanks
