### ISSUE TITLE
Grunt won't add Semantic UI path to index.html file.

### ISSUE THREAD

**Issue by Pablocgdev** [angular-fullstack/generator-angular-fullstack#1901]
I'm installing Semantic UI using bower, while other packages are working as expected, Semantic UI paths are not added automatically with `grunt wiredep:client`

**Comment by Awk34** [comment]
Did you only install Semantic UI, or did you build it too? Semantic isn't a package of front-end resources like bootstrap, you have to follow their doc to init it with the options that you'd like.
