### ISSUE TITLE
Adding Socket.io after you've already generated scaffolding 

### ISSUE THREAD

**Issue by croossin** [angular-fullstack/generator-angular-fullstack#1904]
I understand that I could just rescaffold the entire project, keep all the files that are already there and then add Socket.io that way.  However, I was curious if there was a simple yo command with your generator that allowed you to inject socket.io in pre existing projects? Thanks!

**Comment by Awk34** [comment]
Nope. Your best bet would probably be to commit/stash all your unsaved changes, and run the generator again on top of your current code. Then you can easily see which files are changed/created.
