### ISSUE TITLE
Facebook login: where can I get the data?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1906]
Question regarding logging in with facebook/google/etc.
So the user does not have to register? she can just put her facebook credential and log in.
What will be in the user table? nothing?  I must have a record where i can attach her transactions, activities, etc.
Where is the point where i get the data from facebook/google and I can take that and create or update the user record?

**Comment by Awk34** [comment]
Why don't you try it out and see?

The user will have a `facebook` object attached with all the data that the Facebook OAuth API gives you

**Comment by RonAlmog** [comment]
True. Thank you! :)
