### ISSUE TITLE
Convert/update my angular-fullstack release 3.0.0-rc8 project to the last release 3.7.0

### ISSUE THREAD

**Issue by Emidomenge** [angular-fullstack/generator-angular-fullstack#1909]
Since there is some change between release **3.0.0-rc8** and **3.7.0**, I'm wondering if it's hard or not to update my angular-fullstack project.

Do I need to re-write everything ? Or should I make some partial changes ?

Thanks !
_____________________________________________________________________________

 - [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.0.0-rc8
Node | 5.7.1
npm | 3.6.0
Operating System |  Windows 7
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML
CSS | CSS 
Router | ngRoute 
Build Tool | Grunt
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
etc | etc

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/issues/185
