### ISSUE TITLE
Proper logo

### ISSUE THREAD

**Issue by Awk34** [angular-fullstack/generator-angular-fullstack#1910]
![12663106](https://cloud.githubusercontent.com/assets/5545474/15430484/92caf574-1e73-11e6-8b8e-541a951088ca.png)

I threw together the current logo a while ago, just because we didn't have one at all, but I'd like to get a proper good-looking logo. The Yeoman graphics source files are here: yeoman/media](https://github.com/yeoman/media). I was thinking we could use some of those to make a yeoman cartoon specific to this generator.

**Comment by Koslun** [comment]
Wondering if we should try to connect it to Node.js as well in some way. If so here is the link to the official resources for Node.JS: https://nodejs.org/en/about/resources/. Would mostly only dare use it to get the colors right.

Wild Suggestions:
* Change both or one of the halves of the angular shield to a shade of node.js green or white.
* Put a modified yeoman guy on top of some angular shield. Change his color scheme to some blend of the Angular red or/and NodeJS green and white and maybe change the "Y" on his shirt to "JS".

**Comment by blakemanzo** [comment]
@Koslun @Awk34 too christmassy?
![angular-fullstack-2](https://cloud.githubusercontent.com/assets/8487266/16362438/3b3901c4-3bf2-11e6-8da3-79caba0c4fd0.png)
![angular-fullstack-1](https://cloud.githubusercontent.com/assets/8487266/16362439/3b40cde6-3bf2-11e6-8677-c2f74e15c63d.png)

**Comment by Koslun** [comment]
@blakemanzo Heh, you're right. The green and blue combination does give a very christmassy feel. Not sure that I mind much myself.

Think I prefer the bottom one of the two.

Might be interesting to experiment with more white from node js logo. Like the color of his shirt. Might end up making it even more christmassy though.

Might be that we need to make a more original cartoon, like @Awk34 mentioned above though.

**Comment by Awk34** [comment]
I should also mention #460

I'm not a fan of either, @blakemanzo . I like the direction, and thanks for submitting them, but if you're ever going to use another project's logo, **never** change it's color.

**Comment by Koslun** [comment]
Fair point with changing the color scheme of another project's logo.

Not very hopeful about #460 author coming back but seems like a good template for a site. Currently   however mostly looking over at http://fountainjs.io/ for inspiration.

Thinking one direction we're on then is using the Angular logo shield with some original cartoon with a blend of Node and Angular colors, i.e. green, red and white.

Could potentially also do something fun like the logo in http://fountainjs.io/gulp-angular/ (yeoman guy sipping on gulp while sitting on angular).

**Comment by Awk34** [comment]
I wouldn't even mind something like what #460 has. Simple.

I also like that gulp-angular logo. Maybe edit so that he's sitting on a bunch of boxes?

**Comment by blakemanzo** [comment]
Good point about not changing color schemes! I didn't notice #460 - that looks like a great start and something simple might be the way to go,

![angular-fullstack-3](https://cloud.githubusercontent.com/assets/8487266/16421419/3d530e26-3d98-11e6-8d54-8fee4145fe58.jpg)

There's also the artwork of the yeoman gentleman holding boxes with the names - could replace these with Mongo/SQL/Express/Angular/Node boxes?

Or a mixture of both? The official logo simple, similar to 460, and then we use the holding boxes artwork as well,

**Comment by Awk34** [comment]
@blakemanzo Cool!

For the boxes, I was thinking something more like this:

```
   Y
   _  
 _|_|_
|_|_|_|
```

With the top box being Angular, and the bottom being the back-end. Is that doable?

I also really like the top-left icon :D

**Comment by blakemanzo** [comment]
How's this?

![angular-fullstack-5](https://cloud.githubusercontent.com/assets/8487266/16498965/915a4c66-3efe-11e6-919a-f70d5057f6e5.jpg)

**Comment by Awk34** [comment]
@blakeblackshear ugh, perfect. Do you think you can add SVG's of this and the top-left one from the previous post?

**Comment by blakemanzo** [comment]
You mean this?

![yeoman-hat](https://cloud.githubusercontent.com/assets/8487266/16499483/05125002-3f01-11e6-9fe9-469f8137307d.jpg)

This is the standard yeoman logo from here;
[](https://github.com/yeoman/media)

**Comment by Awk34** [comment]
@blakemanzo with the four circles next to it

**Comment by blakemanzo** [comment]
No worries - i'll add SVG / AI versions of everything in a pull request

**Comment by blakemanzo** [comment]
Pull request at #2032
