### ISSUE TITLE
all frontend files are 404'ing after building app

### ISSUE THREAD

**Issue by mrmayfield** [angular-fullstack/generator-angular-fullstack#1914]
![screen shot 2016-05-20 at 9 57 21 pm](https://cloud.githubusercontent.com/assets/7200471/15446440/f5c9cc88-1ed5-11e6-9b3f-d166238654e8.png)

`grunt serve` works fine without this error. this is happening when I build though, the app seems to work but what is this for? 

another time I'm building, I get these same errors and nothing appears for the app.

**Comment by Awk34** [comment]
I believe there are a few duplicate issues about the same thing (hard to find the exact ones, I'm on my phone). Check that you have consistent line endings, grunt-usemin doesn't like inconsistent line endings.

**Comment by Awk34** [comment]
#370
