### ISSUE TITLE
Different config files

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1915]
Can anybody please explain the purpose of the different files in server/config ?
in the folder 'environment' i see several files that might be for dev/prod etc. but what is index.js?
and shared.js?  do they contain settings for all environments?
where is the best place for example for storing the facebook_id ?
it is both in local.env.js, and index.js.

**Comment by Awk34** [comment]
`local.env.js` loads everything given as environment variables. It's good for keeping your dev IDs & secrets for ex. a dev facebook login.
`environment/index.js` loads all the common config, shared config, and config specific to which env you're in (development, production, test, etc). In node.js, if you load `environment/`, it will look for an `index.js` file in that folder.
`shared.js` has all the config that is shared between front-end and back-end. Config in this file will get loaded into the `client/app/app.constant.js` file.

**Comment by RonAlmog** [comment]
great explanation. thank you!
