### ISSUE TITLE
yo angular-fullstack:heroku not working

### ISSUE THREAD

**Issue by savli** [angular-fullstack/generator-angular-fullstack#1916]
Hello, I am trying to deploy a brand new application, via the `yo angular-fullstack:heroku` command but for some reason it is not working. 

When I enter the `yo angular-fullstack:heroku` command via CLI, I get the first line:

`Name to deploy as (Leave blank for a random name):`

And then the command fails to continue and no heroku application is made. Any help would be appreciated. I am logged into my Heroku account, so this does not seem to be the issue.

**Comment by savli** [comment]
Instead of running `yo angular-fullstack:heroku`, I created a new application via my Heroku account, and ran the command `git push heroku master` from the `dist` folder. This worked great

**Comment by wikett** [comment]
Hi, I have the same problem, but I don't know how to fix it.

After installing angular-fullstack, have I to create a heroku app?

1. cd dist
2. heroku create
3. git init
4. git add .
5. git commit -m "first commit"
6. git push heroku master
7. heroku open

Can you tell me whats the correct order and what folder must I be??

Regards
