### ISSUE TITLE
deployment to openshift suddenly broken

### ISSUE THREAD

**Issue by davidkonrad** [angular-fullstack/generator-angular-fullstack#1919]
I have updated my openshift app many, many times by using 

```
grunt build
grunt buildcontrol:openshift

```
Today this suddenly is failing, I get the error

```
 ...
 Pushing master to openshift
 Warning: fatal: 'openshift' does not appear to be a git repository
 fatal: Could not read from remote repository.

```
I have changed nothing, and my openshift app is alive and I can use remote mysql and so on. 

What could possible be wrong? Have anyone experienced something similar? It seems as the link to the openshift git is broken, how do I update that? I have seen this closed issue -> https://github.com/angular-fullstack/generator-angular-fullstack/issues/1351 but I have not changed anything regarding git.

**Comment by Awk34** [comment]
Try deleting `dist/.git` and redeploying, maybe

**Comment by davidkonrad** [comment]
@Awk34 , That was a very good idea!! But no luck. I delete `dist/.git`, run `grunt build` and `grunt buildcontrol:openshift`, but get the same error message.

**Comment by Awk34** [comment]
You fixed it?

**Comment by davidkonrad** [comment]
@Awk34 , sry no - if I had, I would certainly have posted the solution. Nothing worked, not even deleting the app on openshift and reinstall completely.  I dont know how, but I guess somehow my git was broken. So I gave up, after all my openshift install was only a temporary solution while I was waiting to have the time to set up a server up myself - so did this instead, RHEL and so on as well. No problems at all. The buildcontrol:openshift is really cool and handy and have worked for me as a charm, I will use it again - guess I just was unlucky in an area where I am not so skilled, to say the least :)
