### ISSUE TITLE
Roadmap to 2.0.0

### ISSUE THREAD

**Issue by DaftMonk** [angular-fullstack/generator-angular-fullstack#192]
For Angular Fullstack 2.0.0, I'm making some major changes to the way the project is structured. I want to get feedback from the community on the direction I'll be going.

Here's the relevant links, with explanation of the changes below

New generator that will take the role of the fullstack sub-generators: https://github.com/DaftMonk/generator-ng-component. 

New project structure: 
https://github.com/DaftMonk/modular-fs
### Changes to build process and structure:

The server and client sides are now using a modular file structure, and the build process has been improved to handle it. 
- Angular client now uses the Google's project recommendations: 
  https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub
- Component scss is automatically injected into app.scss.
- Templates are now compiled into a single javascript payload using grunt-angular-templates.

The Express server now follows similar structure:
- Each server component folder would contain something like this:
  -  name.js         (for routes)
  -  name-model.js
  -  name-model_spec.js
  -  name-controller
  -  name-controller_spec.js
- Server component models and routes are automatically loaded.
- Better 404 handling. Asset folders will now send a 404 if there is no defined resource, which will override the catch-all redirect to index.html. 
- Client and server side tests now look for `_spec.js` files to run their tests.
- Views folder is now meant purely for express rendered views. Having express and angular share views files only complicated things in the build process and in the app. Even if you use a preprocessor like jade for your html views, they should compile down into html so that they can be served as an html to js payload.
### Changes to the generator:

I will be removing all current angular-fullstack sub generators, and creating a separate generator for angular components.  The .yo-rc.json file will allow you to configure project and template paths. I've started work on this here: https://github.com/DaftMonk/generator-ng-component. 

The new ng-component generator will support scaffolding routes with the angular-ui router as well as  ngRoute.

The angular-fullstack generator will save configurations in the .yo-rc.json file as well, so you can reuse your configurations between projects.

A link to the new project structure is provided above. You can clone the new project structure for yourself, npm and bower install, and try it out. Please tell me what you think!

**Comment by wrjanan** [comment]
I started using this generator as a means to provide a standard input to my Company's coding style.
Having originally custom built an app without a generator, I found much use with node-restful https://github.com/baugarten/node-restful which builds a restful api based on the schema provided. 

The most important function it provided was the built-in filters which allows for targeted data selection.

Am wondering if there will be an implementation for this function in the future, or maybe if others will find this useful too - to add in functionality to build a restful api.
