### ISSUE TITLE
babel needed to run gulpfile?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1922]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 6.2.0
npm | 3.9.2
Operating System | Windows 10 
etc | etc

Item | Answer
----- | -----
Transpiler |  TypeScript
Build Tool |  Gulp
etc | etc

I ran the generator with Typescript and Gulp selected.
the gulp file is called gulpfile.babel.js, and contains things like:
import _ form 'lodash';
that are ES6.
gulp yells at me that import is bad.
Does that mean that i have to install babel before i can run gulp?

**Comment by Awk34** [comment]
Make sure you have the latest version of `gulp-cli` installed globally. Gulp will use the `babel-register` package that should be listed in your `package.json`.

**Comment by RonAlmog** [comment]
Yup, that works!
but there are many transpile errors. most of them are small things, as far as i can see.
just vars that have not been declared, like:
Property 'user' does not exist on type 'LoginController'.
so it can easily be fixed locally.
Thanks!

**Comment by Awk34** [comment]
@RonAlmog yeah, the TypeScript is missing some of those declarations. If you get the time, Pull Requests would be appreciated.
