### ISSUE TITLE
css and images doesn't work in deploy

### ISSUE THREAD

**Issue by deniz946** [angular-fullstack/generator-angular-fullstack#1927]
Hello, my css and images from my template are not working, i just get white page, without styles, but with grunt serve it works... any help? This is [the repo](https://github.com/deniz946/blog) where Im working.

![NO CSS]
(http://img110.xooimage.com/files/3/4/7/screenshot-from-2...13-18-04-4f7676d.png)

**Comment by RonAlmog** [comment]
hit F12 to open developer tools (chrome), and see what's going on. 
"not working" is not enough info. are the css files being injected to index.html? 
in dev tools, check console for errors, network for file loads or trials, and you will know more.
explain "but with grunt serve it works". don't you always work this way? where it does not work?

**Comment by Koslun** [comment]
Everything @RonAlmog said, sounds like you might be new to this and understandably using the project in ways it was not designed for.

Please also enter the your operating system as well as your nodejs, npm and MongoDB versions. Any issue might be something specific to this. Can check what versions you're using by running the following in the console:
```bash
node --version
npm --version
mongo --version
```
Additionally you could check the global npm packages you have installed by running `npm list -g --depth=0`

Checking your `.yo-rc.json` file I see that you used version 3.6.1 of the generator with the following choices:
```javascript
     "filters": {
      "js": true,
      "babel": true,
      "html": true,
      "css": true,
      "uirouter": true,
      "bootstrap": true,
      "uibootstrap": true,
      "auth": true,
      "models": true,
      "mongooseModels": true,
      "mongoose": true,
      "oauth": true,
      "googleAuth": true,
      "grunt": true,
      "jasmine": true,
      "mocha": false,
      "should": false,
      "expect": false
    }
```

**Comment by deniz946** [comment]
node --version - v5.0.0
npm --version 3.3.6
mongo --version MongoDB shell version: 2.6.10

npm list -g --depth=0:

├── angular-cli@0.1.0
├── bower@1.7.9
├── generator-angular-fullstack@3.6.1
├── generator-meanjs@0.4.4
├── grunt@1.0.1
├── grunt-cli@1.2.0
├── npm@3.3.6
├── surge@0.18.0
└── yo@1.8.3

And in f12 console log i get this error but i don't really understand it..

```Mixed Content: The page at 'https://blogcms.herokuapp.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS.
blogcms.herokuapp.com/:14 Mixed Content: The page at 'https://blogcms.herokuapp.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'. This request has been blocked; the content must be served over HTTPS.
blogcms.herokuapp.com/:15 Mixed Content: The page at 'https://blogcms.herokuapp.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'. This request has been blocked; the content must be served over HTTPS.
vendor.3688cbde.js:5 Mixed Content: The page at 'https://blogcms.herokuapp.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:9000/api/posts/active'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ vendor.3688cbde.js:5
vendor.3688cbde.js:5 XMLHttpRequest cannot load http://localhost:9000/api/posts/active. Failed to start loading.(anonymous function) @ vendor.3688cbde.js:5
inject.js:56 Capturing clicks```

**Comment by RonAlmog** [comment]
ok, that's easy. you are mixing http and https.
if your app in heroku is using https (which is i think by default), then all your css links etc. need to be https as well. usually you can just change the link like this:
http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css
will be
https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css

try that.
