### ISSUE TITLE
How to update existing afullstack project?

### ISSUE THREAD

**Issue by eaidland** [angular-fullstack/generator-angular-fullstack#1932]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.6.1
Node | v5.11.0
npm | 3.8.6
Operating System | Windows 10 

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML
CSS | CSS 
Router | ui-router
Build Tool |  Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y
Amazon

Hi!

This is rather a question, than a issue:

How do one update to lastest i.e gulpfile.babel.js script, auth controller etc from an existing project?
Is it possible to add socketio.js afterwards?

Thanks!

**Comment by elfouad** [comment]
hi,

look at [1718](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1718) .
In your project you can simple run yo angular-fullstack again.

**Comment by eaidland** [comment]
Thanks!
