### ISSUE TITLE
[New Feature Request] Token based Authentication on Socket.io

### ISSUE THREAD

**Issue by ashishbajaj99** [angular-fullstack/generator-angular-fullstack#1934]
It will be great to add on an option in the generator to allow user to secure the Socket.io channel via authentication...this is a typical use case and so it would be good to allow this as a default chosen option for the generator (unless someone says ignore authentication).

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.4/templates/app/server/config/socketio(socketio).js#L29-L37
