### ISSUE TITLE
Heroku typings not found

### ISSUE THREAD

**Issue by morriq** [angular-fullstack/generator-angular-fullstack#1935]
Hello. 

I have error when I'm pushing repo on heroku.

But I added in package.json in scripts

`"preinstall": "npm install typings -g",`

And it starts working. Shouldn't we add it to repo?

**Comment by thierryskoda** [comment]
+1 
Thanks @morriq ! Your solution works! Have you found any other solution? I'm wondering if it's good to install globaly tpyings everytime we push to heroku haha!

Thanks a lot!

**Comment by joserc87** [comment]
I don't understand why is this issue closed. I just encountered this error and solved it with the solution provided by morriq (thank you very much). Shouldn't this be addressed in the generator so that the generated project is ready to deploy on Heroku?

**Comment by Awk34** [comment]
I'm not sure that @morriq 's solution should be added to everyone's generated `package.json`, @joserc87 . It might make sense to have it in your `package.json` when you push to Heroku, but I feel like this would be a poor choice to add to everyone's `package.json`. I would get quite annoyed if npm tried to re-install stuff every time I did an `npm install`. I personally have my global npm modules pre-installed on my Docker images. There might even be a better solution for Heroku as well.

**Comment by gal1419** [comment]
@morriq is this still working? I tried adding the "preinstall" script with no luck.
