### ISSUE TITLE
Reload issue, crypto deprecation warning

### ISSUE THREAD

**Issue by aceymer** [angular-fullstack/generator-angular-fullstack#1940]
Been so pleased with this generator.

But now its just started to go downhill..
Installed the newest version of the generator and created a new project.

1: Grunt Serve does not reload my page on change anymore (not even html changes)
2: Getting errors after grunt serve of CLEAN project -> (node:40144) Warning: a promise was created in a handler but was not returned from it
3: Getting errors after grunt serve of CLEAN project -> (node:40144) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest

I will try to downgrade some version until I get a ok generator again..

**Comment by aceymer** [comment]
Going back to a more stable version (3.4.0)

**Comment by Awk34** [comment]
1. need details
2. Most likely one of the dozen some-odd same issues reported, it's not us, it's upstream
3. need details

**Comment by Awk34** [comment]
Closed due to inactivity
