### ISSUE TITLE
Session Token Value Overwritten for Multiple Applications, Same Server, Different Ports

### ISSUE THREAD

**Issue by b-bibble** [angular-fullstack/generator-angular-fullstack#1945]
Item | Version
----- | -----
generator-angular-fullstack | 2.0.13
Node | 5.4.0
npm | 3.8.6
Operating System | Windows 8.1

Item | Answer
----- | -----
Markup | HTML
CSS | SCSS
Router | ui-router
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB
Auth | Y

When running multiple versions of applications generated with angular-fullstack, the authentication token stored in the browser is overwritten. The browser token is named "token" for each application. If I run two applications locally (on localhost) using two different port numbers, I can authenticate into application A with no issue. However, if I authenticate into application B, the token value is overwritten, which interferes with the session for application A.

Is there a way to set the browser token uniquely for each application?

**Comment by Awk34** [comment]
[RFC6265](http://tools.ietf.org/html/rfc6265) states: "Similarly, cookies for a given host are shared across all the ports on that host, even though the usual "same-origin policy" used by web browsers isolates content retrieved via different ports."

You can change the name of the key where the token gets placed on the cookie ('token_a'/'token_b'), but you would only run into this issue in prod if you were trying to run two different apps on the same exact domain with different ports, but I doubt you would be doing that.

**Comment by b-bibble** [comment]
Thank you, @Awk34. Do you happen to know where I can change the name of the key where the token gets placed on the cookie? I have a prototype that will make its way to production where I am, in fact, running two different apps on the same domain with different ports.

**Comment by Awk34** [comment]
@b-bibble here's a list of all the places I found:

https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/server/auth(auth)/auth.service.js#L69
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/client/app/app(js).js#L25-L26
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/client/app/app(js).js#L36
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/client/components/auth(auth)/auth.service(js).js#L6
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/client/components/auth(auth)/auth.service(js).js#L28
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/client/components/auth(auth)/auth.service(js).js#L48
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/client/components/auth(auth)/auth.service(js).js#L64
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/client/components/auth(auth)/auth.service(js).js#L143
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/server/api/user(auth)/user.controller.js#L33
https://github.com/angular-fullstack/generator-angular-fullstack/blob/legacy-2.x.x/app/templates/server/api/user(auth)/user.model.js#L50

**Comment by b-bibble** [comment]
Thank you, @Awk34. Line 28 in app/components/aut.service.js is what I needed to update. 

Keep up the great work, and thank you for the quick replies!
