### ISSUE TITLE
How to work with TypeScript?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#1948]
Item | Answer
----- | -----
Transpiler | TypeScript
Build Tool | Gulp

Can anybody please provide some basic guidance on how to work with TypeScript in this project?
my editor is Sublime 3. should i install anything?
I see that  "typings" is installed out of the box, along with some typings.json that contains some info for angular, jquery, etc.   What should i do in order for the angular for example to be recognized as a type, and get full intellisense?

**Comment by Koslun** [comment]
Depends what you mean with "work with". Given that you've installed global and local dependencies the typescript configuration should just work.

Regarding Intellisense I think there are plugins for Sublime and Atom to achieve something like it. Webstorm and Visual Studio Code come with it out of the box. Might need to configure where they find the config file for either of the editor choices. Believe Visual Studio for instance searches for `tsconfig.json`, so might have to just copy or rename the `tsconfig.client.json` to `tsconfig.json`.

Can check the typescript [homepage](https://www.typescriptlang.org/) for how TypeScript syntax.

Can check the typings [homepage](https://github.com/typings/typings) for how you can update and add more typings for dependencies.

**Comment by Awk34** [comment]
Your typings should get updated every time you `npm i`, through the `postinstall` script that's included (https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.4/templates/app/_package.json#L182)

**Comment by AmirGilboa** [comment]
Thanks. after reinstalling the plugin and playing with node settings, i have the code completion now. but i don't have proper warnings. like if i assign int to a string var, it puts the squiggles to designate problem, but it does not say what's wrong.

**Comment by Awk34** [comment]
Sounds like a problem with the Sublime plugin. I suggest trying VS Code or Webstorm.
