### ISSUE TITLE
gulp serve:dist does't work

### ISSUE THREAD

**Issue by ES-SOFYANY** [angular-fullstack/generator-angular-fullstack#1949]
in local i have node 6.2 so gulp serve works well 
but if i want to work with the build of my app it doesn't work

error:
vendor-4b129d5fe7.js:5 Error: [$injector:unpr] Unknown provider: eProvider <- e

mybe probleme of injection

example of code:

class myClass{
  constructor($rootScope) {
    this.rootScope = $rootScope;
  }
  fermer() {
    this.rootScope.missionVisible = false;
  }}

const name = 'myClass';

angular.module(name, [
]).component(name, {
  templateUrl: `components/${name}/${name}.html`,
  controllerAs: name,
  controller: myClass
});

thanks for your response

More details:

There are a probleme with minification: if I remove .pipe(plugins.uglify()) its works well if not its does't work

**Comment by ES-SOFYANY** [comment]
it's a probleme of uglify: *
if i remove .pipe(plugins.uglify()) from gulpfile.babel.js it works well 
But i need to uglify my code

**Comment by Awk34** [comment]
Closed due to inactivity
