### ISSUE TITLE
keep getting Error: State 'admin' is already defined when running grunt build

### ISSUE THREAD

**Issue by flexpert** [angular-fullstack/generator-angular-fullstack#1956]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.0
Node | 5.1.0
npm | 3.5.1
Operating System | OS X 10
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS |  SCSS 
Router | ui-router
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB
Auth | Y

When ever I'm building the project using `grunt serve` there is an error telling that: 
```
vendor.cfccb2d7.js:3 Uncaught Error: [$injector:modulerr] Failed to instantiate module shulstarterV1App due to:
Error: State 'login' is already defined
```

And I can see in the /.tmp/concat/app/app.js duplication of admin.route.js mapping.

This is really driving me nuts.
Please advice on what can I do.

Thanks,
Royee

**Comment by RonAlmog** [comment]
login state is defined in clietn/app/account/account.js
admin state is defined in admin.router.js

make sure your are not creating them again. like in your app.js for example

**Comment by flexpert** [comment]
I'm familiar with the structure, 
I think the problem related to the concatenation of js or ts files. 

Just to make it clear, grunt serve works as expected, the problem is with grunt serve:dist, and also grunt build and then running the server from dist folder

**Comment by Awk34** [comment]
Do a `grep` or something on `'login'`. What have you changed from the original scaffold?

**Comment by flexpert** [comment]
The generated app.js file after concatenation contains duplication, which means exactly same code executed twice, that's why angular throw an error when trying to configure same state. 

I've added new route that's it and eventually tried to revert all of my changes but it still happening.

**Comment by flexpert** [comment]
sure,

after `grunt build`:
in the file **`.tmp/concat/app/app.js`**
```javascript
..
//# sourceMappingURL=app.js.map
'use strict';
angular.module('royeeApp', [
    'royeeApp.auth',
    'royeeApp.admin',
    'royeeApp.constants',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ui.router',
    'ui.bootstrap',
    'validation.match',
    'angular-loading-bar'
]).config(["$urlRouterProvider", "$locationProvider", function ($urlRouterProvider, $locationProvider) {
    $urlRouterProvider.otherwise('/');
    $locationProvider.html5Mode(true);
}]);
angular.element(document).ready(function () {
    angular.bootstrap(document, ['royeeApp']);
});
//# sourceMappingURL=app.js.map
'use strict';
angular.module('royeeApp.admin', [
    'royeeApp.auth',
    'ui.router'
]);
//# sourceMappingURL=admin.module.js.map
'use strict';
angular.module('royeeApp.admin', [
    'royeeApp.auth',
    'ui.router'
]);
//# sourceMappingURL=admin.module.js.map
'use strict';
angular.module('royeeApp.auth', [
    'royeeApp.constants',
    'royeeApp.util',
    'ngCookies',
    'ui.router'
])
    .config(["$httpProvider", function ($httpProvider) {
    $httpProvider.interceptors.push('authInterceptor');
}]);
//# sourceMappingURL=auth.module.js.map
...
```
I can see that ***`//# sourceMappingURL=admin.module.js.map`*** is duplicated.

What am I missing here?

**Comment by Awk34** [comment]
Is that the only file that get's duplicated?

**Comment by flexpert** [comment]
yeah.

I tied to remove the entire `admin.module` and register everything directly on main app module but then I got the same error for the `login` state

**Comment by Awk34** [comment]
So it is the only one duplicated, or `login` is also duplicated?

**Comment by Awk34** [comment]
What does your `index.html` look like after you run `build`?

**Comment by Awk34** [comment]
Also make sure that all your files have the same line endings

**Comment by flexpert** [comment]
ok, after some more investigation and comparing agains other project with older version of the generator.

**old** generator: after running `grunt build --verbose`, I can see that:
```
Reading client/app/app.js...OK
Reading client/app/account/account.js...OK
Reading client/app/account/login/login.controller.js...OK
Reading client/app/account/settings/settings.controller.js...OK
Reading client/app/account/signup/signup.controller.js...OK
Reading client/app/admin/admin.controller.js...OK
Reading client/app/admin/admin.js...OK
Reading client/app/common/coomon.directives.js...OK
Reading client/app/home/device/device.controller.js...OK
Reading client/app/home/device/device.js...OK
Reading client/app/home/home.controller.js...OK
Reading client/app/home/home.js...OK
Reading client/app/home/new-device-modal/add-new-device.controller.js...OK
Reading client/app/home/report/report.controller.js...OK
Reading client/app/home/report/report.js...OK
Reading client/app/main/main.controller.js...OK
Reading client/app/main/main.js...OK
Reading client/components/auth/auth.service.js...OK
Reading client/components/auth/user.service.js...OK
Reading client/components/device-dashboard/device-dashboard.directive.js...OK
Reading client/components/modal/modal.service.js...OK
Reading client/components/mongoose-error/mongoose-error.directive.js...OK
Reading client/components/navbar/navbar.controller.js...OK
Reading client/components/report-dashboard/report-dashboard.directive.js...OK
Reading client/components/socket/socket.service.js...OK
Reading .tmp/templates.js...OK
Reading .tmp/tmp-templates.js...OK
Writing .tmp/concat/app/app.js...OK
File .tmp/concat/app/app.js created.
```

---

**new** generator (different project) after running `grunt build --verbose`, I can see that:
```
Reading client/app/app.js...OK
Reading .tmp/app/admin/admin.module.js...OK
Reading client/app/admin/admin.module.js...OK
Reading .tmp/components/auth/auth.module.js...OK
Reading .tmp/components/util/util.module.js...OK
Reading .tmp/components/auth/interceptor.service.js...OK
Reading client/components/auth/interceptor.service.js...OK
Reading .tmp/app/admin/admin.controller.js...OK
Reading .tmp/app/account/account.js...OK
Reading client/app/account/account.js...OK
Reading .tmp/app/admin/admin.router.js...OK
Reading client/app/admin/admin.router.js...OK
Reading .tmp/app/initiate/initiate.controller.js...OK
Reading .tmp/app/initiate/initiate.js...OK
Reading client/app/initiate/initiate.js...OK
Reading .tmp/app/main/main.controller.js...OK
Reading .tmp/app/main/main.js...OK
Reading client/app/main/main.js...OK
Reading .tmp/app/account/settings/settings.controller.js...OK
Reading client/app/account/settings/settings.controller.js...OK
Reading .tmp/components/auth/auth.service.js...OK
Reading .tmp/app/account/login/login.controller.js...OK
Reading client/app/account/login/login.controller.js...OK
Reading .tmp/components/auth/router.decorator.js...OK
Reading client/components/auth/router.decorator.js...OK
Reading .tmp/components/auth/user.service.js...OK
Reading .tmp/components/footer/footer.directive.js...OK
Reading .tmp/components/modal/modal.service.js...OK
Reading .tmp/components/mongoose-error/mongoose-error.directive.js...OK
Reading .tmp/components/navbar/navbar.controller.js...OK
Reading client/components/navbar/navbar.controller.js...OK
Reading .tmp/components/navbar/navbar.directive.js...OK
Reading .tmp/components/oauth-buttons/oauth-buttons.controller.js...OK
Reading .tmp/components/oauth-buttons/oauth-buttons.directive.js...OK
Reading .tmp/app/account/signup/signup.controller.js...OK
Reading client/app/account/signup/signup.controller.js...OK
Reading .tmp/components/util/util.service.js...OK
Reading .tmp/app/app.constant.js...OK
Reading client/app/app.constant.js...OK
Reading .tmp/templates.js...OK
Reading .tmp/tmp-templates.js...OK
Writing .tmp/concat/app/app.js...OK
File .tmp/concat/app/app.js created.
```

every file is taken twice, from `client` and from `.tmp`, why is that?

**Comment by flexpert** [comment]
OK, I think I figured it out...

before running `grunt build` or `grunt serve:dist` (for that purpose) I deleted all `*.js` / `*.js.map` under `client/app` folder.
BOOM, work like charm!

so I wanted to make sure this is really the problem, 
for that I installed the latest version of the generator (again) and scaffold a whole new project from scratch, 
then without touching any file I tried `grunt serve:dist` and it worked as expected, 
then I touched some of the `*.ts` file so my intellij compiler will compile them, 
then `grunt serve:dist` again, 
BOOM!, failed

OMFG

is it because my intellij compiler?? 
I mean, how come it's not reproducible in any of other guys environments, couldn't be!

**Comment by Awk34** [comment]
Oh, yeah, that'd be your problem right there. Don't use the built in Intellij/WebStorm watchers. We have a `grunt watch`/`gulp watch` for a reason. The operations we perform are a bit more involved than the included IDE watchers out of the box.

**Comment by flexpert** [comment]
hey, why not adding support for all intellij users? it's really useful to use the built-in typescript compiler in dev time, the generator just need to make sure not taking all the generated *.js and *.js.map file during the build, don't you think so?

**Comment by RonAlmog** [comment]
do we really understand what happened there? is it the the on-save conversion to js that fucked things up?
I'm not using webstorm, so i don't know what those watchers are. what are they doing?
whatever they do is most likely local only. they don't go and change your .tmp folder.
so first let's see what they do. then check how that can cause problem with what the generator's grunt script is doing. 
i plan to move very shortly to TS with sublime. will i have similar issues? we'll see.

**Comment by Awk34** [comment]
I use WebStorm (part of the IntelliJ platform) and I never use the watchers for these kinds of projects. I have no plans to build IDE/editor-specific code into this generator. Webstorm supports running Grunt/Gulp/npm commands from the GUI, which will show the terminal in a 'Run' pane. Why not do this? The watchers in WebStorm are just a simpler version of our Grunt/Gulp pipeline.

@RonAlmog WebStorm includes 'watchers' (which you can choose to turn on) that will watch for changes on your source code and give compiled files right next to the sources. Sublime doesn't come with anything like this out of the box.

**Comment by RonAlmog** [comment]
Ah, now i got it. app.ts for example was transplied automatically to app.js, and the script took both of them..  and obviously they are the same, so you got those states twice...  all clear now.  So all we have to do is turn off this feature of the ide.  Thanks!

**Comment by Awk34** [comment]
@RonAlmog It's not turned on in WebStorm by default
