### ISSUE TITLE
Throws out from the logged in state if server side code is changed,edited by gulp serve and also clears the cookie from the brower

### ISSUE THREAD

**Issue by biks152207** [angular-fullstack/generator-angular-fullstack#1957]
Throws out from the logged in state if server side code is changed,edited by gulp serve and also clears the cookie from the brower  and also clears out newly registered user from the mongodb database.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 5.0.0
npm | 3.5.1
Operating System | OS X 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Awk34** [comment]
Yes, this is very much intended. Whenever you change server-side code during development, the database is re-seeded, so your token is reset. If you don't want this while developing, go to the `development.js` config file and set `seedDb: false` (I don't suggest)
