### ISSUE TITLE
Duplicate dummy data error on initial 'grunt serve' run.

### ISSUE THREAD

**Issue by Cogiva** [angular-fullstack/generator-angular-fullstack#1963]
I have an issue immediately after creating the fullstack app.  When running it for the first time I get an error when the seed data is entered into the Mongo DB for the initial users.

It comes up with a duplicate key error.

`Unhandled rejection WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error index: hapnote-dev.users.$username_1 dup key: { : null }","op":{"salt":"CgpFSO9/+HQlbv65ujW9Gg==","provider":"local","name":"Admin","email":"admin@example.com","password":"hounBClD2Rn4DPuExu1YKTJV2HE8jyUEFGaCuZwFbwRRlXLWYiwhJSEozkJSRVWb8TeDwYrPpv5VPSrgqVRX0g==","_id":"5759809ba6d430b90b05fa8b","role":"admin","__v":0}})
    at Function.MongoError.create`

Is this to do with my install or is this a bug that others have encountered?

Thanks.
 
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 5.6.0
npm | 3.6.0
Operating System | OS X 10 
MongoDB | 3.0.4

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | CSS 
Router | ngRoute 
Build Tool | Grunt 
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
etc | etc

**Comment by Awk34** [comment]
I suggest using something like [mongo-express](https://github.com/mongo-express/mongo-express) to take a direct look at your Mongo database. Maybe try wiping your entire dev database.

**Comment by Cogiva** [comment]
I've got RoboMongo, but the DB didn't exist when I first ran the application.

**Comment by Awk34** [comment]
What's your Mongo version?

**Comment by Cogiva** [comment]
3.0.4 (Added to edited question!)

**Comment by Cogiva** [comment]
The delete DB worked, randomly!  Thanks.  Can't say why it happened, but it's not happening!

**Comment by Awk34** [comment]
@Cogiva yeah, I figured that would work. I can only assume it was some error in creating the DB.

**Comment by Cogiva** [comment]
Thanks for the help!  (I hate it when "rebooting" solves a problem...I like to know the why!)
