### ISSUE TITLE
Test coverage is wrong for clean project.

### ISSUE THREAD

**Issue by otarsko** [angular-fullstack/generator-angular-fullstack#1968]
Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | v6.2.0
npm | 3.8.9
Operating System |  Ubuntu 14.04

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS 
Router |  ui-router
Build Tool | Grunt
Client Tests | Mocha
DB | MongoDB
Auth | N

After generating new project and running `grunt test:coverage` I am getting coverage only for _mocha.conf.js_ file.

![screenshot from 2016-06-10 12 44 01](https://cloud.githubusercontent.com/assets/3098837/15960577/249dddb8-2f09-11e6-8120-bc5865f4107a.png)
![screenshot from 2016-06-10 12 44 17](https://cloud.githubusercontent.com/assets/3098837/15960585/2918522e-2f09-11e6-85cb-026291a91668.png)
![screenshot from 2016-06-10 12 42 20](https://cloud.githubusercontent.com/assets/3098837/15960529/ede23472-2f08-11e6-89c7-2741a8ea338e.png)

Am I missing something or it's an issue?

**Comment by Awk34** [comment]
Hmmm, I've never seen this. I'll have to see if I can reproduce somehow.

**Comment by AdrienEtienne** [comment]
I had this issue before. I solved it by changing Istanbul dependency from 0.4.1 to 1.0.0-alpha.2.

**Comment by otarsko** [comment]
Adrien, thank you, It fixes the issue. Also version **1.1.0-alpha.1** seems to be ok as well.
