### ISSUE TITLE
Heroku deployment infinite loop because of multiple partial directories?

### ISSUE THREAD

**Issue by JaKXz** [angular-fullstack/generator-angular-fullstack#197]
After having #164 solved and "successfully" deploying my app to heroku, I've run into the dreaded infinite loop problem [described in some detail here](http://stackoverflow.com/q/18553847/1444541). 

I believe I have a similar problem as that person, because I have subdirectories for my views - my project `app` folder looks like this:

```
views/
    client/
        pageA.html
        pageB.html
    distributor/
        pageC.html
        pageD.html
    partials/
        navbar.html
        ...
```

I tried adding these lines to the end of the routes.js file:

```
app.get('/client/*', index.partials);
app.get('/distributor/*', index.partials);
app.get('/*', middleware.setUserCookie, index.index);
```

but unfortunately that did not do the trick. I'm sure refactoring my project structure (i.e. having all the views inside `partials`) would fix the problem, but perhaps it might be worth considering supporting multiple directories under views for organization's sake? It does make naming files nicer imho.

I will continue trying things, but if someone beats me to a solution (or has already solved this) that'd be lovely. :)

**Comment by yoavgecht** [comment]
I have the same problem now
Infinite loop on Heroku.
how did you solve it?
