### ISSUE TITLE
Fix required in contoller test

### ISSUE THREAD

**Issue by atomfried** [angular-fullstack/generator-angular-fullstack#1974]
Hey there,

the generated contoller specs contain this line:

    TestComponent = $componentController('TestComponent', {

The test always fails. It should be:

    TestComponent = $componentController('test', {

Regards

M

**Comment by atomfried** [comment]
To be more specific: I'm talking about the angular-fullstack:route generator and I'm using angular-mocks 1.5.0.

**Comment by Awk34** [comment]
Please fix and submit a PR to that repo: https://github.com/DaftMonk/generator-ng-component/blob/master/templates/route/name.controller.spec.js
