### ISSUE TITLE
Question: How to embed markdown files in the project?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1975]
What's an easy way to use markdown documents in the application?
I mean all those 'terms and conditions', 'How does it work', pages, that it would be convenient to edit with https://stackedit.io or one of those editors. but how to embed them in the angular application?

**Comment by Awk34** [comment]
I think there's two ways to include markdown for this stack: In a `.md` file, or as text in the database. I personally use text in the database for various documents. When I grab a document from the DB, I then use a client-side JS library to render the markdown into HTML. You could also use a server-side lib to convert the markdown to HTML. The same could be done for `.md` files, probably stored in the `assets` folder.

**Comment by RonAlmog** [comment]
makes sense. Thanks!
