### ISSUE TITLE
Mongo Credentials 

### ISSUE THREAD

**Issue by Gregoyle** [angular-fullstack/generator-angular-fullstack#1986]
As someone relatively new to MEAN development, I'm wondering where the generator looks for username and password variables for the Mongo database. I understand that there are .env files but I can't seem to figure out what the environment variable should be called for the Mongo password and user and how to incorporate it into the app.

(Additionally, I was wondering if anyone could point me to a good sample of an application using this generator that I can use to study).

Thanks and sorry if this is not the appropriate place to ask this question.

--

- [ X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | v6.2.1
Node | v6.2.1
npm | 3.9.3
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS 
Router | ngRoute
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB 
Auth | Y
etc | etc

**Comment by Gregoyle** [comment]
Nevermind. I'm foolish.

**Comment by Awk34** [comment]
FYI you can find more information here: http://mongoosejs.com/docs/connections.html

**Comment by Gregoyle** [comment]
Thanks. I found that from an earlier thread as well. It seems like today I find the solution right after I feel like I'm going to tear my hair out. Thanks for the link!
