### ISSUE TITLE
ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by MorizelHodges** [angular-fullstack/generator-angular-fullstack#1999]
I recently ran the Angular-fullstack generator and have been unable to get the localhost:9000 to launch the initial site.  There are a bunch of reference error:angular is not defined errors listed in the Mozilla console. Where is the angular module defined within this generator?

![yeoman_angularerror](https://cloud.githubusercontent.com/assets/14810598/16232223/b528913e-3797-11e6-9826-025929687801.jpg)

 - [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 6.0.0
npm | 3.8.6
Operating System | Windows 7 64bit 

Item | Answer
----- | -----
Transpiler | **Babel** / TypeScript
Markup | **HTML** / Jade
CSS | **CSS** / LESS / SCSS / Stylus
Router | **ngRoute** / ui-router
Build Tool | **Grunt** / Gulp
Client Tests | **Jasmine** / Mocha
DB | **MongoDB** / SQL
Auth | Y / **N**

**Comment by Awk34** [comment]
It is loaded in from the `client/bower_components` folder. Bower is the front-end dependency manager used. `npm install` & `bower install` should have been run after you first scaffolded your project. Make sure Angular is in that folder. Also make sure that there's a script tag in your `index.html` for Angular and all other front-end dependencies. These are injected in by a Grunt task.

**Comment by MorizelHodges** [comment]
Thanks for the info; I just realized the bower install command failed due to corp proxy. I'll work through that piece - should be good to go once bower components get pulled down... thanks again!
