### ISSUE TITLE
Failed to load external module babel-register, and several others

### ISSUE THREAD

**Issue by MaximilianLloyd** [angular-fullstack/generator-angular-fullstack#2004]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.2
Node | 6.2.2
npm | 3.5.3
Operating System | Windows 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS 
Router |  ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y

![capture](https://cloud.githubusercontent.com/assets/10583205/16245214/17ae2a22-3800-11e6-9cba-76b690648ade.PNG)
No matter what I do. I still get the errors listed above. I tried installing babel globally, but it did not change anything.

**Comment by Awk34** [comment]
As you can see, it tried to run the babel require hook from three different locations, but failed to find any of them. `npm install` should be run after scaffolding your project for the first time, which includes installing `babel-register` in your local dependencies.

**Comment by MaximilianLloyd** [comment]
The connection at the place i am is terrible, so is the speed of my hardrive. So i tried being clever by cloning, npm and bower installing on my digital ocean server and zipping it. Then copying the zip to my desktop. Everything is fine now once i npm cache clean and install.
