### ISSUE TITLE
Some css missing from build

### ISSUE THREAD

**Issue by nabilzhafri** [angular-fullstack/generator-angular-fullstack#2012]
Hi, looking at the default `gulpfile.babel.js`, it didn't seem to include these files automatically:

```
<link rel="stylesheet" href="components/themes/admin-lte/css/custom.css" />
```

Default style rule:
`gulp.src(``${clientPath}/{app,components}/**/*.css``, {read: false})`

From what I can tell, above rule should also cover the `custom.css`.

Also, it doesn't seem to include these bower files automatically:
```
<link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css" />
<link rel="stylesheet" href="bower_components/AdminLTE/dist/css/skins/_all-skins.min.css" />
```
It does however include these files automatically:
```
<link rel="stylesheet" href="bower_components/AdminLTE/dist/css/AdminLTE.css" />
<script src="bower_components/AdminLTE/dist/js/app.js"></script>
```

I'm not sure why it automatically include `AdminLTE.css` but not `_all-skins.min.css` & `font-awesome.min.css`. Tried to update the gulpfile but seems like it should include them as well.

Any idea why?

**Comment by Awk34** [comment]
Oh, that looks like a bug. Does #2013 fix this?

**Comment by nabilzhafri** [comment]
Hi, yes! The link seems to fix the `custom.css` issue :) Can you explain a bit what it does here?

However, the `font-awesome.min.css` and `_all-skins.min.css` still didn't get loaded. Both are located inside `bower_components` folder instead of components folder.

I saw inside the `gulpfile.babel.js`, there's a comment at the top of one of the tasks saying there's issue with font-awesome isn't getting loaded? Is it still an issue?
```
//FIXME: looks like font-awesome isn't getting loaded
gulp.task('build', cb => {
    runSequence(
        [
            'clean:dist',
            'clean:tmp'
        ],
        'inject',
        'wiredep:client',
        [
            'transpile:client',
            'transpile:server'
        ],
        [
            'build:images',
            'copy:extras',
            'copy:fonts',
            'copy:assets',
            'copy:server',
            'build:client'
        ],
        cb);
});
```

**Comment by Awk34** [comment]
It's just using `gulp-concat` to combine all the CSS files into `app.css`.

As for your Bower CSS files, those should get taken care of by `gulp wiredep:client`. 

That `FIXME` is from a long time ago; that should be removed.

**Comment by Awk34** [comment]
`wiredep` looks at a module's `bower.json`, like [font-awesome's](https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json). See http://blog.getbootstrap.com/2015/06/15/bootstrap-3-3-5-released/#wiredep-and-bower

**Comment by nabilzhafri** [comment]
@Awk34 ahh I see how it works now. Learnt something new and valuable today. Now I understand the auto build better. Thanks very much! :) and thanks for the earlier fix.
