### ISSUE TITLE
angular-bootstrap-datetimepicker not injected

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2016]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 6.2.0
npm | 3.9.2
Operating System |  Windows 10 
etc | etc

Item | Answer
----- | -----
Build Tool | Grunt 

I installed angular-bootstrap-datetimepicker with npm --save (then later with bower --save).
the files seems to be installed correctly to these folders (node_modules, bower_components)
but it is not being injected into index.html.
How do i go about finding the reason, and fix that?

oh, and i have checked bower.json, and it is there:

  "dependencies": {
    "angular": "~1.4.0",
    .....
    "angular-bootstrap-datetimepicker": "^1.0.1"
  },

**Comment by Awk34** [comment]
If you *really* are on 3.7.5, your `bower.json` should have Angular ~1.5.0.

Use the [`wiredep:client`](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.5/templates/app/Gruntfile(grunt).js#L261-L281) Grunt task to inject bower deps into your `index.html`. If the lib you're trying to use doesn't properly declare its `main` field in the `bower.json`, you'll have to manually add a tag for that lib.

**Comment by AmirGilboa** [comment]
yes! i have added this line to bower.json, and it works now. 
"main": ["src/js/datetimepicker.js","src/js/datetimepicker.templates.js"],

i wonder why this line is not there to begin with. it's like a standard, no?
Anyways, thanks for the quick help!

**Comment by Awk34** [comment]
@AmirGilboa I believe so: https://github.com/taptapship/wiredep#what-can-go-wrong
