### ISSUE TITLE
Document changes for 4.0.0

### ISSUE THREAD

**Issue by Awk34** [angular-fullstack/generator-angular-fullstack#2020]
### [Webpack](http://webpack.github.io/)
* No more Bower
* Webpack is a Module Bundler for the front-end.
* Everything starts in `client/app.js`. It imports (using CommonJS / ES2015 imports) everything else needed from there.
* Whenever we create a new Angular 1 module, we export its name, and import that name in another module up the tree, all the way to `client/app.js`. This design pattern allows for easy lazy-loading.

### Gulp v Grunt
Grunt has been removed. 
* Gulp is significantly faster to run
* Gulp focuses on programmatic configuration, which makes it a breeze to configure compared to Grunt's JSON-config-focused configuration.
* Gulp development is much more active, with Gulp 4.0.0 hopefully being released soon.

### ESLint
JSHint + JSCS have been replaced with ESLint. ESLint provides a gigantic amount of rules, and is easily pluggable with many plugins. It uses Espree. Also, JSCS has merged with ESLint.

### Types
Flow support has been added. TypeScript type errors have been fixed.

### Async/Sync Auth methods
The following methods from the client Auth service have been split into two: `getCurrentUser`, `isLoggedIn`, `hasRole`, `isAdmin`. The reason that these methods could be both synchronous and asynchronous depending on how many arguments were passed is because they were called from Angular templates. Now, the Angular templates call the sync form of these methods (e.x. `getCurrentUserSync`), and the original functions are now only async.

### Constants
The task runner no longer takes care of creating an Angular module for config constants. It is taken care of by webpack now (the `shared.js` files is now just `require`d)

### Endpoint PUT/PATCH
PUT now defaults to an upsert. PATCH now actually does an HTTP PATCH.

### -Livereload +Browsersync
Livereload has been removed in favor of [Browsersync](https://www.browsersync.io/)

**Comment by ronrbc** [comment]
is there any estimation on  when will ver 4.0 be released?
i'm considering refactoring, so i guess this will be a good time.

**Comment by arkdelkaos** [comment]
So...no more bower...ok, but: **How I'm supposed to install those "bower only" packages?**
What is the alternative? `npm install` them? Because most of them respond like `'textAngular' is not in the npm registry`

**Comment by Awk34** [comment]
Pretty much any maintained library that was a Bower package is also available as an npm package. If it's not available on npm, feel free to bring bower back, or set up some other way of getting your lib, but we don't support anything like that. Everything that we use is available on npm.

**Comment by Koslun** [comment]
@arkdelkaos You might have to go to the project github repository in question to confirm that the package is called the same thing on npm. Like every other popular library I've seen, Textangular is [available on npm ](https://www.npmjs.com/package/textangular) but apparently without the camelCasing as `textangular`.

**Comment by honkskillet** [comment]
What was new in 4.1?

**Comment by Awk34** [comment]
@honkskillet not a whole lot was added in 4.1.0. Look to the 4.0.0 changelog for all the big changes
