### ISSUE TITLE
problem on file.controller.spec.js when running "grunt test:client" for a new route 

### ISSUE THREAD

**Issue by Emidomenge** [angular-fullstack/generator-angular-fullstack#2029]
If I run : `yo angular-fullstack:route example`

And then run `grunt test:client --force`

I got this error just after `example.controller.spec.js` has been created :  (I'm beginner with Jasmine)

![jasmine_error_1](https://cloud.githubusercontent.com/assets/15636263/16480739/213b16a0-3ea8-11e6-8042-a950165ccfe6.png)

File `example.controller.spec.js` looks like this : 
```
'use strict';

describe('Component: ExampleComponent', function () {

  // load the controller's module
  beforeEach(module('myModule'));

  var ExampleComponent, scope;

  // Initialize the controller and a mock scope
  beforeEach(inject(function ($componentController, $rootScope) {
    scope = $rootScope.$new();
    ExampleComponent = $componentController('ExampleComponent', {
      $scope: scope
    });
  }));

  it('should ...', function () {
    expect(1).toEqual(1);
  });
});

```
And file `example.controller.js` looks like this : 
```
'use strict';
(function(){

class ExampleComponent {
  constructor() {
    this.message = 'Hello';
  }
}

angular.module('myModule')
  .component('example', {
    templateUrl: 'app/example/example.html',
    controller: ExampleComponent
  });

})();

```

 - [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.4
Node | 5.7.1
npm | 3.6.0
Operating System |  Windows 7

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS 
Router | ngRoute 
Build Tool | Grunt
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y

**Comment by Emidomenge** [comment]
It works if `example.controller.spec.js` looks like this :

changing **"ExampleComponent"** by **"example"**

```
'use strict';

describe('Component: ExampleComponent', function () {

  // load the controller's module
  beforeEach(module('myModule'));

  var ExampleComponent, scope;

  // Initialize the controller and a mock scope
  beforeEach(inject(function ($componentController, $rootScope) {
    scope = $rootScope.$new();
    ExampleComponent = $componentController('example', {
      $scope: scope
    });
  }));

  it('should ...', function () {
    expect(1).toEqual(1);
  });
});
```

**Comment by Awk34** [comment]
This has been fixed with https://github.com/DaftMonk/generator-ng-component/commit/72ad578ab6b4d49e32acf61ef017cd36d42efcdb. I just need to make another release.

**Comment by Awk34** [comment]
Closed with https://github.com/angular-fullstack/generator-angular-fullstack/commit/80957817cb4ccaebe41bcf12aa691098ce2f53e0; wait for next release of generator.
