### ISSUE TITLE
Update generator-ng-component for 4.0.0

### ISSUE THREAD

**Issue by Awk34** [angular-fullstack/generator-angular-fullstack#2031]
We need to be able to generate components compatible with the new setup.

**Comment by ronrbc** [comment]
can you please briefly explain what is generator-ng-component doing?
i have checked the github page, and there is no description or use case.  thanks!

**Comment by Awk34** [comment]
@ronrbc  This generator is made up of the main generator, and the endpoint sub-generator. generator-ng-component is responsible for all the Angular front-end sub-generators (routes, components, services, etc)

**Comment by ronrbc** [comment]
Ok, thanks!
