### ISSUE TITLE
yo angular-fullstack:route / or anything else not working except :endpoint

### ISSUE THREAD

**Issue by akeucon** [angular-fullstack/generator-angular-fullstack#2034]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 4.4.5
npm | 3.9.6
Operating System | Windows7
yo | 1.8.4

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS |  SCSS 
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB |  SQL
Auth | Y 
etc | etc

Like in the Title mentioned the 
yo angular-fullstack:route test / not working
yo angular-fullstack:endpoint test / working normally

ReferenceError: genUtils is not defined
    at Generator (C:\Users\alex_kreuder\AppData\Roaming\npm\node_modules\generat
or-angular-fullstack\node_modules\generator-ng-component\script-base.js:19:22)
    at new Generator (C:\Users\alex_kreuder\AppData\Roaming\npm\node_modules\gen
erator-angular-fullstack\node_modules\generator-ng-component\route\index.js:8:14
)
    at Environment.instantiate (C:\Users\alex_kreuder\AppData\Roaming\npm\node_m
odules\yo\node_modules\yeoman-environment\lib\environment.js:328:10)
    at composeWith (C:\Users\alex_kreuder\AppData\Roaming\npm\node_modules\gener
ator-angular-fullstack\node_modules\yeoman-generator\lib\base.js:623:26)
    at compose (C:\Users\alex_kreuder\AppData\Roaming\npm\node_modules\generator
-angular-fullstack\generators\route\index.js:7:10)
    at Object.<anonymous> (C:\Users\alex_kreuder\AppData\Roaming\npm\node_module
s\generator-angular-fullstack\node_modules\yeoman-generator\lib\base.js:431:23)
    at C:\Users\alex_kreuder\AppData\Roaming\npm\node_modules\generator-angular-
fullstack\node_modules\run-async\index.js:26:25
    at C:\Users\alex_kreuder\AppData\Roaming\npm\node_modules\generator-angular-
fullstack\node_modules\run-async\index.js:25:19
    at C:\Users\alex_kreuder\AppData\Roaming\npm\node_modules\generator-angular-
fullstack\node_modules\yeoman-generator\lib\base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by Awk34** [comment]
Thanks. This is a bug in generator-ng-component that will be fixed in the next patch release of it.

**Comment by Awk34** [comment]
@akeucon please reinstall generator-ng-component and confirm that this is fixed

**Comment by akeucon** [comment]
Did it and now it works again. 
Thx mate
