### ISSUE TITLE
grunt serve is working but grunt serve:dist throwing Uncaught SyntaxError: Unexpected token < in the browser..

### ISSUE THREAD

**Issue by rohitdharavath** [angular-fullstack/generator-angular-fullstack#2038]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 2.1.1 |
| Node | 4.2.6 |
| npm | 3.7.2 |
| Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc |
| etc | etc |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | HTML |
| CSS | CSS |
| Router | ui-router |
| Build Tool | Grunt |
| Client Tests | Jasmine |
| DB | MongoDB |
| Auth | Y / |
| etc | etc |

**Comment by Awk34** [comment]
Please note: Grunt is deprecated and will be removed in the next major release

**Comment by bbatalla92** [comment]
Hi, I have this exact issue, is there a solution for this?

**Comment by Awk34** [comment]
Note the 'needs details' tag @bbatalla92

**Comment by Awk34** [comment]
Closed due to inactivity
