### ISSUE TITLE
No live reload available

### ISSUE THREAD

**Issue by DanMMX** [angular-fullstack/generator-angular-fullstack#2040]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | canary branch -- latest
Node | 5.5.0
npm | 3.3.12
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | Babel
Markup | Jade
CSS | LESS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | SQL
Auth | Y

On clean generated project, when reloading in any route but `/` I get this

```
Error: ENOENT: no such file or directory, stat '/Volumes/SD/Work/ccsubsidiary/client/index.html'
   at Error (native)

```

**Comment by Awk34** [comment]
4.0.0-beta.4 has been pushed to npm, please try with that version
