### ISSUE TITLE
Run selected tests

### ISSUE THREAD

**Issue by atomfried** [angular-fullstack/generator-angular-fullstack#2044]
Hi there,

what's the recommended way to run only one or a few mocha server tests?

Also: where should I have asked this question (not exactly an "issue", is it?)

Thanks for answers

M

**Comment by Awk34** [comment]
Mocha has options to only run certain tests. One options is to add a `.only` onto the test you want to run. You can also pass specific files to the Mocha CLI, or use the `--grep` option to match specs on a pattern. Mocha docs are located here: http://mochajs.org/
