### ISSUE TITLE
model controller update function uses lodash merge instead of extend

### ISSUE THREAD

**Issue by ctchisholm** [angular-fullstack/generator-angular-fullstack#2049]
When generating an endpoint API, the update function uses lodash merge instead of lodash extend.  This results in no update happening if the object you are saving has arrays, some of whose elements were removed.  

consider an object: 

{ _id:'133453464567456', title:'test title', authors: [{name:'author1'},{name:'author2'}]}

now lets say we remove an author:
{ _id:'133453464567456', title:'test title', authors: [{name:'author1'}]}

If I use the current update function, the saved object still has both authors, because merge added it back in.  Extend, on the other hand, will properly copy the entire new authors array to the model object for saving.

function saveUpdates(updates) {
  return function(entity) {
    var updated = _.merge(entity, updates);
    return updated.save()
      .then(updated => {
        return updated;
      });
  };
}

should be replaced with

function saveUpdates(updates) {
  return function(entity) {
    var updated = _.extend(entity, updates);
    return updated.save()
      .then(updated => {
        return updated;
      });
  };
}

- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Awk34** [comment]
The way that this works will change in 4.0.0, see PR #2033
