### ISSUE TITLE
Support for Javascript

### ISSUE THREAD

**Issue by prashanth-sams** [angular-fullstack/generator-angular-fullstack#2050]
Do we have support for normal Javascript rather than using Babel or TS? cos am new to Babel and bit confused to start with. The normal way of coding AngularJS is bit different I guess.

**Comment by Awk34** [comment]
Babel is a transpiler that mainly transforms Modern JavaScript into older JS that is compatible with older browsers. It also converts other things, like JSX and new JS proposals into older JS, but I think the only non-standard JS feature we really use is class properties.

**Comment by prashanth-sams** [comment]
@Awk34 I need to use standard JS feature rather than using class properties; is tat possible to get it ? or any future updates on it ?

**Comment by Koslun** [comment]
@prashanth-sams I'm not really sure of the specific need for coding in standard JavaScript (ES5) as it gets compiled to ES5 for production anyway.

Either way, no. There are not currently any plans to support that I believe. The future plans are primarily focused on first getting support for webpack and then Angular 2. Turning away from the class structure would more or less require maintaining another set of client files, which is a bit of a nightmare and not something we want to do without a very good reason.

Something similar to this structure will also be best practice in Angular 2 so I would rather instead recommend adapting as I don't see any other reason than personal preference to shy away from class properties.

Please do correct me if I'm wrong though.

**Comment by Awk34** [comment]
@prashanth-sams the project supports all standard JS features. If you don't want to use class properties, just remove them from the code.
