### ISSUE TITLE
saveUpdates function in server controllers does not handle null properly

### ISSUE THREAD

**Issue by Megasonic988** [angular-fullstack/generator-angular-fullstack#2052]
In the promise chain:

```javascript
return Model.findById(req.params.id).exec()
  .then(handleEntityNotFound(res))
  .then(saveUpdates(req.body))
  .then(respondWithResult(res))
  .catch(handleError(res));
```

If the entity is not found, `handleEntityNotFound` passes null to `saveUpdates`.

```javascript
function saveUpdates(updates) {
  return function(entity) {
    var updated = _.merge(entity, updates);
    return updated.save()
      .then(updated => {
        return updated;
      });
  };
}
```

But if the entity is null, then the return of the merge (the `updated` variable) will not be a Mongoose doc. Then, when `updated.save()` is called, it will throw a `save is a not a function of null` error. To fix, saveUpdates should be wrapped in an if statement: 

```javascript
function saveUpdates(updates) {
  return function(entity) {
    if (entity) {
      var updated = _.merge(entity, updates);
      return updated.save()
        .then(updated => {
          return updated;
        });
    }
  };
}
```

**Comment by Awk34** [comment]
`handleEntityNotFound` shouldn't be returning `null`

**Comment by Megasonic988** [comment]
If the entity is not found, the query returns null, and then `handleEntityNotFound` will return null as seen here: 

```javascript
function handleEntityNotFound(res) {
  return function (entity) {
    if (!entity) {
      res.status(404).end();
      return null;
    }
    return entity;
  };
}
```

**Comment by Awk34** [comment]
Hmm, the way this is set up might be need to be rethought... but for now, I think your suggestion is best. I would welcome a PR.
