### ISSUE TITLE
not an issue Querry - Q: Restrict Admin or XYZ User from viewing other Pages

### ISSUE THREAD

**Issue by robinpoulose1** [angular-fullstack/generator-angular-fullstack#2054]
Shared :  Hierarchy wise View : 
   Here admin has access to all the pages  and is the Super set of all users . 
 userRoles: ['guest','sales','cem','user','admin']
****************************************************************************************************
auth.services  (Query that make this happen )  is given below .  

Now , the Admin  here can view all the pages .
user can view all the pages except admin page 
cem can view all the pages except  user and admin 
and So on ......................

How can i restrict Admin from viewing other pages   and 
How can  One restrict  user from viewing sales page  

****************************************************************************************************
 /**
                 * Check if a user has a specified role or higher
                 *   (synchronous|asynchronous)
                 *
                 * @param  {String}     role     - the role to check against
                 * @param  {Function|*} callback - optional, function(has)
                 * @return {Bool|Promise}
                 */
                hasRole(role, callback) {
                    var hasRole = function (r, h) {
                        return userRoles.indexOf(r) >= userRoles.indexOf(h);
                    };

                    if (arguments.length < 2) {
                        return hasRole(currentUser.role, role);
                    }

                    return Auth.getCurrentUser(null)
                        .then(user => {
                            var has = user.hasOwnProperty('role') ? hasRole(user.role, role) : false;
                            safeCb(callback)(has);
                            return has;
                        });
                },

 isSales() {
                    return Auth.hasRole.apply(Auth, [].concat.apply(['sales'], arguments));
                },

            
                isCem() {
                    return Auth.hasRole.apply(Auth, [].concat.apply(['cem'], arguments));
                },

                isUser() {
                    return Auth.hasRole.apply(Auth, [].concat.apply(['user'], arguments));
                },

                isAdmin() {
                    return Auth.hasRole.apply(Auth, [].concat.apply(['admin'], arguments));
                },

 - [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by robinpoulose1** [comment]
return Auth.hasRole.apply

can i create something like this : 
 isUser() {
        return Auth.hasRole.apply(Auth, [].concat.apply(['user'], arguments));
      },

**Comment by Awk34** [comment]
I don't know what you're trying to say..

**Comment by Awk34** [comment]
Closed due to inactivity
