### ISSUE TITLE
CORS problem when setting a basic auth

### ISSUE THREAD

**Issue by Emidomenge** [angular-fullstack/generator-angular-fullstack#2056]
I've implemented basic auth using angular and I've got an error : 
`angular.js:11755 Refused to set unsafe header "Access-Control-Request-Headers"`

Which leads to this : 
`XMLHttpRequest cannot load http://xxxxxxxxxxxxxxxx:9200/_cluster/state/version. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.`

As it seems to be a CORS problem, I tried to follow [ this guide ](http://enable-cors.org/server_expressjs.html) in `server\config\express.js` but **whithout success**. 

I tried also to remove : (but still **without success**) 
```
/**
   * Lusca - express server security
   * https://github.com/krakenjs/lusca
   */
  if (env !== 'test' && !process.env.SAUCE_USERNAME) {
    app.use(lusca({
      csrf: {
        angular: true
      },
      xframe: 'SAMEORIGIN',
      hsts: {
        maxAge: 31536000, //1 year, in seconds
        includeSubDomains: true,
        preload: true
      },
      xssProtection: true
    }));
  }
```

So I don't understand how to config express in order to removed this safety.

Any suggestion ? Thanks

 - [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.4
Node | 5.7.1
npm | 3.6.0
Operating System |  Windows 7

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS 
Router | ngRoute 
Build Tool | Grunt
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y

**Comment by Awk34** [comment]
What is "http://xxxxxxxxxxxxxxxx:9200"?

**Comment by Emidomenge** [comment]
Censored url ^^

**Comment by elfouad** [comment]
Hi,

you actually sending a request to elastic search. This has nothing to do with this generator. This is why your config on server\config\express.js has no effect on your request. You must set cors on elasticsearch. Maybe this can help you: http://stackoverflow.com/questions/33051405/elasticsearch-js-client-connection-refused-access-control-allow-origin-not-reco?answertab=votes#tab-top

**Comment by Emidomenge** [comment]
@elfouad  Problem solved thanks to you !
