### ISSUE TITLE
Server.Js is set to port 3000, Page only opens at localhost:9000 any suggestions on reason?

### ISSUE THREAD

**Issue by RyzoRobinson** [angular-fullstack/generator-angular-fullstack#2058]
I am following an online tutorial, he uses a slightly older version of the fullstack (3.1.1) and i am using a more up to date one (3.3.0) is there any reason that the initial page is only working on localhost:9000 when my server file is set to localhost:3000

server.js

``` js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {

  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

thanks, 

RR 
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 3.3.0 |
| Node | x.x.x |
| npm | x.x.x |
| Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc |
| etc | etc |

| Item | Answer |
| --- | --- |
| Transpiler | Babel / TypeScript |
| Markup | HTML / Jade |
| CSS | CSS / LESS / SCSS / Stylus |
| Router | ngRoute / ui-router |
| Build Tool | Grunt / Gulp |
| Client Tests | Jasmine / Mocha |
| DB | MongoDB / SQL |
| Auth | Y / N |
| etc | etc |

**Comment by Koslun** [comment]
Port 9000 has been the default for a while. Changing again back to 3000 in very recent commit to canary (v4).

In the latest 3.X branch the port is set in `server/config/environment/index.js` and then loaded at will. Not sure that it is the case in that earlier version though. Regardless there are other places that port is used. In the grunt or gulp file the port is for instance set to determine what port is used in the browser tab that is launched.

I don't think there is any real reason to change the port though. Rather every time the tutorial mentions the old port you could just use port 9000 instead.
