### ISSUE TITLE
.editorconfig ignored by webstorm

### ISSUE THREAD

**Issue by ralyodio** [angular-fullstack/generator-angular-fullstack#206]
I installed the plugin and restarted, but webstorm still is indenting wrong based on the code, when I hit `<enter>` it starts on next line 4 spaces in, but everything appears to be 2 space.

**Comment by rofrol** [comment]
> it doesn't seem to work for me after instsalling plugina nd restarting webstorm. WS still thinks i'm using 4 spaces while .editconfig dsays to use 2 spaceds.

https://youtrack.jetbrains.com/issue/IDEA-87499#comment=27-726676
