### ISSUE TITLE
userRoles: ['guest','sales','cem','user','admin']  ---TO be populated from database itself .Master table for roles. 

### ISSUE THREAD

**Issue by robinpoulose1** [angular-fullstack/generator-angular-fullstack#2061]
Can some one guide to make master table for Roles and the array get populated from the database. 

So that we dont have to make changes at sever config level and we make all changes to Db level.

 - [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Koslun** [comment]
Unsure what you mean. If you want to change which roles you can use to authenticate with you should change in `server/config/environment/shared.js`. You should then be able to safely save any added role to the db.

**Comment by Awk34** [comment]
Closed due to inactivity
