### ISSUE TITLE
build errors with gulp

### ISSUE THREAD

**Issue by ilanzaro** [angular-fullstack/generator-angular-fullstack#2062]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 4.2.3
npm | 2.14.7
Operating System | Windows 8
etc | etc

Item | Answer
----- | -----
transpiler | TypeScript
markup | HTML
css | SCSS
router | ui-router
task runner | Gulp
client tests | Mocha
db | MongoDB
Auth |  N
etc | etc

Hi,

Generated this project and it seems there are some errors regarding TS when using gulp. 
then i tried to generate this project with grunt and the build went well.
is there any issues with 'gulp serve' build ? is there any command i can use to avoid those errors?

Thanks in advance.
![image](https://cloud.githubusercontent.com/assets/16477274/16829843/dfe813fe-49a3-11e6-9def-d49806a23bb7.png)

**Comment by Awk34** [comment]
These are just type errors for TypeScript. You can ignore them, or fix them. 4.0.0 shouldn't have any of these.
