### ISSUE TITLE
yo angular-fullstack:router ContactUs not working

### ISSUE THREAD

**Issue by SagarBaggaOutlook** [angular-fullstack/generator-angular-fullstack#2068]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
yo version | 1.8.4
generator | 3.7.6
Node | 4.4.4
npm | 2.15.1
Operating System |  Windows 8

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS 
Router | ui-router
Build Tool | Grunt 
Client Tests | Jasmine 
DB | MongoDB 
Auth | N

Issue: When I attempt to manually go to the link http://localhost:9000/ContactUs it just brings me back to http://localhost:9000. It has created a folder with all files but unable to route.

**Comment by Awk34** [comment]
which generator version did you use?

**Comment by SagarBaggaOutlook** [comment]
F:\NG\ngFullStack>yo generator-angular-fullstack --version
1.8.4

**Comment by Awk34** [comment]
That's your `yo` version

**Comment by Awk34** [comment]
`npm list -g --depth=0 | grep generator-angular-fullstack`

**Comment by SagarBaggaOutlook** [comment]
Sagar@RAM MINGW64 /f/ng/ngFullStack
$ npm list -g --depth=0 | grep generator-angular-fullstack
├── generator-angular-fullstack@3.7.6

Thanks for sharing code.

**Comment by Awk34** [comment]
Do you get any console errors?

**Comment by kongaraju** [comment]
Me too facing the same issue, will it work with old generator?

I found that newly generated files for route not included in index.html, I suspect gulp or webpack.

**Comment by pabSec** [comment]
Same error here

**Comment by kongaraju** [comment]
Its basically not including the files into your app.js, you can manually include files to your app.js. Refer main route to export and import new route files.

**Comment by zagapyan** [comment]
Same error on my end when using routes generator. The page just redirects to the main state.

**Comment by Awk34** [comment]
@SagarBaggaOutlook check to make sure that the proper files are getting injected into your `index.html`. 

To everyone else that's on 4.x.x, you have to import your modules in your `client/app.js`

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by srikanth-venturew** [comment]
Please reopen this issue again . I am facing this issue . 
I am using the angular-fullstack version : 
- generator-angular-fullstack@4.2.2

There are no files included in index.html , and I can't figure out what happens with the newly created routes , I cannot access them by any way they are re-directing to home page .

Please help with this issue.

**Comment by Awk34** [comment]
@srikanth-venturew please open a new issue
