### ISSUE TITLE
Socket events for user created by auth boilerplate

### ISSUE THREAD

**Issue by haplo31** [angular-fullstack/generator-angular-fullstack#2074]
Hello,
For my project, I have some notifications for each user that I save inside my user database.
For that, I've modified the user model from the auth boilerplate and I've added some new functions inside my user.controller.js file.

I use the socket functionnality (socket.syncupdates) for the other endpoints of my application but the user endpoint generated by the application doesn't have this functionnality.

Can i add this functionnality to the user endpoint the same way it appears in other endpoints or is this something not recommended?

Thanks for your time

**Comment by Awk34** [comment]
Sure, it can be done. Just be aware, it will likely take some more logic. The default socket behavior is to push updates to every listening client, whereas you would likely only want live updates per-user to only be sent out to that user, not everyone.

**Comment by haplo31** [comment]
I did not think about that!
I found issue #690 who seems to talk about this logic, I will try to use it.
 Thanks!
