### ISSUE TITLE
gulp build not including package installs

### ISSUE THREAD

**Issue by chackerian** [angular-fullstack/generator-angular-fullstack#2076]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 0.12.0
npm | 3.6.0
Operating System | OS X 10.11.5

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS | SCSS
Router |  ui-router
Build Tool | Gulp
Client Tests | Jasmine 
DB | MongoDB
Auth | Y 

The issue I'm facing is that gulp build does not seem to be including any package I install. For example I installed the select 2 bower package and I can see it located in my bower_components folder. When I run gulp build, this package is not included and I cannot use it in my app. Additionally, the bootstrap install does not seem to included properly for all the bootstrap features. The grid classes showcased in the demo main.html work but things like dropdowns don't seem to work. I had to manually include a CDN link for bootstrap to get this to work.

**Comment by Awk34** [comment]
Front-end JS to be added should be placed here: https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.5/templates/app/client/index.html#L49-L53

The 3.x.x project uses [usemin](https://github.com/zont/gulp-usemin) to package front-end deps during build-time. If the script isn't inside those 'build:js' directives, it won't get built. The project also uses [wiredep](https://github.com/taptapship/wiredep) to attempt to automatically inject any Bower deps that you include, but this doesn't always work.

Please confirm that your script tag is inside of the 'build:js' directives.

**Comment by chackerian** [comment]
No, the script tags are not showing up there. I just tried to manually include one for that select2 package I mentioned before. I ran gulp build and this seems to have removed it.

**Comment by Awk34** [comment]
Looking at the [select2 GitHub page]https://github.com/select2/select2), it *does* look like they have a proper `bower.json`, which is what wiredep uses to include scripts/css. Can you confirm that running `gulp wiredep:client` does not insert your select2 script tag into `<!-- bower:js --><!-- endbower -->`?

Also, if you were to manually include the script, it should look something like this:

```html
<!-- build:js({client,node_modules}) app/vendor.js -->
      <!-- bower:js -->
      <!-- endbower -->
      <script src="socket.io-client/socket.io.js">
      <script src="select2/dist/js/select2.js">
<!-- endbuild -->
```

**Comment by chackerian** [comment]
Yeah I just tried it and didn't insert anything. 

Here is the relevant part of my index.html file if that is helpful:

 ```
<!--[if lt IE 9]>
    <script src="bower_components/es5-shim/es5-shim.js"></script>
    <script src="bower_components/json3/lib/json3.min.js"></script>
    <![endif]-->
    <!-- build:js({client,node_modules}) app/vendor.js -->
      <!-- bower:js -->
      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/angular-socket-io/socket.js"></script>
      <script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
      <script src="bower_components/angular-validation-match/dist/angular-validation-match.min.js"></script>
      <!-- endbower -->
      <script src="socket.io-client/socket.io.js"></script>
    <!-- endbuild -->
    <!-- build:js(.tmp) app/app.js -->
      <script src="app/app.js"></script>
      <!-- injector:js -->
      <script src="app/admin/admin.module.js"></script>
      <script src="components/auth/auth.module.js"></script>
      <script src="components/util/util.module.js"></script>
      <script src="app/account/account.js"></script>
      <script src="app/account/login/login.controller.js"></script>
      <script src="app/account/settings/settings.controller.js"></script>
      <script src="app/account/signup/signup.controller.js"></script>
      <script src="app/add-listing/add-listing.controller.js"></script>
      <script src="app/add-listing/add-listing.js"></script>
      <script src="app/admin/admin.controller.js"></script>
      <script src="app/admin/admin.router.js"></script>
      <script src="app/app.constant.js"></script>
      <script src="app/main/main.controller.js"></script>
      <script src="app/main/main.js"></script>
      <script src="components/auth/auth.service.js"></script>
      <script src="components/auth/interceptor.service.js"></script>
      <script src="components/auth/router.decorator.js"></script>
      <script src="components/auth/user.service.js"></script>
      <script src="components/footer/footer.directive.js"></script>
      <script src="components/listing-card/listing-card.directive.js"></script>
      <script src="components/modal/modal.service.js"></script>
      <script src="components/mongoose-error/mongoose-error.directive.js"></script>
      <script src="components/navbar/navbar.controller.js"></script>
      <script src="components/navbar/navbar.directive.js"></script>
      <script src="components/socket/socket.service.js"></script>
      <script src="components/util/util.service.js"></script>
      <!-- endinjector -->
    <!-- endbuild -->
```

**Comment by Awk34** [comment]
@chackerian is it in your `bower.json`?

**Comment by chackerian** [comment]
It wasn't. I thought it what get included automatically. I'm still however have trouble using it.

**Comment by Awk34** [comment]
When you install a Bower dep, you need to use `bower install --save select2` to have it save to your `bower.json`. Doing so *should* fix this.

**Comment by chackerian** [comment]
Ok. I'm still having bootstrap issues

**Comment by Awk34** [comment]
You are referring to the Bootstrap JS functionality, yes? I see that you chose to include [UI Bootstrap](https://github.com/angular-ui/bootstrap), from the `<script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>` included. When you choose to use UI Bootstrap, the regular `bootstrap.js` gets excluded, since you'll be using the UI Bootstrap components instead. I believe this issue can be closed now.

**Comment by akshayseth** [comment]
hello @Awk34 ,
I am using fullstavk v3.8.0 and when I am adding a CDN in index.html it gets automatically deleted when i hit gulp serve...any fix for the same?
