### ISSUE TITLE
Use Camo as ODM for MongoDB.

### ISSUE THREAD

**Issue by michaeljota** [angular-fullstack/generator-angular-fullstack#2077]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 3.7.5 |
| Node | 6.2.1 |
| npm |  |
| Operating System | Windows 10 Pro 64 Bits |

Hi! Thanks for this work. I've use this since 2014 I think, awesome tool. I came across with Camo this year. It's "A class-based ES6 ODM for Mongo-like databases." It currently support NeDB and Mongo, of curse. But Scott plans to support more soon. Check it out.

**Comment by Awk34** [comment]
It looks interesting, and I definitely like the syntax, but we wouldn't move to something like that anytime in the near future. That repo has 129 commits and 3 contributors, while mongoose has 6339 commits and 270 contributors. For a project like this, we definitely want to go for stability + power over some nice features.

**Comment by ronrbc** [comment]
even the owners says in the website they are not ready for production. so i guess we'll give them some time. and i love mongoose anyways.
