### ISSUE TITLE
Login & Register buttons are not working

### ISSUE THREAD

**Issue by Brian1111** [angular-fullstack/generator-angular-fullstack#2087]
I installed angular-fullstack generator.  When I go to localhost:9000 and fill in the register form, after I press the register button, nothing just happens.  Also, in the login page when I press the login button nothing just happens.

Chrome console for sign-up states:  Failed to load resource: the server responded with a status of 403 (Forbidden) http://localhost:9000/auth/local

And for sign-in states:  POST http://localhost:9000/auth/local 403 (Forbidden)

I tried to login with Facebook and Twitter, but it only shows a circle rolling counter-clockwise.

- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
generator-angular-fullstack | 3.7.5
Node | 6.3.1
npm | 3.10.3
Operating System | Windows 10, 64 bit

Item | Answer
Transpiler | Babel 
Markup | HTML 
CSS | CSS
Router | ngRoute
Client Tests | Mocha
DB | MongoDB
Auth | Y

**Comment by Brian1111** [comment]
I typed npm install.  Then after I ran for the second time gulp build and gulp serve, it fixed the issue.  Now I can register and login.  So for now I close the issue.

**Comment by Awk34** [comment]
Strange. I guess there was a dependency failure.
