### ISSUE TITLE
main.html 404 after build

### ISSUE THREAD

**Issue by arkdelkaos** [angular-fullstack/generator-angular-fullstack#2088]
On develop everything works great.
After `gulp build`and deploying to heroku, I got a blank page, and then I do verify that my main.thml was missing (404).
With `gulp serve:dist` I got the same problem, so I watch the app.js and saw that there is no main.html anywhere.
But I do have mention to `main.js` and `main.controller.js` on `index.thml`
I've make little changes, and I think that I didn't touch anything after scaffolding this morning.
[github:eecr](http://www.github.com/arkdelkaos/EECR).

**I cannot find where this is failing** (maybe because I'm kind of tired), but I want to deploy ASAP :) **Any help will be very appreciated** :)

- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 6.3.1
npm | 3.10.3
Operating System | OS X

Item | Answer
----- | -----
Transpiler | Babel
Markup | Jade
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

**Comment by Awk34** [comment]
`main.html` is *supposed* to be gone when you build. Take a look into the dependency [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.5/templates/app/_package.json#L49), [gulp-angular-templatecache](https://github.com/miickel/gulp-angular-templatecache)

**Comment by Awk34** [comment]
What's your `dist/index.html` look like?

**Comment by arkdelkaos** [comment]
OK, I see now that my problem is that I'm updating an old project to the latest generator-fullstack, and some things just "don't work" as I thought they should.
For example, I thought that I may use jade "just when I wanted", so `main.html` and some other weren't jade files, but just the html views I had in the original project.
After rewriting them on jade, they are builded into index.html's templates.

But now I'm having other problems, like some controllers not being processed, or even bootstrap's glyphicons...

Why there is so much difference between dev mode (gulp serve), that works perfectly, and the production version? Its there a easies't way to see what I'm doing wrong? Because I feel like hunting for witches, having to build every time I try something to see if I got it right :(

I'm feel kind of down right now, so I'll rest for a while, and keep trying later :) It very discouraging having the dev version finished, and then have no clue about why the building process is failing like that :( (my fault, obviously)

**Comment by Awk34** [comment]
You *can* write both HTML and Jade side-by-side in 4.0.0-rc.0+ (by using multiple Webpack loaders), but I wouldn't really suggest it.

In everything before 4.0.0, the dev & prod builds **are** quite different, because the dev version just loads every file individually since it is quite fast (just communicating with the webserver on the same machine), and we concatenate all the files together for prod (for HTTP/1.1 reasons). Dev & prod versions for ^4.0.0 are quite similar, with the main difference being that the prod files are minified and hash-named.

Trust me, I know, having issues only in prod is a real pain. I do suggest you try installing `4.0.0-rc.0` and see how that works.

**Comment by arkdelkaos** [comment]
I'll try the beta :)
...btw, what do you recommend to "upgrade" a project from a "old" version of generator-fullstack to a new one?
Right now I'm following this steps:
-1 Rename folder from project to project_old
-2 yo -> new folder "project"
-3 I see whats different between the sample files and mine
-4 Manually copy the old project folders, update, and define them at index.html's injector:js zone
I suspect there is a better way, but everyone I ask for just do the same xD

**Comment by Awk34** [comment]
That's a fine way of converting. That would probably be especially better for upgrading an older project to something generated by 4.0.0

**Comment by arkdelkaos** [comment]
Perfect then :) I'll start with 4.0.0 tonight; I hope the caffeine god hear my prayers xD
