### ISSUE TITLE
webpack make fails for windows due to incompatible entry point file path

### ISSUE THREAD

**Issue by yogesum** [angular-fullstack/generator-angular-fullstack#2091]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.0-beta
Node | v6.2.2
npm | 3.9.5
Operating System | Windows 7

Item | Answer
----- | -----
Transpiler | Babel
Markup | Jade
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | SQL
Auth | N

**Snapshot:**

console error on chrome
![error-1](https://cloud.githubusercontent.com/assets/2473279/17166768/9a4054d0-53f6-11e6-8297-e6f560eab1c2.PNG)

in source map of `app.bundle.js`
![error-2](https://cloud.githubusercontent.com/assets/2473279/17166774/a8ecc27a-53f6-11e6-9e96-5b66409d6684.PNG)

**fix:**
I have made a pull request for solution also.

**Comment by Awk34** [comment]
Please update to `4.0.0-rc.0` and try again

**Comment by yogesum** [comment]
@Awk34 Tested with 4.0.0-rc.0. on same machine work. so closing this issue.
