### ISSUE TITLE
After saving he adds weird Stuff Automatically at the end. Bug?

### ISSUE THREAD

**Issue by atodicebear** [angular-fullstack/generator-angular-fullstack#2093]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 4.4.5
npm | 3.9.6
Operating System | Windows7
yo | 1.8.4

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS |  SCSS 
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB |  SQL
Auth | Y 
etc | etc

Working with AtomIDE.
Gulp serve is Running whole time while i do changes and save.

I couldnt check when it happens but sometimes after I save my work it adds something at the end and the Programm Errors.
```
    }
  }
  angular.module('euconDictionaryApp')
    .component('dictvalue', {
      templateUrl: 'app/dictvalue/dictvalue.html',
      controller: DictvalueComponent,
    });
})(); // everything below he Generates sometimes by himself
onent,
});
})();

onent,
});
})();

```
I dont know when it does it because its not happening after Every save.
This only appears to be in .js files. In .html if i remember correctly this didnt happen before?
And its only "copy paste" some of the last few Lines in the File.

**Comment by Awk34** [comment]
Who is "he"? I would tell him to stop messing with your programs :stuck_out_tongue_winking_eye: 

I've never seen something like this before

**Comment by atodicebear** [comment]
I dont know how to recreate the Problem because as mentioned it occurs Randomly?
Some Ideas what it could be?

**Comment by Awk34** [comment]
¯\\\_(ツ)\_/¯

**Comment by Koslun** [comment]
Think it's something wrong with your Atom configuration. `gulp serve `does not change the source files as far as I've know.

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by atodicebear** [comment]
Oh yeah Sorry.
The Problem seems to be with the Plugin for the AtomEditor -> AtomBeautify.
It Beautifys the code automatically after saving. In this Process it adds somehow sometimes some new Code.
So can be closed because it is not a Bug outgoing from the Fullstack.

Have a nice Weekend.
