### ISSUE TITLE
When creating a route called "Map"

### ISSUE THREAD

**Issue by BTruer** [angular-fullstack/generator-angular-fullstack#2097]
In this generator when using the command `yo angular-fullstack:route map`. It generates a page with /map.....However, if you look at the page there is an actual map pre generatored on the page. This is due to the `map.controller.js` having the `angular.module().component('map',{......., controllerAs: Map}` instead of controllerAs: 'Map'. Therefore the issue is **controllerAs not having the string value by default....we need to manually add quotes which not knowing this issue causes problems**
 - [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack |3.x.x
Node | x.x.x
npm | x.x.x
Operating System | Win 7

Item | Answer
----- | -----
JS
Markup | HTML 
CSS | CSS 
Router | ngRoute
Client Tests | Jasmine
DB | MongoDB 
Auth | Y

**Comment by Koslun** [comment]
Please state which versions you're looking at for this issue. Just 3.X or just 4.X? Or both?

**Comment by Awk34** [comment]
Closed due to inactivity

Anyhow, you probably shouldn't be using a browser structure like `Map` as a controller name.
