### ISSUE TITLE
Font Awesome Css  link deleted from index.html - Gulp task

### ISSUE THREAD

**Issue by robinpoulose1** [angular-fullstack/generator-angular-fullstack#2101]
css link was not found for fontawesome . So i manually linked it . However , whenever i run gulp task it remove the Css link for font awesome . did anyone know why this is happening. Is it becoz i am using both bootstrap and Fa. 
anyways , any idea how to fix it  . it will save my time 

 - [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by robinpoulose1** [comment]
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
      
if i place the fa.css below bootstrap css it get deleted. seems will have to use either glypicon or fa

**Comment by Koslun** [comment]
Anything placed between the two bower comments will be automatically replaced. Place it below or above those two comment tags to avoid that.

Font-awesome should have no issues to work with bootstrap.
