### ISSUE TITLE
How to refresh NavBar?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2104]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.x
Node | 6.2.2
npm | 3.9.2
Operating System | Windows 10 
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS
Router | ui-router
Client Tests | Jasmine
DB | MongoDB 
Auth | Y 
etc | etc

in one of my server side actions, i change the user's role. user apply for this role, controller calls the server side action, and the role is changing in database.
the navbar (using Auth)  is checking for the role, and displaying different menu options for the roles.
the problem is that the navbar is not updated with the new role change.
if i hit refresh, the menu shows the correct options.
what is the command or call to read the user from server to update the navbar?

**Comment by Awk34** [comment]
The *easiest* thing to do IMO would be to only complete (200 success) the HTTP request to change the role once it is updated in the DB and done. Then, on the client-side, when that request comes back successful, just refresh the browser page.

**Comment by ronrbc** [comment]
ok, great. i will try that.
i wanted actually to go somewhere else with $state.go(...   and what you're saying is use $state.reload() to refresh. that will make it difficult to go to the next page. maybe leave a flag to myself, do the refresh, check the flag, it it set, then $state.go...  just thinking out loud here...  thanks, i will work on this.

**Comment by Awk34** [comment]
Well, if you want something more complicated, where you *don't* have to refresh, you need to be able to signal to the navbar component that the user has changed, and the navbar should use an updated `user` object for it's data.

**Comment by ronrbc** [comment]
Yea! that's what i want. to broadcast to navbar: hey navbar, update yourself!  but i don't know what method to use in the navbar controller. maybe getCurrentUser?

**Comment by Awk34** [comment]
@ronrbc it might not be the **Best<sup>tm</sup>**  solution, but you can use [$rootScope.$broadcast](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$broadcast) to broadcast an event like so:

```js
rootScope.$broadcast('user_changed', newUser);
```

```js
$scope.$on('user_changed', function(response) {
      // ....
});
```

**Comment by ronrbc** [comment]
yes, that's what i did. i know how to do broadcast. what i don't know is what to do inside the $scope.$on function. how to cause the navbar to read the updated user?
thanks.

**Comment by Awk34** [comment]
Well, you'd have the `$scope.$on` in your navbar controller, and when it receives a new user, it should set `this.user` to be the new one.

**Comment by ronrbc** [comment]
will try that. thanks!

**Comment by robinpoulose1** [comment]
it would be bad practice to change the role in middle of production env. For such cases one should ask the user to logout and the make the necessary role changes and post role change as the user to login .

**Comment by AmirGilboa** [comment]
@robinpoulose1 why bad practice? i have students and teachers (and more). once you registered as a teacher (and provided what's needed), i want to show you the teacher's menu. so far with no luck.
even $state.reload() does not work. i suspect because i am in a sub state, inheriting from abstract state.
but technical difficulties aside, i don't think its a bad practice. just do what you need to do.

**Comment by Awk34** [comment]
@AmirGilboa I could see it getting very complicated very quickly. I've never tried to live-update a user, but when you have a lot of component logic that depends on user-state (ex. role), it's just a lot easier to fully unload and reload the app.

**Comment by AmirGilboa** [comment]
All right, i see what you mean. so for now i just kick them out and navigate to the login page. then after login obviously the new role is displayed. not the prettiest, but it works. thanks!

**Comment by DanMMX** [comment]
You can try this

### Controller

```
this.currentUser = Auth.getCurrentUser;
```

### HTML

```
<span ng-bind='vm.currentUser().name'></span>
```

or for your specific case:
```
<ul ng-if='vm.currentUser().role === 'myRoleA'> ... </ul>
<ul ng-if='vm.currentUser().role === 'myRoleB'> ... </ul>
```

You could as well modify the `Auth` service to have `isRoleA` / `isRoleB` functions returning a `Boolean` so the jade/html is easier to read.

With this, you will have the `$scope` to notice the change on the `Auth.getCurrentUser()` value.
