### ISSUE TITLE
Option to use Jasmine in server side test

### ISSUE THREAD

**Issue by michaeljota** [angular-fullstack/generator-angular-fullstack#2108]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.2 || 4.0.0.rc0
Node | 6.3.1
npm | 3.10.3
Operating System | Windows 10 T2

Item | Answer
----- | -----
Transpiler | Babel || TypeScript
Markup | HTML 
CSS | CSS 
Router | ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 

Problem: Asking to test with Jasmine result in Mocha, Chai and Sinon being used in anyway. 
What the expected behavior: Jasmine being used all alone.
How to reproduce? Select Jasmine as test framework.

Why/how is that a problem? Jasmine is a test framework with it's own systax and need nothing else to work and run.

**Comment by Awk34** [comment]
@michaeljota are you aware that the only option for server tests is Mocha?

**Comment by michaeljota** [comment]
Not, I'm not. 

But, why? Jasmine can be use to test serve too.

**Comment by Awk34** [comment]
Yes, but nobody set up the generator to support server-side jasmine tests. See #608

**Comment by michaeljota** [comment]
Ok. Thanks you. I'll look into that, see if I can help. :)
