### ISSUE TITLE
How to debug server side?

### ISSUE THREAD

**Issue by ronrbc** [angular-fullstack/generator-angular-fullstack#2109]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.x
Node | 6.2.2
npm | 3.9.2
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS
Router |  ui-router
Client Tests | Jasmine 
DB | MongoDB
Auth | Y 
etc | etc

so i have rtfm, and it said:
Use gulp serve:debug for a more debugging-friendly environment.

nice. can i please get the longer version? how does it work? what to install? how to begin? how to set my first breakpoint?
are we based on some package like node-inspector, or other?

What's the plan for the upcoming version 4? the same mechanism? new one?

Thanks for any tip.

**Comment by Awk34** [comment]
4.0.0 mainly overhauls things on the front end. You can see a preview of the changelog here: #2020

I have been working on expanding the docs. I know that they are lacking for how popular this project is.

`gulp serve:debug` uses node-inspector, yes. It *should* give you instructions once it starts. Note: starting using node-inspector will take more time than starting up a normal dev / prod server.

**Comment by ronrbc** [comment]
wonderful. great pointers to start. thanks!
