### ISSUE TITLE
gulp-filter@4.0.0 will miss file when building, while gulp-filter@3.0.1 OK

### ISSUE THREAD

**Issue by jacinchan** [angular-fullstack/generator-angular-fullstack#2146]
Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 5.10.1
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS |  SCSS
Router | ui-router
Client Tests |  Mocha
DB | MongoDB 
Auth |  N
etc | etc

when I use gulp build, i found app.js did not uglity or rev
problem is  
gulp-filter@4.0.0 will miss some files.
if i reset to gulp-filter@3.0.1, it's OK
see the gulp file here

in gulp.task('build:client')

return gulp.src(paths.client.mainView)
        .pipe(plugins.useref())
            .pipe(appFilter)
                .pipe(plugins.addSrc.append('.tmp/templates.js'))
                .pipe(plugins.concat('app/app.js'))
            .pipe(appFilter.restore)     -------------   // **app/app.js is included**
            .pipe(jsFilter)                     -------------    // **app/app.js is excluded!**
                .pipe(plugins.ngAnnotate())
                .pipe(plugins.uglify())
            .pipe(jsFilter.restore)
            .pipe(cssFilter)
                .pipe(plugins.cleanCss({
                    processImportFrom: ['!fonts.googleapis.com']
                }))
            .pipe(cssFilter.restore)
            .pipe(htmlBlock)            //the same problem here
                .pipe(plugins.rev())
            .pipe(htmlBlock.restore)
        .pipe(plugins.revReplace({manifest}))
        .pipe(gulp.dest(`${paths.dist}/${clientPath}`));

**Comment by Awk34** [comment]
Could you elaborate more? Why would gulp-filter 4 break this while it works with 3?

**Comment by jacinchan** [comment]
gulp-filter@4.0.0 change the way of calling multimatch
4.0.0 -- > multimatch(path.relative(file.cwd, file.path), pattern, options)
test
console.log(minimatch(".tmp/app/app.js", "**/*.js")); //false
console.log(minimatch(".tmp/app/app.js", "**/*.js",{dot:true})); //true
that the problem.
so if we use gulp-filter@4.0.0
our filter option must add {dot:true}
that's
var appFilter = plugins.filter('**/app.js', {restore: true, dot:true});
var jsFilter = plugins.filter('**/*.js', {restore: true, dot:true});
var cssFilter = plugins.filter('**/*.css', {restore: true, dot:true});
var htmlBlock = plugins.filter(['**/*.!(html)'], {restore: true, dot:true});

**Comment by Awk34** [comment]
Would you be comfortable sending a pull request to the *3.x.x* branch?

**Comment by jacinchan** [comment]
well, it's my first pull request... i don't know how to use actually.
