### ISSUE TITLE
deploy to heroku doesn't work

### ISSUE THREAD

**Issue by azakharo** [angular-fullstack/generator-angular-fullstack#2148]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1
Node | 4.4.7
npm | 3.10.6
Operating System | Windows 8.1
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | Pug
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y
etc | etc

=============================================

`>yo angular-fullstack:heroku
Error angular-fullstack:heroku

You don't seem to have a generator with the name angular-fullstack:heroku installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 17 registered generators run yo with the `--help` option.`

=============================================

At the same time, if I run the cmd for openshift I see the following:

`>yo angular-fullstack:openshift
(!) NamedBase constructor is deprecated. See https://github.com/yeoman/generator/issues/882
? Name to deploy as: (fullstackgen)
`

**Comment by luismanuel001** [comment]
Any updates on this issue?

**Comment by Awk34** [comment]
@luismanuel001 I've been quite busy lately, and haven't had much time to work on this. In the mean time, you can take a gander at this: http://angular-fullstack.github.io/generator-angular-fullstack/Examples/Heroku_Deployment.html
