### ISSUE TITLE
Question: where is the css?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2152]
I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1
Transpiler | Babel 
CSS | CSS

Looking at the result of gulp:build, and the **dist** folder, i notice there is no css files.
also the index.html does not reference any css files. obviously they are there somewhere, but i can't see them. is this related to webpack? if anyone can shed some light on this, or provide some links to read about it, that would be great. Thank you.

**Comment by Awk34** [comment]
4.x.x uses webpack, css gets packaged into the js bundles

**Comment by RonAlmog** [comment]
thanks.
why put css in js file? any advantage?
is there a way to not the bundling and use regular css files?

**Comment by AmirGilboa** [comment]
I see. but why would you want to embed your css in a javascript file? any benefit?

**Comment by Azayzel** [comment]
The reason is minification; faster page loading. When you bundle it into .js your http overhead drops significantly. I found a good article for you to read up on.

https://www.sitepoint.com/faster-page-loads-bundle-your-css-and-javascript/

Can we close this question?

**Comment by AmirGilboa** [comment]
thanks for your answer.
I did minification before that. but thanks anyways, and yes, i will close the question.
