### ISSUE TITLE
Set seedDB: false in Backend not working Bug?

### ISSUE THREAD

**Issue by atodicebear** [angular-fullstack/generator-angular-fullstack#2161]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 4.4.5
npm | 3.9.6
Operating System | Windows7
yo | 1.8.4

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS |  SCSS 
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB |  MsSQL
Auth | Y 
etc | etc

Hey its me Again :),
In seed.js is stated
```
/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */
in my config/environment/index.js
  // Should we populate the DB with sample data?
  seedDB: false, // set false 
in my server/app.js
// Populate databases with sample data
if (config.seedDB) { require('./config/seed'); } //
```
But its still Populating seed.js on every server start.
Bug? or have I change somewhere else as well something?
```
// Populate databases with sample data
if (config.seedDB) {
  console.log(config.seedDB);
  console.log("seedb check");
  // require('./config/seed');
}
```
Checked the config.seedDB variable and its allways true whether i set it false or true.
Define a new Variable in index.js
```
  seedDB: false,
seedDB2: false,
checking in app.js the new Value
// Populate databases with sample data
if (config.seedDB2) {
  console.log(config.seedDB); // output true
  console.log("seedb check");
  console.log(config.seedDB2);// output false
  // require('./config/seed');
}
```
That is working fine if i set seedDB2: false or change to true.

So somewhere is seedDB set allwasy to true by exporting?

**Comment by Awk34** [comment]
In `config/index.js`, `seedDbB` is set to `false` by default, but since you're probably running with a `NODE_ENV` of `development`, the `config/development.js` probably overwrites this: https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/server/config/environment/development.js#L26

**Comment by atodicebear** [comment]
Yeah you are right.
Changing the Value there solves the Problem.
