### ISSUE TITLE
Doesn't work in Chrome with AngularJS Batarang (Stable) 0.4.3

### ISSUE THREAD

**Issue by valsaven** [angular-fullstack/generator-angular-fullstack#2162]
When the extension is enabled - it shows just an empty window.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1
Node | 6.3.1
npm | 3.10.6
Operating System | Linux Mint 18 Cinnamon
Google Chrome | 52.0.2743.116 (64-bit)

Item | Answer
----- | -----
Transpiler | Babel
Markup | Pug
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | SQL
Auth | N

**Comment by Koslun** [comment]
Looking at the reviews I think this is a bug with AngularJS Batarang (Stable). You can note that a reviewer   named Troy Haran states: 

> Please note that this won't work with ng-strict-di directive on the ng-app.
> 
> Remove the ng-strict-di directive and it works fine.
> 
> Thanks for uploading this more useful version.

This is best-practice in Angular 2 and would be a non-trivial change imo. So don't see us changing this. This fork from the main Batarang app is also outdated, even linking to the main app on its Github page: https://github.com/spalger/angularjs-batarang. Though I believe the main version is still quite buggy and might still have to point to limitations with that when you work with it. Personally given up on the project but great if it works for you.

For the future I however have a lot of hope on https://github.com/rangle/augury. The spiritual successor to Batarang initially presented on an Angular conference a year or two ago. Expect it to work reasonably well within the year.

**Comment by Awk34** [comment]
Yaeh, try again with the latest version of Batarang

**Comment by Awk34** [comment]
Closed due to inactivity
