### ISSUE TITLE
How can I delete or disable some log tests in the console browser 

### ISSUE THREAD

**Issue by ignacio-chiazzo** [angular-fullstack/generator-angular-fullstack#2165]
I don't know where the messages come from. I want to delete these messages, just the log printed on the console. 

The messages : 

<img width="878" alt="screen shot 2016-08-21 at 1 25 04 pm" src="https://cloud.githubusercontent.com/assets/11672878/17838383/be6ab958-67a2-11e6-90f5-e71f9e1e3aff.png">

Is there a way to disable these prints from a config file?

**Comment by RonAlmog** [comment]
is this on the client console (browser, f12)? or in your server side console?
usually these log messages appear because the programmer put them in the code... you didn't?
just trying to find out the background, so we can help you better...

**Comment by Awk34** [comment]
I've never seen these before
