### ISSUE TITLE
Question: what's the best way to include a js lib in a single page?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2167]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | x.x.x
npm | 6.2
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS 
Router |  ui-router
DB | MongoDB 
Auth | Y 
etc | etc

i need to add these lines to my page:

`<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
  Stripe.setPublishableKey('YOUR_PUBLISHABLE_KEY');
</script>`

and have my code running **after** that, so it uses features of the stripe library. what's the way to do that?
i could add the line to index.html, but that would add it to any page, which is a waste. i only need it in certain pages. any idea?

**Comment by Awk34** [comment]
Why not just add it to the template of the page you want?

**Comment by AmirGilboa** [comment]
I will try that.  (that was my first attempt, didn't work)
for now i installed angular-stripe that helps the integration with stripe. the main js call is still in index.html, maybe now it will work. thanks.
