### ISSUE TITLE
Server tests : Authentication in Mocha + Chai + Sinon

### ISSUE THREAD

**Issue by JulienMalige** [angular-fullstack/generator-angular-fullstack#2168]
I can't find a solution to run integration tests under authentication.

Is the [Chai ](http://chaijs.com/plugins/chai-http/)`.auth('user', 'pass')` working ?

```
    beforeEach(function(done) {
      request(app)
        .get('/api/searches')
        .auth('test@example.com', 'test')
        .expect(200)
        .expect('Content-Type', /json/)
        .end((err, res) => {
          if (err) {
            return done(err);
          }
          searchs = res.body;
          done();
        });
    });
```

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

**Comment by Awk34** [comment]
If you look at the top of the file you should see `import request from 'supertest';`. `request` here is an instance of [supertest](https://github.com/visionmedia/supertest). This isn't using Chai HTTP.

**Comment by JulienMalige** [comment]
@Awk34 Excuse me for the confusion. In fact, I hesitated to ask the question here or on stackoverflow.
 
More globally, I try to find the cleanest way to "log a user" to make several sets of test. Should we have to use the  superset Agent ? (https://github.com/visionmedia/supertest/issues/46). I try it, but I'm also confused between cookies and token.

**Comment by Awk34** [comment]
This question has been asked a few times, which I can see with [this search](https://github.com/angular-fullstack/generator-angular-fullstack/issues?utf8=%E2%9C%93&q=is%3Aissue%20authenticated%20tests) I think you'll find what you're looking for in those issues.

**Comment by JulienMalige** [comment]
Thanks @Awk34. I found my solution in #494.
