### ISSUE TITLE
Promises not loading data in new Chrome version

### ISSUE THREAD

**Issue by flaurian** [angular-fullstack/generator-angular-fullstack#2169]
The new Chrome release (52) introduces a bug on promises with Windows. The fix is to add on server side in the express.js file the following line:

`app.set('etag', false); //turn off to fix Chrome 52 issue`

source:
[https://github.com/angular/angular.js/issues/15013](url)

**Comment by Awk34** [comment]
Thanks for the info. Hopefully Chrome will have a rollback / patch soon
