### ISSUE TITLE
generator-angular-fullstack fails on Windows 8.1

### ISSUE THREAD

**Issue by adamgcraig** [angular-fullstack/generator-angular-fullstack#2170]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1
Node | 6.4.0
npm | 3.10.3
Operating System | Windows 8.1 (64 bit)
yo | 1.8.4
gulp-cli | 1.2.2

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y
etc | etc

Upon calling 'yo angular-fullstack' and again upon calling 'npm install' in the project folder, the npm log ends with the following:
```
173890 info lifecycle iltorb@1.0.12~install: iltorb@1.0.12
173891 verbose lifecycle iltorb@1.0.12~install: unsafe-perm in lifecycle true
173892 verbose lifecycle iltorb@1.0.12~install: PATH: C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\bin\node-gyp-bin;C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\iltorb\node_modules\.bin;C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\.bin;C:\Program Files\nodejs;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\a'\AppData\Roaming\npm,C:\"Program Files"\MongoDB\Server\3.2\bin;C:\Python27\python.exe;C:\Users\a'\AppData\Roaming\nvm;C:\Program Files\nodejs
173893 verbose lifecycle iltorb@1.0.12~install: CWD: C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\iltorb
173894 silly lifecycle iltorb@1.0.12~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
173895 silly lifecycle iltorb@1.0.12~install: Returned: code: 1  signal: null
173896 info lifecycle iltorb@1.0.12~install: Failed to exec install script
173897 verbose unlock done using C:\Users\a'\AppData\Roaming\npm-cache\_locks\staging-c4819cc1d46684e7.lock for C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\.staging
173898 silly rollbackFailedOptional Starting
173899 silly rollbackFailedOptional Finishing
173900 silly runTopLevelLifecycles Starting
173901 silly runTopLevelLifecycles Finishing
173902 silly install printInstalled
173903 warn optional Skipping failed optional dependency /chokidar/fsevents:
173904 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
173905 warn optional Skipping failed optional dependency /stylint/chokidar/fsevents:
173906 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
173907 warn optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
173908 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
173909 verbose stack Error: iltorb@1.0.12 install: `node-gyp rebuild`
173909 verbose stack Exit status 1
173909 verbose stack     at EventEmitter.<anonymous> (C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\lib\utils\lifecycle.js:242:16)
173909 verbose stack     at emitTwo (events.js:106:13)
173909 verbose stack     at EventEmitter.emit (events.js:191:7)
173909 verbose stack     at ChildProcess.<anonymous> (C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\lib\utils\spawn.js:40:14)
173909 verbose stack     at emitTwo (events.js:106:13)
173909 verbose stack     at ChildProcess.emit (events.js:191:7)
173909 verbose stack     at maybeClose (internal/child_process.js:852:16)
173909 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
173910 verbose pkgid iltorb@1.0.12
173911 verbose cwd C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest
173912 error Windows_NT 6.3.9600
173913 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
173914 error node v6.4.0
173915 error npm  v3.10.3
173916 error code ELIFECYCLE
173917 error iltorb@1.0.12 install: `node-gyp rebuild`
173917 error Exit status 1
173918 error Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
173918 error Make sure you have the latest version of node.js and npm installed.
173918 error If you do, this is most likely a problem with the iltorb package,
173918 error not with npm itself.
173918 error Tell the author that this fails on your system:
173918 error     node-gyp rebuild
173918 error You can get information on how to open an issue for this project with:
173918 error     npm bugs iltorb
173918 error Or if that isn't available, you can get their info via:
173918 error     npm owner ls iltorb
173918 error There is likely additional logging output above.
173919 verbose exit [ 1, true ]
```
Trying to run 'gulp serve' anyway causes the server to crash with the following message:
`server/**/*
[nodemon] starting `node server`
module.js:457
    throw err;
    ^

Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (express.js:10:1)
    at Module._compile (module.js:556:32)
    at loader (C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node
modules\babel-register\lib\node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\a'\Doc
ments\UploadTest\ACraig\software\UploadTest\node_modules\babel-register\lib\nod
.js:158:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (app.js:26:1)
    at Module._compile (module.js:556:32)
    at loader (C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node
modules\babel-register\lib\node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\a'\Doc
ments\UploadTest\ACraig\software\UploadTest\node_modules\babel-register\lib\nod
.js:158:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
 [nodemon] app crashed - waiting for file changes before starting...
^CTerminate batch job (Y/N)? Y

C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest>`

**Comment by Awk34** [comment]
Please note the following, directly from the project readme's prerequisites section:

[`node-gyp`](https://github.com/nodejs/node-gyp) - You'll likely need to be able to use `node-gyp`, Node's tool for compiling native add-ons (for things like database drivers). See its [Installation section](https://github.com/nodejs/node-gyp#installation) for more instructions.

**Comment by adamgcraig** [comment]
Thank you for the quick reply.
I thought node-gyp was already installed on the machine, but it was not.
I have since installed it.
I also attempted to install Windows build tools with ` npm install --global --production windows-build-tools `, but it spent more than 24 hours at `Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... |`.
I have installed Python 2.7, Visual Studio 2015 with Visual C++ and Common Build Tools.
I have uninstalled all other versions of Python and run `npm config set python C:\Python27\python.exe`.
I have checked that this is the correct path to the Python executable.
I also ran ` npm config set msvs_version 2015 `.
I still get the following errors when running yo angular-fullstack:
`
npm WARN deprecated isparta-instrumenter-loader@1.0.1: isparta-instrumenter-load
er is deprecated. Please use isparta-loader instead
npm WARN deprecated isparta-loader@2.0.0: This package is deprecated in favor of
 istanbuljs/babel-plugin-istanbul
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a bu
ild toolchain, use it instead!
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use
@segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue

> v8-debug@0.7.7 preinstall C:\Users\a'\Documents\UploadTest\ACraig\software\Upl
oadTest\node_modules\.staging\v8-debug-aa2690ad
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall C:\Users\a'\Documents\UploadTest\ACraig\software\
UploadTest\node_modules\.staging\v8-profiler-0f6f4f14
> node -e 'process.exit(0)'

npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global node-inspector@0.12.8 should be installed with -g

> iltorb@1.0.12 install C:\Users\a'\Documents\UploadTest\ACraig\software\UploadT
est\node_modules\iltorb
> node-gyp rebuild


C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\iltorb>
if not defined npm_config_node_gyp (node "C:\Users\a'\AppData\Roaming\nvm\v6.4.0
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  dictionary.c
  bit_reader.c
  decode.c
  huffman.c
  state.c
  win_delay_load_hook.c
C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\node_modules\node-gyp\s
rc\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition;
 different type modifiers [C:\Users\a'\Documents\UploadTest\ACraig\software\Upl
oadTest\node_modules\iltorb\build\decode.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
  dictionary.c
  backward_references.c
  bit_cost.c
  block_splitter.c
  brotli_bit_stream.c
  cluster.c
  compress_fragment.c
  compress_fragment_two_pass.c
  encode.c
  entropy_encode.c
  histogram.c
  literal_cost.c
  memory.c
  metablock.c
  static_dict.c
  utf8_util.c
  win_delay_load_hook.c
C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\node_modules\node-gyp\s
rc\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition;
 different type modifiers [C:\Users\a'\Documents\UploadTest\ACraig\software\Upl
oadTest\node_modules\iltorb\build\encode.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\a'\AppData\Roaming\nvm\v6.4.
0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a'\\AppData\\
Roaming\\nvm\\v6.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.j
s" "rebuild"
gyp ERR! cwd C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_mo
dules\iltorb
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
[               ...] - install: info lifecycle iltorb@1.0.12~install: Failed to

...


`-- webpack-stream@3.2.0
  +-- lodash.clone@4.5.0
  +-- lodash.some@4.6.0
  +-- memory-fs@0.3.0
  `-- vinyl@1.2.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm WARN optional Skipping failed optional dependency /stylint/chokidar/fsevents
:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fseve
nts:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\npm-deb
ug.log

C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest>`

**Comment by Awk34** [comment]
With the `npm install --global --production windows-build-tools`, I believe it will download/run some installers that you have to click through yourself.

**Comment by adamgcraig** [comment]
Thanks for your continued help with this, but it does not show any prompt for input or open up any GUIs; it just says, "Launched installers, now waiting for them to finish. This will likely take some time - please be patient! Waiting for installers..." and shows the spinning line: '-', then '\', then '|', then '/', then back to '-', and so on...

**Comment by Awk34** [comment]
@adamgcraig since that doesn't seem to be working, try the manual method of installing the required dependencies from the [node-gyp installation section](https://github.com/nodejs/node-gyp#installation) (Windows option 2)
