### ISSUE TITLE
Error: Cannot resolve module 'angular-socket-io'

### ISSUE THREAD

**Issue by juangl** [angular-fullstack/generator-angular-fullstack#2172]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1 
Node | v6.4.0
npm | 3.10.6
Operating System | Archlinux

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS |  SCSS 
Router |  ui-router
Client Tests | Mocha
DB | MongoDB 
Auth | Y 
Socket.io | N

![screenshot from 2016-08-24 14-23-42](https://cloud.githubusercontent.com/assets/1887029/17944953/6875bf0e-6a07-11e6-84ae-c1362397feed.png)

**Comment by Awk34** [comment]
Remove [this line](https://github.com/angular-fullstack/generator-angular-fullstack/blob/65c765586550bef048a807f935f04ff73e61e4f2/templates/app/webpack.make.js#L52) from your webpack.make.js

**Comment by juangl** [comment]
👍 Yeah. It's solved.
