### ISSUE TITLE
I need to use bower library with Webpack in v4.0.1

### ISSUE THREAD

**Issue by navin10sharma** [angular-fullstack/generator-angular-fullstack#2176]
Hello Guys 

I just try to start playing with generator-angular-fullstack@beta v4.0.1  according to Docs it support Webpack  and my default setup looks grate and working perfectly.

I didn't found any option to install bower component with v4.0.1 i knew Webpack suggest to use npm modules instead of bower but the problem some of the library am looking to use they don't have npm version yet so somehow we need some bower component as well.

Can you suggest is there any npm library available then i can we use bower as well.

Thanks

**Comment by Awk34** [comment]
Although Webpack works best with Node modules, you can still install front-end JS libs with Bower if you need to, or even include the JS lib in your project's assets.

Most up-to-date front-end libs available on bower are also available on npm.
