### ISSUE TITLE
V4.0.1 breaks on 'production' deployment due to devDep imports. (browser-sync, ansi-strip)

### ISSUE THREAD

**Issue by dhaazen** [angular-fullstack/generator-angular-fullstack#2178]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
-----|-----
generator-angular-fullstack | 4.0.1
Node | 4.4.5
npm | 3.10.5
Operating System | OS X 10

Item | Answer
-----|-----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | SQL
Auth | N

V4.0.1 breaks on 'production' deployment due to devDep imports. (browser-sync, ansi-strip) in express.js

Fixed by moving the:

```
const stripAnsi = require('strip-ansi');
var browserSync = require('browser-sync').create();  
```

Dependencies which are only in devDeps. To within the:

```
if ('development' === env) {
```

block.

**Comment by Awk34** [comment]
See #2124
