### ISSUE TITLE
Can not build with "yo angular-fullstack appname"

### ISSUE THREAD

**Issue by khanhoct** [angular-fullstack/generator-angular-fullstack#2187]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1
Node | v4.5.0
npm | v3.10.6
Operating System | Windows 10 - 64 bit

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router |  ui-router
Client Tests | Jasmine
DB | MongoDB
Auth |  No
socket.io | No

Error Log:
```
160017 error Windows_NT 10.0.10586
160018 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\khanh.nguyen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
160019 error node v4.5.0
160020 error npm  v3.10.6
160021 error code ELIFECYCLE
160022 error iltorb@1.0.12 install: `node-gyp rebuild`
160022 error Exit status 1
160023 error Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
160023 error Make sure you have the latest version of node.js and npm installed.
160023 error If you do, this is most likely a problem with the iltorb package,
160023 error not with npm itself.
160023 error Tell the author that this fails on your system:
160023 error     node-gyp rebuild
160023 error You can get information on how to open an issue for this project with:
160023 error     npm bugs iltorb
160023 error Or if that isn't available, you can get their info via:
160023 error     npm owner ls iltorb
160023 error There is likely additional logging output above.
160024 verbose exit [ 1, true ]
```

**Comment by RonAlmog** [comment]
have you installed node-gyp ?  it's a new requirement.

**Comment by Azayzel** [comment]
You have to download the Windows build tools https://www.microsoft.com/en-us/download/details.aspx?id=48159

And make sure your me on the latest version of npm

**Comment by khanhoct** [comment]
@Azayzel : Need Windows build tool , so why this was not mention on document?

**Comment by Awk34** [comment]
@khanhoct this is noted in the readme here: https://github.com/angular-fullstack/generator-angular-fullstack
