### ISSUE TITLE
Deploy on Cloud Foundry

### ISSUE THREAD

**Issue by Crazy-Ace** [angular-fullstack/generator-angular-fullstack#2194]
I have an angular fullstack project that I would like to deploy on cloud foundry (pivotal). Can maybe someone please tell me how I can accomplish this? Until now I have only deployed my projects on heroku.
But I have absolutely no clue how to deploy on cloud foundry.
Can someone please help me?

**Comment by QuartzSG** [comment]
Deploying any nodejs project to cloud foundry on pivotal is simply changing the way your project gets env variables. Cloud foundry uses manifest.yml in addition to package.json. You might want to google for cf docs, or search for cloud foundry pivotal nodejs. Some i found include https://docs.run.pivotal.io/buildpacks/node/node-tips.html. You might need to see what services (like mongodb for you db) are available, and learn to create and bind such services to your nodejs app on cf.

**Comment by dhaazen** [comment]
I would suggest doing a build then change to the dist directory and then running a 'cf push' from there. You can cp in a manifest file if you are using one.

**Comment by Crazy-Ace** [comment]
Thank you very much. I already solved the problem. 
As @dhaazen & @QzSG said, you just have to put in the cf env variables, build your project, insert the manifest file an then push it to cf.

Was actually very easy :)
