### ISSUE TITLE
Export .name modules@ 4.0.2

### ISSUE THREAD

**Issue by krokhale** [angular-fullstack/generator-angular-fullstack#2196]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 6.2.2
npm | 3.9.5
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | Pug
CSS | SCSS 
Router | ngRoute
Client Tests | Jasmine
DB | 
Auth | N
etc | etc

I am upgrading to the 4.X version from a 3.X. And maybe i don't understand this well enough, and i looked around for documentation, could't find anything relevant.

How does once access constants. In the new generator the modules are returned as strings using the '.name' that is exported. So when i 

    console.log(constants)

in client/app.js, i get

    'myAppName.constants'

Just the string name of the exported function. How do i actually get the constants JSON itself?

Thanks!

**Comment by Awk34** [comment]
[here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/4.0.2/templates/app/client/app/app.constants.js#L5) we add an Angular constant named `appConfig`, and [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/4.0.2/templates/app/client/components/auth(auth)/auth.service.js#L15)'s  an example of where it's used.
