### ISSUE TITLE
Can we use ES6 generators?

### ISSUE THREAD

**Issue by aabm00** [angular-fullstack/generator-angular-fullstack#2197]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 4.4.5
npm | 3.8.9
Operating System | Windows 7
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router |  ui-router
Client Tests | Jasmine
DB | MongoDB
Auth | Y
socket.io | Y

Hi

I want to know if I can use ES6 generators, both in the server and client with this generator.
I just try a simple example in the server side and I get and error.

The example is:

    var x = 1;

    function *foo() {
      x++;
      yield; // pause!
      console.log( "x:", x );
    }
    function bar() {
     x++;
    }

    var it = foo();
    // start `foo()` here!
    it.next();
    console.log(x); // 2
    bar();
    console.log(x); // 3
    it.next(); // x: 3`

And the error is:

> var _marked = [foo].map(regeneratorRuntime.mark);
>                         ^
> 
> ReferenceError: regeneratorRuntime is not defined
>     at Object.<anonymous> (D:\002_IOT\WS_IOT\iotfs376\server\api\data\data_day\data_day.socket.js:30:25)
>     at Module._compile (module.js:409:26)
>     at loader (D:\002_IOT\WS_IOT\iotfs376\node_modules\babel-register\lib\node.js:158:5)
>     at Object.require.extensions.(anonymous function) [as .js] (D:\002_IOT\WS_IOT\iotfs376\node_modules\babel-register\lib\node.js:168:7)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at onConnect (socketio.js:68:3)
>     at Namespace.<anonymous> (socketio.js:120:5)
>     at emitOne (events.js:77:13)
>     at Namespace.emit (events.js:169:7)
>     at Namespace.emit (D:\002_IOT\WS_IOT\iotfs376\node_modules\socket.io\lib\namespace.js:206:10)
>     at D:\002_IOT\WS_IOT\iotfs376\node_modules\socket.io\lib\namespace.js:174:14
>     at nextTickCallbackWith0Args (node.js:420:9)
>     at process._tickCallback (node.js:349:13)
> 

Thanks

**Comment by Awk34** [comment]
@aabm00 add `babel-plugin-transform-runtime` dependency to your project and add `transform-runtime` [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/4.0.2/templates/app/_.babelrc#L3)

**Comment by aabm00** [comment]
thanks for the quick answer.

When you say  **add babel-plugin-transform-runtime dependency to your project**, do you mean that I have to add this plugin to the package? 
   **npm install add babel-plugin-transform-runtime  --save**

thanks

**Comment by Awk34** [comment]
@aabm00 yes

**Comment by aabm00** [comment]
Sorry 
I suposse that when you say  **add transform-runtime here**
here is:
  **generator-angular-fullstack/templates/app/_.babelrc**
And it's a generator code,
 I suposee you mean the file **.babelrc** in the project

>     "presets": ["es2015"],
>     "plugins": ["transform-class-properties", 
>                      "transform-runtime"]
   
In the new version of the generator is the ES6 generators supported without having to do this modifications?

Thanks

**Comment by Awk34** [comment]
@aabm00 since the generated project doesn't use generator functions out-of-the-box, no, the babel runtime is not used by default

**Comment by aabm00** [comment]
So with this changes I can work with ES6 generators in the server side and in the client side (Typescript)?

**Comment by Awk34** [comment]
@aabm00 yes. I believe you can use generator functions with TypeScript without changing any configuration.

**Comment by aabm00** [comment]
Thanks, as always you're very helpful

**Comment by aabm00** [comment]
Sorry to come back again.

Looking at the documentation about generator I have seen that ES7 simplifies a lot the use of generators using (async/await) and I wonder if it's posible to use ES7 instead of ES6 in the angular-fullstack (server & client side), and what would be the changes I have to do.

Thanks

**Comment by Awk34** [comment]
I've been using this plugin instead: https://babeljs.io/docs/plugins/transform-async-to-generator/

**Comment by aabm00** [comment]
I get the same error with this plugin. I don't know what I am doing wrong. 
Am I missing something?

Thanks

**Comment by Awk34** [comment]
Maybe you have a syntax error somewhere else in your file

**Comment by aabm00** [comment]
The problem is solved. Thanks

I was trying it in a new project (No fullstack) an probably I was missing something. If I do the steps I indicated in the fullstack project it works.

**Comment by Awk34** [comment]
Great to hear @aabm00
