### ISSUE TITLE
production mode (gulp build) leads to app which lacks .html files

### ISSUE THREAD

**Issue by dnewman-polar3d** [angular-fullstack/generator-angular-fullstack#2198]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.0-rc.0
Node | v4.4.7
npm | 3.10.6
Operating System | OS X 10.9.5

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | MongoDB 
Auth | Y

The dist version of the project is missing `.html` files down the `client/` tree.  `gulp serve` works fine.

    % gulp serve:dist
    [10:51:25] Requiring external module babel-register
    (node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
    (node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
    [10:51:29] Using gulpfile ~/git/yunshiquan/gulpfile.babel.js
    [10:51:29] Starting 'serve:dist'...
    [10:51:29] Starting 'build'...
    [10:51:29] Starting 'clean:dist'...
    [10:51:29] Starting 'clean:tmp'...
    [10:51:29] Finished 'clean:tmp' after 6.79 ms
    [10:51:29] Finished 'clean:dist' after 146 ms
    [10:51:29] Starting 'inject'...
    [10:51:29] Starting 'inject:scss'...
    [10:51:29] gulp-inject 12 files into app.scss.
    [10:51:30] Finished 'inject:scss' after 65 ms
    [10:51:30] Finished 'inject' after 65 ms
    [10:51:30] Starting 'transpile:server'...
    [10:51:30] Finished 'transpile:server' after 946 ms
    [10:51:30] Starting 'build:images'...
    [10:52:13] gulp-imagemin: Minified 62 images (saved 532.17 kB - 19.5%)
    [10:52:13] Finished 'build:images' after 43 s
    [10:52:13] Starting 'copy:extras'...
    [10:52:13] Starting 'copy:assets'...
    [10:52:13] Starting 'copy:fonts:dist'...
    [10:52:13] Starting 'copy:server'...
    [10:52:13] Starting 'webpack:dist'...
    [10:52:14] Finished 'copy:server' after 320 ms
    [10:52:17] Finished 'copy:extras' after 3.55 s
    [10:52:19] Finished 'copy:fonts:dist' after 5.84 s
    [10:52:19] Finished 'copy:assets' after 5.88 s
    [10:52:35] Version: webpack 1.13.2
                                    Asset     Size  Chunks             Chunk Names
              app.7a957def1c13dac3bf41.js   507 kB       0  [emitted]  app
        polyfills.7a957def1c13dac3bf41.js   134 kB       1  [emitted]  polyfills
           vendor.7a957def1c13dac3bf41.js   728 kB       2  [emitted]  vendor
          app.7a957def1c13dac3bf41.js.map  1.81 MB       0  [emitted]  app
    polyfills.7a957def1c13dac3bf41.js.map   574 kB       1  [emitted]  polyfills
       vendor.7a957def1c13dac3bf41.js.map  5.66 MB       2  [emitted]  vendor
                     ../client/index.html  1.49 kB          [emitted]  
    Child html-webpack-plugin for "../client/index.html":
       
    [10:52:35] Finished 'webpack:dist' after 21 s
    [10:52:35] Starting 'revReplaceWebpack'...
    [10:52:35] Finished 'revReplaceWebpack' after 22 ms
    [10:52:35] Finished 'build' after 1.08 min
    [10:52:35] Starting 'env:all'...
    [10:52:35] Finished 'env:all' after 4.93 ms
    [10:52:35] Starting 'env:prod'...
    [10:52:35] Finished 'env:prod' after 525 μs
    [10:52:35] Starting 'start:server:prod'...
    [10:52:35] Finished 'start:server:prod' after 43 ms
    [10:52:35] Starting 'start:client'...
    [nodemon] 1.10.2
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: /Users/dnewman/git/yunshiquan/dist/server/**/*
    [nodemon] starting `node dist/server`
    Express server listening on 3000, in production mode
    Not adding new users; they likely already exist
    [10:52:36] Finished 'start:client' after 1.46 s
    [10:52:36] Finished 'serve:dist' after 1.1 min
    GET /app/layouts/navbar/navbar.html 404 10.372 ms - 14
    GET /app/layouts/plusButton/plusButton.html 404 1.914 ms - 14

While this project was generated with 4.0.0-rc.0, it is using a 4.0.2 `webpack.make.js` with one additional loader,

       preLoaders: [],
        loaders: [
              {
                test: /angular\.headroom\.js/,
                loader: 'imports?Headroom=headroom.js/dist/headroom'
         }, {
            // JS LOADER

While I don't believe that to be relevant, I mention it for disclosure.

The main `index.html` file does have consistent LF terminators,

    <script type="text/javascript" src="/vendor.bundle.js"></script>
    <script type="text/javascript" src="/polyfills.bundle.js"></script>
    <script type="text/javascript" src="/app.bundle.js"></script>

**Comment by dnewman-polar3d** [comment]
I have an inkling of the issue...`layout` needs to be added to  `{app,components}`....

**Comment by dnewman-polar3d** [comment]
False alarm.  Those files are under `app/` already,

    % find client -name navbar.html
    client/app/layouts/navbar/navbar.html
    client/components/navbar/navbar.html

So they are already covered by the existing places `gulpfile.babel.js` looks.  Do however, note that different copies exist under both `app/` and `components/`.  Different contents, different paths.

**Comment by Awk34** [comment]
Can you try out a fresh 4.0.2 scaffold and see if you have the same issues? I can't remember if we fixed anything with `gulp serve:dist` between 4.0.0-rc.0 and 4.0.2

**Comment by dnewman-polar3d** [comment]
I tried that earlier today with a spanking fresh-off-of npm angular-fullstack 4.0.2.  Got an interesting error (see below) which prevents `gulp serve:dist` from running.

    % gulp serve:dist
    ....
    ERROR in ./~/css-loader!./~/sass-loader!./client/app/app.scss
    Module build failed: 
    @import '~bootstrap-sass/vendor/assets/stylesheets/bootstrap';
    ^
          File to import not found or unreadable: ~bootstrap-sass/vendor/assets/stylesheets/bootstrap
    Parent style sheet: stdin
         in /Users/dnewman/fluf-2/client/app/app.scss (line 2, column 1)
     @ ./client/app/app.scss 4:14-120
    Child html-webpack-plugin for "../client/index.html":

Now, a scaffolded app from about 4 weeks ago with 4.0.1, works fine.

Again, the gulpfile.babel.js are identical between my 4.0.0-rc.0 and the 4.0.1 and 4.0.2. (Other than the version comment added at the top.)  However, the package version differences could well be different.  And may make a difference?

**Comment by dnewman-polar3d** [comment]
As an aside, there were plenty of changes to `webpack.make` between 4.0.0-rc.0 and 4.0.1.  However, I'm using the latest `webpack.make` and updated my gulp-imagemin dependency since that was needed by changes to `webpack.make`.

**Comment by dnewman-polar3d** [comment]
To be clear, what worked for me with the 4.0.1 was running just the scaffolded, auto-generated app.  Were you instead asking me to copy my `client/` and `server/` directories to a new 4.0.1 or 4.0.2 scaffolding and then try that?  (After merging `package.json` dependencies.)  I can do that, but I would expect just using the 4.0.2 `gulp.babelfile` and `webpack.make` files in my 4.0.0-rc.0 setup to suffice.

**Comment by Awk34** [comment]
change `@import '~bootstrap-sass/vendor/assets/stylesheets/bootstrap';` to `@import '~bootstrap-sass/assets/stylesheets/bootstrap';`

**Comment by Awk34** [comment]
I was just asking you to use a brand-new 4.0.2 app and see how it works out.

**Comment by dnewman-polar3d** [comment]
It works.   I noticed that the launch of the web browser by gulp sent me to localhost:3000 even though the app listens on 8080 in production mode.  (Unrelated, but figured I'd mention it.)

So, the 4.0.2 auto-gen'd app works.

**Comment by dnewman-polar3d** [comment]
Here's a thought.  (I'm not a front end/angular person so bear with me.)

The scaffolded app has every `.html` file also referenced via require() in a js file.  They're templates for an angular component.  Fine.

Now, these HTML files not appearing for my app are not used in such a context.  E.g.,

    'use strict';
    
    export function routeConfig($urlRouterProvider, $locationProvider, $stateProvider) {
      'ngInject';
    
      $urlRouterProvider.otherwise('/');
    
      $locationProvider.html5Mode(true);
    
      $stateProvider.state('app', {
        abstract: true,
        views: {
          'navbar@': {
            templateUrl: 'app/layouts/navbar/navbar.html',
            controller: 'navbarCtrl',
            controllerAs: 'vm'
          },
          'plusButton@': {
           templateUrl: 'app/layouts/plusButton/plusButton.html',
            controller: 'plusButtonCtrl',
            controllerAs: 'vm'
          }
        }
      });
    }

So is the bundling actually requiring references to these `.html` files down the client `app/` and `components/` directory trees?

**Comment by Awk34** [comment]
4.x.x doesn't support using `templateUrl` for Angular templates. Templates are `require`d, which Webpack uses to bundle everything together (it basically inlines the raw HTML text). If you wanted to use `templateUrl`, you'd have to set up serving the templates yourself.

**Comment by dnewman-polar3d** [comment]
Yup.  Got it.

**Comment by dnewman-polar3d** [comment]
And thanks very much!  I hit COMMENT there too early.  Didn't mean to be so terse.
