### ISSUE TITLE
Preserving a folder on grunt build

### ISSUE THREAD

**Issue by rufogongora** [angular-fullstack/generator-angular-fullstack#2199]
So I'm moving my app to production, the only problem is that I have a custom "uploads" folder that goes into:

dist/client/uploads

After the first deployment to production it is a matter of just creating the folder and users can now upload files into it.

The problem is that I'm using the stock gruntfile.js, and after I run grunt build for the second time it gets rid of my dist/client/uploads folder, I don't really have much experience with Grunt so I was wondering if there's a way of not letting it delete that folders.

Here's my gruntfile for reference:

http://pastebin.com/JUQbPT1k

**Comment by elfouad** [comment]
Hi,

in line 758 you can see the task "clean:dist". This command deletes the dist folder. Jump to line 153  there you can change the pattern. Look at http://gruntjs.com/configuring-tasks#globbing-patterns . You can do something like  '<%= yeoman.dist %>/!(.git*|.openshift|Procfile|uploads)**' . That preserving the dist/uploads folder.

**Comment by Awk34** [comment]
The dist folder is not meant to have any sort of state like uploads. Those should be taken care of by another database process.
