### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by iamromeo** [angular-fullstack/generator-angular-fullstack#2204]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /stylint/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v6.5.0/bin/node" "/home/vagrant/.nvm/versions/node/v6.5.0/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! path /var/www/project/node_modules/escodegen/bin/esgenerate.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/var/www/project/node_modules/escodegen/bin/esgenerate.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/var/www/project/node_modules/escodegen/bin/esgenerate.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/project/npm-debug.log

Item | Version
----- | -----
generator-angular-fullstack | master
Node | 6.5
npm | 3.10.6
Operating System |  Ubuntu 12.04

**Comment by Awk34** [comment]
Looks like there was some issue installing your node dependencies. Try `rm -rf ./node_modules` and then re-installing them (`npm install`)

**Comment by Awk34** [comment]
Closed due to inactivity
