### ISSUE TITLE
Is the latest angular-fullstack-generator(v4.0.4) creating an angular 2 app instead of angular 1?

### ISSUE THREAD

**Issue by kaushik-evani** [angular-fullstack/generator-angular-fullstack#2210]
I used the latest angular-fullstack-generator - v4.0.4 to create an app, but the client looks a lot like angular 2. It has components instead of controllers, it has classes, constructors etc. New routes are creating components as well and not controlllers. Have you stopped angular 1 now? Is there any option that I can set to create the app in angular 1? I do not know angular 2 yet. Thanks!
 
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.4
Node | 6.5.0
npm | 3.10.3
Operating System | Ubuntu 16.04 
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS 
Router |  ui-router
Client Tests | Mocha
DB | None
Auth |  N
etc | etc

**Comment by amygdaloideum** [comment]
It's angular 1.5, where components are available: https://toddmotto.com/exploring-the-angular-1-5-component-method/

The classes and constructors are part of ES6!
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

**Comment by kaushik-evani** [comment]
Cheers @amygdaloideum ! That's helpful.

**Comment by Awk34** [comment]
@kaushik-evani yep, as @amygdaloideum said. The code *is* moving in a more Angular 2-like direction, but it's still all just Angular 1. Soon you'll get the option to make a hybrid ng1 / ng2 app.

**Comment by kaushik-evani** [comment]
@Awk34 Yeah, the option to choose between ng1 and ng2 would be great.
