### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by daniel7912** [angular-fullstack/generator-angular-fullstack#2212]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.4
Node | 5.3.0
npm | 3.3.12
Operating System | Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel / **TypeScript**
Markup | **HTML** / Pug
CSS | CSS / LESS / **SCSS** / Stylus
Router | ngRoute / **ui-router**
Client Tests | Jasmine / **Mocha**
DB | **MongoDB** / SQL
Auth | Y

I just ran `yo angular-fullstack` which worked OK. Then I ran `gulp serve`, and the page loaded with the following error in the console window:

`angular.js:13920 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at auth.service.ts:138`

This is causing the nav bar to display the logout button instead of login too, and I can access the profile page even though I haven't logged in.

**Comment by daniel7912** [comment]
Same problem on OS X with node v6.4.0 and npm v3.10.3

**Comment by Runaider** [comment]
Check if argument is defined before calling hasOwnProperty method. 
`var is = user && user.hasOwnProperty('role'); `should solve this error.

**Comment by yozzd** [comment]
i run into this problem too..
try change all `_User` into `User` in your `auth.service`

**Comment by daniel7912** [comment]
Confirmed working after @yozzd's solution.

**Comment by andrewt3000** [comment]
yozzd solution does get rid of the console error.  not sure if the authentication works though?
