### ISSUE TITLE
gulp build not compiling jade to dist

### ISSUE THREAD

**Issue by nedmac101** [angular-fullstack/generator-angular-fullstack#2215]
Trying to get a successful deploy to Heroku using a barebones project with the settings below. After running gulp build, there are no html files in dist/client/*.
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 3.8.6 |
| Node | v4.2.2 |
| npm | 3.8.6 |
| Operating System | OS X 10 |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | Pug |
| CSS | Sass |
| Router | ui-router |
| Client Tests | Mocha |
| DB | MongoDB |
| Auth | Y (FB, G+, Twitter) |

**Comment by Awk34** [comment]
We don't have a 3.8.6 version, so please check that again.

There will only ever be one HTML file in your dist folder; the `index.html` file. All the other HTML code is put into the JS bundles.

**Comment by RonAlmog** [comment]
obviously this is the npm version.
finding the generator version is not trivial. can you pls remind us?

**Comment by Awk34** [comment]
you can see the versions of your global npm modules with `npm list -g --depth=0`

**Comment by nedmac101** [comment]
You can close this.
