### ISSUE TITLE
New services issue "Not available"

### ISSUE THREAD

**Issue by nutanlade** [angular-fullstack/generator-angular-fullstack#2216]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 5.4.1
npm | 3.10.4
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute 
Client Tests | Jasmine
DB | MongoDB 
Auth | Y

I'm trying to add new service to my project using below command.

yo angular-fullstack:service communityService

When I start the application I'm getting below exception.

Error: [$injector:nomod] Module 'guwhaApp.communityService' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=guwhaApp.communityService

Below is my index.html from my project.

<script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/AdminLTE/dist/js/app.js"></script>
      <script src="bower_components/jquery-ui/jquery-ui.js"></script>
      <script src="bower_components/wysihtml5x/dist/wysihtml5x.min.js"></script>
      <script src="bower_components/wysihtml5x/dist/wysihtml5x-toolbar.min.js"></script>
      <script src="bower_components/rangy-1.3/uncompressed/rangy-core.js"></script>
      <script src="bower_components/rangy-1.3/uncompressed/rangy-cssclassapplier.js"></script>
      <script src="bower_components/rangy-1.3/uncompressed/rangy-highlighter.js"></script>
      <script src="bower_components/rangy-1.3/uncompressed/rangy-selectionsaverestore.js"></script>
      <script src="bower_components/rangy-1.3/uncompressed/rangy-serializer.js"></script>
      <script src="bower_components/rangy-1.3/uncompressed/rangy-textrange.js"></script>
      <script src="bower_components/handlebars/handlebars.js"></script>
      <script src="bower_components/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.min.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-route/angular-route.js"></script>
      <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/angular-socket-io/socket.js"></script>
      <script src="bower_components/angular-validation-match/dist/angular-validation-match.min.js"></script>
      <script src="bower_components/allmighty-autocomplete/script/autocomplete.js"></script>
      <script src="bower_components/ng-table/dist/ng-table.js"></script>
      <script src="bower_components/moment/moment.js"></script>
      <script src="bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
      
      <script src="socket.io-client/socket.io.js"></script>
    
    
      <script src="app/app.js"></script>
      
      <script src="app/admin/admin.module.js"></script>
      <script src="components/auth/auth.module.js"></script>
      <script src="components/util/util.module.js"></script>
      <script src="app/account/account.js"></script>
      <script src="app/account/login/login.controller.js"></script>
      <script src="app/account/signup/signup.controller.js"></script>
      <script src="app/admin/admin.controller.js"></script>
      <script src="app/admin/admin.router.js"></script>
      <script src="app/app.constant.js"></script>
      <script src="app/billservice/billservice.controller.js"></script>
      <script src="app/billservice/billservice.js"></script>
      <script src="app/dashboard/billpayments/billpayments.directive.js"></script>
      <script src="app/dashboard/communityprofile/communityprofile.directive.js"></script>
      <script src="app/dashboard/dashboard.controller.js"></script>
      <script src="app/dashboard/dashboard.js"></script>
      <script src="app/dashboard/financialaudits/financialaudits.directive.js"></script>
      <script src="app/dashboard/plugins/datepicker/dcalendar.picker.js"></script>
      <script src="app/dashboard/plugins/js/app.js"></script>
      <script src="app/dashboard/plugins/js/app.min.js"></script>
      <script src="app/dashboard/plugins/js/demo.js"></script>
      <script src="app/dashboard/plugins/js/pages/dashboard.js"></script>
      <script src="app/dashboard/plugins/js/pages/dashboard2.js"></script>
      <script src="app/dashboard/settings/settings.controller.js"></script>
      <script src="app/dashboard/settings/settings.js"></script>
      <script src="app/main/main.controller.js"></script>
      <script src="app/main/main.js"></script>
      <script src="components/auth/auth.service.js"></script>
      <script src="components/auth/interceptor.service.js"></script>
      <script src="components/auth/router.decorator.js"></script>
      <script src="components/auth/user.service.js"></script>
      <script src="components/community/communityService/communityService.service.js"></script>
      <script src="components/footer/footer.controller.js"></script>
      <script src="components/footer/footer.directive.js"></script>
      <script src="components/modal/modal.service.js"></script>
      <script src="components/mongoose-error/mongoose-error.directive.js"></script>
      <script src="components/navbar/navbar.controller.js"></script>
      <script src="components/navbar/navbar.directive.js"></script>
      <script src="components/oauth-buttons/oauth-buttons.controller.js"></script>
      <script src="components/oauth-buttons/oauth-buttons.directive.js"></script>
      <script src="components/socket/socket.service.js"></script>
      <script src="components/util/util.service.js"></script>

Can someone help me resolve this issue.

**Comment by Awk34** [comment]
What does your `communityService.service.js` look like? How was it created?

**Comment by nutanlade** [comment]
Below is what generated with generator.

'use strict';

function communityServiceService() {
	// AngularJS will instantiate a singleton by calling "new" on this function
}

angular.module('guwhaApp.communityService')
  .service('communityService', communityServiceService);

**Comment by Awk34** [comment]
change `angular.module('guwhaApp.communityService')` to `angular.module('guwhaApp.communityService', [])`
