### ISSUE TITLE
karma-chai-plugins missing from package.json => failing gulp test:client

### ISSUE THREAD

**Issue by erikrenberg** [angular-fullstack/generator-angular-fullstack#2219]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.4
Node | 6.5.0
npm | 3.10.7
Windows 10 
Client Tests

I generated a fresh app with  "mocha": false and I noticed that gulp test:client fails because of a missing npm package:

`{ Error: Cannot find module 'karma-chai-plugins'
`

And indeed that file is required by the generated karma.conf.js, but is not included in the likewise generated package.json. 

The template file for package.json seems to only include that package if mocha is enabled, which again I didn't select when running the generator.

_So either I made some strange combination of choices :), or karma-chai-plugins should be added by the generator not just when mocha is selected?_

PS. I also noticed that two require('karma-chai-plugins') seems to be added by the generator if "mocha":true. See lines 50 and 56 in templates/app/karma.conf.js. This doesn't seem right either. DS.

Here is a potentially relevant part of my .yo-rc.json: 
  ```
    "jasmine": true,
      "mocha": false,
      "should": false,
      "expect": false
```

**Comment by Awk34** [comment]
The `require` should be excluded if you use Jasmine for the front-end tests

**Comment by erikrenberg** [comment]
Thanks, right you are (I guess my issue subject was a bit misleading).

(Simply removing the first require of karma-chai-plugins (on line 50) in templates/app/karma.conf.js probably fixes the issue with the generator, since it is included for mocha on line 56 anyway).
