### ISSUE TITLE
yo angular-fullstack:route myroute generates component

### ISSUE THREAD

**Issue by okonon** [angular-fullstack/generator-angular-fullstack#2223]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1
Node | 6.4.0
npm | 3.10.3
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

When running `yo angular-fullstack:route event` generator command i am getting following files, which correspond to component rather then a route.
![screen shot 2016-09-11 at 8 54 05 pm](https://cloud.githubusercontent.com/assets/1832398/18421898/ee7a83ba-7861-11e6-9d5a-79246022cff1.png)

**Comment by Awk34** [comment]
Yes, it generates a component, as well as routing info to route to that component.
