### ISSUE TITLE
Login need to be Clicked twice. CSRF Token missing.

### ISSUE THREAD

**Issue by atodicebear** [angular-fullstack/generator-angular-fullstack#2224]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 3.7.5 |
| Node | 4.4.5 |
| npm | 3.9.6 |
| Operating System | Windows7 |
| yo | 1.8.4 |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | HTML |
| CSS | SCSS |
| Router | ui-router |
| Build Tool | Gulp |
| Client Tests | Mocha |
| DB | MsSQL |
| Auth | Y |
| etc | etc |

Hey,
If I start my Project fresh it is needed to be to "Login" twice because at the first time it Errors:
Error: CSRF Token missing.
Post 403 Auth Forbidden.
After that it is working allright.
How can I change that ? Because later in Production it is not "fine" if every Customer/User has to Login himself twice.

**Comment by atodicebear** [comment]
It seems it has more to do with the Browser?
Open Chrome->Click Login->Click second time because CSRF missing->now logout login again working fine by clicking once->
Open FireFox/INternetExplorer->Login has to be clicked twice again because CSRF missing-> after that working fine.

**Comment by Awk34** [comment]
@atodicebear I have never seen this. Have you modified the code at all?

**Comment by atodicebear** [comment]
Yeah I did but mostly only removing the Register Button and Function.
So that its only a normal Login Page.
Which code do you need to see for that?
client->app->account->login
**login.controller.js**
```
'use strict';

class LoginController {
  constructor(Auth, $state) {
    this.user = {};
    this.errors = {};
    this.submitted = false;

    this.Auth = Auth;
    this.$state = $state;
  }

  login(form) {
    this.submitted = true;

    if (form.$valid) {
      this.Auth.login({
          email: this.user.email,
          password: this.user.password
        })
        .then(() => {
          // Logged in, redirect to home
          this.$state.go('main');
        })
        .catch(err => {
          this.errors.other = err.message;
        });
    }
  }
}

angular.module('myApp')
  .controller('LoginController', LoginController);

```
**login.html**
**<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Login</h1>
      <p>Bitte Loge dich ein mit deinen LogIn Daten ein</p>
       Default account is <code>test@example.com</code> / <code>test</code></p>
      <p>Admin account is <code>admin@example.com</code> / <code>admin</code></p>
    </div>
    <div class="col-sm-12">
      <form class="form" name="form" ng-submit="vm.login(form)" novalidate>

        <div class="form-group">
          <label>Email</label>

          <input type="email" name="email" class="form-control" ng-model="vm.user.email" required>
        </div>

        <div class="form-group">
          <label>Password</label>

          <input type="password" name="password" class="form-control" ng-model="vm.user.password" required>
        </div>

        <div class="form-group has-error">
          <p class="help-block" ng-show="form.email.$error.required && form.password.$error.required && vm.submitted">
             Please enter your email and password.
          </p>
          <p class="help-block" ng-show="form.email.$error.email && vm.submitted">
             Please enter a valid email.
          </p>

          <p class="help-block">{{ vm.errors.other }}</p>
        </div>

        <div>
          <button class="btn btn-inverse btn-lg btn-login" type="submit">
            Login
          </button>
        
        </div>

      </form>
    </div>
  </div>
  <hr>
</div>**

So after gulp serve it opens localhost/9000 and shows this Page/login.html.
Anyone has first to Login to come to other Pages.

**Comment by atodicebear** [comment]
@Awk34  Something new on this ? :)

**Comment by Awk34** [comment]
I can't really investigate this any further since I can't reproduce it :/

**Comment by atodicebear** [comment]
Oh ok :/
Here is the Error output maybe this helps you a bit.
This comes after `gulp serve` -> window Opens with the LoginPage ->Clicking Login
```
Error: CSRF token missing
    at checkCsrf (C:\svn\EuconDictionary\node_modules\lusca\lib\csrf.js:89:18)
    at C:\svn\EuconDictionary\node_modules\lusca\index.js:48:21
    at hsts (C:\svn\EuconDictionary\node_modules\lusca\lib\hsts.js:25:9)
    at C:\svn\EuconDictionary\node_modules\lusca\index.js:48:21
    at xframe (C:\svn\EuconDictionary\node_modules\lusca\lib\xframes.js:12:9)
    at C:\svn\EuconDictionary\node_modules\lusca\index.js:48:21
    at xssProtection (C:\svn\EuconDictionary\node_modules\lusca\lib\xssprotectio
n.js:16:9)
    at C:\svn\EuconDictionary\node_modules\lusca\index.js:48:21
    at lusca (C:\svn\EuconDictionary\node_modules\lusca\index.js:53:9)
    at Layer.handle [as handle_request] (C:\svn\EuconDictionary\node_modules\exp
ress\lib\router\layer.js:95:5)
    at trim_prefix (C:\svn\EuconDictionary\node_modules\express\lib\router\index
.js:312:13)
    at C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\svn\EuconDictionary\node_modules\express\lib\
router\index.js:330:12)
    at next (C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:271
:10)
    at session (C:\svn\EuconDictionary\node_modules\express-session\index.js:438
:7)
    at Layer.handle [as handle_request] (C:\svn\EuconDictionary\node_modules\exp
ress\lib\router\layer.js:95:5)
Executing (default): SELECT TOP 1 [id], [sid], [data], [createdAt], [updatedAt]
FROM [Sessions] AS [Session] WHERE [Session].[sid] = N'rLhENt1rGGRCRrSg-qaZUB60E
MM7laZG';
Executing (default): INSERT INTO [Sessions] ([sid],[data],[createdAt],[updatedAt
]) OUTPUT INSERTED.* VALUES (N'rLhENt1rGGRCRrSg-qaZUB60EMM7laZG',N'{"cookie":{"o
riginalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"_csrfSecret":"2S
xopXWyaMQJvw=="}',N'2016-10-19 07:40:09.000',N'2016-10-19 07:40:09.000');
POST /auth/local 403 16.605 ms - -
```

And this as warning after clicking the Second time but this time Logging in Correct:
```
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at [object Object].Model.findAll (C:\svn\EuconDictionary\node_modules\sequel
ize\lib\model.js:1347:18)
    at [object Object].Model.findOne (C:\svn\EuconDictionary\node_modules\sequel
ize\lib\model.js:1519:34)
    at localAuthenticate (C:/svn/EuconDictionary/server/auth/local/passport.js:5
:8)
    at Strategy._verify (C:/svn/EuconDictionary/server/auth/local/passport.js:35
:12)
    at Strategy.authenticate (C:\svn\EuconDictionary\node_modules\passport-local
\lib\strategy.js:90:12)
    at attempt (C:\svn\EuconDictionary\node_modules\passport\lib\middleware\auth
enticate.js:348:16)
    at authenticate (C:\svn\EuconDictionary\node_modules\passport\lib\middleware
\authenticate.js:349:7)
    at C:/svn/EuconDictionary/server/auth/local/index.js:10:3
    at Layer.handle [as handle_request] (C:\svn\EuconDictionary\node_modules\exp
ress\lib\router\layer.js:95:5)
    at next (C:\svn\EuconDictionary\node_modules\express\lib\router\route.js:131
:13)
    at Route.dispatch (C:\svn\EuconDictionary\node_modules\express\lib\router\ro
ute.js:112:3)
    at Layer.handle [as handle_request] (C:\svn\EuconDictionary\node_modules\exp
ress\lib\router\layer.js:95:5)
    at C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\svn\EuconDictionary\node_modules\express\lib\
router\index.js:330:12)
    at next (C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:271
:10)
    at Function.handle (C:\svn\EuconDictionary\node_modules\express\lib\router\i
ndex.js:176:3)
    at router (C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:4
6:12)
From previous event:
    at Promise.then (C:\svn\EuconDictionary\node_modules\sequelize\lib\promise.j
s:21:17)
    at E4Store.get (C:\svn\EuconDictionary\node_modules\express-sequelize-sessio
n\lib\e4store.js:56:12)
    at session (C:\svn\EuconDictionary\node_modules\express-session\index.js:444
:11)
    at Layer.handle [as handle_request] (C:\svn\EuconDictionary\node_modules\exp
ress\lib\router\layer.js:95:5)
    at trim_prefix (C:\svn\EuconDictionary\node_modules\express\lib\router\index
.js:312:13)
    at C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\svn\EuconDictionary\node_modules\express\lib\
router\index.js:330:12)
    at next (C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:271
:10)
    at initialize (C:\svn\EuconDictionary\node_modules\passport\lib\middleware\i
nitialize.js:53:5)
    at Layer.handle [as handle_request] (C:\svn\EuconDictionary\node_modules\exp
ress\lib\router\layer.js:95:5)
    at trim_prefix (C:\svn\EuconDictionary\node_modules\express\lib\router\index
.js:312:13)
    at C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\svn\EuconDictionary\node_modules\express\lib\
router\index.js:330:12)
    at next (C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:271
:10)
    at cookieParser (C:\svn\EuconDictionary\node_modules\cookie-parser\index.js:
70:5)
    at Layer.handle [as handle_request] (C:\svn\EuconDictionary\node_modules\exp
ress\lib\router\layer.js:95:5)
    at trim_prefix (C:\svn\EuconDictionary\node_modules\express\lib\router\index
.js:312:13)
    at C:\svn\EuconDictionary\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\svn\EuconDictionary\node_modules\express\lib\
router\index.js:330:12)
```
Maybe this helps a bit. 
If not I would need to track it down myself by comparing with a Clean Install of the Fullstack@3.7.5

**Comment by minchomilev** [comment]
Hi, I have the same issue, because I moved my authentication to the front page and I don't have an CSRF token loaded. So the first time when I submit the login form I am receiving CSRF Token missing, and the second time I can send the request correctly. Do you have any Ideas how to load the CSRF token in the first page before first post request?

**Comment by asifahmed11** [comment]
Hi, I am facing the same issue as @minchomilev . I am loading the login page first. Any ideas on how to solve this?

**Comment by celcoder** [comment]
Hi, I'm facing exactly same issue as well.  First post request generates an CSRF token missing, however when second post request is made it works as intended.  Any solution to this yet?

**Comment by Awk34** [comment]
Is this only happening with SQL?

**Comment by celcoder** [comment]
it's configured with lusca, with express, and mongoose.  no passport.

**Comment by maximilianloy** [comment]
Same here

**Comment by MichaelMarkieta** [comment]
I also see the error using sequelize with PostgreSQL.

**Comment by jussolutions** [comment]
Guys,

Anyone got an answer on this yet, using 4.1.0 of the generator and this problem is still happening, have searched the net to the ends of the world but is still leaving me scratching my head. Hopefully people have some advice, found a potentially solution but it does not work which was to add the following to the middleware after lusca call:

    app.use( function( req, res, next ) {
        res.cookie('XSRF-TOKEN', res.locals._csrf );
        next();
    });

But still no joy.

**Comment by atodicebear** [comment]
Maybe someone by whom its working could Post his Code/Changes/Webbrowser+Version to Check where the Problem lies?

**Comment by atodicebear** [comment]
@jussolutions 
Did that solve the Problem?
Where did you Paste it?
```
  /**
   * Lusca - express server security
   * https://github.com/krakenjs/lusca
   */
  if (env !== 'test' && !process.env.SAUCE_USERNAME) {
    app.use(lusca({
      csrf: {
        angular: true
      },
      xframe: 'SAMEORIGIN',
      hsts: {
        maxAge: 31536000, //1 year, in seconds
        includeSubDomains: true,
        preload: true
      },
      xssProtection: true
    }));
   //Did not help
   /* app.use( function( req, res, next ) {
        res.cookie('XSRF-TOKEN', res.locals._csrf );
        next();
    });*/
  }
   //Did not help
   /* app.use( function( req, res, next ) {
        res.cookie('XSRF-TOKEN', res.locals._csrf );
        next();
    });*/
```

**Comment by radianz** [comment]
Any updates on this issue?

**Comment by jussolutions** [comment]
@atodicebear and @radianz 

Apologies for the delays. This needed to be added to a little demo site so for the time being I commented out the code to give me some time to look at it but have moved onto other parts of the site, this remains a priority for me.

If you want to temporarily get rid of this issue, in the express.js file comment out the following:

  /**
   * Lusca - express server security
   * https://github.com/krakenjs/lusca
   */
  if(env !== 'test' && !process.env.SAUCE_USERNAME) {

    // Turn off the lusca as we get CSRF Missing issues and Lusca is not supporting
    // angular properly at the moment
    //
  /*  app.use(lusca({
      csrf: {
        angular: true
      },
      xframe: 'SAMEORIGIN',
      hsts: {
        maxAge: 31536000, //1 year, in seconds
        includeSubDomains: true,
        preload: true
      },
      xssProtection: true
    }));*/
  }

Not the best answer I know but for the demo site it is fine. I need to go back and have a look at it.

Some solutions did recommend adding the following:

app.use( function( req, res, next ) {
    res.cookie('XSRF-TOKEN', res.locals._csrf );
    next();
});

But I found that this did not work either.

If anyone does have a solution could they share?

Many thanks

**Comment by rotatopoti** [comment]
Same issue. Anyone?

**Comment by radianz** [comment]
As far as I understand this might be an issue with Lusca: https://github.com/krakenjs/lusca/issues/95

**Comment by radianz** [comment]
I think a possible workaround for the moment (never tested) is to send an API call (that does nothing) as soon as the login page is loaded. This call should fail but it will exchange the token which will make all successive API calls work.

**Comment by smirciat** [comment]
@radianz idea worked just fine for me.  I just threw

**Comment by daraosn** [comment]
Hi everyone!

This is NOT a problem of `lusca`, I debugged the whole middleware chain and found the issue, it's on `server/config/express.js`

if you replace..
```
app.use(express.static(app.get('appPath')));
```
with..
```
app.get('/assets/*', express.static(app.get('appPath')));
```

It works, and the reason is because `index.html` was being served statically, this also explains why `/` is never logged by `morgan`, also this might be related to #2611 

**The fix described above is NOT correct though.** It causes many other issues related to webpack... I played a lot trying to find a nice solution, and a simple solution that worked for me was to rename `_index.html` to `app.template.html`.

I pushed a pull request with the proper fix here https://github.com/angular-fullstack/generator-angular-fullstack/pull/2613
