### ISSUE TITLE
Hide the webpack:// folder in dev tool

### ISSUE THREAD

**Issue by GuofuHuang** [angular-fullstack/generator-angular-fullstack#2225]
I got a question about this, I just don't want anybody to see the javascript code for the client. Is there any way to hide the webpack:// folder? It is OK to see bundle.js or app.js, just don't want others to be able to see actually javascript code in webpack:// folder.

Thanks

**Comment by Awk34** [comment]
Set `config.devtool` according to the [options for it](http://webpack.github.io/docs/configuration.html#devtool) for when `BUILD` is `true`. I believe the one you want is `'eval'`.
