### ISSUE TITLE
When logout clicked: Error: No template configuration specified for '$default@' 

### ISSUE THREAD

**Issue by Climax777** [angular-fullstack/generator-angular-fullstack#2226]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.4
Node | 5.6.0
npm | 3.10.7
Operating System | Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel
Markup | Pug
CSS | SCSS
Router | ui-router
Client Tests | Jasmine
DB | MongoDB
Auth | Y(local only)

`account.routes.js` has an empty template for the `logout` state. This causes the error when clicking on `logout`. Filling the template with anything fixes the problem. I'm not sure if this is the correct way to fix it.

**Comment by Climax777** [comment]
I updated angular-ui to 1.0.0 beta 1, which may cause the different behaviour.

**Comment by Awk34** [comment]
@Climax777 yes, I believe that this is causing the issue. I'm not seeing this in my own testing. Do you know of a solution that would work for both versions?

**Comment by Climax777** [comment]
What works for me is to add a placeholder instead of an empty string.
Anything works

**Comment by Awk34** [comment]
So `" "` would work?

**Comment by Climax777** [comment]
I believe so yes. As long as it's not empty. I haven't tried removing the
template field completely. I will give it a go and let you know.

**Comment by Climax777** [comment]
Take a look at this [stackoverflow] (http://stackoverflow.com/questions/19171655/ui-router-a-route-with-no-view-template)

**Comment by Awk34** [comment]
@Climax777 so the takeaway is to use an `onEnter` instead of a controller?

**Comment by Climax777** [comment]
@Awk34 I think so. But I've been playing around with it and it does indeed solve the issue. ButI can't get the referral system to work with this.

```
onEnter: function($state, Auth) {
        'ngInject';
        var referrer = $state.params.referrer /*not working*/ || $state.current.referrer /*not working*/ || _.get(this, 'name') /*this is supposed to be the "current" name*/ || 'main';
        Auth.logout();
        $state.go(referrer);
    }
```

**Comment by Awk34** [comment]
I'm closing this since there isn't a problem with the generator.

In future versions, where ui-router ^1.0.0 are used, this issue will be addressed

**Comment by diegodesouza** [comment]
I'm currently experiencing this issue, adding the template haven't fixed it for me. Any suggestion? 
I have asked a question on SO [here](http://stackoverflow.com/questions/41497884/angular-1-5-ui-router-1-0-0-beta-3-no-template-configuration-specified-for), with that has more details.
