### ISSUE TITLE
Login / Logout without redirect but custom callback

### ISSUE THREAD

**Issue by molerat619** [angular-fullstack/generator-angular-fullstack#2228]
Is there a way to use the authentication module of Angular-Fullstack for login / logout that does not redirect?

I would like to do other stuff in the callback instead. The redirect disturbs my process.

**Comment by Awk34** [comment]
Sure. Here's where redirection to the homepage is done for login: https://github.com/angular-fullstack/generator-angular-fullstack/blob/4.0.4/templates/app/client/app/account(auth)/login/login.controller.js#L51. Just put whatever other logic you want in there.

**Comment by molerat619** [comment]
Thank you. The most obvious thing just worked fine now. The last time I tried, I had problems - can't remember why. Anyway for future reference - we can just do

```
Auth.login({
    email: email,
    password: password
}).then(res => {  // res = user
    // your callback
}).catch(err => {
   // error handling
});
```
