### ISSUE TITLE
Using string templates for server/config/express.js

### ISSUE THREAD

**Issue by nstuyvesant** [angular-fullstack/generator-angular-fullstack#2239]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 4.0.5 |
| Node | 6.6.0 |
| npm | 3.10.8 |
| Operating System | MacOS 10.11.6 |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | Pug |
| CSS | SCSS |
| Router | ui-router |
| Client Tests | Mocha |
| DB | MongoDB |
| Auth | N |

Would it make sense to use ES6 string templates for server/config/express.js
change line 45 from

``` javascript
app.set('views', config.root + '/server/views');<% if(filters.html) { %>
```

to

``` javascript
app.set('views', `${config.root}/server/views`);<% if(filters.html) { %>
```

and line 105

``` javascript
proxy: 'localhost:' + config.port,
```

to

``` javascript
proxy: `localhost:${config.port}`,
```

This would remove the ESLint errors.

**Comment by Awk34** [comment]
Yes, it would. Feel free to make a PR.

**Comment by petrgazarov** [comment]
From what I could tell, a commit fixing this has already been merged, amirite?

**Comment by Awk34** [comment]
@petrgazarov seems so
