### ISSUE TITLE
font, background image url path not working from the app.css

### ISSUE THREAD

**Issue by biks152207** [angular-fullstack/generator-angular-fullstack#2242]
I have app.css generated by yo angular-fullstack with .css stylesheet.I am trying add background image from app.css "background: url("/assets/images/top-background.jpg") no-repeat;" however it doesn't show up in the frontend.This is even not working for fonts.The path doesn't seem to work.Any images or fonts loading from app.css are not working at all.Guys please help me

**Comment by kannach** [comment]
I have the same issue. However, when i serve using gulp seve:dist, all fonts adn images are working

**Comment by kannach** [comment]
I had to change the following line to make it work

-            publicPath: BUILD || DEV || E2E ? '/' : `http://localhost:${8080}/`,
+            publicPath: BUILD || DEV || E2E ? `http://localhost:${3000}/` : `http://localhost:${8080}/`,

**Comment by Gusi** [comment]
On windows, I had to change to:

publicPath: BUILD || DEV || E2E ? 'http://localhost:3000/' : 'http://localhost:${8080}/',

But I've only tried with gulp serve by now

**Comment by syzer** [comment]
👍

**Comment by syzer** [comment]
@kannach solution works for me!

**Comment by smeks** [comment]
I tested the change for publicPath: `http://localhost:${3000}/` and the fonts load properly on the local dev machine but any remote devices will not be able to load the page since all resources will try to load from localhost instead of the relative server path.

**Comment by ishmeetbindra** [comment]
@kannach solution is not working for me. Can anybody help me out?

**Comment by smirciat** [comment]
angular-fullstack/generator-angular-fullstack#2188 might be related

**Comment by Awk34** [comment]
^ closing, assuming the same solution will fix it

**Comment by MichaelJCole** [comment]
Hey, ran into this.  `npm start` runs `node server.js`.  So it seems to be designed to work with `gulp build`.  If you want to test during development, use `gulp serve`
