### ISSUE TITLE
Webpack watcher does not reload on small changes

### ISSUE THREAD

**Issue by kalcheat** [angular-fullstack/generator-angular-fullstack#2245]
I have kind of the same problem as https://github.com/angular-fullstack/generator-angular-fullstack/issues/2230 with the webpack watcher.

If i make a small change to a file, webpack does NOT notice it and does NOT reload the file (most of the times).

Only whenever i make a big change to a file it says `webpack: bundle is now INVALID.` and then it does a reload. 

Any suggestions how i can solve that very annoying problem?

**Comment by Awk34** [comment]
@kalcheat did you find a solution to this? Also, were you using WebStorm?
