### ISSUE TITLE
Modal unknown provider

### ISSUE THREAD

**Issue by hopeworkscamden** [angular-fullstack/generator-angular-fullstack#2247]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.4
Node | 5.4.0
npm | 3.10.7
Operating System |  cloud9

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests |  Mocha
DB | MongoDB
Auth | Y 

I cannot figure out why the Modal service injection is not working. I have added it as a dependency to the app.js and as well have added the dependency to the controller which I would like to use it from. Very desperate to get this working and appreciate anyone who can help me figure this out.

**app.js**
```
import _Auth from '../components/auth/auth.module';
import account from './account';
import admin from './admin';
import navbar from '../components/navbar/navbar.component';
import footer from '../components/footer/footer.component';
import main from './main/main.component';
import constants from './app.constants';
import util from '../components/util/util.module';
import socket from '../components/socket/socket.service';
import modal from '../components/modal/modal.service';

import './app.scss';

angular.module('camdenfirstApp', [ngCookies, ngResource, ngSanitize, 'btford.socket-io', uiRouter,
    uiBootstrap, modal, _Auth, account, admin, navbar, footer, main, constants, socket, util, 'leaflet-directive'
  ])
  .config(routeConfig)
  .run(function($rootScope, $location, Auth) {
    'ngInject';
    // Redirect to login if route requires auth and you're not logged in
```

**controller trying to use the Modal**
```
import angular from 'angular';
import uiRouter from 'angular-ui-router';
import routing from './main.routes';

export class MainController {
  $http;
  socket;
  Modal;
  awesomeThings = [];
  newThing = '';
  camden = {autoDiscover:true};
  locFound = false;

  /*@ngInject*/
  constructor($http, $scope, socket, Modal) {
    this.Modal = Modal;
    this.$http = $http;
    this.socket = socket;

    $scope.$on('$destroy', function() {
      socket.unsyncUpdates('thing');
    });
    
    $scope.delete = this.Modal.confirm.delete()('asdf');
    
    $scope.events = { // or just {} //all events
                        markers:{
                          enable: [ 'dragend' ]
                          //logic: 'emit'
                        }
                    }
    
    $scope.camden = {autoDiscover:true};
    
     $scope.$on('leafletDirectiveMap.locationfound', function(event){
        $scope.eventDetected = "ZoomStart";
         var instancePosition = {
                            lat: $scope.camden.lat,
                            lng: $scope.camden.lng,
                            focus: true,
                            message: "Drag to Flooding Instance",
                            draggable: true
                        };
          
       $scope.markers = {
                        instancePosition: angular.copy(instancePosition)
                      }
    });
    
    $scope.$on("leafletDirectiveMarker.dragend", function(event, args){
                $scope.camden.lat = args.model.lat;
                $scope.camden.lng = args.model.lng;
                $scope.markers.instancePosition.lat = args.model.lat;
                $scope.markers.instancePosition.lng = args.model.lng;
            });
    
  }

    
  $onInit() {
    this.$http.get('/api/things')
      .then(response => {
        this.awesomeThings = response.data;
        this.socket.syncUpdates('thing', this.awesomeThings);
      });
  }
  
  
  addThing() {
    if(this.newThing) {
      this.$http.post('/api/things', {
        name: this.newThing
      });
      this.newThing = '';
    }
  }

  deleteThing(thing) {
    this.$http.delete('/api/things/' + thing._id);
  }
}

export default angular.module('camdenfirstApp.main', [uiRouter])
  .config(routing)
  .component('main', {
    template: require('./main.html'),
    controller: MainController
  })
  .name;
```
EDIT: if you;d like to see the project itself you can find it here: https://camden-first-hopeworks.c9users.io:8081/

**Comment by Awk34** [comment]
Please surround your different code blocks with triple ticks (```). Your code is quite hard to read as-is.

**Comment by hopeworkscamden** [comment]
@Awk34 sorry about that, I have updated

**Comment by Awk34** [comment]
Can you provide a full stack trace as well?

**Comment by hopeworkscamden** [comment]
here is the full error that occurs

angular.js:13920ReferenceError: Modal is not defined
    at new MainController (https://camden-first-hopeworks.c9users.io:8081/app.bundle.js:1143:19)
    at Object.invoke (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:4845:20)
    at $controllerInit (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:10481:35)
    at nodeLinkFn (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:9390:35)
    at compositeLinkFn (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:8747:14)
    at publicLinkFn (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:8627:31)
    at Object.<anonymous> (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:38087:10)
    at https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:1374:19
    at invokeLinkFn (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:10061:10)
    at nodeLinkFn (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:9462:12)
    at compositeLinkFn (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:8747:14)
    at publicLinkFn (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:8627:31)
    at lazyCompilation (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:8971:26)
    at updateView (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:38005:24)
    at https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:37954:12
    at Scope.$broadcast (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:18132:29)
    at https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:37335:23
    at processQueue (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:16510:29)
    at https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:16526:28
    at Scope.$eval (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:17809:29)
    at Scope.$digest (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:17622:32)
    at Scope.$apply (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:17917:25)
    at bootstrapApply (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:1888:16)
    at Object.invoke (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:4845:20)
    at doBootstrap (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:1886:15)
    at Object.bootstrap (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:1906:13)
    at https://camden-first-hopeworks.c9users.io:8081/app.bundle.js:93:22
    at HTMLDocument.trigger (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:3334:8)
    at defaultHandlerWrapper (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:3624:12)
    at HTMLDocument.eventHandler (https://camden-first-hopeworks.c9users.io:8081/vendor.bundle.js:3612:10) <div ui-view="" class="ng-scope">

**Comment by thedewpoint** [comment]
Can you post what's in modal.service? You're expecting the import to provide you a module name but I'm not sure that's what you're importing

**Comment by hopeworkscamden** [comment]
```
'use strict';

import angular from 'angular';

export function Modal($rootScope, $uibModal) {
  /**
   * Opens a modal
   * @param  {Object} scope      - an object to be merged with modal's scope
   * @param  {String} modalClass - (optional) class(es) to be applied to the modal
   * @return {Object}            - the instance $uibModal.open() returns
   */
  function openModal(scope = {}, modalClass = 'modal-default') {
    var modalScope = $rootScope.$new();

    angular.extend(modalScope, scope);

    return $uibModal.open({
      template: require('./modal.html'),
      windowClass: modalClass,
      scope: modalScope
    });
  }

  // Public API here
  return {

    /* Confirmation modals */
    confirm: {

      /**
       * Create a function to open a delete confirmation modal (ex. ng-click='myModalFn(name, arg1, arg2...)')
       * @param  {Function} del - callback, ran when delete is confirmed
       * @return {Function}     - the function to open the modal (ex. myModalFn)
       */
      delete(del = angular.noop) {
        /**
         * Open a delete confirmation modal
         * @param  {String} name   - name or info to show on modal
         * @param  {All}           - any additional args are passed straight to del callback
         */
        return function() {
          var args = Array.prototype.slice.call(arguments);
          var name = args.shift();
          var deleteModal;

          deleteModal = openModal({
            modal: {
              dismissable: true,
              title: 'Confirm Delete',
              html: '<p>Are you sure you want to delete <strong>' + name + '</strong> ?</p>',
              buttons: [{
                classes: 'btn-danger',
                text: 'Delete',
                click(e) {
                  deleteModal.close(e);
                }
              }, {
                classes: 'btn-default',
                text: 'Cancel',
                click(e) {
                  deleteModal.dismiss(e);
                }
              }]
            }
          }, 'modal-danger');

          deleteModal.result.then(function(event) {
            del.apply(event, args);
          });
        };
      }
    }
  };
}

export default angular.module('workspaceApp')
  .factory('Modal', Modal)
  .name;
```

**Comment by Azayzel** [comment]
Your specific issue seems to be case. In your app.js you're importing with lowercase 'm' but in your controller your using it as 'M'. Try fixing it to a capital 'M' when importing and in your injection.

**Comment by Azayzel** [comment]
Ive created a PR that fixes this issue. [#2254](https://github.com/angular-fullstack/generator-angular-fullstack/pull/2254)

The problem lies at the export of the factory. Change
```
export default angular.module('workspaceApp')
  .factory('Modal', Modal)
  .name;
```
to
```
export default angular.module('workspaceApp.Modal')
  .factory('Modal', Modal)
  .name;
```

**Comment by Azayzel** [comment]
I have to fix the PR I submitted. That'll be sent in tonight.

**Comment by hopeworkscamden** [comment]
Thanks @Azayzel ! I really appreciate it! Got my first modal to pop up today using the Modal service. Next stop is injecting the controller scope i'm calling the modal from into the modal itself.

**Comment by zaphinath** [comment]
I'm seeing the same issue - angular.js:14525 Error: [$injector:strictdi] Modal is not using explicit annotation and cannot be invoked in strict mode.

Any solution?

**Comment by thedewpoint** [comment]
Usually that happens when you forget an nginject annotation

On Apr 23, 2017 11:15 PM, "Derek Carr" <notifications@github.com> wrote:

I'm seeing the same issue - angular.js:14525 Error: [$injector:strictdi]
Modal is not using explicit annotation and cannot be invoked in strict mode.

Any solution?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/angular-fullstack/generator-angular-fullstack/issues/2247#issuecomment-296515310>,
or mute the thread

**Comment by zaphinath** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2203 Fixed the issue.
