### ISSUE TITLE
How to add a third-party lib without using Webpack (import or require syntax)

### ISSUE THREAD

**Issue by amirmog** [angular-fullstack/generator-angular-fullstack#2250]
If a third-party lib is not supported by npm, bower, etc.
How do you include its source in the index.html ?

ie.
<script type="text/javascript" src="/assets/external-assets/scripts/ngmap/markers.js"></script>

Every time 'gulp serve' command is run, anything that is added to the index.html would be reset.

Thanks.

**Comment by Awk34** [comment]
@amirmog There's a `_index.html` template that's used.

You can also add a script in say, the `client/assets/` folder, and then `import` it.

**Comment by amirmog** [comment]
@Awk34 Thank you, the _index.htnk works great however, I noticed that the _index.htnk template is only set to be used in TEST mode, is this correct and if so how would you approach this in production mode?
Thanks.
