### ISSUE TITLE
Consultation: split the app?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#2255]
Question to the experts here: I'm considering splitting our app to 2: one for the client facing app, one for the back-office admin app, using only the mongodb database as a common point.
the app currently use ver 3.7.5 (yea, kind of old school)
The main reasons for this:
1. security. we don't want people to be able to hack into our backend or even see the menus, api routes or js code.
2. different theme, all different ui.
3. one dev is working on client facing app, one on the admin. separation will decouple the efforts and will reduce their dependency on each other.
My questions to you:
1. is this possible? good practice? recommended under the above scenario?
2. do you anticipate any problems or gotchas? things to pay attention?

Thanks everybody.

**Comment by Awk34** [comment]
One thing that I do is use Webpack's code splitting to split all the client code for the admin section into it's own bundle. That way regular viewers never need to download that code.

What you're talking about is a little more involved. You might want to go so far as to even create two completely separate applications, maybe sharing some client component code, and protecting the other application behind an auth wall.
