### ISSUE TITLE
AngularJS 2 and Typescript support

### ISSUE THREAD

**Issue by jariwbh** [angular-fullstack/generator-angular-fullstack#2258]
How do we migrate fullstack code to AngularJS 2 & Typescript client ?

**Comment by khwerhahn** [comment]
I have tried the angular cli over the weekend. It would be nice if we could use that as the angular team will support it...

**Comment by Awk34** [comment]
You can track Angular 2 support at #1869. Once it is possible to create a hybrid ng1/ng2 app with the generator, you will be able to see how to convert your components/services piece-by-piece.
