### ISSUE TITLE
moving to prod!

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2261]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 6.6.0
npm | 3.10.3
Operating System | Ubuntu 16.04 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS 
Router |  ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
etc | etc

Trying to push my project to production.
not sure what the grunt command is to produce the server version.
my best guess is 'grunt build'.
this produces a dist folder with client and server folders in it, and a package.json.
i'm copying all this to my ubuntu server on digital ocean.
should i run npm install? i read [here](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1641) that i should not. but i don't see the packages anywhere else.
so i just cd to my server folder, and run 
node index.js
is that the right command?
i get an error:

Error: Cannot find module 'babel-runtime/helpers/interop-require-default'....

Any idea how to take it from here? 
Thanks.

**Comment by Awk34** [comment]
For a production build, you should run `npm install --production`. This will exclude devDependencies.

**Comment by AmirGilboa** [comment]
makes sense. thanks!
