### ISSUE TITLE
redundant files in index.html, in dist folder

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2262]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.3
Node | 6.2.0
npm | 3.9.2
Operating System | Windows 10 
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS
Router | ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
etc | etc

running 'grunt build' to build my project in order to deploy to production.
looking at dist/client/index.html, i see this:

   <script src="app/vendor.e3eb5c5b.js"></script>
         
    
      <script src="app/app.81b3a27d.js"></script>
      
      <script src="app/admin/admin.module.js"></script>
      <script src="components/auth/auth.module.js"></script>
      <script src="components/util/util.module.js"></script>
      <script src="app/account/settings/settings.controller.js"></script>
      <script src="app/account/signup/init.controller.js"></script>
      <script src="app/account/signup/signup.controller.js"></script>
      <script src="app/account/signup/userOnboard.controller.js"></script>

i understand files like app/vendor.e3eb5c5b.js (and they exist).
but the folder 'account' and all the controllers in it, just don't exist. they are compressed into app.81b3a27d.js, so why do i see them in my index.html? of course they will not be found.
maybe i should manually remove them?

same thing happens with css files. here is what i see in index.html (in dist folder!)

      <link rel="stylesheet" href="app/app.a17744da.css">
      
      <link rel="stylesheet" href="app/styles/myapp.css">
      <link rel="stylesheet" href="app/styles/upload.css">
      
    

again, app.a17744da.css contains all the css needed.
myapp.css should not be there, and i don't even have the 'styles' folder in dist.

what am i doing wrong?
Thank you.

**Comment by Awk34** [comment]
Please see #370

**Comment by AmirGilboa** [comment]
thanks.
so he says there: "Make sure that your source HTML (e.g. index.html) does not mix linefeed styles (unix/windows)". great.  But how do i know which one i have?  i use sublime 3 on windows. 
Thank you.

**Comment by Awk34** [comment]
You can search around the web for how to see if you are mixing them. I use the `dos2unix` program to convert CRLF to LF endings.

**Comment by AmirGilboa** [comment]
cool. than you.
