### ISSUE TITLE
handling angular-fullstack Static files in IISnode

### ISSUE THREAD

**Issue by MorizelHodges** [angular-fullstack/generator-angular-fullstack#2263]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 6.2.2
npm | 3.9.5
Operating System | Windows Server 2008 R2
etc | etc

Item | Answer
----- | -----
Transpiler | **Babel** / TypeScript
Markup | **HTML** / Pug
**CSS** | CSS / LESS / SCSS / Stylus
Router | n**gRoute** / ui-router
Client Tests | Jasmine / **Mocha**
DB | **MongoDB** / SQL
Auth | **Y** / N
etc | etc

My angular-fullstack app launches with iisnode, but the static files are being processed by native iis instead of iisnode which results in a blank html page being displayed.

**Comment by Azayzel** [comment]
Use the web.config in the [docs](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/docs/Examples/IIS.md)

/docs/Examples/IIS.md

Basically you want to tell IIS to shut up and color and let iisnode do the work.

**Comment by Awk34** [comment]
We don't officially support anything other than Node.js
