### ISSUE TITLE
only the default application is running and user created components and controllers not working in angular-fullstack

### ISSUE THREAD

**Issue by sambath11** [angular-fullstack/generator-angular-fullstack#2266]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | x.x.x |
| Node | 6.6.0 |
| npm | 3.10.3 |
| Operating System | Ubuntu 16.04 |
| etc | etc |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | HTML |
| CSS | SCSS |
| Router | ui-router |
| Client Tests | Jasmine / Mocha |
| DB | MongoDB |
| Auth | Y |
| etc | etc |

**Comment by Awk34** [comment]
please fill out `generator-angular-fullstack	x.x.x` and provide some details

**Comment by Awk34** [comment]
Closed due to inactivity
