### ISSUE TITLE
PUT/:id run forever

### ISSUE THREAD

**Issue by barata0** [angular-fullstack/generator-angular-fullstack#2276]
| Item | Version |
| --- | --- |
| generator-angular-fullstack | 3.10.8 |
| Node | 4.4.7 |
| npm | 3.10.8 |
| Operating System | Fedora 22 |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | HTML |
| CSS | LESS |
| Router | ui-router |
| Client Tests | Mocha |
| DB | MongoDB |
| Auth | Y |

After initializing the app with _yo angular-fullstack_ 

Find any inexisting id for a thing. e.g: **57f016222b63c46b76bf9980**

So 

```

GET localhost:3000/api/things/57f016222b63c46b76bf9980

returns 404 not found!

```

When trying to put an thing with this ID:

e.g:

```

PUT localhost:3000/api/things/57f016222b63c46b76bf9980

body: {"name": "hello"}

```

The item is created on the database but HTML get no response at all (browser waiting forever...)

To fix I added a **handleEntityNotFound** on the file:_server/api/thing/thing.controller.js_ (line 100) on the upsert method

```
export function upsert(req, res) {
  if(req.body._id) {
    delete req.body._id;
  }
  return VizField.findOneAndUpdate({_id: req.params.id}, req.body, {upsert: false, setDefaultsOnInsert: true, runValidators: true}).exec()
    .then(handleEntityNotFound(res))    // <-- NEW CODE HERE
    .then(respondWithResult(res))
    .catch(handleError(res));
}
```

But as the PUT method returns the old instance, I get a 404 response with this approach which is ugly and may let the client confused.

To get the newly created instance you must pass the option _{new: true}_  as param on the findByIdAndUpdate method.

But this way the integration spec is broken because it expects the **OLD** instance after **PUT** and not the newly **UPDATED** instance

**Comment by barata0** [comment]
Another points to consider are:

1. When creating a new instance on PUT http status must return 201.
2. The socket does not notify clients through the findByIdAndUpdate method.

**Comment by Awk34** [comment]
We don't have a 1.8.5, so please check that.

**Comment by Awk34** [comment]
According to [the RFC](https://tools.ietf.org/html/rfc2616#section-9.6), you're correct about the response codes.

**Comment by barata0** [comment]
The version was wrong (thanks).

I'm not sure but **PUT** shouldn't also **replace the entire entity** and not only the fields present on the request body. 

And is there a thread or discussion explainig why does PUT **returns the old instance** instead the new one?

Ps. I don't know if here is the most appropriate place to discuss this. Please let me know if there is another place.

Thanks for this great job.

**Comment by barata0** [comment]
Sorry. I didnt want to close the request. just the window....

**Comment by Awk34** [comment]
A PUT **should** fully replace the stored entity. That's how the RFC defines it.

As for what is returned by a PUT, I don't believe there's any spec on that. There could probably be a case for either, or maybe even sending both old and new.

**Comment by tommybananas** [comment]
I think returning the new object by default would be the best choice.

**Comment by barata0** [comment]
Closing due inactivity
