### ISSUE TITLE
sign up without password was successful

### ISSUE THREAD

**Issue by kannach** [angular-fullstack/generator-angular-fullstack#2278]
I tried to signup just with a username. Instead of getting failure, the signup was successful, as a result the password field and salt field in the database are missing. Subsequently, logging in with the signed up user never returns.

**Comment by Awk34** [comment]
Which settings did you scaffold with? Which generator version?

**Comment by AmirGilboa** [comment]
this should not happen. (and does not happen in the default installation)
make sure in user model that the password looks something like this:
password: {type: String, minlength: [6, 'Password must be 6 characters or more.'], maxlength: 100},

give more details if you still need help.
