### ISSUE TITLE
findOneAndUpdate return by default original document

### ISSUE THREAD

**Issue by enrychemp** [angular-fullstack/generator-angular-fullstack#2284]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 6.7.0
npm | 3.10.3
Operating System | OS X 10.12

Item | Answer
----- | -----
Transpiler | Babel 
Markup |/ Pug
CSS | SCSS 
Router | ui-router
Client Tests | Jasmine
DB | MongoDB 3.2.7
Auth | Y

report link
https://github.com/Automattic/mongoose/issues/2262

and mongodb 
https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/

```
export function upsert(req, res) {
  if(req.body._id) {
    delete req.body._id;
  }
  return Thing.findOneAndUpdate(req.params.id, req.body, {upsert: true, setDefaultsOnInsert: true, runValidators: true}).exec()

    .then(respondWithResult(res))
    .catch(handleError(res));
}

```
modified return saved document
```
export function upsert(req, res) {
  if(req.body._id) {
    delete req.body._id;
  }
  return Thing.findOneAndUpdate(req.params.id, req.body, {new: true, upsert: true, setDefaultsOnInsert: true, runValidators: true}).exec()

    .then(respondWithResult(res))
    .catch(handleError(res));
}

```

**Comment by Awk34** [comment]
Feel free to submit a PR for these sorts of things

**Comment by thomsa** [comment]
👍  +1
