### ISSUE TITLE
Generate Route Problem

### ISSUE THREAD

**Issue by tguelcan** [angular-fullstack/generator-angular-fullstack#2285]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.3
Node | 6.3.1
npm | 3.10.3
Operating System | OS X 10 

Use:
Babel, Pug, SCSS, ui-router, Jasmine, MongoDB, Auth

> $ yo angular-fullstack:route overview

? What module name would you like to use? myApp.overview
? Where would you like to create this route? client/app/account
? What will the url of your route be? /overview

   > create client/app/account/overview/overview.routes.js
   > create client/app/account/overview/overview.component.js
   > create client/app/account/overview/overview.component.spec.js
   > create client/app/account/overview/overview.scss`

It generate a component but not a view.
Whats wrong?

**Comment by Awk34** [comment]
Nothing's wrong. Everything for the view is contained within an Angular 1.5 component.

Just make sure to include the new Angular module as a dependency of some parent Angular module.

**Comment by tguelcan** [comment]
And the Documentations are right?

**Comment by Awk34** [comment]
@tguelcan let me check

**Comment by Awk34** [comment]
@tguelcan I've updated the route docs: http://angular-fullstack.github.io/generator-angular-fullstack/Generators/route.html
