### ISSUE TITLE
Facebook auth, then user/password, possible?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2286]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.3

Item | Answer
----- | -----
Transpiler | Babel 
DB | MongoDB 
Auth | Y 
etc | etc

With Facebook authentication, only email and name are created in the db, and then the user is logged in. what if she now want/try to login with email and password? Is this supposed to be possible?
she cannot register, because her email already exists. maybe "reset password"?
Just wondering what are the assumptions, how it supposed/planned to work, and what are the best practices.

**Comment by Awk34** [comment]
The generator is not set up to support a single user using different types of login out-of-the-box. It's something that has been brought up before, but will probably require quite a bit of work to get fully implemented.

**Comment by AmirGilboa** [comment]
Ok, fair enough.
Did anybody take this any further and can share some ideas or code?

So if i get this correctly, if the user chose Facebook as her way to login, she is not supposed to attempt to login in any other way, like twitter or just user/password. right?
it that case, i think we have to communicate that somehow. i will play with this.
thanks.

**Comment by Awk34** [comment]
I have a basic setup here: https://github.com/Awk34/aksite/blob/master/server/auth/github/passport.js#L16-L27. It basically looks to see if a user is already logged in when trying to authenticate with a new OAuth type.
