### ISSUE TITLE
yarn install

### ISSUE THREAD

**Issue by jensim** [angular-fullstack/generator-angular-fullstack#2291]
yarn install after app generated, if yarn is available
```yarn``` is much faster than ```npm i```
workaround with ```--skip-install``` && ```yarn``` afterwards is a bit tedious.

**Comment by Awk34** [comment]
```bash
$ yo angular-fullstack --skip-install && yarn
```
While it might seem tedious for you, I use the `--skip-install` almost every day, since I am constantly re-running the generator to test things out. I'm not sure about looking for `yarn` in the generator itself yet; it's still a brand-new tool.`

**Comment by benmarten** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/pull/2537

**Comment by benmarten** [comment]
#2537
