### ISSUE TITLE
Error while generating project seed : node-gyp rebuild

### ISSUE THREAD

**Issue by GHA0991** [angular-fullstack/generator-angular-fullstack#2293]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 4.4.5
npm | 3.5.3
Operating System |  Windows 7
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | LESS
Router | ui-router
Client Tests | Jasmine
DB | MongoDB / SQL
Auth | Y 
etc | etc
========================
the above are my system spec.

I was generating the project tree then i had this error:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Ghassen\\
ppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ghassen\Desktop\mean\npm-debug.log

could someone help me ?

**Comment by Awk34** [comment]
Follow the instructions for `node-gyp`: https://github.com/nodejs/node-gyp#installation
