### ISSUE TITLE
Generated directive won't work in prod

### ISSUE THREAD

**Issue by dhaazen** [angular-fullstack/generator-angular-fullstack#2294]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 4.4.5
npm | 3.10.5
Operating System | OS X
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS
Router | ngRoute
Client Tests | Mocha
DB | SQL
Auth | N
etc | etc

When generating a directive and including html the generated code uses:

```
      templateUrl: 'app/myDirective/myDirective.html',
```

which when bundled breaks because the path doesn't exist.

This can be resolved by simply changing the line to

```
      template: require('./myDirective.html'), 
```

**Comment by dhaazen** [comment]
Hey @Awk34, Did you want me to try to go through the process of just submitting these as pull requests for small changes like this or..? Just because I was about to open another small bug for the generated directive.spec which would be only a couple liner. But I'm not sure how much red tape is involved in trying to contribute to the project. I looked through the guidelines and it seemed pretty strict on making commits. Let me know. Thanks.

**Comment by Awk34** [comment]
@dhaazen go ahead. This would be a PR against https://github.com/DaftMonk/generator-ng-component though.

The main thing is try to conform to our commit message guidelines, like so:

```
fix(directive): fix template definition for webpack
```

We enforce this because it allows us to automatically extract a lot of data from these messages

**Comment by dhaazen** [comment]
Thanks @Awk34 I looked into it and in the generator-ng-component directive has an if else checking for 'filters.webpack' 

```
      <%_ if(filters.webpack) { -%>
      template: require('./<%=name%>.<%=templateExt%>'),
      <%_ } else { -%>
      templateUrl: '<%= htmlUrl %>',
      <%_ } -%>
```

I can see the filters are added when an new project is created using the generator-angular-fullstack does anyone else use generator-ng-component that wouldn't be using webpack? because if it needs to have that use case then we would need to set the 'filters.webpack' variable in this project. Otherwise remove the if else and stick with the webpack version of the template. Let me know which way you'd like me to go with it.

**Comment by Awk34** [comment]
I'm not sure if anyone else uses that repo anymore. Anyhow, once the project is fully moved over to Angular 2, We'll have another subgenerator specific to Angular 2 components/etc.

If you look [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/src/generators/app/index.js#L419), you'll see that we're adding the `webpack` filter to the `ng-component` config, so I wonder what's getting messed up here...

**Comment by dhaazen** [comment]
Hey, Figured it out. It didn't account for filters being an array it expected it to be an object. Changed it the:

```
 <%_ if(filters.webpack) { -%>
```

to 

```
 <%_ if(filters.indexOf('webpack') > -1) { -%>
```

And now it works fine. I submitted a pull request to the other project.

Cheers,
Dale

**Comment by Awk34** [comment]
https://github.com/DaftMonk/generator-ng-component/releases/tag/1.0.4

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/pull/2300
