### ISSUE TITLE
command line generator wizard to generates a new API endpoint based on user roles to grant access

### ISSUE THREAD

**Issue by amirmog** [angular-fullstack/generator-angular-fullstack#2295]
yo angular-fullstack:endpoint [options] <name>

When using the command line generator wizard to generates a new API endpoint.
Would it possible to add the type of user roles (ie. 'admin', 'collaborator', 'guest', etc.) that should be able to access each verb of the endpoints via the command line generator?

If not, how can this be done in the code?

Thanks.

**Comment by Awk34** [comment]
`server/auth/auth.service.js` has this function:

```js
/**
 * Checks if the user role meets the minimum requirements of the route
 */
export function hasRole(roleRequired) {
  if (!roleRequired) {
    throw new Error('Required role needs to be set');
  }

  return compose()
    .use(isAuthenticated())
    .use(function meetsRequirements(req, res, next) {
      if (config.userRoles.indexOf(req.user.role) >= config.userRoles.indexOf(roleRequired)) {
        return next();
      } else {
        return res.status(403).send('Forbidden');
      }
    });
}
```

In `server/api/endpoint/index.js`, use it as such:

```js
router.get('/', auth.hasRole('admin'), controller.index);
```

In this code example, any user with the role `admin` or higher can access the API route. I don't think specifying this sort of thing in the generator would be worthwhile.

**Comment by AmirGilboa** [comment]
i agree. i prefer to do this manually, as sometimes different methods have different restrictions, within the same file. (i allow all registered users to read stuff, but only admins to write...). so you can't automate everything.

**Comment by amirmog** [comment]
@Awk34 Thanks you very much, that's great.
@AmirGilboa That makes sense. Thanks.

**Comment by amirmog** [comment]
@Awk34 
Would it be possible to pass more than one role?
ie.
```
router.get('/', auth.hasRoles(['admin', 'collaborator']), controller.index);
```

**Comment by AmirGilboa** [comment]
The hierarchy, and this is very important, and not really documented, is the order in which the roles are written in app.constant.js.  for examples:

.constant('appConfig', {userRoles:['guest','user', 'cook','chef', 'admin']})

cook is higher then user. chef is higher then cook. admin is higher then chef.   the order in the list is important!
knowing that can save you some trouble...

**Comment by amirmog** [comment]
The hierarchy, sounds super cool, however, could you please tell me how to manage a scenario where for example an app would require two completely independent role access areas as such:

An application has two parts, one part of the app has to do with users with role 'cook' and  'chef' and another part of the app would require access to routes related to users with roles: 'athlete' and 'trainer'. 

Neither roles 'athlete' nor 'trainer' should have access to any of the routes related to roles  'cook'  AND 'chef'. 

So now if we have to specify the hierarchy this way:
```
.constant('appConfig', {userRoles:['guest','user', 'cook','chef', 'athlete', 'trainer', 'admin']}) 
```
Then the 'athlete' AND 'trainer' both would have access to routes that are for 'cook' and 'chef' roles.

and on a more common level, there might be cases where simply even the 'chef' should not have access to 'cook' routes...

How would you restrict the 'chef' from accessing 'cook' routes and how would you restrict 'athlete' AND/OR 'trainer' from accessing 'cook' AND/OR 'chef' ?

Currently concept of roles is not well documented here; so please guide me to understand this better as this may help others with the same tyope of questions. Roles are quite vital in architecting applications and having a concrete understanding of how things work, can be beneficial.


Thanks alot.
Amiro

@Awk34 @AmirGilboa @gonzaloruizdevilla @passy @rahim
