### ISSUE TITLE
Cannot see changes after save, does not compile

### ISSUE THREAD

**Issue by nadien** [angular-fullstack/generator-angular-fullstack#2297]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.5
Node | 6.4.0
npm | 3.10.3
Manjaro 16.08 Ellada

Item | Answer
----- | -----
Transpiler | Babel / TypeScript

> with gulp serve

Hi, when i save changes, gulp compiles and shows it in console, but only in some files, like app.ts.

Also, when i make a change in _index.html or main.html, even the controller of each, *.ts, i cannot see any change in the browser and console.
I supose it can be nodemon or something. What can i do?. Regards

**Comment by Awk34** [comment]
We never had a 1.8.5 version. Please check that again.

Are you saying you're running `gulp serve` and your changes aren't automatically reflected in the browser?

**Comment by nadien** [comment]
@Awk34 
Sorry for the mistake, is version 4.0.5

Yes, only reflected with server files. If i add something to file in client side and save changes, nothing shows in console. When i save changes in server side «webpack: bundle is now VALID.» appears in the console.

**Comment by Awk34** [comment]
Livereload will only trigger if the client files you're editing are `require`d somewhere in your application. Make sure any files you want to use are `require`d/`import`ed somewhere below the dependency tree starting from `client/app/app.ts`

**Comment by nadien** [comment]
Oohh!, that works. now works with index, i don't why.

Sorry for noob question, i appreciate your time, good day.
