### ISSUE TITLE
scss for directives, components not in app

### ISSUE THREAD

**Issue by bingomanatee** [angular-fullstack/generator-angular-fullstack#2298]
your injection model for scss only moves scss for components in the app folder; it doesn't cover scss in components in the clients/ folder or directives, anywhere.

**Comment by bingomanatee** [comment]
looks like, can be fixed with     
change to `gulpfile.babel.js`

 35:
       styles: [\`${clientPath}/{app,components,directives}/**/*.scss\`],

**Comment by Awk34** [comment]
The generator never creates any such `client/directives` folder by default. You must have create that on your own. As such, you can expect this kind of behavior.
