### ISSUE TITLE
Deployment documentation

### ISSUE THREAD

**Issue by bingomanatee** [angular-fullstack/generator-angular-fullstack#2303]
Are you ever going to finish your deployment documentation page?

**Comment by Awk34** [comment]
Yes. If you look at the commit log, my latest commit for the docs was yesterday.

**Comment by fariasfrancisco** [comment]
I can't see anything but STUB in the documentation for deployment. Where can I learn how to deploy it?

**Comment by Awk34** [comment]
@fariasfrancisco I added a quick example of a manual deploy [here](http://angular-fullstack.github.io/generator-angular-fullstack/Deployment/title.html). This, of course, is not the suggested way of deploying, but if you're just learning or prototyping, it should get the job done.

**Comment by fariasfrancisco** [comment]
Thanks a lot man! That will get me started!
