### ISSUE TITLE
[ts] cannot find name 'require'

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2321]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 6.9.1
npm | 3.10.8
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS
Router | ui-router
DB | MongoDB
Auth | Y
etc | etc

Starting a new project with 4.1.0, working with ms code and Typescript.
I get red squiggly lines on some keywords, not all.
for example in index.ts:
[ts] cannot find name 'require'

in main.component.spec.ts:
all these keywords:  describe, beforeEach, it, expect... all marked red. 

Any idea?

**Comment by Awk34** [comment]
Your editor just thinks that those are undefined, while those aren't. I don't know what editor you're using, but you should be able to tell it that you're using CommonJS (`require`) and Mocha/Jasmine (`describe`, etc)

**Comment by AmirGilboa** [comment]
ok, cool. i will find out about those. And yes, it's only the editor, as the website loads correctly.
thanks!
