### ISSUE TITLE
Are components replacing controllers?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2322]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 6.9.1
npm | 3.10.8
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS
Router | ui-router
DB | MongoDB
Auth | Y
etc | etc

in the new 4.1.0 version, i can see that the old (3.7.x) convention of "route" that was a controller, view, route and css, has been changed and instead of the controller there is now a component.
I read a bit about components, and they are a simplified version of directive. 
so how can it replace a controller?
can i still use controllers? (create manually)
What's the motivation behind this change? any link for further reading would be great.

**Comment by Awk34** [comment]
Yes, in the future the main two front-end modules will be Components and Services. This is a basic component using a controller & template:

```js
class thingController {
  constructor() {
    this.name = 'Thing';
  }
}
```

```html
<div ng-controller="thingController as $ctrl" class="thing">{{$ctrl.name}}</div>
```

A directive is basically a more reusable form of this, packaged together:

```html
<thing>{{$ctrl.name}}</thing>
```

And a component is just a certain type of directive, with some directive settings pre-filled. It looks the same:

```html
<thing>{{$ctrl.name}}</thing>
```

You can read more about this stuff elsewhere.

**Comment by AmirGilboa** [comment]
Thanks for the detailed answer!
But can i still use controllers? I guess yes. that will help in the transition.

**Comment by Awk34** [comment]
You can still use controllers, yes. Angular 1.5 added `angular.component`, which is recommended since it eases the path to Angular 2.0, though.
