### ISSUE TITLE
Could not resolve 'buildings' from state ''

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2324]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 6.9.1
npm | 3.10.8
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS
Router | ui-router
DB | MongoDB
Auth | Y
etc | etc

Apologies for the flux of the noob questions. the move from 3.7.5 to 4.10 is not easy...

i'm trying to add a client side page 'old style'. manually adding a folder 'buildings' 
and in it: buildings.controllers.ts, buildings.html, buildings.routs.ts.
here is the routes file:

```js
export default function routes($stateProvider) {
  'ngInject';
  $stateProvider
    .state('buildings', {
      url: '/buildings',
      template: require('./buildings.html'),
      controller: 'BuildingsController',
      controllerAs: 'vm'
    });
};
```

i have added a link to this new page to navbar.html, with ui-sref='buildings'
it does not work, and when clicking the new entry in menu, i get in console:
Could not resolve 'buildings' from state ''

What did i miss?
Oh, and the nodemon does not seem to be working as well. i can change files, save, and i don't see any reload.

**Comment by Awk34** [comment]
Please try to use code formatting (backticks: \`) in future posts.

In your `buildings.controller.ts`, export a controller class: 

```ts
export class BuildingsController {
  constructor() {
    this.thing = 'test';
  }
}
```

And in your `buildings.routes.ts` file, import that controller:

```ts
import {BuildingsController} from './buildings.controller';

export default function routes($stateProvider) {
  'ngInject';
  $stateProvider
    .state('buildings', {
      url: '/buildings',
      template: require('./buildings.html'),
      controller: BuildingsController,
      controllerAs: 'vm'
    });
};
```

This way you can set the contoller function directly on the state definition.

You'd then need to create an Angular module out from all this. You can either create an `index.ts`, or just do it in `buildings.routes.ts`:

```ts
export default angular.module('myApp.buildings')
  .config(routes)
  .name;
```

You'd then need to import this module's name into a higher-up-the-tree module.

**Comment by AmirGilboa** [comment]
Thanks. can you please explain the last sentence? import to where? to app.ts ?
my buildings.routs.ts looks like this:
```
import {BuildingsController} from './buildings.controller';

export default function routes($stateProvider) {
  $stateProvider
    .state('buildings', {
      url: '/buildings',
      template: require('./buildings.html'),
      controller: BuildingsController,
      controllerAs: 'vm'
    });
};

export default angular.module('app.buildings')
  .config(routes)
  .name;
```

so i guess i have to import this new module in app.ts  . like:
```
import buildings from './buildings/app.buildings';
```
but it says: Cannot find module './buildings/app.buildings'
any idea?

**Comment by Awk34** [comment]
First, you can't have more than one default export in a file.

also, you need to **create** an angular module, which you'd do with this syntax:

```js
export default angular.module('app.buildings', [])
```

You need to import the file. The `'app.buildings'` is just a string key Angular uses for modules.

`app.js`
```js
import buildings from './buildings/buildings.routes';

angular.module('app', [
  ...
  buildings 
])
```

**Comment by AmirGilboa** [comment]
Great, thanks!
With this, i was able to fix it.
Only one problem caused me to waste an hour:  in the routes file, i did not write 'ngInject'.
Not 100% sure what it's doing, but obviously we need that.  I read about ng-annotate, and it makes sense for controllers. (not having to type every dependency twice). but in routes file? i don't know.
Anyways, it's working now. happy. thanks!

**Comment by Awk34** [comment]
With Angular Dependency Injection, if you have some class that wants 2 things injected, ex:

```js
class MyComponent {
  constructor(Thing1, Thing2) {}
}
```

You have to be able to tell Angular what these are. That's where the injection annotation comes in:

```js
MyComponent.$inject = ['thing1', 'thing2'];
```

Instead of doing this manually, we use the ng-annotate Webpack loader to do this for us. It knows which functions/classes to annotate with the `'ngInject'` directive.

It's the same thing with the routes, since it's just a function that gets passed into `angular.module(...).config`. It needs the ngRoute/UI-Router dependencies.
