### ISSUE TITLE
error '_' is not defined no-undef

### ISSUE THREAD

**Issue by imSanv** [angular-fullstack/generator-angular-fullstack#2325]
Hello my localhost is blank, I think it's for the 5 mistakes and I could not fix it, but i'm not sure

[17:16:14] Requiring external module babel-register
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
[17:16:17] Using gulpfile ~/Documents/Code/Nodejs/myappdrink/gulpfile.babel.js
[17:16:17] Starting 'serve'...
[17:16:17] Starting 'clean:tmp'...
[17:16:17] Starting 'lint:scripts'...
[17:16:17] Starting 'lint:scripts:client'...
[17:16:17] Starting 'lint:scripts:server'...
[17:16:17] Starting 'inject'...
[17:16:17] Starting 'inject:scss'...
[17:16:17] Starting 'copy:fonts:dev'...
[17:16:17] Starting 'env:all'...
[17:16:17] Finished 'env:all' after 47 ms
[17:16:17] Finished 'clean:tmp' after 126 ms
[17:16:18] gulp-inject 4 files into app.scss.
[17:16:18] Finished 'inject:scss' after 1.04 s
[17:16:18] Finished 'inject' after 1.04 s
[17:16:21] Finished 'copy:fonts:dev' after 3.6 s
[17:16:21] 
/Users/Damm/Documents/Code/Nodejs/myappdrink/server/index.js
  4:11  warning  Unexpected use of process.env  no-process-env
  4:34  warning  Unexpected use of process.env  no-process-env

/Users/Damm/Documents/Code/Nodejs/myappdrink/server/config/express.js
  67:25  warning  Unexpected use of process.env  no-process-env

/Users/Damm/Documents/Code/Nodejs/myappdrink/server/api/thing/thing.controller.js
   29:7  warning  Avoid using Function.prototype.apply, instead use Reflect.apply     prefer-reflect
   91:5  warning  Avoid using the delete keyword, instead use Reflect.deleteProperty  prefer-reflect
  102:5  warning  Avoid using the delete keyword, instead use Reflect.deleteProperty  prefer-reflect

/Users/Damm/Documents/Code/Nodejs/myappdrink/server/api/user/user.model.js
  162:15  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  163:18  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  165:22  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  166:18  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  206:14  warning  Unexpected sync method: 'pbkdf2Sync'            no-sync

✖ 11 problems (0 errors, 11 warnings)

[17:16:21] Finished 'lint:scripts:server' after 3.85 s
[17:16:21] 
/Users/Damm/Documents/Code/Nodejs/myappdrink/client/components/auth/auth.service.js
  **118:19  error    ' _ ' is not defined                                               no-undef
  148:20  error    ' _ ' is not defined                                               no-undef
  161:16  error    ' _ ' is not defined                                               no-undef
  174:29  error    ' _ ' is not defined                                               no-undef
  188:22  error    ' _ ' is not defined                                               no-undef**
  199:30  warning  Avoid using Function.prototype.apply, instead use Reflect.apply  prefer-reflect
  199:57  warning  Use the rest parameters instead of 'arguments'                   prefer-rest-params
  208:14  warning  Unexpected sync method: 'hasRoleSync'                            no-sync

/Users/Damm/Documents/Code/Nodejs/myappdrink/client/components/modal/modal.service.js
  42:22  warning  Avoid using Function.prototype.call, instead use Reflect.apply   prefer-reflect
  42:49  warning  Use the rest parameters instead of 'arguments'                   prefer-rest-params
  68:13  warning  Avoid using Function.prototype.apply, instead use Reflect.apply  prefer-reflect

/Users/Damm/Documents/Code/Nodejs/myappdrink/client/components/util/util.service.js
  59:99  warning  '===' should be placed at the beginning of the line  operator-linebreak

✖ 12 problems (5 errors, 7 warnings)

[17:16:21] Finished 'lint:scripts:client' after 4.19 s
[17:16:21] Finished 'lint:scripts' after 4.19 s
[17:16:21] Starting 'start:server'...
[17:16:21] Finished 'start:server' after 15 ms
[17:16:21] Starting 'start:client'...
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/Damm/Documents/Code/Nodejs/myappdrink/server/*_/_
[nodemon] starting `node server`
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
Express server listening on 9000, in development mode
finished populating users
[BS] Proxying: http://localhost:9000
[BS] Access URLs:

---

```
   Local: http://localhost:3000
External: http://192.168.1.7:3000
```

---

```
      UI: http://localhost:3002
```

 UI External: http://192.168.1.7:3002

---

webpack done hook
Hash: e3fc8ef152bb6cbe36c6
Version: webpack 1.13.3
Time: 12825ms
                  Asset     Size  Chunks             Chunk Names
          app.bundle.js   406 kB       0  [emitted]  app
    polyfills.bundle.js   206 kB       1  [emitted]  polyfills
       vendor.bundle.js  2.48 MB       2  [emitted]  vendor
      app.bundle.js.map   506 kB       0  [emitted]  app
polyfills.bundle.js.map   267 kB       1  [emitted]  polyfills
   vendor.bundle.js.map  2.89 MB       2  [emitted]  vendor
   ../client/index.html  1.39 kB          [emitted]  

WARNING in Using html-webpack-plugin-after-html-processing without returning a result is deprecated.
Child html-webpack-plugin for "../client/index.html":
                   Asset     Size  Chunks       Chunk Names
    ../client/index.html  2.69 kB       0  
webpack: bundle is now VALID.

**Comment by AmirGilboa** [comment]
put the error in google and see what you can get. i just did this for you.
it is a ESlint issue. Disallow Undeclared Variables. do you have one like that?
check it out.

one more guess: _ is usually the var name for the library lodash (or underscore). 
are they installed? imported/required correctly? look at that too.

**Comment by Awk34** [comment]
@AmirGilboa is correct, it's a warning from ESLint about lodash. It looks like we didn't include the import for lodash at the top of that file (`client/components/auth/auth.service.js`). This shouldn't cause the app any problems though, since lodash will automatically export a global instance of `_` as well.

Do you get any errors in your browser/server console?

**Comment by imSanv** [comment]
Hi Guys! thank you, I don't have visible errors, but local is blank and UI is good. i dont know what to do. and on other side server console dont have errors. so the error is not '_' ?

**Comment by mrtrom** [comment]
Be sure to be pointing at the right port. 
It is `Proxying: http://localhost:9000` so you have to check that one instead of 3000.

**Comment by Awk34** [comment]
@imSanv @mrtrom Your browser should automatically open to `http://localhost:3000/`, which is where the UI should be served from

**Comment by imSanv** [comment]
Thanks guys! it's correct, now my browser automatically open to http://localhost:3000/ , but http://localhost:9000/ have the same problem. but well apparently the error is my localhost, I reorganized it and all it's fine

**Comment by Awk34** [comment]
`http://localhost:9000/` won't show anything. `http://localhost:9000/api/things/` should show you the HTTP response for the list of things. Only the API is served from port `9000`

**Comment by reyronald** [comment]
@Awk34 There seems to be a lot of pending ESLint's errors and warnings all throughout the code. I have no problem opening a PR to solve all or most of them if it's going to receive attention from reviewers. Do you think it's worth the effort though?

**Comment by Awk34** [comment]
@reyronald I'm available for reviews

**Comment by Awk34** [comment]
closing this issue
