### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#2328]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 3.7.5 |
| Node | x.x.x |
| npm | x.x.x |
| Operating System | Windows 10 |
| etc | etc |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | HTML |
| CSS | LESS |
| Router | ui-router |
| Client Tests | Jasmine / Mocha |
| DB | MongoDB |
| Auth | Y |
| etc | etc |

Hi there

I'm not able to log in to my app anymore, I even tried to register with a new user, the user is on the db, but still not able to log in, error:

```
Warning: a promise was created in a handler but was not returned from it
    at Query.exec (m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\mongoose\lib\query.js:2208:10)
    at me (user.controller.js:108:59)
    at Layer.handle [as handle_request](m:WebsitesprojekteKundenSVSsvs-ngFullStacknode_modulesexpresslibrouterlayer.js:95:5)
    at next (m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\express\lib\router\route.js:131:13)
    at next (m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\composable-middleware\lib\composable-middleware.js:40:9)
    at auth.service.js:36:11
From previous event:
    at Middleware_Common_Object.<anonymous> (auth.service.js:31:10)
    at next (m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\composable-middleware\lib\composable-middleware.js:59:18)
    at m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\express-jwt\lib\index.js:122:7
    at m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\async\lib\async.js:52:16
    at Immediate._onImmediate (m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\async\lib\async.js:1206:34)
    at processImmediate [as _immediateCallback](timers.js:383:17)
```

Thanks for help

**Comment by Awk34** [comment]
That's a warning, not an error. Something else is causing your problem.

**Comment by AmirGilboa** [comment]
since its 3.7.5 i assume it's not a new installation, but ongoing thing. do you use some source control, like git? see what has changed.  I check in often, just for cases like this.
check your chrome console (f12), maybe there is a clue there.
did you change anything that relates to user object, auth service, or the login process?

**Comment by MarinAngelo** [comment]
oh, I changed a lot, it turned out that as soon as I use $rootscope in the navbar.controller the isLoggedIn() method toes not work any more, but I need $rootscope, how can I resolve this conflict?
*************************************************************************************************
    constructor(Auth, $http, $scope, $sce, $rootScope, $state, cosmicContent, $translate) {
        // this.$rootScope = $rootScope;
        this.isLoggedIn = Auth.isLoggedIn;
        this.isAdmin = Auth.isAdmin;
        this.getCurrentUser = Auth.getCurrentUser;

**Comment by MarinAngelo** [comment]
Hi there, thanks for your answers! It turned out, that I was logged in, but the nav did not change, because isLoggedIn() does not work as long as I use $rootScope. Could you pls. help me to make this work?

**Comment by Awk34** [comment]
It stops working after only injecting `$rootScope`, but not doing anything with it?

**Comment by MarinAngelo** [comment]
As soon as I outcomment 'this.$rootScope = $rootScope;' the 'nav.isLoggedIn()' works again.

I use the $rootScope for a language switcher. The current language is sitting on the $rootScope as follows:

$onInit() {

        console.log('is loged in?: ', this.getCurrentUser);

        var self = this;
        // Dropdown Nav with ui-navbar
        // whatch for current language
        self.$scope.$watch(function() {

            // return actual language
            return self.$rootScope.lang;

        }, function() {
            self.currentLang = self.$rootScope.lang;

            if (self.currentLang === 'de') {
                self.$scope.nav = self.$scope.navDe;
            } else {
                self.$scope.nav = self.$scope.navFr;
            }

            self.$scope.navDe = {
                dropdowns: [{
                    name: 'Verband',
                    tree: [{
                        name: "Portrait",
                        link: "#",
                        subtree: [{
                            name: "Verbandsziele",
                            link: "verbandsziele"
                        }]
                    }, {
                        name: "divider",
                        link: "#"

                    }, {
                        name: "Statuten",
                        link: "statuten"
                    }]
                }, {
                    name: 'Aktuell',
                    tree: [{
                        name: "News",
                        link: "news"
                    }]
                }, {
                    name: 'Produkte Infos',
                    tree: [{
                        name: 'Neuheiten',
                        link: 'neuheiten'
                    }, {
                        name: 'Toy Directory',
                        link: 'toydirectory'
                    }]
                }, {
                    name: 'Medien',
                    tree: [{
                        name: 'Medienmiteilungen',
                        link: 'mediareleases'
                    }]
                }, {
                    name: 'Kontakt',
                    tree: [{
                        name: 'Kontaktformular',
                        link: 'kontaktformular'
                    }, {
                        name: 'sk@spielwarenverband.ch',
                        link: 'mailto:sk@spielwarenverband.ch'
                    }, {
                        name: 'Tel. 044 545 21 69',
                        link: '#'
                    }]
                }]
            };

            self.$scope.navFr = {
                dropdowns: [{
                    name: 'Association',
                    tree: [{
                        name: "Portrait",
                        link: "#",
                        subtree: [{
                            name: "Objectifs de l'association",
                            link: "verbandsziele"
                        }]
                    }, {
                        name: "divider",
                        link: "#"

                    }, {
                        name: "Statuts",
                        link: "statuten"
                    }]
                }, {
                    name: 'Actuel',
                    tree: [{
                        name: "News",
                        link: "news"
                    }]
                }, {
                    name: 'Produit Infos',
                    tree: [{
                        name: 'Nouveautés',
                        link: 'neuheiten'
                    }, {
                        name: 'Toy Directory',
                        link: 'toydirectory'
                    }]
                }, {
                    name: 'Médias',
                    tree: [{
                        name: 'Communiqués de presse',
                        link: 'mediareleases'
                    }]
                }, {
                    name: 'Contact',
                    tree: [{
                        name: 'Formulaire de contact',
                        link: 'kontaktformular'
                    }, {
                        name: 'sk@associationdesjouets.ch',
                        link: 'mailto:sk@associationdesjouets.ch'
                    }, {
                        name: 'Tel. 044 545 21 69',
                        link: '#'
                    }]
                }]
            };
        }, true);
    }

thanks for help in advance!

**Comment by MarinAngelo** [comment]
Hello, anybody there? Should I surch for payed advice?

**Comment by Awk34** [comment]
@MarinAngelo sorry I've been a bit detached from OSS for a while. I just recently started a new job.

It would help if you could scaffold a new project and set up a minimal reproduction case for this, and post it somewhere so I can try to reproduce.

**Comment by Koslun** [comment]
@MarinAngelo This doesn't really seem like a bug with the generator, just your code. So Stackoverflow would probably be a better fit. There is a better incentive for people to answer on their own time there.

Would then help to a slightly simpler example that seems to highlight the issue. Can cut a lot of the meat of that example while also probably needing to add more context as how you've actually defined the controller. My first guess from glancing this would at least be to check that `$rootScope` is even being properly injected.

**Comment by MarinAngelo** [comment]
OK, thank's, I'll try to reproduce a simpler example and publish it on Github.
