### ISSUE TITLE
How to work with sequelize?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#2337]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Operating System| Windows 10 
etc | etc

Item | Answer
----- | -----
Transpiler|  TypeScript
DB |  SQL
Auth | Y 

Those of you who work with sequalize, i need a big favor from you:
show me your file:  /server/config/environment/development.js
(obviously remove passwords.... )
i'm struggeling to connect to my local mysql.
i will paste my file below, maybe you can spot the missing part, but let me also ask:
1. does it work the same way as mongoose, that all the db is defined in code, and generated when the project starts? or should i have my database ready and just connect to it?
2. why do i see all the mongoose stuff in the project when i selected sequalize? is this a bug and i should ignore it, or maybe the idea is to work with them together?

```
'use strict';
/*eslint no-process-env:0*/

// Development specific configuration
// ==================================
module.exports = {

  // MongoDB connection options
  mongo: {
    uri: 'mongodb://localhost/app-dev'
  },

  // Sequelize connection opions
  sequelize: {
    //uri: 'sqlite://',
    dialect: 'mysql',
    
    database: 'mydb',
    username: 'ron',
    password: 'secretpass',
    options: {
      logging: false,
      dialect: 'mysql',
      host:'localhost',
      url: 'mysql://localhost:3306/mydb',
      //storage: 'dev.sqlite',
      define: {
        timestamps: false
      }
    }
  },

  // Seed database on startup
  seedDB: true

};
```

**Comment by RonAlmog** [comment]
Ah, and one more question: how to form relations between tables in sequelize?
I was able to do it with:
```db.Order.hasOne(db.User, { foreignKey: 'userId' , foreignKeyConstraint:true });
db.Thing.hasOne(db.User, { foreignKey: 'userId' , foreignKeyConstraint:true });```

but a foreign key was not really created. so if  you happen to know the trick, please share... <3

**Comment by okcjosh** [comment]
@RonAlmog 
'use strict';
/*eslint no-process-env:0*/

// Development specific configuration
// ==================================
module.exports = {

  // Sequelize connection opions
  sequelize: {
    uri: 'mysql://USERNAME:PASSWORD@DATABASEURL(Probably LOCALHOST):PORT/DATABASE_NAME',
    options: {
      logging: false,
      storage: 'mysql',
      define: {
        timestamps: false
      }
    }
  },

  // Seed database on startup
  seedDB: true

};

**Comment by RonAlmog** [comment]
thank you, much appreciated!
