### ISSUE TITLE
Project not rebuild after changes

### ISSUE THREAD

**Issue by GuofuHuang** [angular-fullstack/generator-angular-fullstack#2340]
I just tried Version 4, but find out that the project is not updated automatically after changes. Sometimes you have to change multiple times to make the update happen. 

Does it should be like that?

**Comment by Awk34** [comment]
Which IDE/editor do you use?

**Comment by GuofuHuang** [comment]
I use webstorm in Mac!

**Comment by Awk34** [comment]
@GuofuHuang I believe people have been having issues before with some setting within WebStorm pertaining to not always saving files to disk. Let me check...

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2230#issuecomment-248469368
