### ISSUE TITLE
Try to load angular more than once

### ISSUE THREAD

**Issue by GuofuHuang** [angular-fullstack/generator-angular-fullstack#2341]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

I use templateUrl instead of template in component, but there exists a warning saying "try to load angular more than once", and the page is always refreshing. 

I type 'sidebar.component.html' for the templateUrl value, do you know what happens to this?

**Comment by GuofuHuang** [comment]
If I typed the correct id of the exciting DOM element, it works fine, otherwise it will always refreshing.

**Comment by Awk34** [comment]
Please fill out the provided details form.

I assume it's because the server doesn't know about that HTML file, so it's just re-serving you the `index.html` file. If you want to load the HTML files from a separate HTTP request (which I don't recommend), you'd need to set the server up to do so.

**Comment by csvan** [comment]
Relevant?

https://github.com/webpack/webpack/issues/2134

**Comment by Awk34** [comment]
Closed due to inactivity
