### ISSUE TITLE
script files are being erased from index.html

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2349]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0

Item | Answer
----- | -----
Transpiler | Babel 
Router | ui-router
etc | etc

Trying to work with kendo ui. problem is, i only have the javascript files, not a standard npm install.
so i put these files in a folder, (or use cdn) and call them in index.html (head section), like this:
```<script src="http://cdn.kendostatic.com/2016.3.1028/js/kendo.all.min.js"></script>```

when i run the gulp, the files disappear from index.html.  my questions:
1. who's doing this? and why?
2. how can i use simple js library without having it under node_modules?
3. what's the best way to solve this?
thank you all.

**Comment by Awk34** [comment]
In 4.0.0+, the `index.html` file is generated from the `_index.html` template. Edit that file instead.

**Comment by Awk34** [comment]
Also, if you can't use a package manager, you can save the 3rd party lib under the `client/assets` directory, and `import` it from there;

**Comment by AmirGilboa** [comment]
Ah, that explains everything. thank you!
now the libs are loaded from cdn.
and maybe you know this also: what should my import line look like in app.js? 
i tried:
```import kendo from 'kendo-directives';```
but no luck

**Comment by Awk34** [comment]
I'm not sure if Kendo supports any sort of module system. I'd assume you can just do this:

```js
import 'assets/kendo.all.min';
```

if you have kendo downloaded in your assets folder

**Comment by AmirGilboa** [comment]
kenod.all.min.js  is a big file, 2800KB.  when i just put it in /assets/kendo/js, without even importing it or anything else, the build is stuck, and after a while breaks with message that ends with:
Javascript heap out of memory.
so it looks like my only choice is to use cdn.

**Comment by Awk34** [comment]
In your `webpack.make.js`, add Kendo to the [`module.noParse`](https://webpack.github.io/docs/configuration.html#module-noparse) option. 

```js
const path = require('path');

...

config.module = {
  noParse: [
    path.join(__dirname, 'client', 'assets', 'kendo.all.min.js'),
  ],
...
```

**Comment by AmirGilboa** [comment]
no luck yet. i put it here in webpack.make.js, and modified the path to match the folder structure:
```    
// Initialize module
    config.module = {
        preLoaders: [],
        noParse: [
                  path.join(__dirname, 'client', 'assets','kendo', 'js', 'kendo.all.min.js'),
                ],
        loaders: [{
            // JS LOADER
```
but it is still get stuck in compiling. if i remove the file, compiling passes.  :(
