### ISSUE TITLE
html-webpack-plugin deprecation warning

### ISSUE THREAD

**Issue by leebailey88** [angular-fullstack/generator-angular-fullstack#2358]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1
Node | 6.9.1
npm | 3.10.8
Operating System | OS X 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y
etc | etc

Getting the following warning:
```
WARNING in Using html-webpack-plugin-after-html-processing without returning a result is deprecated.
Child html-webpack-plugin for "../client/index.html":
```

When the page refreshes I see:
![screen shot 2016-11-20 at 6 18 28 pm](https://cloud.githubusercontent.com/assets/5678278/20468695/e970f53e-af4d-11e6-9dd5-3574c849adcc.png)

**Comment by Awk34** [comment]
Which version of `html-webpack-plugin` are you using? Is the following relevant? https://github.com/ampedandwired/html-webpack-plugin/pull/478

**Comment by Awk34** [comment]
Closed due to inactivity
