### ISSUE TITLE
Missing files when using angular-fullstack:route

### ISSUE THREAD

**Issue by thomasvnl** [angular-fullstack/generator-angular-fullstack#2359]
When creating a route with angular-fullstack:route, within the environment mentioned below, the generator does not produce an html (or pug in this case) ~~and css (or less in this case)~~ file, which according to [this](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/docs/generators/route.md) documentation it should do. Also, the generated component tries to require a html file when pug is selected for the project. 

Anyone experiencing the same issue(s)?

__Environment__
generator-angular-fullstack | 4.1.0
Node | 6.9.1
npm | 3.10.9
Operating System | Windows 10

__Project Settings__
Transpiler | Babel
Markup | Pug
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | MongoDB 
Auth | Y
SocketIO | Y

**Comment by Awk34** [comment]
Would you post all the file names that **do** get created? for sanity's sake. A screenshot of your terminal while generating might be helpful too.

**Comment by thomasvnl** [comment]
I've just run the command and this is it's output, which corresponds with the files being created:

```C:\projects\booky\client>yo angular-fullstack:route test

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: C:\projects\booky
? What module name would you like to use? bookyApp.test
? Where would you like to create this route? client/app/
? What will the url of your route be? /test
   create client\app\test\test.routes.js
   create client\app\test\test.component.js
   create client\app\test\test.component.spec.js
   create client\app\test\test.less```

**Comment by aniknafs** [comment]
Looks like the .pug files don't generate because generator-ng-component had .jade as template. Should be fixed when ng-component is updated.

**Comment by Awk34** [comment]
Please make sure to use `generator-ng-component@1.0.5` or above. This will be enforced in the next release of the generator.
