### ISSUE TITLE
Community for discussion such as Slack?

### ISSUE THREAD

**Issue by viewplatgh** [angular-fullstack/generator-angular-fullstack#2364]
I cannot find a forum or chat group to ask questions and discuss about angular-fullstack. Can we have one if there is not one exists? I recommend to use Slack. generator-fountain-webapp is using it and looks pretty good.

**Comment by atodicebear** [comment]
Try
https://gitter.im/angular-fullstack/generator-angular-fullstack
;)

**Comment by Awk34** [comment]
Yes, we have a Gitter.im channel
