### ISSUE TITLE
ui-route resolve dependency

### ISSUE THREAD

**Issue by Abdizriel** [angular-fullstack/generator-angular-fullstack#2365]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 6.5.0
npm | 3.9.1
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTM
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | SQL
Auth | Y

Hey guys,

I have got creepy issue with ui-route while I want to resolve some dependencies before loading view.

I have got this in profile.route.js:

```JavaScript
'use strict';

export default function routes($stateProvider) {
  'ngInject';

  $stateProvider.state('profile', {
    url: '/profile',
    template: '<profile></profile>',
    authenticate: true,
    data: {
      pageTitle: 'Account'
    },
    resolve: {

      /**
       * Gets all countries
       * @param $http
       * @returns countries
       */
      countries: $http => {
        const url = 'https://restcountries.eu/rest/v1/all';
        return $http.get(url)
          .then(({ data }) => {
            return data.map(({ name, alpha2Code }) => {
              return { name, alpha2Code };
            });
          });
      },

      /**
       * Gets logged user
       * @param Auth
       * @returns user
       */
      user: Auth => {
        return Auth.getCurrentUser();
      }
    }
  });
};
```

And also this in profile.component.js

```JavaScript
 constructor($http, socket, Auth, Modal, user, countries) {
    this.$http = $http;
    this.socket = socket;
    this.Auth = Auth;
    this.Modal = Modal;
    this.user = user;
    this.countries = countries;
}
```

It should work without any issues but I have got this errors (It doesn't matter if I do resolve in profile or any other part of code)

```
angular.js:13920 Error: [$injector:unpr] Unknown provider: userProvider <- user
angular.js:13920 Error: [$injector:unpr] Unknown provider: countriesProvider <- countries
```

Could you tell me what I am doing wrong there?
In other application I make without using this generator it works without issue (countries case)

**Comment by Awk34** [comment]
the user service should be injected as `User`. As for your other provider, it depends how it's defined. Look for the `angular.service` call, and see what string key is given.

**Comment by Abdizriel** [comment]
@Awk34 no it's correct check the code I provided with profile.route.js

```
$stateProvider.state('profile', {
    url: '/profile',
    template: '<profile></profile>',
    authenticate: true,
    data: {
      pageTitle: 'Account'
    },
    resolve: {

      /**
       * Gets all countries
       * @param $http
       * @returns countries
       */
      countries: $http => {
        const url = 'https://restcountries.eu/rest/v1/all';
        return $http.get(url)
          .then(({ data }) => {
            return data.map(({ name, alpha2Code }) => {
              return { name, alpha2Code };
            });
          });
      },

      /**
       * Gets logged user
       * @param Auth
       * @returns user
       */
      user: Auth => {
        return Auth.getCurrentUser();
      }
    }
  });
```


as you can see I can't get resolved values from ui-route

**Comment by Azayzel** [comment]
@Abdizriel he means in your dependency injection. You have it a lower case 'u' and it needs to be upper case, 'U'

**Comment by Abdizriel** [comment]
@Azayzel no It's correct!!!

Check this:

```
/**
       * Gets logged user
       * @param Auth
       * @returns user
       */
      user: Auth => {
        return Auth.getCurrentUser();
      }
```

This is not uppercase User just user with lowercase which is from ui-router which is variable that needs to be resolved before loading controller and in controller I am using user not User where user is variable thats needs to be resolved.

**Comment by Azayzel** [comment]
Try handling the Auth.getCurrentUser() promise. Like you do with countries.

**Comment by Abdizriel** [comment]
@Azayzel but both of them are not working when I am trying to do them with ui-resolve.

I can do them on $onInit but I need them before.

**Comment by Azayzel** [comment]
Just for kicks, can you try without the arrow function? Just go back to ES5
```
$stateProvider.state('profile', {
    url: '/profile',
    template: '<profile></profile>',
    authenticate: true,
    data: {
      pageTitle: 'Account'
    },
    resolve: {

      /**
       * Gets all countries
       * @param $http
       * @returns countries
       */
      countries: function($http) {
        const url = 'https://restcountries.eu/rest/v1/all';
        return $http.get(url)
          .then(({ data }) => {
            return data.map(({ name, alpha2Code }) => {
              return { name, alpha2Code };
            });
          });
      },

      /**
       * Gets logged user
       * @param Auth
       * @returns user
       */
      user:  function(Auth) {
        return Auth.getCurrentUser();
      }
    }
  });
```

**Comment by Azayzel** [comment]
So, you should be using it like this
```
        resolve: {
            user: Auth => {
                'ngInject'
                return Auth.getCurrentUser()
            }
        }
```

I think really the problem was not including 
```
'ngInject'
```

Give that a shot in your code (adding 'ngInject' to both resolve functions) and let us know. This should fix your issue.

```
   resolve: {

      /**
       * Gets all countries
       * @param $http
       * @returns countries
       */
      countries: $http => {
        'ngInject'
        const url = 'https://restcountries.eu/rest/v1/all';
        return $http.get(url)
          .then(({ data }) => {
            return data.map(({ name, alpha2Code }) => {
              return { name, alpha2Code };
            });
          });
      },

      /**
       * Gets logged user
       * @param Auth
       * @returns user
       */
      user:  Auth => {
        'ngInject'
        return Auth.getCurrentUser();
      }
    }
```

**Comment by Awk34** [comment]
Ah, I see now. The issue with your 'unknown provider' errors is that Angular is trying to resolve `user` and `countries` as providers registered with it. Instead, ui-router's recommended way of using `resolve`s with Angular 1.5 is to do a one-way binding, like is mentioned [here](https://ui-router.github.io/guide/ng1/route-to-component#create-a-component). You would use something like this when you register your component:

```js
export default angular.module('myApp.profile', [...])
    .component('main', {
      template: require('./main.<%= templateExt %>'),
      controller: ProfileComponent,
      bindings: {
        user: '<user',
        countries: '<countries',
      },
    })
    .name;
```

You can then access the resolved data on your component.

```html
<span>{{$ctrl.user}}</span>
```

```js
 constructor($http, socket, Auth, Modal) {
    this.$http = $http;
    this.socket = socket;
    this.Auth = Auth;
    this.Modal = Modal;

    console.log(this.user);
    console.log(this.countries);
}
```

**Comment by Abdizriel** [comment]
@Awk34 unfortunately it's not working even after updating to angular-ui-router 1.0.0.beta-3

**Comment by Awk34** [comment]
@Abdizriel I suggest trying to get a minimal reproduction in jsbin/codepen/etc

**Comment by Abdizriel** [comment]
@Awk34 you can find it there: https://github.com/Abdizriel/test

**Comment by Abdizriel** [comment]
Ok... solved issue... My NPM cache layer was not updated and it was still using version 0.2.x of angular-ui-router instead of 1.x.x
