### ISSUE TITLE
Question: How to use modal?

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2368]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
Router |  ui-router
etc | etc

there is this folder /client/components/modal, and 3 files in it: modal.html, modal.service.js, modal.scss.

what are they doing? are they sort of a template to that i should call when i need a modal window?
any example on how to use it, or any explanation would be great. thanks.

**Comment by Awk34** [comment]
#580
