### ISSUE TITLE
How to update generator-angular from older version to latest

### ISSUE THREAD

**Issue by ajai-sandy** [angular-fullstack/generator-angular-fullstack#2372]
Hi,
Currently am using version 3.7.5 I need to upgrade my project to version 4.1.0, kindly help me how to update and retain all my project codes and packages unaffected.

**Comment by RonAlmog** [comment]
As far as i know, there is no way to upgrade.  You have to create a new project with 4.1,  copy from your old project whatever is reusable, and rewrite the rest.
The server side has not changed much, and the changes (if any) are minor and incremental.
The client side has changed dramatically. significant changes i can think of now:
1. it is now ES6, and components. different style, takes a bit to get used to, but doable.
2. Bower is gone, all npm now. 
3. Grunt is out, Gulp is your only option. i'm good with that, i love gulp.
4. Webpack was added, and is doing now much of the work that used to be done by gulp/grunt.  I wish that  was an option. I find webpack to be flaky (or requires knowledge that i don't have) and giving me cryptic errors on every step. my life was good before that addition, and i don't need it. gulp is more than capable to do all the minification/concatenation/linting etc.  But anyways, it's there, so you have to learn to deal with it if you want to move to 4.1.x .

For all these reasons, I would say it is more of a rewrite than an upgrade. especially the client side.

**Comment by csvan** [comment]
I recently moved our project from version 2 to 4. It took a full week and was extremely tedious. Unless you have an absolutely compelling reason to do so (do you *really* need Webpack? Do modules *actually* add something to the quality of your project?), I would advice against it.

**Comment by ajai-sandy** [comment]
Thank you @RonAlmog  and @csvan  for giving me a detailed explanation on this, really appreciate the effort. Will start my mission to migrate my project to this updated version.
