### ISSUE TITLE
How to keep a folder inside dist?

### ISSUE THREAD

**Issue by GuofuHuang** [angular-fullstack/generator-angular-fullstack#2373]
I need help for my website. My website has the ability to upload pictures, and those pictures are saved under assets folder. Once they are built in production mode, all images are erased. 

So how can I keep that folder under production mode?

Thanks

**Comment by DevManny** [comment]
Do you want your local uploaded files to be copied to `/dist` when **`"build"`**? Or are your local files deleted when **`"build"`**?

**Comment by GuofuHuang** [comment]
I want to keep it just for that folder, because it will save all uploaded pictures!

**Comment by GuofuHuang** [comment]
I don't want my uploaded files to be deleted when build dust!

**Comment by Awk34** [comment]
The `dist/` folder isn't meant to keep any persistent state.. It's just for your built code. Any state kept across deploys and across servers should be kept in your database, either MongoDB or SQL (whichever you chose).
