### ISSUE TITLE
grunt build throws an error during uglify (v3.3.0)

### ISSUE THREAD

**Issue by zcsongor** [angular-fullstack/generator-angular-fullstack#2378]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.3.0
Node | 4.4.3
npm | 3.7.3
Operating System | Windows 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS
Router | ui-router
Client Tests | Jasmine
DB | MongoDB
Auth | Y

I'm running an older version of this generator. When I run `grunt serve` everything works fine, but when I want a production build (`grunt build`) it throws an exception:

```
Running "uglify:generated" (uglify) task
JS_Parse_Error {
  message: 'SyntaxError: Unexpected token punc «(», expected punc «:»',
  filename: '../../../.tmp/concat/app/app.js',
  line: 1113,
  col: 11,
  pos: 32004,
```

The corresponding code snippet (commented line 1113):
```
(function() {

authInterceptor.$inject = ["$rootScope", "$q", "$cookies", "$injector", "Util"];
function authInterceptor($rootScope, $q, $cookies, $injector, Util) {
  var state;
  return {
    // Add authorization token to headers
    request(config) { // this is the line 1113, nothing special here
      config.headers = config.headers || {};
      if ($cookies.get('token') && Util.isSameOrigin(config.url)) {
        config.headers.Authorization = 'Bearer ' + $cookies.get('token');
      }
      return config;
    },

    // Intercept 401s and redirect you to login
    responseError(response) {
      if (response.status === 401) {
        (state || (state = $injector.get('$state'))).go('login');
        // remove any stale tokens
        $cookies.remove('token');
      }
      return $q.reject(response);
    }
  };
}

angular.module('planyourtripApp.auth')
  .factory('authInterceptor', authInterceptor);

})();
```

Any idea why this happens? Thanks in advance!

**Comment by Awk34** [comment]
Which version of babel are you using? 3.3.0 defaults to babel versions ^5, which includes es2015 transforms by default, but if you've upgraded to babel 6+, you'll need to change your config.

**Comment by zcsongor** [comment]
I have these versions:
```
"babel-runtime": "^5.8.20", 
"babel-core": "^5.6.4", 
"grunt-babel": "^5.0.3",
```

**Comment by Awk34** [comment]
Hmmm okay, so that shouldn't be the issue.

It looks like the [property shorthand](https://babeljs.io/docs/plugins/transform-es2015-shorthand-properties/) conversion isn't happening, though.

this:
```js
return {
    request(config) {...},
    responseError(response) {...}
  };
```
should turn into this:
```js
return {
    request: function(config) {...},
    responseError: function(response) {...}
  };
```

You could maybe try manually enabling this babel plugin in your config.

**Comment by zcsongor** [comment]
I'm kinda amateur, so... how do I do that? :)

**Comment by Awk34** [comment]
I would highly recommend upgrading to Babel 6. The latest version of the generator (4.1.0) uses Babel 6. A good idea would be to update your generator (`npm i -g generator-angular-fullstack@4.1.0`), scaffold out a new project, and see what's changed.

Basically for Babel 6, you have to use the "ES2015" preset to get all the ES6 transforms.

**Comment by zcsongor** [comment]
Will do it, thanks!
