### ISSUE TITLE
OSX XCode error

### ISSUE THREAD

**Issue by naveenvprakash** [angular-fullstack/generator-angular-fullstack#2382]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

osx - xcode error xcode-select: error: tool 'xcodebuild' requires xcode, but active developer directory '/library/developer/commandlinetools' is a command line tools instance

**Comment by Awk34** [comment]
I don't own a Mac any more, but It looks like you don't have xcode installed

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by naveenvprakash** [comment]
Thankyou, But I resolved the issue. It was the issue with the Node version.
