### ISSUE TITLE
How to add new javascript dependencies in 3.10.8?

### ISSUE THREAD

**Issue by cmiddleton-array** [angular-fullstack/generator-angular-fullstack#2386]
I have added a new javascript dependency through bower, however it does not seem to get "injected" ever.

I have noticed in the generated gulpfile there is no task for the old "wiredep"

any suggestions?

**Comment by Awk34** [comment]
Bower is not used in the latest version of the generator. Use npm instead.

**Comment by cmiddleton-array** [comment]
Thanks!!

**Comment by Awk34** [comment]
I can only assume that you scaffolded with the latest version, 4.1.0 (we have no 3.10.8 version). If you were to want to use `moment`, you would `npm install --save moment`, and then in your front-end file, just `import moment from 'moment';`.
