### ISSUE TITLE
single session per user, prevent simultaneous logins

### ISSUE THREAD

**Issue by bwyss** [angular-fullstack/generator-angular-fullstack#2398]
Is there a known strategy to prevent simultaneous logins?

**Comment by Awk34** [comment]
I would think most people would want their implementations to allow simultaneous logins.

**Comment by bwyss** [comment]
I have an edge case when I need to prevent simultaneous logins, is it possible? If so, can you point me in the right direction?

**Comment by Awk34** [comment]
[Here's](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/server/config/express.js#L60-L69) where sessions are taken care of (just FYI). You'd basically need to check if the user already has a living session when he/she logs in. Probably [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/server/auth(auth)/local/passport.js#L18), you'd want to query the `sessions` collection in your DB and see if the user has a living session. You could then either invalidate the previous session, or not allow a new one, depending on your requirements. Does this help?

**Comment by bwyss** [comment]
@Awk34 yes very helpful, thanks!

**Comment by bwyss** [comment]
Thanks, yes, that is helpful.
Can you provide an example of what that session query might look like?
I don't have a lot of experience working with passport. (looking at the sessions and users in mongo) it's not clear to me how I can find out which session is associated to each user and if a session in living or not?
