### ISSUE TITLE
When running `grunt serve` the client side in google chrome faces with `Aw, snap!`

### ISSUE THREAD

**Issue by saeidalidadi** [angular-fullstack/generator-angular-fullstack#2401]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.x
Node | 6.9.1
npm | 3.x.x
Operating System |  Ubuntu 16.04
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ui-router
Client Tests | Mocha
DB | MongoDB 
Auth | Y / N
etc | etc

**Comment by Awk34** [comment]
Closed due to inactivity
