### ISSUE TITLE
generator-angular-fullstack@alpha create error

### ISSUE THREAD

**Issue by liangwenzhong** [angular-fullstack/generator-angular-fullstack#2403]
when i use generator-angular-fullstack@alpha create a new project .

error:⬇️

![image](https://cloud.githubusercontent.com/assets/6957057/21131078/a7c0dbf2-c147-11e6-94af-3466ed1e7490.png)

Item | Version
----- | -----
generator-angular-fullstack | alpha
Node | 6.6.0
npm | 3.10.3
Operating System | OS X 10

**Comment by adeebbasheer** [comment]
same issue here too...

**Comment by Awk34** [comment]
Thanks for the report

**Comment by saherrera** [comment]
Still getting this issue, i try to uninstall the @alpha version, and running the original generator but it still give me the same error :/
