### ISSUE TITLE
Angular material with this generator

### ISSUE THREAD

**Issue by amehta22** [angular-fullstack/generator-angular-fullstack#2404]
Has anyone used Angular material with this generator? 
Can someone share an example/sample implementation?

I am new to Angular and would appreciate any pointers/resources.
Thanks in advance!

**Comment by Awk34** [comment]
It's been proposed to have the option to scaffold with different UI frameworks: #999

As for examples/samples for using a different UI framework, I'd ask in our [gitter.im](https://gitter.im/angular-fullstack/generator-angular-fullstack) channel.
