### ISSUE TITLE
Error while running yo angular-fullstack

### ISSUE THREAD

**Issue by brittbinler** [angular-fullstack/generator-angular-fullstack#2405]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'babel-plugin-syntax-decorators'
    at Function.Module._resolveFilename (module.js:325:15)
    at require.resolve (internal/module.js:16:19)
    at Array.map (native)
    at Generator.generateProject (/usr/local/lib/node_modules/generator-angular-fullstack/generators/app/index.js:536:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:440:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)

 

- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 4.4.3
npm | 4.0.3
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router | ngRoute
Client Tests | Mocha
DB | MongoDB
Auth | Y

**Comment by suavelizard** [comment]
Ditto

**Comment by donovankim** [comment]
+1

**Comment by Coby-T** [comment]
Same here, 4.1.1.

**Comment by rvillanueva** [comment]
+1 for the 5.0.0 alpha build too

Reinstalling 4.1.0 seems to fix it, thanks @Coby-T

**Comment by Awk34** [comment]
I accidentally marked 5.0.0-alpha.1 as `latest` on npm. It should be corrected to mark 4.1.1 as `latest` now, so if you don't specify a version it will install 4.1.1 by default.

As for 5.0.0-alpha.1, I will fix the issue.

**Comment by Awk34** [comment]
5.0.0-alpha.2 has been published to address this. It is available under the `alpha` tag (`generator-angular-fullstack@alpha`).
