### ISSUE TITLE
index.html stripped of edits upon server reload | generator v. 4.1.1

### ISSUE THREAD

**Issue by mgreezy** [angular-fullstack/generator-angular-fullstack#2408]
Changes to index.html get stripped upon restarting the server (gulp-serve) using the settings below.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.1
Node | 6.2.2
npm | 3.9.5
Operating System | OS Sierra 10.12

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Jasmine 
DB | MongoDB
Auth | Y

**Comment by Awk34** [comment]
`index.html` is re-rendered from the `_index.html` template
