### ISSUE TITLE
Shifting to Angular 2?

### ISSUE THREAD

**Issue by JoelParke** [angular-fullstack/generator-angular-fullstack#2414]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.1
Node | 4.4.4
npm | 3.10.5
Operating System Ubuntu 16.10

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB 
Auth | Y 

Has anyone successfully shifted the generated app to using Angular 2?
I haven't had any luck yet.

**Comment by Awk34** [comment]
`generator-angular-fullstack@alpha` uses Angular 2.

**Comment by JoelParke** [comment]
Thank you very much!

**Comment by Awk34** [comment]
@JoelParke it's hosted on the *canary* branch
