### ISSUE TITLE
Please create labels so that the community can mark issues as duplicates, questions, bugs, etc...

### ISSUE THREAD

**Issue by JoelParke** [angular-fullstack/generator-angular-fullstack#2418]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

It would be most helpful if one could mark issues with a label showing a partial classification of an issue.  I greatly appreciate this project, but am in the midst of learning Angular2 and moving a project I built around an earlier version of this project, and anything that would accelerate it's development would be great.  

I can't commit the time to this suggestion, but I believe it would help the community contribute to the project.  Thanks!

**Comment by Awk34** [comment]
We have issue tags, including various ones for community involvement. Only repository collaborators have the rights to use the labels on issues, though.

You can add a tag to your issue title though, like this: "[question] example question?"
