### ISSUE TITLE
grunt-forever commond

### ISSUE THREAD

**Issue by malipraful** [angular-fullstack/generator-angular-fullstack#2419]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

D:\xampp\htdocs\myproject\assets\js>grunt forever:test:start
Running "forever:test:restart" (forever) task
Attempting to restart /Server/index.js...
/Server/index.js not found in list of processes in forever. Starting new instanc
e...
Attempting to start /Server/index.js as daemon.
Adding to config: errFile, undefined
Adding to config: outFile, undefined
Adding to config: logFile, undefined
Logs can be found at D:\xampp\htdocs\myproject\assets\js\forever.

Done, without errors.
 how to solve this error

**Comment by Awk34** [comment]
I'm not sure if this project has even ever had a `grunt forever` command...
