### ISSUE TITLE
Is Grunt deprecated in latest angular-fullstack?

### ISSUE THREAD

**Issue by duoli** [angular-fullstack/generator-angular-fullstack#2428]
In latest 4.1.1 version build system seems become gulp by default and grunt is no longer an option in initialization. 
What's the purpose of deprecating grunt?

**Comment by Awk34** [comment]
Please read the changelog: https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/CHANGELOG.md#400-2016-08-08
