### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by wolli2710** [angular-fullstack/generator-angular-fullstack#2431]
One of those questions...
This is not a bug report, it's just a question.
I just wondered why the default server file of socket.io is in the config folder?
Shouldn't it be a separate subfolder like the api folder?

**Comment by Awk34** [comment]
It *could* be, but it also makes sense that it would be in the config folder. It contains the initial Socket.io config for the server. Each route has its *own* socket config in `api/thing/thing.socket.js`.
