### ISSUE TITLE
Trouble installing shrink-ray on generation

### ISSUE THREAD

**Issue by smirciat** [angular-fullstack/generator-angular-fullstack#2441]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack |4.1.1
Node | 6.2.2
npm | 3.9.5
Operating System | Ubuntu 14.04

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS 
Router | ngRoute 
Client Tests | Mocha
DB |  SQL
Auth | Y 

I kept getting node-gyp fallback to build errors on initial generation and subsequent npm install re-tries.  node-gyp was installed -g and I tried several node versions before settling on 6.2.2.  The hangup was always on shrink-ray and its dependency `node-zopfli@1.4.0`.  I was able to install both globally just fine, so finally my workaround was to remove shrink-ray from package.json and copy the global shrink-ray folder to node_modules.  That seems to work just fine, but not sure why I can build this globally but not on node_modules.

**Comment by DanMMX** [comment]
You can check [this](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2309#issuecomment-265545304). That worked for me

**Comment by Awk34** [comment]
@DanMMX @smirciat what about [this possible workaround](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2462#issuecomment-274341701)?

**Comment by DanMMX** [comment]
That might work, however there are other compiled dependencies which aren't causing any problems (at least not any that took me a lot to solve). Don't think that is a good solution, more like a shrink-ray compilation problem due to iltorb. Not an expert on compiled libs, that's why I can't contribute more regarding that 😞

**Comment by yeaske** [comment]
@DanMMX suggestion worked fine for me (CentOS ) for similar issue.

**Comment by smirciat** [comment]
Whatever the issues were with the dependencies, they seem to have resolved.  I can npm install without issue now when starting from scratch.
