### ISSUE TITLE
DI Error when there is no $onInit method in class.  Error: [$injector:strictdi] MasterComponent is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by keithminder** [angular-fullstack/generator-angular-fullstack#2443]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.1
Node | 5.3.0
npm | 3.3.12
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS |  SCSS 
Router | ui-router
Client Tests |  Mocha
DB | MongoDB
Auth | Y

I get the following message when I add a trivial route to my app:
Error: [$injector:strictdi] MasterComponent is not using explicit annotation and cannot be invoked in strict mode
  
The code follows for the module:
```
const angular = require('angular');
const uiRouter = require('angular-ui-router');
import routes from './master.routes';
export class MasterComponent {
  /*@ngInject*/
  constructor($http) {
    
  }


}

export default angular.module('bianchiApp.master', [uiRouter])
  .config(routes)
  .component('master', {
    templateUrl: 'app/master/master.html',
    controller: MasterComponent,
    controllerAs: 'masterCtrl'
  })
  .name;
```

The issue goes error goes away if i add $onInit() method to my class.

The following code works without issue:
```
const angular = require('angular');
const uiRouter = require('angular-ui-router');
import routes from './master.routes';
export class MasterComponent {
  /*@ngInject*/
  constructor($http) {
    
  }

  $onInit(){}

}

export default angular.module('bianchiApp.master', [uiRouter])
  .config(routes)
  .component('master', {
    templateUrl: 'app/master/master.html',
    controller: MasterComponent,
    controllerAs: 'masterCtrl'
  })
  .name;
```
The only difference between the two is that the one that works includes an $onInit method whereas the one without it errors.

Is this a bug?  Is this an angular issue or an angular-fullstack issue?

**Comment by Awk34** [comment]
The annotation is done by [ng-annotate](https://github.com/olov/ng-annotate). It might be a transpiler thing. One surefire way to include the directive is like this:

```js
class MasterComponent {
  constructor() {
    'ngInject';
  }
}
```

**Comment by keithminder** [comment]
I tried that.  I still get the same behavior.  When I include the $onInit(){} method it works.  When I exclude it, I get the same error.

**Comment by keithminder** [comment]
The angular-fullstack generator uses the "/*@ngInject*/" form.  Shouldn't it use the other form?
