### ISSUE TITLE
Using jQuery instead of jQuery lite on AngularJS

### ISSUE THREAD

**Issue by yoshiokatsuneo** [angular-fullstack/generator-angular-fullstack#2445]
I could not find the way to use jQuery instead of jQuery Lite on AngularJS.
AngularJS requires to load jQuery on global scope, but "import" is asynchronous and not in global scope.
I googled, but could not find the way to fit in generator-angular-fullstack.

What is the best practice to use jQuery on AngularJS on generator-angular-fullstack ?

**Comment by Awk34** [comment]
`import` is most definitely **not** async. Also none of our code should mutate the global `window` object on purpose. If you look at the jQuery file that get's installed with npm, you'll see this:

```js
( function( global, factory ) {

	"use strict";

	if ( typeof module === "object" && typeof module.exports === "object" ) {

		// For CommonJS and CommonJS-like environments where a proper `window`
		// is present, execute the factory and get jQuery.
		// For environments that do not have a `window` with a `document`
		// (such as Node.js), expose a factory as module.exports.
		// This accentuates the need for the creation of a real `window`.
		// e.g. var jQuery = require("jquery")(window);
		// See ticket #14549 for more info.
		module.exports = global.document ?
			factory( global, true ) :
			function( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			};
	} else {
		factory( global );
	}

// Pass this if window is not defined yet
} )( typeof window !== "undefined" ? window : this, function( window, noGlobal ) {

...

if ( !noGlobal ) {
	window.jQuery = window.$ = jQuery;
}

return jQuery;
})
```

This will attach the jQuery globals to the `window`. As long as you `require`/`import` jQuery **before** Angular, it will be available on the window.

**Comment by yoshiokatsuneo** [comment]
@Awk34 Thanks !
I tried to add "import 'jquery'" in the beginning of "app.js" like below.
```
import 'jquery';
import angular from 'angular';
```
But it does not work because angular is built as "vendor.bundle.js", while other libraries are built as "app.bundle.js", and the "vendor.bundle.js" is loaded before "app.bundle.js".

So, now,  I added 'jquery' on "webpack.make.js" like below(without adding "import jquery" to app.js"), to build jquery as "vendor.bundle.js", and it works.
```
        config.entry = {
            app: './client/app/app.js',
            polyfills: './client/polyfills.js',
            vendor: [
                'jquery',
                'angular',
                ...
```

And yes, how modules are loaded with "import" looks not being defined in the specification but up to the module loader, but practically it looks definitive.

**Comment by Awk34** [comment]
Ah yes, it seems correct that you would also need to make sure jquery comes before angular in the vendor bundle.

ECMA-262 clearly defines the `import`/`export` syntax as static. If you're interested in a proposal for a dynamic `import()` function, see https://github.com/tc39/proposal-dynamic-import

**Comment by yoshiokatsuneo** [comment]
@Awk34 Just a curious, but may I hear where may I read that ```import``` is static ?

**Comment by Awk34** [comment]
http://www.ecma-international.org/ecma-262/7.0/index.html#sec-imports-static-semantics-importentries

**Comment by yoshiokatsuneo** [comment]
@Awk34 Thanks ! I see that the ```import``` line itself is parsed before running the script.

**Comment by aabm00** [comment]
Hi

I am just starting with the generator  version 4.2.2 and webpack trying to upgrade a project made with version 3.7.6.
I use the component  **angular-bootstrap-datetimepicker**  and it need jquery and bootstrap to run.

I have installed

> npm install jquery --save
> npm install angular-bootstrap-datetimepicker –save
> bootstrap is already installed. 
 
Following the comments in this post I did:

In **webpack.make** I only added jquery before angular in vendor.

    if(TEST) {
        config.entry = {};
    } else {
        config.entry = {
            app: './client/app/app.ts',
            polyfills: './client/polyfills.ts',
            vendor: [
                'jquery',
                'angular',
                ... 
                'lodash',
            ]
        };
    }

In **app.ts** I imported bootstrap.min.js and angular-bootstrap-datetimepicker and added the  angular-bootstrap-datetimepicker as dependency in the application module

    import 'bootstrap/dist/js/bootstrap.min.js';
    import 'angular-bootstrap-datetimepicker';
  
    import './app.css';

    angular.module('TGMApp', [
      ngCookies,
      .......
      uiRouter,
      uiBootstrap,
      util,
      'ui.bootstrap.datetimepicker'
])

In **app.css** I added 

     @import '~angular-bootstrap-datetimepicker/src/css/datetimepicker.css';

Then I run **gulp serve** and I get this message in the browser:

    bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
        at Object.<anonymous> (bootstrap.min.js:6)
        at __webpack_require__ (bootstrap 259bd1e…:52)
        at Object.<anonymous> (app.ts:30)
        at __webpack_require__ (bootstrap 259bd1e…:52)
        at webpackJsonpCallback (bootstrap 259bd1e…:23)
        at app.bundle.js:1

I don't know what I missed.

In the other hand in version 3.7.6 we can see all the imported files easily in index.html  where I can see them in the 4.2.2?

And another doubt would be What dependecies must be placed in app.ts and what in webpack.make (config.entry.vendor) ?

Thanks

**Comment by aabm00** [comment]
Hi

I solve the problem. I use the **ProvidePlugin** in the **webpack.make** to inject implicit globals. So

In **webpack.make** I didn't added jquery before angular in vendor instead I added jquery via **ProvidePlugin **  in the BUILD and DEV options:

    if(BUILD) {
        config.plugins.push(
             ....
            // Reference: https://webpack.github.io/docs/list-of-plugins.html#defineplugin
            // Define free global variables
            new webpack.DefinePlugin({
                'process.env': {
                    NODE_ENV: '"production"'
                }
            }),
            new webpack.ProvidePlugin({
                $: "jquery",
                jQuery: "jquery"
            })
        );
    }

    if(DEV) {
        config.plugins.push(
            // Reference: https://webpack.github.io/docs/list-of-plugins.html#defineplugin
            // Define free global variables
            new webpack.DefinePlugin({
                'process.env': {
                    NODE_ENV: '"development"'
                }
            }),
            new webpack.ProvidePlugin({
                $: "jquery",
                jQuery: "jquery"
            })
        );
    }

In **app.ts** I imported bootstrap.min.js and angular-bootstrap-datetimepicker and added the angular-bootstrap-datetimepicker as dependency in the application module

    import 'bootstrap/dist/js/bootstrap.min.js';
    import 'angular-bootstrap-datetimepicker';

    import './app.css';

    angular.module('TGMApp', [
      ngCookies,
      .......
      uiRouter,
      uiBootstrap,
      util,
      'ui.bootstrap.datetimepicker'
    ])

In **app.css** I added

     @import '~angular-bootstrap-datetimepicker/src/css/datetimepicker.css';

And now it works fine !!!
