### ISSUE TITLE
404 for html templates when I run gulp serve:dist

### ISSUE THREAD

**Issue by keithminder** [angular-fullstack/generator-angular-fullstack#2446]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.1
Node | 5.3.0
npm | 3.3.12
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | SCSS
Router | ui-router
Client Tests | Jasmine
DB | MongoDB 
Auth | Y 

I looks like most of my html files are missing when I run gulp serve:dist.

I notice that for the ones that are missing the module definitions look like:
export default angular.module('bianchiApp.doors', [uiRouter])
  .config(routes)
  .component('doors', {
    templateUrl: 'app/doors/doors.html',
    controller: DoorsComponent,
    controllerAs: 'doorsCtrl'
  })
  .name;

while the ones that work fine are defined like this:
export default angular.module('bianchiApp.materials', [uiRouter])
  .config(routes)
  .component('materials', {
    template: require('./materials.html'),
    controller: MaterialsComponent,
    controllerAs: 'materialsCtrl'
  })
  .name;

I dont understand why the generator is putting out ones with "templateURL" vs "template" which work fine.

**Comment by Awk34** [comment]
The server does not serve out the HTML files for the client. Instead, we `require` them, and webpack will basically just inline the HTML text. This means that there are no extra HTTP requests for template files, which aids HTTP/1.1 speeds. If you look in the [`webpack.make.js file, here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/4.1.1/templates/app/webpack.make.js#L195-L199), you can see that HTML requires just use the webpack raw-loader (which just spits the file out as raw text).
