### ISSUE TITLE
Font-awesome Fonts work in gulp serve:dist but not on gulp serve

### ISSUE THREAD

**Issue by ajai-sandy** [angular-fullstack/generator-angular-fullstack#2450]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.1
Node | 6.2.2
npm | 3.9.5
Operating System | Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS
Router |  ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 

Font-awesome works well in **gulp serve:dist** mode or replacing the fonts import with maxCDN, but fonts are not displaying in normal **grunt serve** mode. I have not changed the default setup related to the fonts.
Thanks in advance.

**Comment by Awk34** [comment]
See #2188

**Comment by MichaelJCole** [comment]
Hey, if you're getting this with: `npm start`, it seems to be designed to work after `gulp build`.  If you want to test during development, use `gulp serve`
