### ISSUE TITLE
DynamoDB support

### ISSUE THREAD

**Issue by devmanny** [angular-fullstack/generator-angular-fullstack#2454]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

**Is there any plan to integrate Amazon DynamoDB?**
I think it's a great database and it has a low cost

**Comment by Awk34** [comment]
There is no plan to, but I'll take this as a feature requests / offer to submit. Feel free to discuss adding this more.
