### ISSUE TITLE
Signup page Password Matching not working

### ISSUE THREAD

**Issue by rohanshar** [angular-fullstack/generator-angular-fullstack#2457]
The implementation of match using angular-validation-match in /signup page seems to be not working. Its not throwing the password mismatch error. 

 - [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 6.9.1
npm | 4.0.2
Operating System | Ubuntu 14

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS
Router | ngRoute
Client Tests | Jasmine
DB | MongoDB
Auth | Y

**Comment by imornar** [comment]
I had that issue myself.

What I did is just uncomment line 12 at file /client/app/app.js (for 'angular-validation-match' package) and add it as dependency for bootstraped module in the same file.

Hope it will help.

**Comment by Awk34** [comment]
closed by #2516
