### ISSUE TITLE
Using bower with the typescript version

### ISSUE THREAD

**Issue by sethu4acellere** [angular-fullstack/generator-angular-fullstack#2458]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.2
Node | 6.9.1
npm | 40.05
Operating System | Windows 7

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | Pug
CSS | SCSS 
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y 

So I am not sure if this is an issue, in the babel version I used to specify any external dependencies in my bower.json and the modules would be injected and installed.

Can I use bower for the typescript version, I assume many such bower components don't have a typings

**Comment by Awk34** [comment]
Bower is not officially supported in 4.x.x+. You can still use it if you wish, though. Since 4.x.x uses webpack, the suggested package manager is npm, but there are [webpack docs for using it with bower](http://webpack.github.io/docs/usage-with-bower.html)

**Comment by sethu4acellere** [comment]
I ended up using 
https://github.com/lpiepiora/bower-webpack-plugin

I understand that bower is becoming obsolete in few years so this move was taken. Few current angular 1.x.x packages can be installed only via bower.
