### ISSUE TITLE
awesome-typescript-loader and DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.

### ISSUE THREAD

**Issue by nstuyvesant** [angular-fullstack/generator-angular-fullstack#2461]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 6.9.4
npm | 4.1.1
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | Pug
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | PostgreSQL
Auth | Y

Whenever I did a gulp serve, was getting:
(node:20751) DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:20751) DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.

I updated awesome-typescript-loader from 0.17.0 to 2.2.4 and it got rid of these warnings. Tracked it down by adding " --trace-deprecation".

But since I'm using Babel and not TypeScript, this had no impact for me but wondering if anyone using TypeScript has tried this and found it not to cause problems. If so, perhaps it would make sense to have the generator default to specify awesome-typescript-loader 2.2.4?

**Comment by Awk34** [comment]
The [changelog](https://github.com/s-panferov/awesome-typescript-loader/blob/master/CHANGELOG.md) doesn't seem to show any breaking changes for 1.0.0 or 2.0.0, so I would assume it would be pretty safe.

**Comment by Awk34** [comment]
#2465

**Comment by Awk34** [comment]
#2466

**Comment by Awk34** [comment]
Actually, it appears the latest version is incompatible with webpack 1.x.x
