### ISSUE TITLE
Adding sass source maps for 3.7.x version

### ISSUE THREAD

**Issue by saeidalidadi** [angular-fullstack/generator-angular-fullstack#2468]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.x
Node | 6.9.x
npm | 3.10.x
Operating System |  Ubuntu 16.04 

Item | Answer
----- | -----
Transpiler | Babel
Markup | Pug
CSS |  SCSS
Router |  ui-router
Client Tests |  Mocha
DB | MongoDB 
Auth | Y / N
etc | etc

I am not familier a lot with `Grunt` and I want to add `source maps` to `sass` files.
How I can change the `Gruntfile` to reach this goal?

**Comment by Awk34** [comment]
Add `sourceMap: true` to the options, [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.6/templates/app/Gruntfile(grunt).js#L686-L688)
