### ISSUE TITLE
please check your gh-pages,

### ISSUE THREAD

**Issue by KwakYeongCheol** [angular-fullstack/generator-angular-fullstack#2473]
hi, please check your gh-pages,

what is true link?
a > https://angular-fullstack.github.io/
b > https://angular-fullstack.github.io/generator-angular-fullstack/

all of resource's link is broken!

I re-build it, docs > template.ejs

remove '/generator-angular-fullstack'

**Comment by Awk34** [comment]
Hey, thanks for the report! I'm not sure how those got back in there, but I just fixed it on *master*, it should be redeployed here in a few minutes..

**Comment by Awk34** [comment]
It appears to be fixed now.
