### ISSUE TITLE
Should mocha unit tests call done()?

### ISSUE THREAD

**Issue by nstuyvesant** [angular-fullstack/generator-angular-fullstack#2478]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.2
Node | 6.9.4
npm | 4.1.2
Operating System | OS X 10
Mocha | 3.2.0

Item | Answer
----- | -----
Transpiler | Babel
Markup | Pug
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | PostgreSQL
Auth | Y

The generated mocha tests do not call done(). See [this posting on StackOverflow](http://stackoverflow.com/questions/35656837/ensure-the-done-callback-is-being-called-in-this-test-mocha-chai-sinon).

Would it make sense to add it to generated tests? For example...
```
  describe('DELETE /api/things/:id', function() {
    it('should route to thing.controller.destroy', function(done) {
      expect(routerStub.delete
        .withArgs('/:id', 'thingCtrl.destroy')
        ).to.have.been.calledOnce;
      done();
    });
  });
```

Mocha is new for me so my apologies if this request seems naive.

**Comment by Awk34** [comment]
That's only needed if you're doing some async stuff in a test that uses callbacks. The routerStub stuff should by synchronous. Any async tests we run either run `done()`, or return a promise, which mocha accepts.
