### ISSUE TITLE
Mongoose@4.8.0 causes issues

### ISSUE THREAD

**Issue by sagyeli** [angular-fullstack/generator-angular-fullstack#2479]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.2
Node | 4.5.0
npm | 3.10.2
Operating System | Windows 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

Please be aware: the following event on thing.events.js does not work: `Thing.schema.post(e, emitEvent(event));`, since Thing.schema.post event is not triggered with mongoose@4.8.0

**Comment by Awk34** [comment]
Are you sure there is a Mongoose issue here? I don't see anything breaking in the [4.8.0 changelog](https://github.com/Automattic/mongoose/blob/master/History.md#480--2017-01-28)

**Comment by gordonaspin** [comment]
+1 I had same problem with Thing.schema.post(e, emitEvent(event)) not emitting events in mongoose 4.8.1, downgraded to mongoose 4.7.7 and everything ok. Also, I would suggest adding ghostMode: false to the browsersync config in server/config/express.js as the default.

**Comment by Awk34** [comment]
Have either of you submitted a bug report to Mongoose yet?

**Comment by gordonaspin** [comment]
I did not. I wasn’t sure it was mongoose at fault or not. I’m kind of new to fullstack and not confident I could pull together a stand-alone example of the event emitting not working.

**Comment by Awk34** [comment]
From reading this bug report, it seems like there might have been an unintended breaking API change in mongoose 4.8.0

**Comment by EliKrumholz** [comment]
I think I was able to replicate the bug, I opened an issue with mongoose: https://github.com/Automattic/mongoose/issues/4955

**Comment by EliKrumholz** [comment]
From the Mongoose folks:

> mutating the underlying schema after the Thing model has been created by mongoose.model() isn't a supported behavior. Make sure you define all your hooks before calling mongoose.model()

@Ernisto has a solution in #2491 that does just that.

**Comment by akoudal** [comment]
Downgrading to 4.7.9 solved it for me too, but @Ernisto looks more correct.

**Comment by Awk34** [comment]
@Ernisto do you thing you might submit a Pull Request for your fix?

**Comment by Climax777** [comment]
+1 for the @Ernisto fix

**Comment by Ernisto** [comment]
@Awk34 Yes it would be Great! But I need some time to create Pull Request according to rules and best practices.
