### ISSUE TITLE
How to add external dependency 

### ISSUE THREAD

**Issue by gladsonqb** [angular-fullstack/generator-angular-fullstack#2480]
Have added ui-grid to the app using npm install angular-ui-grid
How to add the css file of this plugin to our app.
Am using gulp, webpack ..
any help please.

**Comment by Awk34** [comment]
#2386

**Comment by gladsonrobinson** [comment]
@Awk34 After adding it with npm the js part is ok. What in case of css files coming along with the package.  How to include these css. Our whole app uses scss,

**Comment by Awk34** [comment]
@gladsonrobinson 
```scss
@import '~some_npm_package/styles.css`;
```
