### ISSUE TITLE
Not able to delete the default list items from the new build.

### ISSUE THREAD

**Issue by dylannnn** [angular-fullstack/generator-angular-fullstack#2484]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.2
Node | 6.9.5
npm | 3.10.10
Operating System | Windows 10

Today, I use yo to update my "Angular Fullstack". However, with the latest new build, there seems a bug.

The issue is, after the new build and run "gulp serve", in the default demo, I'm not able to delete the items. But the CMD console says deleted.

If I refresh the page, then the item is gone.

Not sure what's the issue but I'm afraid to use the latest version.

Best,
![sample](https://cloud.githubusercontent.com/assets/6026590/22527537/ed8f5e24-e8cf-11e6-9411-15e14755ba79.gif)

**Comment by Awk34** [comment]
This has to be an issue with your websocket connection. The creation / deletion of Things is done via HTTP, but the auto-updating of the Things on the front-end is communicated through WebSockets (socket.io)

**Comment by Awk34** [comment]
Try setting some breakpoints in `client/components/socket/socket.service.js` to start some investigation

**Comment by Ernisto** [comment]
#2479

**Comment by Ernisto** [comment]
Seems like related to #2479

**Comment by dylannnn** [comment]
Yes, It's related to #2479 ! 
I've downgrade Mongoose to v4.7.7  and the issue been fixed. Thanks

**Comment by Awk34** [comment]
Alright, I'll close this issue to keep the discussion there.
