### ISSUE TITLE
Fonts not working after serve:dist

### ISSUE THREAD

**Issue by nutanlade** [angular-fullstack/generator-angular-fullstack#2494]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 5.4.1
npm | 3.10.4
Operating System 	| OS X 10
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS | SCSS 
Router | ngRoute 
Client Tests | Jasmine
DB | MongoDB
Auth | Y
etc | etc

My application is working perfectly with fontawesome, simple line icons and glyphicons with gulp serve. But when I'm using serve:dist I see 404 errors in console for fonts. I have to manually copy fonts folder and bower_components to dist folder to work. Is there any work around apart from copying manually.

My code from app.scss is below.
`$fa-font-path: "../bower_components/fontawesome/fonts";
@import '../bower_components/fontawesome/scss/font-awesome';
@import '../bower_components/simple-line-icons/scss/simple-line-icons';`

**Comment by Awk34** [comment]
This should be taken care of automatically by the `copy:fonts` task: https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.8.0/templates/app/gulpfile.babel(gulp).js#L664-L668

**Comment by nutanlade** [comment]
Thanks @Awk34 . Worked after tweatking copy:fonts task to copy fontawesome and fonts folder to dist/client location.
