### ISSUE TITLE
UNMET PEER DEPENDENCY rxjs and zone.js (alpha)

### ISSUE THREAD

**Issue by klemensz** [angular-fullstack/generator-angular-fullstack#2495]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-alpha.4
Node | v6.9.4
npm | 3.10.10
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | Pug
CSS | Sass
Router | ngRoute
Client Tests | Mocha
DB | MongoDB
Auth | Y

When running `$ npm install -g yo generator-angular-fullstack@alpha` and then `$ yo angular-fullstack` with the settings from above I get the following messages:

```
├─┬ UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
...
└── UNMET PEER DEPENDENCY zone.js@0.6.26
```
```
npm WARN angular2-jwt@0.1.28 requires a peer of rxjs@^5.0.0 but none was installed.
npm WARN @angular/http@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@3.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.6 requires a peer of zone.js@^0.7.2 but none was installed.
```

In package.json I see:

```
  "devDependencies": {
    ...
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.25",
    ...
```

**Comment by jeepcreep** [comment]
as of today I'm running into the same issue with node 6.10.0 and npm 3.10.10:

`npm WARN @angular/core@2.4.9 requires a peer of zone.js@^0.7.2 but none was installed.`

using ng2/less/express and node both for coding and transpiling

**Comment by Awk34** [comment]
^ see this commit

**Comment by Awk34** [comment]
This was kind of a breaking change between minor Angular versions. Check the `package.json` for the specific version of Angular you're using, ex `2.4.9` uses `rxjs` `^5.0.1` (https://github.com/angular/angular/blob/2.4.x/package.json)

**Comment by Awk34** [comment]
^this one's better. Explicitly use Angular 2.4.x, which updates rxjs to ^5.0.1

**Comment by jeepcreep** [comment]
thanks @Awk34 ...the point really is not what to explicitly use or not but that this is the consequence of a usually totally-automatic process when I do

`yo ng-fullstack`

as a normal user I would expect to have a smooth workflow coming through and not an error that somehow of course could be fixed when manually choosing some specific version or what-not... ng-fullstack is not about choosing that versions over another one but answering a little bunch of questions and then have a boilerplate webapp up and running.

but, thanks anyways! ;)

**Comment by Awk34** [comment]
That's the point of that last commit I made. Once a new Alpha is released, you won't run into this issue anymore.
