### ISSUE TITLE
Getting Started hyperlink is a 404

### ISSUE THREAD

**Issue by wemiao** [angular-fullstack/generator-angular-fullstack#2501]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by wemiao** [comment]
![getting started bug](https://cloud.githubusercontent.com/assets/16315883/23074881/46fae156-f4ef-11e6-8a45-5a30361b6221.PNG)

This link on the readme is still broken.

**Comment by wemiao** [comment]
![bug image](https://cloud.githubusercontent.com/assets/16315883/23074962/9929ac0a-f4ef-11e6-897d-126aeb4e184e.PNG)

The picture on the top of the github readme is also missing

**Comment by Awk34** [comment]
Fixed
