### ISSUE TITLE
Karma tests not running

### ISSUE THREAD

**Issue by melo0187** [angular-fullstack/generator-angular-fullstack#251]
From what I understand angular-fullstack generates both server tests for mocha and client tests for karma. For a newly generated app - after fixing both Gruntfile.js (see #247) and  karma.conf.js (see #248) - I get following error when running <code>grunt test</code> :

```
[...]
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.10.10 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Linux)]: Connected on socket uyLE9920uagXDkUA7XIC
PhantomJS 1.9.7 (Linux): Executed 0 of 0 ERROR (0.149 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.
[...]
```

It's strange to read <code>Executed 0 of 0</code> since from what I understand there is  a unit test. Does this mean that karma is failing to prepare test execution? How can I further investigate?

Thanks in advance!

**Comment by minmur** [comment]
I also had similar issue, but found out that newly installed bower_components were not loaded. Don't know if generator is meant to add them to karma.conf.js automatically, but i added manually and it works now.

**Comment by MillerRen** [comment]
please remove angular-scenario.js.

**Comment by ben-ids** [comment]
@minmur I had a similar problem - missing includes in karma.conf as bower didn't add them automatically. Your comment saved me some trouble, thank you.

**Comment by mikefisher84** [comment]
Wow @MillerRen thanks so much for this. I was banging my head against the wall debugging karma (I inherited an old repo) and heaving angular-mocks in my bower.json was breaking my tests.

**Comment by Shawful** [comment]
I was able to fix this error by adding the following to my karma.conf.js file:

<code>   
 // list of files / patterns to exclude

    exclude: [
      "**/*.git",
      "**/angular-scenario.js"
    ],
</code>


The trick was to exclude angular-scenario.js, but I'm not sure why.  If anyone knows, please share.

Cheers!

**Comment by Shawful** [comment]
I mean, I know angular-mocks is for unit tests and angular-scenario is for end to end tests... so maybe a conf.js file cannot contain both without this error occurring....  Either way the error message needs to be improved.

**Comment by mikefisher84** [comment]
@Shawful Angular scenario runner is deprecated. You want to be using Protractor

**Comment by Shawful** [comment]
I don't understand.  How exactly would I go about making the switch?

**Comment by Shawful** [comment]
Okay, so I found some docs (linked below).  I imagine I would download the grunt-protractor runner using NPM (node package manager) from the command line, add the protractor task to my "grunt test" task list, and set it up to call it's own protractor config file and test files.  Does that sound right?

Grunt Protractor Runner - NPM
https://www.npmjs.com/package/grunt-protractor-runner

Getting Started with Protractor
https://angular.github.io/protractor/#/

**Comment by Shawful** [comment]
oh and I would need to remove any references to angular-scenario.js from my original karma.conf.js file too.

**Comment by Shawful** [comment]
My team is working on AngularJS version 1.2.28 and hasn't made the move to 1.3.x yet.  How do I find out if protractor works with 1.2.28?

**Comment by henrichsson** [comment]
I have a persisten problem:

Running "karma:unit" (karma) task
WARN [karma]: Port 8080 in use
INFO [karma]: Karma v0.12.37 server started at http://localhost:8081/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket Av5C7bRBz2eyogyWTzrp with id 17632309
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.

I do not understand what is wrong here??

**Comment by vivekwisdom** [comment]
Still no solution, I have gone through all the suggestions above.. Chrome browser is opening and immediately closing..

```
Running "wiredep:test" (wiredep) task

Running "karma:unit" (karma) task
16 02 2016 07:06:19.221:INFO [karma]: Karma v0.13.20 server started at http://localhost:8080/
16 02 2016 07:06:19.236:INFO [launcher]: Starting browser Chrome
16 02 2016 07:06:22.416:INFO [Chrome 48.0.2564 (Linux 0.0.0)]: Connected on socket /#QsrP_HYzeu4Pjk6LAAAC with id 67562059
Warning: Task "karma:unit" failed. Used --force, continuing.

Done, but with warnings.

```

Really appreciate any help.

**Comment by zyxue** [comment]
Still no fix?

**Comment by megamindbrian** [comment]
Doesn't run from command-line when autoWatch: false is set.
