### ISSUE TITLE
Error: CSRF token missing

### ISSUE THREAD

**Issue by nutanlade** [angular-fullstack/generator-angular-fullstack#2511]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack 	|3.7.6
Node 	|5.4.1
npm 	|3.10.4
Operating System 	|OS X 10
etc 	|etc

Item 	|Answer
----- | -----
Transpiler 	|Babel
Markup 	|HTML
CSS 	|SCSS
Router 	|ngRoute
Client Tests 	|Jasmine
DB 	|MongoDB
Auth 	|Y
etc 	|etc

I'm facing below issue while trying to access /api/auth/local from mobile app.

```
Error: CSRF token missing
    at checkCsrf (/Users/nutan/Desktop/Guwha/Guwha-devbranch/guwha/node_modules/lusca/lib/csrf.js:89:18)
    at /Users/nutan/Desktop/Guwha/Guwha-devbranch/guwha/node_modules/lusca/index.js:48:21
    at hsts (/Users/nutan/Desktop/Guwha/Guwha-devbranch/guwha/node_modules/lusca/lib/hsts.js:25:9)
    at /Users/nutan/Desktop/Guwha/Guwha-devbranch/guwha/node_modules/lusca/index.js:48:21
    at xframe (/Users/nutan/Desktop/Guwha/Guwha-devbranch/guwha/node_modules/lusca/lib/xframes.js:12:9)
    at /Users/nutan/Desktop/Guwha/Guwha-devbranch/guwha/node_modules/lusca/index.js:48:21
```

My login code is below. I'm using nativescript for mobile application.

```
login(user: User) {
  let headers = new Headers();
  headers.append("Content-Type", "application/json");

  return this.http.post(
    Config.apiUrl + "auth/local",
    JSON.stringify({
      email: user.email,
      password: user.password,
      grant_type: "password"
    }),
    { headers: headers }
  )
  .map(response => response.json())
  .do(data => {
    Config.token = data.Result.access_token;
  })
  .catch(this.handleErrors);
}
```

My express.js code is below.

```
if ('test' !== env) {
    app.use(lusca({
      csrf: {
        angular: true
      },
      xframe: 'SAMEORIGIN',
      hsts: {
        maxAge: 31536000, //1 year, in seconds
        includeSubDomains: true,
        preload: true
      },
      xssProtection: true
    }));
  }
app.use( function( req, res, next ) {
    res.cookie('XSRF-TOKEN', res.locals._csrf );
    next();
});

My app.js code is below.

```
// CORS (Cross-Origin Resource Sharing) headers to support Cross-site HTTP requests
 app.all('*', function(req, res, next) {
     res.cookie('XSRF-TOKEN', res.locals._csrf );
     res.header("Access-Control-Allow-Origin", "*");
     res.header("Access-Control-Allow-Headers", "X-Requested-With");
     next();
 });

Can someone please help in resolving this issue.
```
```

**Comment by atodicebear** [comment]
Is it similar to this #2224  ?
Your Project Opens first the Login Page and you want to Log In but the Token is missing an it is working after second attempt to Log In?

**Comment by nutanlade** [comment]
@atodicebear I also referred to that issue initially and tried solutions mentioned there. But still not working. I also even tried twice from my mobile app to login even that also didn't worked.

**Comment by Awk34** [comment]
@nutanlade If this is blocking you, you can just disable CSRF checks until this is figured out

**Comment by anudeepjusanu** [comment]
Go to your .\server\config\express.js and either change xssProtection to false or add an 'development' !== env to the if statement:

if ('test' !== env && 'development' !== env) { // <- add development env here
    console.log("using lusca");

    app.use(lusca({
      csrf: {
        angular: true
      },
      xframe: 'SAMEORIGIN',
      hsts: {
        maxAge: 31536000, //1 year, in seconds
        includeSubDomains: true,
        preload: true
      },
      xssProtection: true // <- or change this to false
    }));
  }

**Comment by nutanlade** [comment]
@anudeepjusanu I'm in production phase. Is there any logic so that I can send some token for authentication  from mobile app?

**Comment by smirciat** [comment]
@nutanlade I just finished doing a mobile front-end attached to my generated app.  I followed this advice: https://github.com/angular-fullstack/generator-angular-fullstack/issues/1582#issuecomment-273192615 .  It worked fine, I did not understand at first that I needed to change in express.js  to 
```
app.use(lusca({
      csrf: false,
      xframe: 'SAMEORIGIN',
      hsts: {
        maxAge: 31536000, //1 year, in seconds
        includeSubDomains: true,
        preload: true
      },
```
The rest I was able to follow, but making mobile only routes to add above app.use(lusca.csrf({angular:true})) took some thought.  I ended up making an indexMobile.js file in each endpoint folder as a mirror of the original index.js file there.  Then added the route above the lusca add in routes.jslike this:
```
app.use('/api/things/mobile', require('./api/thing/indexMobile'));
app.use(lusca.csrf({angular:true}));
app.use('/api/things', require('./api/thing'));
```
Nob my mobile app can access the routes with /mobile at the end of the api, and I can control what the mobile app can access without CSRF.  Hope this helps.

**Comment by radianz** [comment]
Any joy with this issue?

**Comment by viewplatgh** [comment]
Got hit by this error after I just use mysql configs instead of sqlite.

**Comment by Awk34** [comment]
#2613 merged

**Comment by rombernardino** [comment]
I changed the name to app.template.html and app.html, but it's still not working.

**Comment by tuanzhang7** [comment]
same here, change to app.template.html issue still there

**Comment by rohita77** [comment]
does not work for 
gulp build followed by gulp serve:dist

works for npm run start:server , npm run start:client

**Comment by koraysels** [comment]
OKay, this is not working.. Th eonly way to get it to work when you build for production with gulp build is to remove this 
```
  app.use(lusca({
            csrf: {
                header: 'x-xsrf-token',
            },
            xframe: 'SAMEORIGIN',
            hsts: {
                maxAge: 31536000, //1 year, in seconds
                includeSubDomains: true,
                preload: true
            },
            xssProtection: true
        }));
```

from `server/config/express.js`
