### ISSUE TITLE
Gulp build:images path not specified 

### ISSUE THREAD

**Issue by almgwary** [angular-fullstack/generator-angular-fullstack#2512]
build failed in Task `Gulp build:images `
this path not valid `images: ${clientPath}/assets/images/**/*`

**Comment by almgwary** [comment]
it worked when change path to images: `${clientPath}/assets/images/`,`

**Comment by almgwary** [comment]
it worked when change path to `images: ${clientPath}/assets/images/`
in `gulp.bable.js` file

**Comment by stephengardner** [comment]
Fix me!
