### ISSUE TITLE
Error: Cannot find module 'babel-register'

### ISSUE THREAD

**Issue by ashuSvirus** [angular-fullstack/generator-angular-fullstack#2523]
HI. trying to deploy my code. using gulp serve:dist to create the dist folder.
build successful( * no errors thrown)
pasted the dist folder to ec2 instance.
starting the index.js file with pm2.
i get an error in the pm2 logs.

> Error: Cannot find module 'babel-core/register' at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Module.require (module.js:353:17) at require (internal/module.js:12:17) at Object.<anonymous> (/home/ubuntu/dist/server/index.js:8:3) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Function.Module._load (module.js:300:12) at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js

i even tried with bable-register in package.json under devDependencies

**Comment by stherrienaspnet** [comment]
Hello ashuSvirus, could you provide the usual information about the generator version and your current configuration please.

**Comment by ashuSvirus** [comment]
```
generatorVersion: 4.1.2,
filters": {
      "js": true,
      "babel": true,
      "flow": false,
      "html": true,
      "css": true,
      "uirouter": true,
      "bootstrap": false,
      "uibootstrap": false,
      "models": true,
      "mongooseModels": true,
      "mongoose": true,
      "jasmine": true,
      "mocha": false,
      "should": false,
      "expect": false
    }
```

with webpack.make

I am not configuring much with this generator at the moment.
Using gulp for building and serving.

**Comment by ashuSvirus** [comment]
installed node-gyp with root.
now its working.
