### ISSUE TITLE
Please update Readme.md file Generator links

### ISSUE THREAD

**Issue by Den368** [angular-fullstack/generator-angular-fullstack#2525]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

You have changed the directory and didn't update the readme file.
Please update the README.MD file. Just add `content/` to path for example for "Server Side angular-fullstack:endpoint" : 
https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/docs/content/generators/endpoint.md

**Comment by Awk34** [comment]
thanks
