### ISSUE TITLE
method SendIndex in StaticDispatcher class not invoked!

### ISSUE THREAD

**Issue by zetekla** [angular-fullstack/generator-angular-fullstack#2531]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.4
Node | v6.9.2
npm | 3.10.9
Operating System | OS X 10 El Capitan
etc | etc

Item | Answer
----- | -----
TypeScript
HTML
SCSS
Router
Client Tests | Jasmine / Mocha
MongoDB
Auth | Y

vcs at
https://github.com/zetekla/mean2fullstack

Unable to kickstart the app using `npm run dev`, the method SendIndex in StaticDispatcher class is not invoked. It could be a stream problem, Gulp finished the tasks earlier than invoking SendIndex (stream >> Promise issue).

Result in:
Error: ENOENT: no such file or directory, open '/Users/pristinetran/phuc/test/mean2-fullstack/index.html'

This line is not displayed in the console.
https://github.com/zetekla/mean2fullstack/blob/master/server/commons/static/index.ts#L15

**Comment by Awk34** [comment]
It does not appear that your project was scaffolded with generator angular fullstack

**Comment by zetekla** [comment]
I did use the generator with Typescript for both client and server sides. I added console.log to check if the method gets invoked.

**Comment by Awk34** [comment]
I looked at the github project you linked, and it is very clearly not related to this project at all.

**Comment by zetekla** [comment]
My bad. sorry. thank you for your prompt reply.
