### ISSUE TITLE
How to add angular dependencies from cdn network?

### ISSUE THREAD

**Issue by saeidalidadi** [angular-fullstack/generator-angular-fullstack#2538]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

I am not using this generator currently, but I will use it for next project and for now I am wondering for using angular dependencies from cdn network.

**Comment by Awk34** [comment]
The easiest way would just be to add another `<script>` tag to your HTML, with the `url` being the CDN url you want

**Comment by Awk34** [comment]
Here's the link to the Webpack docs: https://webpack.js.org/configuration/externals/#externals
