### ISSUE TITLE
socket.SyncUpdate does not works Heroku

### ISSUE THREAD

**Issue by elmeerr** [angular-fullstack/generator-angular-fullstack#2542]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

I fully understand the guides but I don't know how to be explicit about this issue and I just want to ask to see if any of you can help me with it:

I use an old version of the generator to create my app. now everything works as expected in my local machine but I noticed today that, after I deploy to heroku, the socket.syncUpdates stop working. I try to figured out by myself but until now, no success.

I just came here to know if do you guy has any idea what could be the problem. (if you want to me to provide any piece of code, just let me know, I can't even think what could be helpfull with my situation.)

**Comment by Awk34** [comment]
which generator version did you use?

**Comment by elmeerr** [comment]
@Awk34 sorry for taking too long to answer...I used at the time, the version 3.0.2...(more or less on december 2015) (I've updated the version later - and I don't remember which is now - but the socket code was generated by the 3.0.2)...I remember seeing syncUpdates working on Heroku...but I just noticed now that is not working anymore. (I still use grunt to build to Heroku)...maybe this is a Heroku issue, I just came here to ask because maybe you can help me better to figured out what could be the problem.

Kind regards.

**Comment by elmeerr** [comment]
I figured out that the problem is related to this bug #2479 .

Closing.
