### ISSUE TITLE
Error: Module '"lodash"' has no default export.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [angular-fullstack/generator-angular-fullstack#2549]
- [*] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

I just installed the latest generator-angular-fullstack@4.2.0.
And, I just generated a project as a TypeScript project.
Then, "gulp serve" cause error like:

```
[default] /private/tmp/yots3/client/components/auth/auth.service.ts:3:8 
    Module '"lodash"' has no default export.
[default] /private/tmp/yots3/client/components/auth/auth.service.ts:192:14 
    Supplied parameters do not match any signature of call target.
```

Item | Version
----- | -----
generator-angular-fullstack | 4.2.0
Node | 6.10.2
npm | 3.10.10
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

**Comment by Awk34** [comment]
I assume this is because we are importing it as `import _ from 'lodash'`, which is the syntax for import the `default export`, but the regular `lodash` module uses `commonjs` exports, not ES2015 `import`/`export`s

**Comment by davemaude** [comment]
I have this issue too. I changed it to read `import * as _ from "lodash";` but that didn't resolve the second error regarding supplied parameters not matching any signature of call target. Is there any incompatibility between angular-fullstack and lodash?

**Comment by kailanjian** [comment]
I had the same issue. I used@davemaude's fix and (it looks like) it worked. The auth checks were not working correctly with the default code generated so maybe this should be changed?

**Comment by albert-92** [comment]
Would be great if the generator gets updated with that fix soon.

It took me 1/2 an hour to figure out what was going on.

**Comment by OBout** [comment]
+1
