### ISSUE TITLE
yo angular-fullstack :error spawn yarn ENOENT

### ISSUE THREAD

**Issue by srilives** [angular-fullstack/generator-angular-fullstack#2551]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | latest version
Node | 6.10.0
npm | 3.10.10
Operating System | Ubuntu 16.10 / etc
etc | etc

Item | Answer
----- | -----
Babel / TypeScript
HTML 
CSS | CSS 
 ngRoute / 
Client Tests | Jasmine 
DB | MongoDB
Auth | Y 
etc | etc

when yo angular-fullstack is done, everything works well till
  force client/polyfills.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

please help us in resolving this... I am not sure if we can goahead and install package.json without angular is installed?

**Comment by Awk34** [comment]
Do you have Yarn installed? [This](https://github.com/angular-fullstack/generator-angular-fullstack/pull/2537) is the PR that changed the install code. You should just be able to run `npm install` as normal.

**Comment by srilives** [comment]
thats this worked.

**Comment by Awk34** [comment]
@benmarten

**Comment by srilives** [comment]
thanks for the support

**Comment by benmarten** [comment]
so seems the check for npm/yarn is not working on linux then?

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/pull/2557
