### ISSUE TITLE
GET /api/pointsummarys/user/0505652031 404 24.010 ms - -

### ISSUE THREAD

**Issue by srilives** [angular-fullstack/generator-angular-fullstack#2552]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 6.10.0
npm | 3.10.10
Operating System |  Ubuntu 16.10 
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML 
CSS | CSS 
Router | ngRoute 
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
etc | etc

[14:30:57] Requiring external module babel-register
[14:30:57] Working directory changed to ~/mycityclub
[14:31:00] Using gulpfile ~/mycityclub/gulpfile.babel.js
[14:31:00] Starting 'start:server'...
[14:31:00] Finished 'start:server' after 84 ms
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /root/mycityclub/server/**/*
[nodemon] starting `node server`
Express server listening on 9000, in development mode
[BS] Proxying: http://localhost:9000
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://xxx.xxx.xxx.xxx:3000
 --------------------------------------
          UI: http://localhost:3002
 UI External: http://xxx.xxx.xxx.xxx:3002
 --------------------------------------
webpack done hook
Hash: 4ae1b9f349b2e3f2662a
Version: webpack 1.15.0
Time: 13341ms
                                 Asset     Size  Chunks             Chunk Names
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]  
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]  
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]  
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]  
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  
                         app.bundle.js   512 kB       0  [emitted]  app
                   polyfills.bundle.js   207 kB       1  [emitted]  polyfills
                      vendor.bundle.js  2.42 MB       2  [emitted]  vendor
                     app.bundle.js.map   650 kB       0  [emitted]  app
               polyfills.bundle.js.map   267 kB       1  [emitted]  polyfills
                  vendor.bundle.js.map  2.83 MB       2  [emitted]  vendor
                  ../client/index.html  1.39 kB          [emitted]  
Child html-webpack-plugin for "../client/index.html":
                   Asset    Size  Chunks       Chunk Names
    ../client/index.html  2.7 kB       0       
webpack: Compiled successfully.
GET /api/pointsummarys/user/0505652031 404 24.010 ms - -
GET /api/pointsummarys/user/0505652031 404 270.624 ms - -
GET /api/pointsummarys/user/0505652031 404 267.219 ms - -

I am testing the api via postman... it fails.. please help... these apis are used in mobile apps.

**Comment by Awk34** [comment]
Have you modified your backend API to be able to respond to those requests? What does your `server/api/pointsummary/index.js` look like?

**Comment by srilives** [comment]
'use strict';

var express = require('express');
var controller = require('./PointSummary.controller');

var router = express.Router();

   
router.get('/',controller.hasAuthorization, controller.index);
router.get('/active', controller.active);
router.get('/:id', controller.show);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.patch('/:id', controller.update);
router.delete('/:id', controller.destroy);

router.get('/user/:id', controller.userpos);

router.post('/GetPointBalance/', controller.GetPointBalance);

module.exports = router;
~                            


also there is a file 

index.spec.js 

            return routerStub;
        }
    },
    './PointSummary.controller': PaymentMethodCtrlStub
});

describe('PointSummary API Router:', function() {

    it('should return an express router instance', function() {
        PointSummaryIndex.should.equal(routerStub);
    });

    describe('GET /api/PointSummarys', function() {

        it('should route to PointSummary.controller.index', function() {
            routerStub.get
                .withArgs('/', 'PointSummaryCtrl.index')
                .should.have.been.calledOnce;
        });

    });

});

**Comment by srilives** [comment]
but this when installed on windows, the api works.. but when we put on an ubuntu server it throws 404

**Comment by Awk34** [comment]
You should probably add a case to your router like this:

```js
router.get('/user/:id', controller.hasAuthorization, controller.getByUser);
```

**Comment by Awk34** [comment]
Also please make sure to surround your code in backticks (\`\`\` above and below) in the future for better code visibility

**Comment by srilives** [comment]
No luck.. Same error
