### ISSUE TITLE
Error: Cannot find module '/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node'

### ISSUE THREAD

**Issue by Pattern88** [angular-fullstack/generator-angular-fullstack#2554]
on my mac i run the yo generator and created my angular fullstack app
after that i uploaded to github with git
and then i ssh to my server and git clone the repository
run npm install
and then gulp serve
this is when i recieved the error

Error: Cannot find module '/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node'

when i try `npm rebuild`

I get this error:

` node-zopfli@1.4.0 install /home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli
 node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.10.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.4.0-72-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64" "--python=/path/to/executable/python2.7" "--msvs_version=2015"
gyp ERR! cwd /home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64 --python=/path/to/executable/python2.7 --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-72-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli
node-pre-gyp ERR! node -v v6.10.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/lib/binding/node-v48-linux-x64 --python=/path/to/executable/python2.7 --msvs_version=2015' (1)

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-zopfli@1.4.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-zopfli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-zopfli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-zopfli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/projects/mean-test-v5/node_modules/node-zopfli/npm-debug.log`

Item | Version
----- | -----
generator-angular-fullstack | 4.2.0
Node | 6.10.2
npm | 3.10.10
Operating System | Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Pattern88** [comment]
Helpppppp!!!!!!!!!

**Comment by Awk34** [comment]
We have already discussed this in issue #2553 you made. Please do not spam the GitHub issues section here with tech support requests.

**Comment by Pattern88** [comment]
I don't.

but still no solution here or over the internet!
