### ISSUE TITLE
Error running new application generation: "throw er; Unhanded 'error' event"

### ISSUE THREAD

**Issue by brugh** [angular-fullstack/generator-angular-fullstack#2556]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.0
Node | 6.10.2
npm | 3.10.10
Operating System | Ubuntu 16.04
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | SCSS
Router | ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y (google+facebook)
etc | etc

After configuring the app with 'yo angular-fullstack', the generator fails at the point where it created  server/api/thing/index.spec.js with a very generic error: 
    create server/api/thing/thing.controller.js
    create server/api/thing/thing.events.js
    create server/api/thing/thing.integration.js
    create server/api/thing/thing.model.js
    create server/api/thing/thing.socket.js
    create server/api/thing/index.js
    create server/api/thing/index.spec.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I ran 'npm -g install yo generator-angular-fullstack typescript gulp-cli' before I ran 'yo'

**Comment by brugh** [comment]
btw, if I use Babel instead of Typescript, i get the same error but with a different file: 
   create client/components/footer/footer.component.js
   create client/components/modal/modal.service.js
   create client/components/navbar/navbar.component.js
   create client/components/ui-router/ui-router.mock.js
   create client/components/util/util.module.js
   create client/components/util/util.service.js
   create client/polyfills.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by Awk34** [comment]
See: https://github.com/angular-fullstack/generator-angular-fullstack/issues/2551

There's an issue with running the yarn/npm check after scaffolding is done. If you don't want to see this error, run `yo angular-fullstack --skip-install` to not run the install afterwards, and run it yourself with `npm install`.

**Comment by Awk34** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/pull/2557
