### ISSUE TITLE
Getting 401 Unauthorized when trying to login

### ISSUE THREAD

**Issue by rXp** [angular-fullstack/generator-angular-fullstack#2575]
[x ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.0
Node | 7.10.0
npm | 4.2.0
Operating System | Windows 10 pro
IDE | Webstorm 2017.1

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | LESS
Router | ui-router
Client Tests | Jasmine
DB | SQL = ProgreSQL
Auth | Y

I added 4 new tables and a component but did not touch the Auth system.
When I want to connect in the login page with any login (correct or wrong) I get
`angular.js:12587 POST http://localhost:3000/auth/local 401 (Unauthorized)`

And this is what the server is telling me at this instant : 
`Executing (default): SELECT "data" FROM "Sessions" AS "Session" WHERE "Session"."sid" = '8ne9tHX2YIwIyZz2SqP1Uv7AiPmH97Oo' LIMIT 1;
(node:10012) Warning: a promise was created in a handler at C:\Users\***\WebstormProjects\AngularLeagues\node_modules\express\lib\router\layer.js:95:5 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.bind (C:\Users\***\WebstormProjects\AngularLeagues\node_modules\bluebird\js\release\bind.js:65:20)
Executing (default): SELECT "_id", "name", "email", "role", "password", "provider", "salt" FROM "auth"."Users" AS "User" WHERE "User"."email" = 'admin@example.com' LIMIT 1;
POST /auth/local 401 54.118 ms - 2`

**Comment by Awk34** [comment]
Are you running this with `NODE_ENV` as `production` or `development`? If it's `production`, you need to add users first.

**Comment by rXp** [comment]
I am running it as dev.
This is what the User table contains : 
```
299;"Test User";"test@example.com";"user";"test";"local";""
300;"Admin";"admin@example.com";"admin";"admin";"local";""
```

And the server is saying : 
`Executing (default): INSERT INTO "auth"."Users" ("_id","name","email","role","password","provider") VALUES (DEFAULT,'Test User','test@example.com','user','test','local'),(DEFAULT,'Admin','admin@example.com','admin','admin','local');`

**Comment by rXp** [comment]
Apparently there is a problem with a user object so that it cannot find the function authenticate : 
```
TypeError: user.authenticate is not a function
    at Model.<anonymous> (C:/Users/.../WebstormProjects/AngularLeagues/server/auth/local/passport.js:17:12)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I'm not too familiar with Sequelize so it's hard for me to find why that is happening.
1) The user is correctly found
2) The function is correctly implemented and declared

I am still looking into this problem.

**Comment by rXp** [comment]
My mistake I put the additional options (schema, table) in a third block {} between the first and the second.
The problem is that sequelize wants the first block for the columns and the second for the rest.
