### ISSUE TITLE
Cannot find module '../../webpack.make' when pm2 start 

### ISSUE THREAD

**Issue by juansupp** [angular-fullstack/generator-angular-fullstack#2583]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.0
Node | 6.10.3
npm | 3.10.10
Operating System |  Windows 10 
Pm2 | 2.4.6

Item | Answer
----- | -----
Transpiler | Babel 
Markup |  Pug
CSS |  Stylus
Router |  ui-router
Client Tests | Jasmine 
DB | NONE
Auth |  N

Hi, I'm having problems with starting the app on the server with pm2, when I run pm2 start eco.json, it starts but in the pm2 monit  reports the following Error: Cannot find module '../../webpack.make', I understand that the module is called in line 47 of the dist/server/configexpres.js file but just should called if env variable is development. There is my eco.json file

```json

{
  "apps": [

    {
      "name": "app",
      "script": "dist/server/index.js",
      "env_production": {
        "NODE_ENV": "production",
        "PORT": "8080"
      },
      "args": ["--release"],
      "port": "8080",
      "watch": false
    }

  ]

}
 
```

**Comment by Awk34** [comment]
See https://angular-fullstack.github.io/deployment/#manual-linux-server-

You should be running your server in production with the `NODE_ENV` environment variable set to `production`.

**Comment by juansupp** [comment]
I see, fyi in windows you need put `set` before the `NODE_ENV` like `set NODE_ENV=production`
