### ISSUE TITLE
Loading RxJS 5 in the Client side 

### ISSUE THREAD

**Issue by aabm00** [angular-fullstack/generator-angular-fullstack#2585]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 6.9.2
npm | 3.10.9
Operating System |  Windows 7
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS | CSS 
Router | ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y
socket.io

Hi.

I have installed RxJS 5 via **npm install rxjs** as commented in their [web](https://github.com/ReactiveX/rxjs), so I can work with it in the server side, but there isn't a way to load it via **bower** so I can't use it with **Angular**.

I don't want to hardcode a **CDN** in the index.html, so Is there a way to load this library in the client side to work with it?

Thanks

**Comment by Awk34** [comment]
Is it an option for you to upgrade to generator v4.2.2? the 4.x.x versions use Webpack, which allows you to just `import Rx from 'rxjs/Rx';`

**Comment by aabm00** [comment]
I tried it, but I wasn't succeful, so if there is some other way it'd be nice.

Thanks

**Comment by Awk34** [comment]
@aabm00 is this still an issue? In the latest version it's imported as such:

```js
import { Observable } from 'rxjs';
```

**Comment by aabm00** [comment]
Not at all. Thanks.
