### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by grantm44** [angular-fullstack/generator-angular-fullstack#2589]
Trying to build and deploy to Heroku. Running gulp build produces this error 

> [12:35:41] Starting 'build:images'...
> Error: The system cannot find the path specified.
> 
>   at notFoundError (C:\Users\Grant\Contacts\Desktop\portfolio\mean-stockchart-app\node_modules\cross-spawn\lib\enoent.js:11:11)
>   at verifyENOENT (C:\Users\Grant\Contacts\Desktop\portfolio\mean-stockchart-app\node_modules\cross-spawn\lib\enoent.js:46:16)
>   at ChildProcess.cp.emit (C:\Users\Grant\Contacts\Desktop\portfolio\mean-stockchart-app\node_modules\cross-spawn\lib\enoent.js:33:19)
>   at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Also it looks like the dist folder only has files from server and not from client. I'm not sure if that is the intended result. I thought it would have the client also.

**Comment by Awk34** [comment]
hmm, it doesn't tell you exactly which file it can't find?

**Comment by grantm44** [comment]
I ended up removing the build:images task. The file path looked correct for the images folder.
