### ISSUE TITLE
WebStorm, Yeoman and Angular-Fullstack automation

### ISSUE THREAD

**Issue by francissalvamantePTX** [angular-fullstack/generator-angular-fullstack#2604]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.0.0-rc4
Node | 5.7.1
npm | 3.6.0
Operating System | Ubuntu 16.04

I am currently using WebStorm as my IDE and I just found out that I could create project using Yeoman by going to File > New > Project then selecting Yeoman and choosing angular-fullstack. But apparently, angular-fullstack or yeoman asks for user input. And WebStorm's New Project feature (I think), doesn't cater user input. Is there a way for me to automate the selection process?

**Comment by anstarovoyt** [comment]
https://youtrack.jetbrains.com/issue/WEB-22841

**Comment by Awk34** [comment]
Thanks @anstarovoyt . Seems to work for me on WS 172.3317.8.
