### ISSUE TITLE
Can't render express route to "/" in server , instead of the client side html served by webpack

### ISSUE THREAD

**Issue by kdfproject** [angular-fullstack/generator-angular-fullstack#2611]
I need to use templating (handlebars) in my index.html file, and i need to do it in the server side, however eventhough i set a route in express to "/" to render the view, i still see the client version of the html. Somehow seems that webpack is rendering the route to "/" no matter what i set in the express routes.js file.

 - [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by daraosn** [comment]
@kdfproject check my PR at https://github.com/angular-fullstack/generator-angular-fullstack/pull/2613 this might fix the issue

**Comment by Awk34** [comment]
#2613 merged
