### ISSUE TITLE
Auth.getCurrentUser giving me a resource object !

### ISSUE THREAD

**Issue by akshayseth** [angular-fullstack/generator-angular-fullstack#2612]
Hi,I am using yeoman's angular fullstack generator to scaffold my web project.I am using Auth service's getCurrentUser() method.It is working just fine in my other controllers but in  one of my controller it is returning me a resource object and I can't access email,_id with using "." operator.Below is my code and the console i got.
'use strict';

(function(){

class MyProfileComponent {
  constructor(Auth) {
    this.message = 'Hello';
    var obj=Auth.getCurrentUser();
    console.log(obj);//Print the details successfully
    console.log(obj.email);//returned undefined
  }
}

angular.module('ctrlCApp')
  .component('myProfile', {
    templateUrl: 'app/myProfile/myProfile.html',
    controller: MyProfileComponent,
    controllerAs: 'myProfileCtrl'
  }).controller('MyProfileComponent',MyProfileComponent);;

})();
-------------------------------------------------------------------
Output is:
Resource {$promise: Promise, $resolved: false}
myProfile.controller.js:10 undefined

**Comment by daraosn** [comment]
`Auth.getCurrentUser()` returns a promise, you must wait until it's resolved before accessing the values.

Two ways to solve it:
1. use `then()`
```
Auth.getCurrentUser().then(function(me) {
  console.log('me.email', me.email);
});
```
2. use its `callback`
```
Auth.getCurrentUser(function(me) {
  console.log('me.email', me.email);
});
```

**Comment by piux** [comment]
you have to use resolve so it resolves the action before even start running anything in controller. in your 'controllername.routes.js' you have to put this

```
'use strict';

export default function routes($stateProvider) {
  'ngInject';

  $stateProvider.state('main', {
    url: '/main', 
    authenticate: 'user',    
    resolve:{
      'getCurrentUser':function(Auth){
        return Auth.getCurrentUser();
     }
    },
    template: '<main></main>'
  });
}
```
