### ISSUE TITLE
Generating Angular Fullstack with typescript wants babel.

### ISSUE THREAD

**Issue by xavidram** [angular-fullstack/generator-angular-fullstack#2615]
- [ X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.2
Node | 6.11.2
npm | 5.3.0
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | / TypeScript
Markup | HTML 
CSS |  SCSS 
Router | ngRoute 
Client Tests | Jasmine 
DB |  SQL
Auth | Y / N

So I started up a new project. But I want to generate the project with typescript support. 
I don't have an issue running the project if I don't install any new dependencies. But I noticed that when I install any new dependency, take ldap for example. 
'npm install --save-dev ldap'  
Once that command finishes, I can no longer run the project. I recieve the following
![screen shot 2017-08-03 at 5 38 56 pm](https://user-images.githubusercontent.com/1348719/28946901-a6b87840-7872-11e7-87b1-d65b3e98b896.png)

Now. I can fix this by adding babel-core to the dev dependencies, but then I also have to install gulp into the dev dependencies as it prompts me that I do not have gulp installed in the project. 

I am curious if anyone else has come accross this issue. I noticed the gulp file is written in babel. When I install any new dependencies, the babel core for some reason seems to get removed from both node_modules and the package.json dependencies. So I would have to ad them back in. I figured I wouldn't need babel if I wanted the angular fullstack project to have typescript support but it seems the gulpfile requires it as it is written in babel.

Another thing I noticed. After installing babel-core and gulp into the project's dev dependencies, I get some new errors that were not there before. I can fix all these error by once again running 'npm install' and it will add any missing dependencies.

**Comment by Awk34** [comment]
hmm, I'm not sure why you'd have packages being deleted when installing another one.. That `removed 1923 packages` sections is quite worrying..

When the generator asks you whether you'd like to use babel/typescript, that's for the client only. The server only uses Babel.

**Comment by xavidram** [comment]
That sense. But yes you are correct. I have attempted using this on multiple environments and when generating a project with typescript, when adding third party dependencies, it keeps removing all packages except the newly added package. I simply have to run npm install every time I add a new dependency to fix the issue.
