### ISSUE TITLE
Cannot Update boolean fields of a mongoose model

### ISSUE THREAD

**Issue by gt0p** [angular-fullstack/generator-angular-fullstack#2622]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.0
Node | 6.11.2
npm | 3.10.10
Operating System | Ubuntu 17.04 

Item | Version
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS / LESS 
Router |  ui-router
DB | MongoDB 
Auth | Y

As I have already searched in this project's docs I have not found a way to make a PATCH req in order to update a **boolean** field of a mongo model.
By sending the following object as the req payload:
`{"id":"599734ee91bfe87934dc9671","patch":[{"op":"replace","path":"/final","value":false}]}`
(The filed 'final' has defined as Boolean in the model)

I get a response with status code 200 although the relative object havent changed in the db.  
Even in the event that Ι send a wrong request I dont understand why the endpoint 'answer' with a response of 200.

Is there a different way to handle the cases in which I want to update a boolean field ?

**Comment by Awk34** [comment]
https://tools.ietf.org/html/rfc6902

You should be sending your array of patches as the request body

**Comment by gt0p** [comment]
Thanks for your time.
I still need to send the body as I have shown because I use $resource service (I need id field) but with your comment I have to pass req.body.patch instead of req.body in the patchUpdates function.
