### ISSUE TITLE
No save session on beta 5.0

### ISSUE THREAD

**Issue by AlexisNichel** [angular-fullstack/generator-angular-fullstack#2625]
Hi, help me   ##pleace
I login in beta 5 proyect... But when refresh page, delete things, etc... close my session
I can remember as V4 proyect??

generator-angular-fullstack | 5.0.0
Node | 7.10.1
npm | 5.3.0
Operating System | Ubuntu 7.04

Item | Answer
----- | -----
Transpiler |  TypeScript
Markup | HTML 
CSS |  SCSS 
Client Tests |  Mocha
DB | SQL
Auth | Y

**Comment by umimehar** [comment]
Hello @AlexisNichel 
after login when you refresh the page do you get any error in browser console?
