### ISSUE TITLE
angular-fullstack  3.6.1 to 4.2.0 questions

### ISSUE THREAD

**Issue by eaidland** [angular-fullstack/generator-angular-fullstack#2627]
- [ x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
generator-angular-fullstack | 3.6.1
Node | 6.10.3
npm | 3.10.10
Operating System | Windows 10 

Item | Answer
Transpiler | TypeScript
Markup | HTML 
CSS
 ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB 
Auth | Y 

Hi!
Quick questions: 
Is it possible to upgrade from AF 3.6.1 to the latest 4.2.0 by changing the "generatorVersion": "3.6.1" in yo-rc.json and then type yo angular-fullstack?

If yes, anything special I need to look out for and possible change since this is a pretty major upgrade?

Thanks!

**Comment by Awk34** [comment]
No. Please see some of the previously created issues regarding upgrading a generated project: https://github.com/angular-fullstack/generator-angular-fullstack/issues/1718

The biggest difference for you will probably be that 4.x.x uses Webpack.
