### ISSUE TITLE
gulp test for new project throwing error

### ISSUE THREAD

**Issue by nstuyvesant** [angular-fullstack/generator-angular-fullstack#2628]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.2
Node | 8.4.0
npm | 5.3.0
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | Pug
CSS | SCSS
Router | ngRoute
Client Tests | Mocha
DB | SQL
Auth | Y

Got this error after scaffolding a project and running gulp test:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
TypeError: The "digest" argument is required and must not be undefined
  at pbkdf2 (crypto.js:635:11)
  at Object.exports.pbkdf2 (crypto.js:623:10)
  at Instance.encryptPassword (/Users/nates/dev/test/server/api/user/user.model.js:187:33)
  at /Users/nates/dev/test/server/api/user/user.model.js:219:18
  at RandomBytes.ondone (/Users/nates/dev/test/server/api/user/user.model.js:160:18)
```

Seems like the function calls on [line 183 of user.model(sequelizeModels).js](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/server/api/user(auth)/user.model(sequelizeModels).js#L183) and [line 187](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/server/api/user(auth)/user.model(sequelizeModels).js#L187) need to specify the digest for newer versions of node.

**Comment by Awk34** [comment]
Correct. Node used to default it to `'sha1'`, so if you already have passwords hashed, use that option. Otherwise you can run `node --print --eval "require('crypto').getHashes()"` in a console to see a list of hashing algorithms that your current version supports. We should set it to `'sha1'` in version 4.x.x so that it doesn't break anyone, and also set a new default in the _canary_ branch for 5.0.0

**Comment by nstuyvesant** [comment]
Makes sense - thanks!
