### ISSUE TITLE
Adding new NPM Modules (Cannot resolve module 'fs') error

### ISSUE THREAD

**Issue by xavidram** [angular-fullstack/generator-angular-fullstack#2644]
- [ x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.2
Node | 6.11.3
npm | 5.4.1
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | SCSS 
Router | ngRoute
Client Tests | Jasmine 
DB | SQL
Auth | Y 

NPM MODULE: bb-rest

I have looked through many of the previous issues with the error 'Cannot resolve module 'fs'' and have done changes to the config variable in the webpack.make.js file from solutions such as these.

1. [Here](https://github.com/josephsavona/valuable/issues/9)
2. [This one as wel](http://jlongster.com/Backend-Apps-with-Webpack--Part-I)
3. [Tried this as well](https://github.com/pugjs/pug-loader/issues/8#issuecomment-55568520)
4. [Last Resort](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2605)

When I attempt to inject the dependency in the app.js file, webpack upon compiling throws a fit. I've tried the approaches in the links provided above in order to resolve this with no luck. I even tried simply importing the required dependency into my controller, or a specific file where I need it, and webpack goes crazy. I set up a test project with just a simple node/express webapp and that works fine. I'm not too familiar with webpack and it's inner workings so I was wondering if anyone had any similar issues when trying to use third party npm modules in the stack.

Console Error Produced by Webpack upon compiling: https://pastebin.com/26RmwEUZ

I already submitted an issue with [Stackoverflow](https://stackoverflow.com/questions/46552646/error-with-webpack-and-angular-fullstack-installing-3rd-party-npm-modules) but figured I should also submit one here in the event someone else has come across this. If I get a resolution over at StackOverflow I'll post the solution and close the issue and vice versa.

**Comment by Awk34** [comment]
It looks like the `bb-rest` module you're trying to use is meant to be used on the server side (Node.js) and not the browser. Its only dependency `request` isn't meant to work in the browser out-of-the-box (you can try something like [this](https://github.com/request/request/issues/1920#issuecomment-165151776))

**Comment by Awk34** [comment]
Thanks for the very detailed issue btw
