### ISSUE TITLE
How can i integrate Payment gateway to angular fullstack

### ISSUE THREAD

**Issue by LokeshBoran** [angular-fullstack/generator-angular-fullstack#2646]
Can anyone integrate paypal/payumoney like any payment gateway to angular fullstack. when i am tried with paypal it has only jquery/javascript plugin available which is like spoiling sprit of angular-fullstack. So Is there any angularjs way to integrate with this template ? 

- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Pug
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Awk34** [comment]
From a simple search I can find that Paypal has an Angular integration: https://github.com/paypal/paypal-checkout/blob/master/docs/frameworks.md#angularjs-element

**Comment by LokeshBoran** [comment]
@Awk34 Thanks for the link let me try it.

**Comment by only2dhir** [comment]
You can try this [PayuMoney Payment gateway integration with Angular ](https://www.devglan.com/angular/payumoney-integration-angular)

**Comment by abanchaudry** [comment]
Any one know teler payment gateway for angular
