### ISSUE TITLE
extractData in util.ts in client `res.text` is not a function

### ISSUE THREAD

**Issue by umimehar** [angular-fullstack/generator-angular-fullstack#2648]
-I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-beta.0
Node | 6.11.4
npm | 3.10.10
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | SCSS 
Router | ngRoute 
Client Tests | Mocha
DB | MongoDB 
Auth | Y 
etc | etc

<img width="658" alt="screen shot 2017-10-10 at 22 01 57" src="https://user-images.githubusercontent.com/11488033/31399720-bc3c92ae-ae06-11e7-897d-9f5e9995343a.png">

Please have a look on this error. 

When admin will be auth in after login, and if we refresh the page, the session is there but there is error in `extractData` function. error is shown in pic. 
and if i see `extractData` method in `util.ts`

this is the code.
```javascript
export function extractData(res: Response) {
    if(!res.text()) return {};
    return res.json() || { };
}
```

and if i console the response in this function that is.

<img width="656" alt="screen shot 2017-10-10 at 22 12 24" src="https://user-images.githubusercontent.com/11488033/31400227-405dd196-ae08-11e7-8941-2ce6316f282e.png">

**Comment by Awk34** [comment]
fixed with https://github.com/angular-fullstack/generator-angular-fullstack/commit/31a6ecf2c6a52cece4426dd36c9dcf3b906e7fca
