### ISSUE TITLE
npm install does not work on linux machine

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#2662]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.2
Node | 6.5.0
npm | 3.10.3
Operating System Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

Hi there

When I run "npm install" after download I get: 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN optional Skipping failed optional dependency /stylint/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2

Can you help?

Kind Regards

Marinus

**Comment by Awk34** [comment]
Those warnings are to be expected. `chokidar` has an optional dependency on `fsevents`, which I believe is an OSX-only module. It isn't necessary.
