### ISSUE TITLE
If I click on site, also other site is clicked

### ISSUE THREAD

**Issue by new-maker-1** [angular-fullstack/generator-angular-fullstack#2669]
Please help me!
I did install a site using angular-full-stack.
but If I click on site, other site also is clicked.
I used Firefox and Chrome browsers.
I don't want this action.
Best regards.

**Comment by new-maker-1** [comment]
![issue](https://user-images.githubusercontent.com/21679713/32878695-14e7c55c-cae2-11e7-96a7-950507bf9fa5.png)

**Comment by albert-92** [comment]
That's a tool called "browser sync". Go to http://localhost:3001/sync-options or http://localhost:3002/sync-options and disable what you don't need/want.

Alternatively you can edit the express.js in your server files and add the ghostMode flag
```
browserSync.init({
      ...,
      ghostMode: false
    });
```

**Comment by new-maker-1** [comment]
I have fixed this error.
I am very happy now.
thank albert-92.

**Comment by Awk34** [comment]
XD sorry about the confusion there @new-maker-1 !
