### ISSUE TITLE
hosting w/ nginx and forever

### ISSUE THREAD

**Issue by ralyodio** [angular-fullstack/generator-angular-fullstack#267]
I'm using the openshift deploy method, only on my own server, which will serve static files from ./dist/public via nginx and run `forever server.js`  on its own port upstream for backend.

How are the views handled, since they are outside ./public in its own director `./dist/views`?

**Comment by idmanish** [comment]
As chovy updated that " The entire app + static files is served by node".
I want my static data to be served via nginx and and app, rest by Node.

I update my nginx.conf file like below.
server {
    listen       80;
    server_name  localhost;

    location / {
                 proxy_pass http://localhost:9000;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection 'upgrade';
                 proxy_set_header Host $host;
                 proxy_cache_bypass $http_upgrade;
    }
}

Looks like still nginx just working as reverse proxy.
How can I configure nginx , to serve just static data

**Comment by dustintheweb** [comment]
I'd also love to hear ideas on how to set this up.
