### ISSUE TITLE
Generating route error (5.0.0-beta.2 canary branch)

### ISSUE THREAD

**Issue by alexbatis** [angular-fullstack/generator-angular-fullstack#2671]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-beta.2
generator-ng-component | 1.0.5
Node | v8.9.1
npm | 5.5.1
Operating System | MacOS High Sierra 10.13.1
Yeoman | 2.0.0

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | SCSS
Router | ngRoute (?)
Client Tests | Mocha
DB | MongoDB
Auth | Y 

I am using the "canary" branch to scaffold a project for an MEAN application with Angular 4+

When trying to create a new route i use the command `yo angular-fullstack:route myroute
 ` as per the documentation [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/canary/docs/generators/route.md).  I receive the following error : 

```
$ yo angular-fullstack:route myroute


/usr/local/lib/node_modules/generator-angular-fullstack/generators/route/index.js:5
var Generator = yeoman.Base.extend({
                            ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/generators/route/index.js:5:29)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.get [as angular-fullstack:route] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:61:39)
```

Here are the contents of the file at /usr/local/lib/node_modules/generator-angular-fullstack/generators/route/index.js : 

```
'use strict';

var yeoman = require('yeoman-generator');

var Generator = yeoman.Base.extend({
  compose: function compose() {
    this.composeWith('ng-component:route', { arguments: this.arguments }, { local: require.resolve('generator-ng-component/generators/route') });
  }
});

module.exports = Generator;
```

What is the problem with trying to generate a new route?

**Comment by Awk34** [comment]
Sorry, the sub-generators are not supported on the 5.0.0 beta yet

**Comment by Awk34** [comment]
I'll update the docs

**Comment by zaphinath** [comment]
Any idea when they will be supported?

**Comment by Awk34** [comment]
The route subgenerator has been added.
