### ISSUE TITLE
socket.io routes are not protected by Auth? Why?

### ISSUE THREAD

**Issue by nigel-dewar** [angular-fullstack/generator-angular-fullstack#2673]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Socket.io routes are not protected? Why? Was there in particular reason not to protect the socket.io routes?

cheers

**Comment by Awk34** [comment]
Are you talking about what's referenced [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/ab8624002cd90aac100dbb6cc263d92f7f599588/templates/app/server/config/socketio(socketio).js#L28)? This was left out by default because it adds a level of complexity that the vast majority of users won't need.

**Comment by Awk34** [comment]
sorry, didn't mean to close

**Comment by nigel-dewar** [comment]
Yes this is exactly what i was looking for . Cheers this answers my question.

**Comment by nigel-dewar** [comment]
Its a shame that the Auth for sockets was at least not added (and then commented out), on the client side.

Because I would really would have/ or could have done with that.

I know this area is for REAL bugs, and what I am describing is not a BUG but a suggested enhancement.

Can we please have the Boilerplate code for Socket.IO Auth added to the Repo. this can be commented out to meet the needs of keeping the repo simple for majority of users, whilst providing a quality example for those whom need the complexity. 

I saw this because after LOTS of googling, the number of quality samples in this area are minimal, and, Angular- full stack is such a kick ass repo, that its pretty much production ready, a quality sample of Socket.io Auth would really top it off with todays real-time needs which are becoming more common as customers get more demanding.

Cheers

**Comment by Awk34** [comment]
It's fine, the issues section here is both for bugs and feature requests.

I haven't used it in quite some time, but I think everything should be there to get you started with authenticated websocket requests. See [socketio-jwt](https://www.npmjs.com/package/socketio-jwt) for their info on what happens server-side.

The generator no longer uses Socket.io on the *canary* branch, and we have yet to implement authenticated socket connections there FYI.

**Comment by nigel-dewar** [comment]
Thanks, no worries. I'll get going with Canary branch, and see what I can knock up. If I can get sockets going well with Auth,  I'll submit a PR, but I understand if you guys want to keep this generator simple. Over complexity does suck when its supposed to be a starter solution right.

I might as well see how I go implemented Token Auth with localStorage on the client side as well as I notice cookies are being used. I have read an explanation in another thread on this, but I feel like its a limiting factor relying on cookies and sessions server side. But I am saying this not fully understanding the security implications. 

Closing this as you've answered all my questions. Cheers.

Cheers

Nigel
