### ISSUE TITLE
No router options displayed

### ISSUE THREAD

**Issue by smileavi** [angular-fullstack/generator-angular-fullstack#2686]
[] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | beta
Node | 6.11.2
npm | 3.10.10
Operating System | OS X 10 
etc | etc

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS 
Router |ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB 
Auth | Y 
etc | etc

Hi,
No router options displayed: UI-router / Angular-route while running yo angular-fullstack.

**Comment by Awk34** [comment]
This is intentional. Last I checked UI-Router for Angular wasn't in a great state, thus making it difficult to support. I haven't checked it lately, so if you believe it's in a place where it can be adapted for this project, I'd be happy to take a PR.
