### ISSUE TITLE
gulp serve not working: TypeError('ERR_INVALID_ARG_TYPE', 'digest

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#2690]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 9.5.0
npm | 5.6.0
Operating System Ubuntu Win10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y
etc | etc

`internal/crypto/pbkdf2.js:35
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'digest',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "digest" argument must be one of type string or null
    at _pbkdf2 (internal/crypto/pbkdf2.js:35:11)
    at Object.pbkdf2 (internal/crypto/pbkdf2.js:25:10)
    at model.encryptPassword (m:/Websites/projekte/eigene/Buchhaltung/angular-fullstack/server/api/user/user.model.js:215:19)
    at m:/Websites/projekte/eigene/Buchhaltung/angular-fullstack/server/api/user/user.model.js:114:12
    at RandomBytes.ondone (m:/Websites/projekte/eigene/Buchhaltung/angular-fullstack/server/api/user/user.model.js:184:9)`

**Comment by MarinAngelo** [comment]
issue resolved after going back to node 5.6.0

**Comment by Awk34** [comment]
@MarinAngelo you can find the fix for this here: https://github.com/angular-fullstack/generator-angular-fullstack/commit/689c3fc22815233b4f32f4162ee2c4339660ec70

**Comment by hoogw** [comment]
@Awk34  Do you mean you fix the error?

If I use node -v 9.6,  should I have no such error?

Or I have to use node 5.6.0 to avoid error?
