### ISSUE TITLE
wrong engines in package.json 

### ISSUE THREAD

**Issue by daton89** [angular-fullstack/generator-angular-fullstack#2696]
wrong engines in package.json 
```json
  "engines": {
    "node": "^6.2.2",
    "npm": "^3.9.5"
  },
```

so during install i got:
```sh
yarn install v1.3.2
warning package.json: "dependencies" has dependency "babel-core" with range "^6.18.2" that collides with a dependency in "devDependencies" of the same name with version "^6.6.5"
warning package.json: "dependencies" has dependency "babel-preset-es2015" with range "^6.18.0" that collides with a dependency in "devDependencies" of the same name with version "^6.6.0"
info No lockfile found.
warning angular-fullstack-generator@0.0.0: "dependencies" has dependency "babel-core" with range "^6.18.2" that collides with a dependency in "devDependencies" of the same name with version "^6.6.5"
warning angular-fullstack-generator@0.0.0: "dependencies" has dependency "babel-preset-es2015" with range "^6.18.0" that collides with a dependency in "devDependencies" of the same name with version "^6.6.0"
[1/5] 🔍  Validating package.json...
error angular-fullstack-generator@0.0.0: The engine "node" is incompatible with this module. Expected version "^6.2.2".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc.0
Node | 8.9.4
npm | 5.6.0
Operating System | OS X 10.11.2

**Comment by albert-92** [comment]
I'm not sure if the supported Node.js version is still 6. If that is the case, everything works as supposed.

You can either downgrade your Node to `>= 6.2.2 && < 7.0.0` or use `yarn install --ignore-engines` after the initial installation fails and see if it works without any incompatibility issues.

Could you give feedback if you run into the same problem https://github.com/angular-fullstack/generator-angular-fullstack/issues/2694 afterwards?

**Comment by Awk34** [comment]
We should change it to be `>=` the latest acceptable 6.x.x version, probably. I wouldn't be against making the minimum node version in the 8.x.x range either, since it's LTS now.

**Comment by albert-92** [comment]
@Awk34 That sounds reasonable. I'll test it with the latest LTS release 8.10.0 and report if i find any compatibility issues.

**Comment by daton89** [comment]
@albert-92 in the project the gulpfile.babel.js was not found after run the generator.. i guess that for install the 5.0.0-rc-0 you need to use node >= 8 so there is no reason to downgrade Node

**Comment by albert-92** [comment]
@daton89 upgrade to 5.0.0-rc-1, the gulpfile.babel.js problem is fixed there and then run `yarn install --ignore-engines` if you want to use node 8.

It looks like generator-angular-fullstack works with either node 6 or node 8 just fine.
