### ISSUE TITLE
New server, login fails

### ISSUE THREAD

**Issue by AmirGilboa** [angular-fullstack/generator-angular-fullstack#2699]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

My app was built with afs version 3.75 or close to that. working fine on a digital ocean server for over a year. I have moved it to a new server (also DO). backed up the database and restored to the new server.
Everything works, except the logins. People, including me, cannot login to the website. (new registrations works!) Obviously i cannot see the passwords, but the 2 databases seems to be identical. and the api's are working (all the functionality works, api, etc), so i can't understand what can be the reason for the login to fail. Any idea?
The only direction i can think of is the versions. Mongodb for example is now 3.6.3, and in the old server it is 3.2.17.   Also the nodejs is newer. How would you debug this?  thanks.

**Comment by albert-92** [comment]
What error message do you get when the login fails?

`'This email is not registered.'` or `'This password is not correct.'` or some other error?

**Comment by AmirGilboa** [comment]
message is: password is not correct.
But the information i gave you was not complete. sorry.
My partner did the move, and he encountered an error with crypto. the new version of crypto requires a new param, like this:

`    return crypto.pbkdf2(password, salt, defaultIterations, defaultKeyLength, 'sha512', (err, key) => {
      if (err) {
        callback(err);
      } else {
        callback(null, key.toString('base64'));
      }
    });`

the 'sha512' was not there before. something is required there, and he found that in the crypto expamples, and that prevents the error. the param name is digest. you can see it here:
[https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback](https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback)

But who knows, maybe the 'digest' have other options and sha512 is not the right one.
I see there that you can use crypto.getHashes() to get all the available hashes.
So if i only new which one we used in the older version of crypto, that would help me...

**Comment by Awk34** [comment]
I believe the default used to be `sha1`

**Comment by AmirGilboa** [comment]
Yes! that did the trick. Thank you!
