### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by imanreih** [angular-fullstack/generator-angular-fullstack#2703]
It was working fine before, but now when I run the client I get this warning:

WARNING in ./node_modules/@angular/core/esm5/core.js
6558:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./client/app/app.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./client/app/app.ts

WARNING in ./node_modules/@angular/core/esm5/core.js
6578:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./client/app/app.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./client/app/app.ts

**Comment by Awk34** [comment]
It's just a warning originating from Angular. Feel free to ignore it. I know, it's annoying. Search the Angular issues for more information.
