### ISSUE TITLE
CSS are not working when i run npm run start:client

### ISSUE THREAD

**Issue by faizushaik** [angular-fullstack/generator-angular-fullstack#2717]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.
Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc1
Node | 8.9.1
npm | 5.6.0
Operating System | macOS

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router | angular-router
Client Tests | Mocha
DB | MongoDB
Auth | N

![screenshot-2018-5-10 angular full-stack generator](https://user-images.githubusercontent.com/34673426/39869965-3ad8a1ee-547d-11e8-9d22-7306470e191b.png)

**Comment by Awk34** [comment]
Any details? Did you look into what was causing the issue at all?

**Comment by faizushaik** [comment]
For SCSS its working fine.
