### ISSUE TITLE
Vendor bundle size

### ISSUE THREAD

**Issue by VocalZero** [angular-fullstack/generator-angular-fullstack#2724]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.2.3
Node | 8.11.2
npm | 5.6.0
Operating System | Debian 9

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
Router | ui-router
Client Tests | Jasmine
DB | MongoDB
Auth | Y

I'm having an issue with Vendor bundle size. I see the size of Vendor bundle is 2.63 MB and because of that my Page needs very Long to Load can anyone Help me with this Problem?

**Comment by gt0p** [comment]
I agree. It seems that angular and lodash are mainly responsible for this size. personally I'm trying to find a way to load only part of loadsh package in order to reduce the size. :/

**Comment by Awk34** [comment]
One example: https://github.com/lodash/babel-plugin-lodash#readme
