### ISSUE TITLE
Initial page doesn't load using babel+sequelize

### ISSUE THREAD

**Issue by luizfox** [angular-fullstack/generator-angular-fullstack#2745]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc.3
Node | 8.11.3
npm | 5.6.0
Operating System | Windows 10

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | SCSS
Router | ngRoute 
Client Tests | Mocha
DB |SQL
Auth | Y 
flow | true

[yo-rc.zip](https://github.com/angular-fullstack/generator-angular-fullstack/files/2196612/yo-rc.zip)

I'm not able to generate a single app using all the default answers. If I change just from Babel to TypeScript, it works.

The problem: When I try to access the initial webpage, the title loads, but the only text that loads is
> Loading...

and nothing happens. I believe it's a bug.

**Comment by Awk34** [comment]
```
app.bundle.js:1383 Uncaught ReferenceError: exports is not defined
    at Module../client/app/app.constants.js (app.bundle.js:1383)
```

**Comment by Awk34** [comment]
Unfortunately, this is due to a bug in Babel that isn't fixed. I will submit a patch to the generator.

**Comment by Awk34** [comment]
See https://github.com/angular-fullstack/generator-angular-fullstack/commit/73d1e29c35b9b215bd17a55e6e5b603e910c7120

**Comment by luizfox** [comment]
Thanks, @Awk34 . Now it works like a charm!
