### ISSUE TITLE
npm run start:server Fails with error

### ISSUE THREAD

**Issue by Ritin** [angular-fullstack/generator-angular-fullstack#2755]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc.3
Node | v8.11.3
npm | 5.6.0
Operating System |  Ubuntu 18.04
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML
CSS | SCSS
Router
Client Tests | Mocha
DB | MongoDB
Auth | Y
Primus | 7.2.2  and 7.0.1
uws | 10.148.2 (deprecated)

Author message: stop using this version
[https://www.npmjs.com/package/uws](url)

> ritin@ritin-Octa:yoangfullstack3 $ npm run start:server

> yoangfullstack3@0.0.0 start:server /home/ritin/myapps/Ang4/generators/yoangfullstack3
> node server

> 
> the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,useNewUrlParser]
> Primus:
> Primus: Missing required npm dependency for uws
> Primus: Please run the following command and try again:
> Primus:
> Primus:   npm install --save uws
> Primus:
> 
> /home/ritin/myapps/Ang4/generators/yoangfullstack3/node_modules/primus/index.js:290
>         throw new PrimusError(this.is(transformer, Primus.transformers).missing(), this);
>         ^
> PrimusError: Missing dependencies for transformer: "uws"
>     at Primus.initialise (/home/ritin/myapps/Ang4/generators/yoangfullstack3/node_modules/primus/index.js:290:15)
>     at new Primus (/home/ritin/myapps/Ang4/generators/yoangfullstack3/node_modules/primus/index.js:111:8)
>     at initWebSocketServer (/home/ritin/myapps/Ang4/generators/yoangfullstack3/server/config/websockets.js:42:14)
>     at Object.<anonymous> (/home/ritin/myapps/Ang4/generators/yoangfullstack3/server/app.js:26:23)
>     at Module._compile (module.js:652:30)
>     at loader (/home/ritin/myapps/Ang4/generators/yoangfullstack3/node_modules/babel-register/lib/node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/ritin/myapps/Ang4/generators/yoangfullstack3/node_modules/babel-register/lib/node.js:154:7)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/ritin/myapps/Ang4/generators/yoangfullstack3/server/index.js:12:28)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:612:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! yoangfullstack3@0.0.0 start:server: `node server`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the yoangfullstack3@0.0.0 start:server script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ritin/.npm/_logs/2018-07-23T12_36_08_786Z-debug.log
> 
> 
>

**Comment by Awk34** [comment]
see ed3b775939511447e629754a1d839aef785564a1. uws published a blank version on npm, which is now causing anyone that relied on it being semver-safe to break. I guess one of the maintainers got fed up with npm: https://gitlab.com/uNetworking/uWebSockets/issues/11
