### ISSUE TITLE
Problem with WebSockets =y .  And webpack.make.js sytanx error on config.plugins.push(xx,xx,)

### ISSUE THREAD

**Issue by wangpingsx** [angular-fullstack/generator-angular-fullstack#2760]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc.3
node | v7.4.0
npm  | v4.0.5
gulp-cli | 2.0.1 
yo | 2.0.5 
Operating System | OS X 10 

a|b
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML 
CSS | SCSS
Router | didn't ask
Client Tests | Mocha
DB | MongoDB
Auth | N
WebSockets | Y

Client

Q|A
----- | -----
? What would you like to write scripts with? | TypeScript
? What would you like to write markup with? | HTML
? What would you like to write stylesheets with? | Sass
? Would you like to include Bootstrap? | Yes
? Would you like to include UI Bootstrap? | Yes

Server

Q|A
----- | -----
What would you like to use for data modeling? | Mongoose (MongoDB)
Would you scaffold out an authentication boilerplate? |  No
Would you like to use WebSockets?  | No

 Project

Q|A
----- | -----
? What would you like to write tests with?  | Mocha + Chai + Sinon
? What would you like to write Chai assertions with?  | Expect

# when I set `WebSockets =y`, i got below error:

### npm run start:client
to make it run i have to remove comma from line 265, 279 and 305 from webpack.make.js

No commas needed after the last var.

### npm run start:server

> lj@0.0.0 start:server /Users/peterwang/Documents/dev/code/lj
> node server

the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,useNewUrlParser]
Primus:
Primus: Missing required npm dependency for uws
Primus: Please run the following command and try again:
Primus:
Primus:   npm install --save uws
Primus:

/Users/peterwang/Documents/dev/code/lj/node_modules/primus/index.js:290
        throw new PrimusError(this.is(transformer, Primus.transformers).missing(), this);
        ^
Error
    at Primus.initialise (/Users/peterwang/Documents/dev/code/lj/node_modules/primus/index.js:290:15)
    at new Primus (/Users/peterwang/Documents/dev/code/lj/node_modules/primus/index.js:111:8)
    at initWebSocketServer (/Users/peterwang/Documents/dev/code/lj/server/config/websockets.js:42:14)
    at Object.<anonymous> (/Users/peterwang/Documents/dev/code/lj/server/app.js:26:23)
    at Module._compile (module.js:571:32)
    at loader (/Users/peterwang/Documents/dev/code/lj/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/peterwang/Documents/dev/code/lj/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/peterwang/Documents/dev/code/lj/server/index.js:12:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

npm ERR! Darwin 17.6.0
npm ERR! argv "/Users/peterwang/.nvm/versions/node/v7.4.0/bin/node" "/Users/peterwang/.nvm/versions/node/v7.4.0/bin/npm" "run" "start:server"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! lj@0.0.0 start:server: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lj@0.0.0 start:server script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lj
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lj
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/peterwang/Documents/dev/code/lj/npm-debug.log

**Comment by Awk34** [comment]
See #2755
