### ISSUE TITLE
unable to load the Client

### ISSUE THREAD

**Issue by sreeyashu** [angular-fullstack/generator-angular-fullstack#2777]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0
Node | 8.12.0
npm | 6.4.1
Operating System | OS X 10 
gulp-cli | 2.0.1

Item | Answer
----- | -----
Transpiler | TypeScript - Type
Markup | HTML
CSS | SCSS 
Router | ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | N
Database | MongoDB

If you initiate a new app with gulp, after gulp serve, unable to see anyoutput:

<img width="783" alt="screen shot 2018-11-30 at 16 20 09" src="https://user-images.githubusercontent.com/4896372/49297765-ea31e400-f4bb-11e8-81ee-dff6d20f3e43.png">

results like this on the browser

<img width="540" alt="screen shot 2018-11-30 at 16 21 23" src="https://user-images.githubusercontent.com/4896372/49297813-0a61a300-f4bc-11e8-9761-57f045b52d42.png">

**Comment by albert-92** [comment]
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2758
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2746
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2715
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2711
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2708
