### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by programming-kid** [angular-fullstack/generator-angular-fullstack#304]
It would be nice to have [CORS support](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing) built in fullstack.

**Comment by rahul-islam** [comment]
you can enable CORS in your app using expressjs by including cors module of expressjs.

Installation

   *npm install cors*

To Enable All CORS Requests. Do following in your app server.

var express = require('express');

var cors = require('cors');

var app = express();

app.use(cors());

for more details go to https://github.com/expressjs/cors

**Comment by Sleeeepy** [comment]
Can anyone please tell me if the above solution still works with generator version 4.1.2. ?

I have added cors:
```
import cors from 'cors';
 
...

// Setup server
var app = express();
app.use(cors());
```
I have deployed to production and now I'm trying to make a post request to `/api/things` with hurl.it:
```
HEADERS
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 25
Content-Type: application/x-www-form-urlencoded
User-Agent: runscope/0.1
PARAMETERS
name: "test from cors"

BODY
name=%22test+from+cors%22

```
I get the following response:
```
HEADERS
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 128
Content-Security-Policy: default-src 'self'
Content-Type: text/html; charset=utf-8
Date: Mon, 13 Mar 2017 20:05:11 GMT
Set-Cookie: XSRF-TOKEN=VkNG35bSumuvmihQvot1DNkMdC4S3wuqK6mBE%3D; Path=/, connect.sid=s%3AiO0grrQFkSEM8KhO7D9lave5JWbPIaUx.JJbdBFvzAOoITKrMRjqDVltvADcbzZR0Mb8Q81WUCBE; Path=/; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: X-HTTP-Method-Override, Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Express
X-Xss-Protection: 1; mode=block
BODY
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      <title>Error</title>
    </head>
    <body>
      <pre>Forbidden</pre>
    </body>


```
