### ISSUE TITLE
fixing generator endpoint exports.update save function

### ISSUE THREAD

**Issue by ericmcgregor** [angular-fullstack/generator-angular-fullstack#310]
I ran into an issue where doing a put to my endpoint resulted in mongoose returning:

    TypeError: Object #<Object> has no method 'save'

I was able to fix this by changing _.merge to _.extend, then calling save directly on the results returned by findById instead of the variable "updated".  

Not sure if anybody else was having this issue, but here is what i did.
```javascript
// Updates an existing list in the DB.
exports.update = function(req, res) {
  if(req.body._id) { delete req.body._id; }

  List.findById(req.params.id, function (err, list) {
    if (err) { return handleError(err); }
    if(!list) { return res.send(404); }
    
    // var updated = _.merge(list, req.body);
    
    _.extend(list, req.body);

    //changed from updated to 'list'
    list.save(function (err) {
      if (err) { return handleError(err); }
      return res.json(200, list);
    });
  });
};
```

**Comment by sh4nji** [comment]
Despite the specific issues above it seems that, on a conceptual level, with `_.merge` you lose the ability to remove values from array properties. Since:

```javascript
var dest = {
  p: [1,2,3]
};

var src = {
  p: []
};

_.merge(dest, src);
```
produces
```javascript
[object Object] {
  p: [1, 2, 3]
}
```

**Comment by georgschlenkhoff** [comment]
I have similar issues with PUT request with an array attribute. I have this model:

```
var ThingSchema = new Schema({
  title: String,
  myArray: Array
});
```

Sending this request, ```http://myserver:9000/api/things/54cac17fa90af52d1636asdd```, with ```{ "myArray": ["val1", "val2"] }``` does not update the myArray attribute at all.

My workaround is use datatype 'String' instead of 'Array'.

I'd guess there's something wrong around [here](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/api/thing/thing.controller.js#L67). @DaftMonk, what you think about this issue? BTW: generator-angular-fullstack is AWESOME!!!

**Comment by Awk34** [comment]
@georgschlenkhoff If you're going to try to send a `JSON` array in a REST call you need to `stringify` it

**Comment by simeg** [comment]
I also ran into this problem, changed from `_.merge` to `_.extend` and now it works.

**Comment by sepans** [comment]
+1
I've had problem updating a property of 'Schema.Types.Mixed' type in a schema and after hours of struggling, I came across this thread and changing <code>\_.merge</code> to <code>\_.extend</code> fixed that problem.

(I am far from being an expert in either mongoose or lodash but wanted to document this for the record)

**Comment by macabrer** [comment]
Hi

I had a similar problem. If you want to update a field that is not in your schema model, this fail with merge and with extends. If you add this field in schema model, merge works. I dont try with MixedTypes

Thanks for your generator. ;-)

**Comment by nlaffey** [comment]
I also ran into the problem of my document doc.update not persisting when trying to update  Schema.Types.Mixed array. Changing from _.merge to _.extend fixed this.

**Comment by akcasoy** [comment]
I am not sure if i am having the same problem. 

This is a part of my schema:

var IdeaSchema = new Schema({
  ratings: [{rater: String, star: Number}]

And i am trying to add a rating to the ratings array like this:

$http.put('/api/ideas/' + idea._id, {ratings: [{rater: 'John', star: 5}] });

After the first put, the newer ratings overwrite the array, and i always have the latest rating in it. I tried the suggested extend but it does not seem to work.. I am not sure if i call the api with the correct syntax at all regarding the parameter ratings. And my update method is the generated one:

exports.update = function(req, res) {
  if(req.body._id) { delete req.body._id; }
  Idea.findById(req.params.id, function (err, idea) {
    if (err) { return handleError(res, err); }
    if(!idea) { return res.send(404); }
    var updated = _.merge(idea, req.body);
    updated.save(function (err) {
      if (err) { return handleError(res, err); }
      return res.json(200, idea);
    });
  });
};

**Comment by Awk34** [comment]
@akcasoy technically HTTP PUT should completely **replace** the object at ID with the new object you give it. HTTP PATCH is the method for modifying an existing resource using a change list.

**Comment by akcasoy** [comment]
I thought after you call your api (which is actually defined by you), put / patch has no meaning anymore. For example i assign this api to the update method of the controller. 
```
router.put('/:id', auth.isAuthenticated(), controller.update);
```
then in the update method i can (of course should not) make also a delete.. or do i miss sth here?

```
exports.update = function(req, res) {
    ....
    idea.remove(function(err) {
    ....
  });
};
```

**Comment by Awk34** [comment]
You are correct that you can really do anything that you want, but that would go against the spec

**Comment by akcasoy** [comment]
I edited my original question

**Comment by Awk34** [comment]
You have two main options. For HTTP PUT, send the entire object with its updated values. For HTTP PATCH, send a list of changes:

```json
[
    { "op": "test", "path": "/a/b/c", "value": "foo" },
    { "op": "remove", "path": "/a/b/c" },
    { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
    { "op": "replace", "path": "/a/b/c", "value": 42 },
    { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
    { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
]
```

**Comment by akcasoy** [comment]
I actually meant sth different. But thank you for your help.

**Comment by jimmy4701** [comment]
._extend instead of ._merge in the saveUpdates() method of my MEANjs controller did the work ;) Thank you A LOOOOOOOOT guys =)

**Comment by tarunaahuja** [comment]
Awesome answer @ericmcgregor , you saved my day. Thanks.

**Comment by ksunilu** [comment]
Wow Tons of thanks. this really saved data for me.

**Comment by ksunilu** [comment]
Code change that worked for me is 
========================== 
function saveUpdates(updates) {
  return function(entity) {
    // var updated = _.merge(entity, updates);  //old line
    var updated = _.extend(entity, updates);   //new changed line
    return updated.save()
      .then(updated => {
        return updated;
      });
  };
}
===========================
