### ISSUE TITLE
grunt build and grunt serve:dist relative url issue with images referenced from css

### ISSUE THREAD

**Issue by jzgdev** [angular-fullstack/generator-angular-fullstack#319]
There is a slight issue with `grunt build` and `grunt serve:dist` when referencing image files from css. 

For example: `main.scss` in the path `/client/app/main` contains a reference to an image in the `assets` directory. To access this directory the relative url would look like `../../assets/images/somefile.png`; but when building with `grunt build`, the directory structure is changed and `../../assets/images/somefile.png` turns up a 404. It's an easy fix to change manually but I just thought I would mention it.

**Comment by sejr** [comment]
I'd like to toss out the fact that this is still an issue. Has anyone managed to get it working correctly?

**Comment by vineshhpatel** [comment]
Still having this issue. Any work around?

**Comment by sejr** [comment]
There may be one, but I was never able to find it. If it isn't too much of a hassle, you could try doing it from your HTML file using style="".
