### ISSUE TITLE
grunt serve:debug warns of watching too many files

### ISSUE THREAD

**Issue by ghelton** [angular-fullstack/generator-angular-fullstack#323]
I receive this message when running `grunt serve:debug` from a fresh install, it still works but it does seem to slow my computer down. Is this supposed to be like this?

```
[nodemon] watching 28,042 files - this might cause high cpu usage. To reduce use "--watch".
```

**Comment by balmasi** [comment]
I added an `ignore: ['node_modules/**']` to nodemond's grunt config, and now its not watching a bajillion files.

Couple that with 
``` javascript
'no-preload': true,
```
in the *'node-inspector'* task and now debugging is uber fast
