### ISSUE TITLE
authenticated api tests using supertest?

### ISSUE THREAD

**Issue by ralyodio** [angular-fullstack/generator-angular-fullstack#363]
Has anyone been able to authenticate a user and use that logged in user with mocha/supertest agent?

I get a 401 Unathenticated on the subsequent requests after a session post appears to work.

https://stackoverflow.com/questions/24796968/how-to-make-authenticated-requests-in-mocha-test-using-supertest-and-agent

**Comment by tharrington** [comment]
link to thread?
