### ISSUE TITLE
Where should I place app-wide styles?

### ISSUE THREAD

**Issue by nathanstaines** [angular-fullstack/generator-angular-fullstack#365]
If I were to remove bootstrap, what would be the recommended directory to store app-wide styles like buttons, tables, forms etc?

Ideally I'd still like to be able to use the injector grunt task to dynamically add the imports to client/app/app.scss. What location makes the most sense based on the current generator structure?

client/app/styles/buttons.scss
client/assets/styles/buttons.scss
client/components/styles/buttons.scss

**Comment by genu** [comment]
what about images that are used by the css files? Would those go in the assets folder? I believe they get renamed if they're there.

**Comment by lifwanian** [comment]
Note that if you place it within the app folder, the grunt file will inject all scss files it finds in the folder within the app.scss file alphabetically. As a result you'll be importing files like _layout.scss and _mixins.scss BEFORE your _normalize.scss which you do not want.

Why would something like this be the issue?

assets
| - images
| - fonts
| - styles
