### ISSUE TITLE
Build is injecting app script files and usemin is not replacing image names in templates.

### ISSUE THREAD

**Issue by fusionstrings** [angular-fullstack/generator-angular-fullstack#370]
While running successful build, controller and other components scripts are injected into index.html.

Also it's is not replacing optimized image names with renamed files in templates or CSS.

**Comment by stieler-it** [comment]
@vinesh245 Did you find out why the scripts are not removed? I currently experience the same problem..

**Comment by stieler-it** [comment]
Ok, maybe this is useful for anyone else: Make sure that your source index.html does not mix linefeed styles (unix/windows). Usemin assumes that the lines are separated equally or block replacement might fail. I read that a migration from reg.exps to a html parser is planned which will probably improve this.

**Comment by raghavbali** [comment]
:+1:  Awesome @stieler-it ! That really did the trick

**Comment by talesporto** [comment]
:+1: Awesome @stieler-it! Thanks about it!!! I work hard here!!!

**Comment by SaintPeter** [comment]
+1 @stieler-it Thank you sir!

**Comment by shairez** [comment]
Thanks @stieler-it !

BTW, the configuration in the grunt injector task options is - 
options: {
  lineEnding: '\r'
}

**Comment by luxueyan** [comment]
@shairez  Thanks！This help me !

**Comment by solon-user** [comment]
I had the same problem but with .css files using a Windows machine. Fixed by changing line endings to 'unix' from 'Windows' in Sublime Text 2.

**Comment by Shingaz** [comment]
I had this issue a year ago, I fixed it adding the following option to injector Grunt task:

```
injector: {
   options: {
      lineEnding: grunt.util.linefeed
   }
}
```

**Comment by Tings** [comment]
You are a genius!

**Comment by Tings** [comment]
@Awk34 : Thank you, your issue linking helped! :+1:
