### ISSUE TITLE
Mongo Connection

### ISSUE THREAD

**Issue by IgorDePaula** [angular-fullstack/generator-angular-fullstack#383]
Where the app connect to mongo? I need add gridfs system to app

https://github.com/aheckmann/gridfs-stream

**Comment by azachar** [comment]
Hi there, so how did you pluged it in? Do you have same sample? Cheers, Andrej

**Comment by Awk34** [comment]
@azachar here's an example: https://github.com/Awk34/aksite/blob/master/server/app.js#L40

**Comment by azachar** [comment]
Thank you!
