### ISSUE TITLE
What are the SEO alternatives to prerender.js/.io?

### ISSUE THREAD

**Issue by colwilson** [angular-fullstack/generator-angular-fullstack#393]
I have 4.5 million pages. If I use angular at all prerender.io would be prohibitively expensive, prerender.js prohibitively slow or cpu expensive. 

It strikes me that the data is in the api already and the css is already compiled, so can i just do a server side render for bots? has anyone done this and can you please give me some tips? 

My pages are fairly static, so you may question if I should be using another technology, but if we could ignore that for the moment please.

**Comment by azachar** [comment]
+1

**Comment by yagobski** [comment]
+1

**Comment by oaosman84** [comment]
+1.

Google works fine now, but we have issues with Facebook / Twitter.  I may do a mix of prerender and server-side page generation, will let you know how it goes, but would love to hear if anyone else has a solution here.

**Comment by Awk34** [comment]
#1072
