### ISSUE TITLE
Add support for sequelize

### ISSUE THREAD

**Issue by DaftMonk** [angular-fullstack/generator-angular-fullstack#414]
We should be able to select between using mongodb with mongoose, or sql with sequelize.

**Comment by pensierinmusica** [comment]
Since this has been merged now, is there any chance we can see it in "master" without having to wait for all the other things in milestone 2.1.0?

**Comment by kevinawoo** [comment]
@pensierinmusica you can generate it and use it locally by cloning it and checking out `canary` then doing a `npm link`. Yoeman will use your local version now.

**Comment by pensierinmusica** [comment]
@kevinawoo, yep thanks, that's what I ended up doing!  :)

**Comment by adam-back** [comment]
@kevinawoo :+1: 

For the love of god, please roll this out already!

**Comment by jeffbuhrt** [comment]
@rayokota support seems to be in the main branch. I have been playing with a prototype using Postgres and it is going well. The sqlite3 build on Fedora 22 x86_64 failed to compile, but PG is great.
