### ISSUE TITLE
Font Awesome and Glyhicons are not referenced to the right location

### ISSUE THREAD

**Issue by khwerhahn** [angular-fullstack/generator-angular-fullstack#421]
Hi everything works fine in grunt, except that the the Glyphicon and font-awesome files are not copied. The vendor.css (public/app/vendor.cssf) points to ../fonts/glyphicons . It should point to the bower_components folders though. 

What do I need to change in order to make it work?

**Comment by behrad** [comment]
Solved it this way:

1. Add webfonts to `dist/public/assets` by adding these into `copy.dist.files`:

```js
{
          // include font-awesome webfonts
          expand: true,
          dot: true,
          cwd: '<%= yeoman.client %>/bower_components/font-awesome',
          src: ['fonts/*.*'],
          dest: '<%= yeoman.dist %>/public/assets'
        },{
          // include bootstrap webfonts
          expand: true,
          dot: true,
          cwd: '<%= yeoman.client %>/bower_components/bootstrap/dist',
          src: ['fonts/*.*'],
          dest: '<%= yeoman.dist %>/public/assets'
        }
```


2. Remove webfonts from rev renaming by commenting the following line under `rev.dist.file.source`

```js
'<%= yeoman.dist %>/public/assets/fonts/*'
```


3. Fixing webfont paths from `../fonts` to `../assets/fonts` in `usemin.options.patterns`:

```js
css: [
            [/(..\/fonts\/)/g, 'Fix webfonts path', function(match) {
              return match.replace('../fonts/', '../assets/fonts/');
            }]
          ]
```
