### ISSUE TITLE
Bower vs browserify

### ISSUE THREAD

**Issue by Toub** [angular-fullstack/generator-angular-fullstack#447]
Hi,

First, thanks for your hudge work on this project!

What do you think about the following comment, recommanding to use browserify with npm packages instead of bower?
https://github.com/mapbox/togeojson/issues/53#issuecomment-52198812

Note that there are tools to use bower components with browserify when they are not packaged in npm: https://github.com/eugeneware/debowerify

**Comment by wmertens** [comment]
@DaftMonk for a full-stack JS application, there is likely to be code shared between server and client, for example data validation. With browserify you'd have a single module implementing the validation and the client side can avoid round trips and code duplication. It also allows using Underscore-like libraries without there having to be a bower package with possibly differing semantics.

That said, browserify and bower can live side-by-side, and cdnify only works with bower AFAIK.
