### ISSUE TITLE
Navbar not collapsing without ui-bootstrap

### ISSUE THREAD

**Issue by Kageetai** [angular-fullstack/generator-angular-fullstack#458]
Hey,

I just tried out the generator and noticed after some changes to the generated project, that the navbar is not collapsing. It seems the directive "collapse" is missing or at least I cannot find it. Am I missing something here?

**Comment by raosushant** [comment]
Depending on your version of UI-Bootstrap you might have to modify

`collapse='isCollapsed'
`
to
`uib-collapse ='isCollapsed'
`
in navbar.html
