### ISSUE TITLE
Insecure API?

### ISSUE THREAD

**Issue by nathanstaines** [angular-fullstack/generator-angular-fullstack#493]
If I add auth.isAuthenticated() to things router.get('/', controller.index) and then navigate to /api/things I get a message saying "UnauthorizedError: No Authorization header was found".

However, if I then view the page source I am able to view the JSON response. I'm assuming this is unexpected behaviour as it doesn't seem to happen with /api/users?

**Comment by haywirespark** [comment]
I had the same issue, but clearing by browser cache didn't work. http://stackoverflow.com/questions/29151894/no-authorization-header-was-found-angular-fullstack
