### ISSUE TITLE
endpoint generator fails due to undefined error

### ISSUE THREAD

**Issue by tmacdonald** [angular-fullstack/generator-angular-fullstack#509]
Note: I included socket.io support on initial angular-fullstack generation.

yo angular-fullstack:endpoint event
[?] What will the url of your endpoint to be? /api/events

``` javascript
/usr/local/lib/node_modules/generator-angular-fullstack/endpoint/index.js:58
  if (this.filters.socketio) {
                  ^
TypeError: Cannot read property 'socketio' of undefined
    at Generator.registerEndpoint (/usr/local/lib/node_modules/generator-angular-fullstack/endpoint/index.js:58:19)
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:387:14
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by TrySpaceCo** [comment]
I have the same problem and it says that I do not have .yo-rc.json in my home directory

**Comment by TrySpaceCo** [comment]
I understand that that is a good thing but where am I supposed to put it? From what I've seen on github, it's supposed to be part of gitignore . . .
