### ISSUE TITLE
Bootstrap script not being injected

### ISSUE THREAD

**Issue by jnwelzel** [angular-fullstack/generator-angular-fullstack#565]
Hi!

Thanks for your awesome generator, it has made life a lot easier for me!

I recently deployed an app to production using `yo angular-fullstack:heroku`, but I noticed that the bootstrap-related javascript was not being loaded as I tried to open a modal. I declared the bootstrap .js file as a bower dependency in `index.html` and all...

I tried looking around the config files etc, but I'm pretty new to this frontend stack and couldn't figure out what could be wrong. I'd appreciate any input on this.

Thanks!

**Comment by MichaelJCole** [comment]
It's in Gruntfile.js, in the 'wiredep' section.

**Comment by SaintPeter** [comment]
I don't understand why this is still true.  This was confusing as heck, as to why my bootstrap.js was not being loaded.

**Comment by kingcody** [comment]
@SaintPeter this is a bug, the `bootstrap.js` exclude regexp should only be included when `filters.uibootstrap === true`. I'll try to get a PR together that addresses the issue. However, if this is something that you feel comfortable fixing; then by all means, submit a PR.

**Comment by SaintPeter** [comment]
@kingcody Pull Request submitted.  I have not tested it, but it's very straightforward.
