### ISSUE TITLE
Issue when running rev:dist

### ISSUE THREAD

**Issue by benshaw** [angular-fullstack/generator-angular-fullstack#592]
```
Running "rev:dist" (rev) task
dist/public/app/app.js >> cc394b57.app.js
dist/public/app/vendor.js >> b642c6ee.vendor.js
Warning: Unable to read "dist/public/bower_components/mapbox.js" file (Error code: EISDIR). Use --force to continue.
```

It appears that the name matching matches because of the poorly named module (mapbox.js is the name of the directory not a file)

**Comment by ascheucher** [comment]
If you do not want to exclude the whole bower_components directory, you can exclude the affected library's folder and include the libraries .js files again. Here an example for 'auth0.js':

        '<%= yeoman.dist %>/public/{,*/}*.js',
        '!<%= yeoman.dist %>/public/bower_components/auth0.js',
        '<%= yeoman.dist %>/public/bower_components/auth0.js/{,*/}*.js',
