### ISSUE TITLE
Ckeditor error not finding other needed files. 

### ISSUE THREAD

**Issue by QuietOmen** [angular-fullstack/generator-angular-fullstack#622]
So I have a feeling that this might be similar to the other issue I just reported (https://github.com/DaftMonk/generator-angular-fullstack/issues/621). So I'm having issues with MIME types. I'm trying to use ckeditor and it has issues until I move the script outside of the bower injector section. So if I simply move 
```
<script src="bower_components/ckeditor/ckeditor.js"></script>
```
out it works. I discovered this from reading this thread (http://ckeditor.com/forums/CKEditor/CKEditor-problem-after-a-grunt-build) I would like to figure out why it doesn't work as is, since I don't want to have to move future script tags out manually...as I feel there has to be a better solution. Here's the error I get when I don't move it out of the bower section in the index.html 

```
Resource interpreted as Script but transferred with MIME type text/html: "http://localhost:8080/". 817928e5.vendor.js:20
Refused to execute script from 'http://localhost:8080/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled. (index):1
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8080/". 817928e5.vendor.js:20
Resource interpreted as Script but transferred with MIME type text/html: "http://localhost:8080/". 817928e5.vendor.js:20
Refused to execute script from 'http://localhost:8080/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled. (index):1
Uncaught TypeError: Cannot set property 'dir' of undefined 
```

Any help on this would be appreciated. Thanks, and let me know if anything else from me would help.

**Comment by entrity** [comment]
:+1:
