### ISSUE TITLE
Dependency problems

### ISSUE THREAD

**Issue by ivailo-stoianov** [angular-fullstack/generator-angular-fullstack#663]
Hello guys,
I am having troubles with using NgInfiniteScroll here. If I try to use it in my module I get very cool error in the console, the "Failed to instantiate module myApp due to: [$injector:unpr] Unknown provider: $stateProvider".
What's so bad in my code, which is:

``` javascript
angular.module('myApp', ['infinite-scroll'])
.controller
```

I tried everything I can think of. Sorry about this stupid question but...

**Comment by alihalabyah** [comment]
@kingcody Dude you're awesome in 2015 too :)
