### ISSUE TITLE
How do I build and deploy to a sub-folder via FTP?

### ISSUE THREAD

**Issue by lifeonlars** [angular-fullstack/generator-angular-fullstack#668]
I'm having problems getting the build function to create the right paths for deploying the app to a subfolder on an FTP. 

The local serve:dist works however after uploading all the paths are referencing root of the domain and are not relative to the subfolder. E.g. when deploying to http://www.exampledomain.com/meanapp/public the js,css, images, routes and apis are referencing http://www.exampledomain.com/

I tried updating the <base href="/"> however that only worked for a handful of the CSS and image files. I also looked at changing the filepath in the grunt file. But both options would break the local preview of serve:dist. 

Is there a config option for this somewhere or a straightforward way of doing this. How can I either ensure that everything in dist uses a relative path or define the correct subfolder for the dist build? 

Is this even possible or do I have to deploy via something like Heroku or Openshift?

Thanks

**Comment by Djalmar** [comment]
@larfa can you find some way to make it work ? i'm experimenting same issue
