### ISSUE TITLE
Error: Failed to lookup view "index" in views directory "/test/dist/app/views"

### ISSUE THREAD

**Issue by alexsuslov** [angular-fullstack/generator-angular-fullstack#67]
OS X:
## init

```
$> yo angular-fullstack --coffee --jade
```
- all yes ;)

```
$> grunt serve:dist

$> cd dist
$> node server.js

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express server listening on port 3000 in development mode
finished populating things
finished populating users
```

Chrome http://localhost:3000

```
...
Error: Failed to lookup view "index" in views directory "/test/dist/app/views"
...
```

'app' - unnecessary

**Comment by TylerPflueger** [comment]
Was anything solved on this? I keep having the same error as above and wasn't able to fix it.

**Comment by karthikeyana** [comment]
use this code to solve the issue

```
app.get('/', function(req, res){
    res.render("index");
});
```

**Comment by akhil-sharma25** [comment]
I fixed this error as I got it couple of times:
   app.get('/', function(req, res){
    res.render("/index");
});
never put "/" before rendering instead use :
app.get('/', function(req, res){
    res.render("index");
});

**Comment by juanjosejaramillo** [comment]
Make sure that your folder is in the proper path. Accidentally I placed the folder inside my controllers folder and that's why I was getting that error.

**Comment by Yohei-Shiina** [comment]
I had the same issue and it turned out that I named views/index as index."js" but "jsx"
