### ISSUE TITLE
canary/ (too) many files in dist/client/bower_components?

### ISSUE THREAD

**Issue by remicastaing** [angular-fullstack/generator-angular-fullstack#671]
I'm wondering why after a `grunt build` there is so many files in the `dist/client` folder.

For angular, there is:
- angular.js
- angular.min.js
- angular.min.js.gzip
- angular.min.js.map
- bower.json
- package.json
- README.md

I'm wondering if there is really a need for all of this files.

As result, a "builded" client side weight 9.4 MB for a fresh scaffolded app.

**Comment by Awk34** [comment]
I think the only real solution for this is to manually tell the build process which files need to be copied over (bootstrap fonts, font-awesome fonts, etc). I have tried this and it seems to work fine.
