### ISSUE TITLE
You need to have Ruby and Sass installed and in your PATH for this task to work

### ISSUE THREAD

**Issue by andrejkaurin** [angular-fullstack/generator-angular-fullstack#677]
Installation goes well. Also I have installed

npm install grunt-contrib-sass --save-dev

When running "grunt serve" following warning occurs 
//
Warning: Running "sass:server" (sass) task
Warning: 
You need to have Ruby and Sass installed and in your PATH for this task to work.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Use --force to continue.

Aborted due to warnings. Use --force to continue.
//
localhost:9000 runs blank page and app.js and app.css files are returning error 404

**Comment by stefek99** [comment]
> You need to have Ruby and Sass installed and in your PATH for this task to work.

This thread is 2nd result.

1st one is here - http://stackoverflow.com/questions/20176410/how-to-resolve-you-need-to-have-ruby-and-sass-installed-and-in-your-path-for-th - ```gem install sass``` (on my machine I had to add ```sudo```)

**Comment by gangsthub** [comment]
:+1:

**Comment by prakyathacharya** [comment]
watch this

https://www.youtube.com/watch?v=VSQf10i0_7c
