### ISSUE TITLE
glyphicon 

### ISSUE THREAD

**Issue by alexsuslov** [angular-fullstack/generator-angular-fullstack#68]
OS X

```
$> yo angular-fullstack --jade

```

Add to footer glyphicon button.

```
.footer
  button.btn.btn-primary
    span.glyphicon.glyphicon-search
  p ♥ from the Yeoman team
```

Look like normal in:

```
$> grunt serve
```

But in

```
$> grunt serve:dist
```

show button with square

**Comment by jeveloper** [comment]
@rodrigouroz Just wanted to add that you can modify gruntile.js 
find: /fbootstrap.js/,  
Remove that portion, that way you'll get that script
Id like to propose changing it to 
/^fbootstrap.js/,
Because there other libs that get excluded for no reason.
