### ISSUE TITLE
Socket.io & JWT

### ISSUE THREAD

**Issue by samgranger** [angular-fullstack/generator-angular-fullstack#690]
I added the JWT token in the socket query as documented in client/components/socket/socket.service.js

However, because socket.io-client/socket.io.js is included in index.html, it tries to connect, even if the user is not authenticated / no token. Removing this line and adding it to a partial file that users see when authenticated causes errors for users that are not authenticated.

How can I connect to socket.io correctly, only when I'm authenticated?

**Comment by mlepperly** [comment]
Using this configuration works, but the user is required to reload their page after authentication and socket will not connect automatically without that. Has anyone figured out how to attempt reconnection after authentication success client side? I implemented the above code.

**Comment by marsanla** [comment]
+100

**Comment by groupsvkg** [comment]
@mlepperly i tried $window.location.href = '/'; to relaod and it works fine for me

**Comment by audrummer15** [comment]
+1

**Comment by macneib** [comment]
I just added a hack to client/components/auth.service.js
after login success, setting a token, getting the user data I broadcast with the following

````javascript
      login: function(user, callback) {
        var cb = callback || angular.noop;
        var deferred = $q.defer();

        $http.post('/auth/local', {
          email: user.email,
          password: user.password
        }).
        success(function(data) {
          $localStorage.token = data.token;
          currentUser = User.get();
          $rootScope.$broadcast('authenticated');
          deferred.resolve(data);
          return cb();
        }).
        error(function(err) {
          this.logout();
          deferred.reject(err);
          return cb(err);
        }.bind(this));

        return deferred.promise;
      },
````

then in components/sockets/socket.service.js

````javascript
    // listen for the authenticated event emitted on the rootScope of
    // the Angular app. Once the event is fired, create the socket and resolve
    // the promise.
    $rootScope.$on('authenticated', function() {
      console.log('$rootScope authenticated');
      ioSocket = io('', {
        // Send auth token on connection, you will need to DI the Auth service above
        forceNew: true,
        query: 'token=' + auth.getToken(),
        path: '/socket.io-client'
      });
    });
````

I left the original socket.service.js code as is, it's just a drop in and seems to work well enough for my purposes.  If you find a better way please post your solution.
Cheers!

**Comment by stephengardner** [comment]
+1000.  Issues referencing each other but no updates.

If I authenticate asynchronously, the socket seems to go bad.  

@macneib what does your `forceNew` parameter do?

**Comment by timum-viw** [comment]
one way to deal with this problem is to make websocket authentication optional. You can do this by modifying the socketio.on('connection') event in server/config/socketio.js like this.

```javascript
socketio.on('connection', function(socket) {
    //add this to allow optional authorization of websockets
    require('socketio-jwt').authorize({
      secret: config.secrets.session,
      required: false
    })(socket);

    socket.address = socket.request.connection.remoteAddress +
      ':' + socket.request.connection.remotePort;

    socket.connectedAt = new Date();

    socket.log = function(...data) {
      console.log(`SocketIO ${socket.nsp.name} [${socket.address}]`, ...data);
    };

    // Call onDisconnect.
    socket.on('disconnect', () => {
      onDisconnect(socket);
      socket.log('DISCONNECTED');
    });

    // Call onConnect.
    onConnect(socket);
    socket.log('CONNECTED');
  })
  .on('authenticated', (socket) => {
    //will be called upon authentication of websocket
    //you can register event handlers here that need authentication
    onAuthenticated(socket);
  });
```
you then have to emit the authentication token upon login or signup with 
```javascript
socket.emit('authenticate', {token: Auth.getToken()});
```
I also added the following line to socket factory to send authentication token upon refresh
```javascript
if(!!Auth.getToken()) {
      ioSocket.emit('authenticate', {token:Auth.getToken()});
}
```

**Comment by Awk34** [comment]
I think that answers it
