### ISSUE TITLE
Documentation needed for NODE_ENV

### ISSUE THREAD

**Issue by stefaneg** [angular-fullstack/generator-angular-fullstack#712]
This should definitely work out of the box on a freshly generated app IMHO

yo angular-fullstack
grunt
cd dist (or dist/server)
node app.js

The error generated is:
     Error: ENOENT, stat 'client/index.html'

It would help to include something in your documentation for running the built application, something like

set -x NODE_ENV production
or
export NODE_ENV=production

Since not everyone is planning to deploy to heroku or similar.

**Comment by kajikaji** [comment]
@stefaneg 
I changed the following.
dist/server/config/express.js
23 line
 //var env = app.get('env');
  var env = 'production';

**Comment by robert-irribarren** [comment]
Hey i know im late to the party

**My Solution:**
I run a string-replace task in my grunt build task

Here is the config

/** 
     * This is used to replace the development string in the dist folder after its built
    **/
    'string-replace': {
      dist: {
        files: {
          '<%= yeoman.dist %>/server/app.js': '<%= yeoman.dist %>/server/app.js',
          '<%= yeoman.dist %>/server/config/express.js': '<%= yeoman.dist %>/server/config/express.js',
        },
        options: {
          replacements: [
          {
            pattern: /process.env.NODE_ENV =.*/ig,
            replacement: function (match, p1) {
              return 'process.env.NODE_ENV = "production";'
            }
          },
          {
            pattern: /var env = .*/ig,
            replacement: function (match, p1) {
              return 'var env = "production";'
            }
          }
          ]
        }
      }
    },
Just put that in grunt.initConfig({
.......
})

then run your grunt task. I use https://github.com/erickrdch/grunt-string-replace

**Comment by sinanmb** [comment]
Thank you @kajikaji!
