### ISSUE TITLE
Get current user in model server-side

### ISSUE THREAD

**Issue by Kageetai** [angular-fullstack/generator-angular-fullstack#727]
Hi there,
I am very new to authentication on the server side and don't really understand most of what the generator does yet.
But I want to save the current user to a field in another model when it is created. So I guess I have to modify the `create` function in my models controller, but I have no idea how to get the currently logged in user. Can anyone help me there?

**Comment by BenjaminConant** [comment]
I could be wrong but I think that `expressJwt` is doing the attaching of the user auth.isAuthenticated() finds the JWT ... either in req.query.access_token or in `req.headers.authorization` .... so the function `validateJwt(req, res, next);` is what attaches the user if the JWT is valid. ... you can see this in `auth.service.js`

**Comment by rugved-inamdar** [comment]
@Kageetai can you please share the snippet of your code. I want the userId to be added to my object before being saved in the db.

**Comment by Kageetai** [comment]
@rugved-inamdar I didn't need anything new code back then, the user already got attached which I didn't see at first :)
