### ISSUE TITLE
canary branch ...sequelize related multiple bugs

### ISSUE THREAD

**Issue by misu200** [angular-fullstack/generator-angular-fullstack#741]
After  generating a sequelize enabled project I encountered some problems:

1) when changing password for a local user it seems the new 'salt' field does not get updated in the sqlite Users table... probably because in the User.beforeUpdate() sequelize hook any fields updated there(like the salt) dont get into the SQL UPDATE query

2)
 in server/api/auth/facebook/passport.js ...

  Searching for a specific facebook user profile using squelize is made in a wrong way because 'facebook' is just a DataTypes.TEXT in our model definition:
  
    User.find({
      where: {
        'facebook.id': .......
      }
    })

**Comment by kingcody** [comment]
@misu200, thank you so much for this bug report. Those issues definitely need to be resolved. I'll look into a fix.

Also, if you have any ideas please feel free to discuss them here.

Thanks again.

**Comment by Awk34** [comment]
@kingcody any news on this?

**Comment by kingcody** [comment]
I could not reproduce the first issue.

The second, however, should be addressed.

**Comment by benjipott** [comment]
simply add facebook: DataTypes.JSON in User Model
