### ISSUE TITLE
Add extra meta tag on index.html

### ISSUE THREAD

**Issue by georgeportillo** [angular-fullstack/generator-angular-fullstack#754]
As the Angular.js docs say:

" To allow indexing of your AJAX application, you have to add special meta tag in the head section of your document:

``` HTML
<meta name="fragment" content="!" />
```

This will cause crawler bot to request links with _escaped_fragment_ param so that your server can recognize the crawler and serve a HTML snapshots.  "

I think it'd be beneficial for us to have this very small changed implemented. Here is the link to the angular doc: https://docs.angularjs.org/guide/$location

**Comment by helgetan** [comment]
Hey i'm not quite sure if this is neccesary? Do we have to add this for good SEO results? And is there an example for "your server can ... serve a HTML snapshot" ?

**Comment by Koslun** [comment]
Think Angular Universal will be a lot more effective at this.
