### ISSUE TITLE
Error while running concurrent:server task

### ISSUE THREAD

**Issue by ghost** [angular-fullstack/generator-angular-fullstack#76]
I am just getting started with generator-angular-fullstack.
I get the following error:

Loading "cdnify.js" tasks...ERROR

> > Error: Unable to create git_template directory: Arguments to path.resolve must be strings

If I run `grunt serve`, though I get the error, I am able to access the app from browser. 
But if I do `grunt server"dist`, I get

Loading "cdnify.js" tasks...ERROR

> > Error: Unable to create git_template directory: Arguments to path.resolve must be strings

Running "serve:dist" (serve) task
Warning: Task "cdnify" not found. Use --force to continue.

So, I use `--force` option. But this, the server is not running.

Thanks

**Comment by juniorabreu07** [comment]
execute `install grunt-google-cd@0.3.0` 

install version 0.3.0 there are components that are not in more updated versions
