### ISSUE TITLE
io undefined after deploy to heroku

### ISSUE THREAD

**Issue by jordanbaucke** [angular-fullstack/generator-angular-fullstack#766]
I went ahead and re-ran the generator with a clean app. just to see if there was anything I could pick-out that I might have changed in the configuration, however, aside from uncommenting the 'Auth' module like so:

```
angular.module('myApp')
    .factory('socket', function(socketFactory, Auth) {

        // socket.io now auto-configures its connection when we ommit a connection url
        var ioSocket = io('', {
            // Send auth token on connection, you will need to DI the Auth service above
            'query': 'token=' + Auth.getToken(),
            path: '/socket.io-client'
        });

        var socket = socketFactory({
            ioSocket: ioSocket
        });
```
`grunt build` & `grunt buildcontrol:heroku` run normally without errors?

However when I load the app in Heroku I still get:

```javascript
ReferenceError: io is not defined
```

**Comment by Tazer** [comment]
I'm having the same problem when running grunt serve:dist .

I do see that in the code there is a config for serveClient , it gets set to false when production. But even if i set it to true, it doesnt work .. the code work fine with "grunt serve"

**Comment by jordanbaucke** [comment]
@Tazer ok good I was starting to think I was the only one...hmmm

**Comment by camcim** [comment]
Same my end. I'm able to grunt serve however I get the above mentioned io error when deployed to heroku

**Comment by fergalmoran** [comment]
What was the solution here, I'm still seeing this, need to set serveClient: true in production.

**Comment by Awk34** [comment]
Closed due to inactivity

**Comment by xeroxoid** [comment]
Hi, just to inform everyone who may face this issue, the problem for me was that newer versions of socket.io-client contain the file within ```dist```, rather than the root directory (as in previous versions).

Thus, in ```index.html``` you would have to change the line:

```<script src="socket.io-client/socket.io.js"></script>```

to

```<script src="socket.io-client/dist/socket.io.js"></script>```

and the bundler will then package it correctly into ```xx.vendor.js```

This came up when I remove the ```node_modules``` folder and freshly installed all the packages.

**Comment by LuxDie** [comment]
Hey, I'm having this issue with version 3.8 of the generator.

I've tried xeroxoid solution but the socket library is still not getting inside vendor.js. I've also tried installing the bower version and pointing to it, like so: `<script src="bower_components/socket.io-client/dist/socket.io.js"></script>`, to no avail.
This happens with a new project out of the box after running `gulp serve:dist`.

Any idea why?

**Comment by WasimAhmad** [comment]
Have same issue here... I am working on a project using angular-fullstack@3.7.6 and having issue on gulp serve:dist
ReferenceError: io is undefined. 
gulp serve is working good..
how to fix it???

**Comment by WasimAhmad** [comment]
for now @xeroxoid solution worked..

**Comment by WasimAhmad** [comment]
to work for both production and development search and update path for 
socket.io-client 
as 
socket.io-client/dist
