### ISSUE TITLE
karma.config.js patterns and preprocessors

### ISSUE THREAD

**Issue by MAustinMMDP** [angular-fullstack/generator-angular-fullstack#787]
I found that when running "grunt test" on a fresh project that did not include coffee or jade in the build the karma.conf.js file still includes the jade and coffee files / patterns to load in the browser. This causes a WARN message to say the pattern does not match any file. 

Example: 

<blockquote>
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "C:/Projects/website/client/app/app.coffee" does not match any file.
WARN [watcher]: Pattern "C:/Projects/website/client/app/**/*.coffee" does not match any file.
WARN [watcher]: Pattern "C:/Projects/website/client/components/**/*.coffee" does not match any file.
WARN [watcher]: Pattern "C:/Projects/website/client/app/**/*.jade" does not match any file.
WARN [watcher]: Pattern "C:/Projects/website/client/components/**/*.jade" does not match any file.
INFO [PhantomJS 1.9.8 (Windows 8)]: Connected on socket jO5LxeSHcf-8-jxvYXyQ with id 83187796
PhantomJS 1.9.8 (Windows 8): Executed 1 of 1 SUCCESS (0.024 secs / 0.027 secs)<br><br>

Done, without errors.
</blockquote>

You can manually comment out the files and preprocessors in karma.conf.js, as shown below, but I'm not sure this is a best practice as it might be removed when running "npm install". 

    // list of files / patterns to load in the browser
    files: [
      'client/bower_components/jquery/dist/jquery.js',
      'client/bower_components/angular/angular.js',
      'client/bower_components/angular-mocks/angular-mocks.js',
      'client/bower_components/angular-resource/angular-resource.js',
      'client/bower_components/angular-cookies/angular-cookies.js',
      'client/bower_components/angular-sanitize/angular-sanitize.js',
      'client/bower_components/angular-route/angular-route.js',
      'client/bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
      'client/bower_components/lodash/dist/lodash.compat.js',
      'client/app/app.js',
      //'client/app/app.coffee',
      'client/app/**/*.js',
      //'client/app/**/*.coffee',
      'client/components/**/*.js',
      //'client/components/**/*.coffee',
      //'client/app/**/*.jade',
      //'client/components/**/*.jade',
      'client/app/**/*.html',
      'client/components/**/*.html'
    ],

    preprocessors: {
      //'**/*.jade': 'ng-jade2js',
      '**/*.html': 'html2js'
      //'**/*.coffee': 'coffee',
    },

Running "grunt test" after manually commenting out the lines above fixes the problem. 

Example: 

<blockquote>
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 8)]: Connected on socket T-kIf5LLmRxRCgawd_Zc with id 95337074
PhantomJS 1.9.8 (Windows 8): Executed 1 of 1 SUCCESS (0.031 secs / 0.026 secs)<br><br>

Done, without errors.
</blockquote>
Not a big deal but it would be nice if the generator was updated to include the test configuration when a feature is not included in the build.

**Comment by Awk34** [comment]
I've noticed this before, but since it doesn't break anything I've been too lazy to fix it

**Comment by Awk34** [comment]
This has been fixed
