### ISSUE TITLE
Small sugestion to display version from package.json

### ISSUE THREAD

**Issue by gintsgints** [angular-fullstack/generator-angular-fullstack#810]
To show version in main page from package.json when using jade:
- add version as jade variable:

``` javascript
     jade: {
       compile: {
         options: {
           data: {
            debug: false,
            version: '<%= pkg.version %>'
           }
         },
         files: [{
```
- put version as text in jade file:

``` javascript
     v.#{version}
```

**Comment by Awk34** [comment]
Seeing the generator version can be useful right after running the generator,  but I dont see much point in keeping it shown after that point

**Comment by gintsgints** [comment]
This is not about generator version. But generated application version.

**Comment by Awk34** [comment]
Ooohhhhh I see what you're saying. Throw a PR up!

**Comment by Awk34** [comment]
Closed due to inactivity
