### ISSUE TITLE
IE 8 issue with Heruku

### ISSUE THREAD

**Issue by jpoiri** [angular-fullstack/generator-angular-fullstack#822]
Hi there,
I am running into a issue when testing my application on Heroku with IE 8. As soon the page open its crashes the browser window (See below). However when I test the same application locally on IE 8 it works perfectly. Has anyone seen this before? Is it problem with Heroku?

![image](https://cloud.githubusercontent.com/assets/6857740/6173014/14644dcc-b2bb-11e4-8ee2-e29688e91237.png)

Thanks
-Justin

**Comment by Awk34** [comment]
Closed due to inactivity
