### ISSUE TITLE
Karma fails testing directives

### ISSUE THREAD

**Issue by georgschlenkhoff** [angular-fullstack/generator-angular-fullstack#823]
Whenever I add a directive with the ```yo angular-fullstack:directive myDirective``` command and afterwards I do ```grunt``` to build the dist folder, karma fails with this message:

```
PhantomJS 1.9.8 (Linux) ERROR
  SyntaxError: Parse error
  at /myproject/client/components/user/user.html.js:3
```

If I add this stupid file everything works fine, but I wonder: where can I fix this?

**Comment by kingcody** [comment]
Whats in your `/myproject/client/components/user/user.html.js` file? Also what tests are in that folder?

**Comment by georgschlenkhoff** [comment]
That's the content of my ```user.html.js``` file:
```
//TODO: remove this file, just for karma
```

The following test is in the folder:

```
'use strict';

describe('Directive: user', function () {
  beforeEach(module('jobhermesApp'));
});
```

And then finally ther is the ``user.directive.js```:

```
'use strict';

angular.module('jobhermesApp')
  .directive('user', function () {
    return {
      templateUrl: 'components/user/user.html',
      restrict: 'A'
    };
  });
```

**Comment by kingcody** [comment]
Thats odd, so if the file DOESN'T exist then it complains about a parse error on line 3 of a non-existing file... (`SyntaxError: Parse error at /myproject/client/components/user/user.html.js:3`)

Maybe check the `.tmp` folder and see whats in there, like `.tmp/components/user/`
