### ISSUE TITLE
Modular Gruntfile Configuration

### ISSUE THREAD

**Issue by kingcody** [angular-fullstack/generator-angular-fullstack#848]
Hi everyone, I'd like to start working on a modular Gruntfile setup for the project. If anyone has any ideas or random thoughts they'd like to add, please feel free to comment.

Side note:
If there are some gulp veterans out there, it'd be really nice if they could help out with porting the modular grunt configs/tasks to modular gulp tasks in the process.

**Comment by kingcody** [comment]
If anyone would like to checkout what I have so far, here's my [feature branch](https://github.com/kingcody/generator-angular-fullstack/tree/feature/modular-grunt).

Opinions welcomed.

**Comment by Awk34** [comment]
*thumbs up*

**Comment by ericmdantas** [comment]
I might give a hand with the gulp config this weekend.

**Comment by remicastaing** [comment]
Is there a way, the [web-starter-kit project](https://github.com/google/web-starter-kit) could be a help for the client side?

**Comment by kingcody** [comment]
@ericmdantas that would be awesome. I'll be around as well this weekend, let me know if you need anything. It'd be really cool if we could get this up for review soon. Then we can start lookin at what it'll take to break it out as a sub-generator.

@remicastaing thanks for the link, let's review it :smile:

**Comment by kingcody** [comment]
I've updated my [feature branch](https://github.com/kingcody/generator-angular-fullstack/tree/feature/modular-grunt) so that the client and server have their own grunt config/tasks. The `Gruntfile.js` is used to define project level configs and tasks needed to implement the original tasks used, calling the proper client and server tasks accordingly.

I would really appreciate some reviews :smiley: 

/cc @Awk34 @ericmdantas @remicastaing @DaftMonk

**Comment by ericmdantas** [comment]
It's looking good, @kingcody.

I really like the separation of concerns there. 

Not to mention how much readable the file actually is, going from 800+ lines to 100~150. I mean, of course it could be a pain to find a specific error, but if we manage to keep the files as stable as possible, that should not happen often.

One thing to keep in mind is the testing of such files - when you're done with the separations, I'd suggest you put the expected files to be generated among [these](https://github.com/kingcody/generator-angular-fullstack/blob/master/test/test-file-creation.js#L289-L305).

I'll take a closer look tomorrow morning.

By the way, I didn't forget about the gulp thing, I just didn't have enough time to do it yet.

**Comment by Awk34** [comment]
@kingcody it's better than everything in one file, but idk how I feel about **that** many files. Is there a way we could do this by splitting them into less files?

**Comment by kingcody** [comment]
@ericmdantas, good to hear. Hopefully it'll be fairly easy to construct the gulp streams with the tasks broken up like they are now.

@Awk34, I definitely here you on the amount of config files there are. The good thing about `load-grunt-configs` is we can split up the config however we want. I'd love to hear some suggestions.

**Comment by Awk34** [comment]
How about files for cleaning, wiring (rev, usemin, etc.), minification, serving (local express), testing, watchers, etc. ?

**Comment by JaKXz** [comment]
One "simple" suggestion I would have to help with this would be the use of coffeescript by default / exclusively for the Gruntfile - I find the cson notation much easier to read especially when certain tasks have options buried quite deep.

In my most recent project it's saved me 300+ LOC from the Gruntfile making the simple switch.

I'll reserve my comments and recent experience with Gulp for a separate issue. But things look good so far @kingcody!

**Comment by dotch** [comment]
as a side note:
angular2 has a very good example of a clean and modular gulpfile
https://github.com/angular/angular/blob/master/gulpfile.js

**Comment by sp90** [comment]
If your going to rewrite the preprocesser, i've build this modular gulp system, maybe you can get some idears of how to do it in grunt, tough it would be nice to have a gulp build aswell for faster sass & script builds :+1: 

Main file
https://github.com/sp90/prototype-builder/blob/master/gulpfile.js

Module folder:
https://github.com/sp90/prototype-builder/tree/master/gulp
