### ISSUE TITLE
how to change url for a project

### ISSUE THREAD

**Issue by dezechristophe** [angular-fullstack/generator-angular-fullstack#854]
hello,

What is the best practice to change the url created by grunt  build ?

I want to get my project works with something like
http://127.0.0.1:9000/test/

Is it possible ?

If it's possible to do this with nginx, it could be an acceptable solution too!
thanks

**Comment by kingcody** [comment]
Hey there @dezechristophe, you can accomplish this in several ways:
- Express [`router.use`](http://expressjs.com/api.html#router.use) + `PORT=SOME_PORT_NUMBER grunt serve`
- Nginx [location](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) + [proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass)

**Comment by dezechristophe** [comment]
ok but ..
if I run NODE_ENV=production npm start , in dist folder,
with this nginx conf :
  location /test {
    proxy_pass http://localhost:8080;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }


 I get 404 errors for app/*css,js files 

And for the "express" way to do this, i'm always redirect to 127.0.0.1:8080/

**Comment by kingcody** [comment]
Try this for your config:
```nginx
location /test {
  rewrite            /test/(.*) /$1  break;
  proxy_pass         http://localhost:8080;
  proxy_set_header   Host $host;
  proxy_set_header   Upgrade $http_upgrade;
  proxy_set_header   Connection 'upgrade';
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Proto $scheme;
  proxy_redirect     off;
  proxy_cache_bypass $http_upgrade;
}
```
Notice the `rewrite` directive.

**Comment by dezechristophe** [comment]
this only works for 127.0.01/test/index.html 

all links and scripts included in index.html are 127.0.0.1/app/*.css or js => 404

it should be http://127.0.0.1/test/app/*js,css

**Comment by dezechristophe** [comment]
location /app {
 rewrite ^/app/(.*)$ /test/app/$1;
}
location /api {
 rewrite ^/api/(.*)$ /test/api/$1;
}


work better !

I just got to remove redirection from http://127.0.0.1/test/ to  http://127.0.0.1/

**Comment by dezechristophe** [comment]
Reloading nginx configuration: [emerg]: unknown directive "proxy_cache_bypass" in /etc/nginx/sites-enabled/default:42

in fact I can't do
location /api {
rewrite ^/api/(.)$ /test/api/$1;
}
I have already  /api on my server

I don't know how to solve my problem

**Comment by Awk34** [comment]
closed due to inactivity
