### ISSUE TITLE
Ideas: Promises or Callbacks? Better 'MVCish' pattern?

### ISSUE THREAD

**Issue by ericmdantas** [angular-fullstack/generator-angular-fullstack#862]
Hey, guys.

I'd like to know your opinion about the servers's api generated files.

Today, when you run this generator, you'll have the following files in ```server/api/thing```:

```
index.js
thing.model.js
thing.controller.js
```

(Just forget for a second the socket and spec files)

Alright, inside **index.js** we have all the routes for ```thing```, and the functions that will take care of each route. I, for one, love this approach. So, in my opinion, nothing to change there.

Inside **thing.model.js** we have the skeleton of ```thing```, and that's it. IMHO, that's also a very nice way to approach it, so all good.

Now, inside **thing.controller.js** we have: 
- requisition;
- response;
- model; 

The last one interacting with your database, doing the logic business and suchs and then, retrieving a response to the client.

I believe we could make this better. We could make the controller take care of the requisition and response objects - by knowing how to understand what the client wants and responding to it - but not necessarily knowing what happens in the DB logic.

I'd create a file called **things.dao.js** and have my data acess logic there.

So, instead of having:

```js

exports.create = function(req, res) {
  Thing.create(req.body, function(err, thing) {
    if(err) { return handleError(res, err); }
    return res.json(201, thing);
  });
};

```

We'd have:

```js

var ThingDAO = require('./thing.dao');

exports.create = function(req, res) 
{
  var _thing = req.body;

  var _onSuccess = function(thing)
  {
       res.status(200).json(thing);
  }

  var _onError = function(error)
  {
       res.status(500).json(error);    
  }

  ThingDAO
     .create(_thing)
     .then(_onSuccess)
     .catch(_onError); 
};

```

And inside my new file (things.dao.js):

```js

var Thing = require('./thing.model');
var Promise = require('bluebird'); // IMO, the best Promise lib out there

exports.create = function(thing)
{
      return new Promise(function(resolve, reject)
      {
             var _onSave = function(error, thing)
             {
                  error ? reject(error)
                        : resolve(thing);
             }

             var _newThing = new Thing(thing);

             _newThing.save(_onSave);
      })
}

```

By doing so, we'd gain a lot. Not only by simplifying the controllers, but making sure each 'layer' of the project really knows how to take care of itself. 

Controllers'll talk to the endpoints and call services, DAOs, models validations and suchs; nothing more.

DAOs will know how to interact with the database. Get data from it, insert data into it, update and delete it. Always returning a [Promise](https://promisesaplus.com/).

By doing so, we could easily chain DAOs that depend on each other for whatever situation, like:

```js

    SomethingDAO
            .getById(id)
            .then(someOtherDAO.doSomethingWithIt)
            .then(whatever.someVerb) 
            .catch(ErrorHandler.handlePossibleException);

```

I'd say if enough people like the idea, we could easily organize a PR and change it as soon as possible.

Let me know if you have any suggestions =]

**Comment by Toub** [comment]
@JaKXz I agree that controllers and services should be isolated.

Services would be easier to test and be reused by other components.

@ericmdantas Could you tell us why this issue has been closed without any comment?

**Comment by ericmdantas** [comment]
@Toub, well, people weren't much interested.

If you feel like brainstorming, I'll gladly reopen it =]

**Comment by ericmdantas** [comment]
Let me just summon some people then:

@kingcody, @Awk34, @DaftMonk, @andrewstuart & @jeffbuhrt.

**Comment by Toub** [comment]
Thanks for replying and let people give a short opinion before to close it.

More generally, it would be nice to always provide a short comment when rejecting an issue.

**Comment by ericmdantas** [comment]
Noted.

**Comment by kingcody** [comment]
@ericmdantas, I really like that separation of logic. I have some very similar (yet slightly different) approaches I use to promisify and separate my controller/api logic.

If you'd like, we could have a collective brain dump and see what kind of cool things come out.

**Comment by ericmdantas** [comment]
@kingcody, I'd love that.

I won't be around this weekend, but feel free to mention me in comments so I can take a look and join the conversation whenever I can.
