### ISSUE TITLE
add no-min-build process to grunt ?

### ISSUE THREAD

**Issue by JoachimR** [angular-fullstack/generator-angular-fullstack#955]
Hi,

I am stuck figuring out what exactly I need to do in order for the 'build' task to produce a functioning 'dist' folder that has however no minfied/uglified code/filenames . 

Does anyone have a grunt task for the generator-angular-fullstack that does this properly?

**Comment by rodriguezmanu** [comment]
I think would be very useful, I'm working on that

**Comment by Awk34** [comment]
what's the use case for this?

**Comment by rodriguezmanu** [comment]
I think you can debug in a env pseudo-prod

**Comment by tomofumikitano** [comment]
https://github.com/yeoman/generator-webapp/issues/463#issuecomment-58881769

This worked for me.

**Comment by rodriguezmanu** [comment]
I've tried https://github.com/yeoman/generator-webapp/issues/463#issuecomment-58881769 but doesn't work correctly, I try to make it work

**Comment by Awk34** [comment]
Closed due to inactivity
