### ISSUE TITLE
Port number shouldn't be hardcoded in template files

### ISSUE THREAD

**Issue by arnauldvm** [angular-fullstack/generator-angular-fullstack#957]
_Gruntfile.js_

See https://github.com/DaftMonk/generator-angular-fullstack/blob/0fee45d47ec174fe8bdfafe4b5e9498ab3140bfe/app/templates/Gruntfile.js#L251 :

            // opens browser on initial server start
            nodemon.on('config:update', function () {
              setTimeout(function () {
                require('open')('http://localhost:=8080/debug?port=5858');
              }, 500);
            });

_karma.conf.js_

See https://github.com/DaftMonk/generator-angular-fullstack/blob/0fee45d47ec174fe8bdfafe4b5e9498ab3140bfe/app/templates/karma.conf.js#L55

    // web server port
    port: 8080,

Especially since 8080 is often used by other software, e.g. local proxy.

**Comment by solastley** [comment]
Is the solution to this as simple as changing to hard-coded port number to process.env.PORT?

**Comment by Awk34** [comment]
@solastley not quite. We're gonna want to keep all these ports (prod, dev, debug) in a centralized location (server/config/environment), and then reference them from elsewhere in the app.
