### ISSUE TITLE
dist images .png corrupt?

### ISSUE THREAD

**Issue by jmbrnrd** [angular-fullstack/generator-angular-fullstack#96]
I'm very much a newbie as far as a full stack approach so please bear with me. I have installed angular-fullstack for the first time, and answered 'y' to all options. Running grunt serve generates a local version perfectly. Great.
However, running 'serve:dist' or 'dist' failed and some searching appeared to point to the imagemin process as a culprit. On this thread https://github.com/gruntjs/grunt-contrib-imagemin/issues/16 Sindre Sorhus suggested updating grunt-contrib-imagemin to fix a similar issue. This update appeared to fix the issue and both 'serve:dist' and 'dist' built successfully.
Unfortunately the 1 .png image used in the demo seems to get corrupted and will not render. Any help would be appreciated?

**Comment by gusta-of** [comment]
Tive o mesmo problema, apenas apaguei a pasta `DIST`e gerei novamente e resolveu
