### ISSUE TITLE
Problem deploying to openshift

### ISSUE THREAD

**Issue by lbilde** [angular-fullstack/generator-angular-fullstack#976]
Hi Daft.

I am getting the following error "Server returned an unexpected error code: 504" when I am trying to do a "yo angular-fullstack:openshift" on a freshly created and build application.
I have had the problem for a week now and I have no clue how to continue!
I tried from 4 different windows machines and my mac.
I made sure the dist folder was there and contained the expected files.
Anyone else have seen this and maybe who have found a solution for it?

Thanks,
Lars.

**Comment by Awk34** [comment]
Closed due to inactivity
