### ISSUE TITLE
Minification steps in assets/fonts leading to error

### ISSUE THREAD

**Issue by ashishbajaj99** [angular-fullstack/generator-angular-fullstack#977]
I have a @font-face declaration in my app.css file that kinda looks like the follows:
```
@font-face {
    font-family:Fantastica;
    src:url(../assets/fonts/fantastica.ttf) format('truetype');
    font-weight:400;
    font-style:normal
}
```
Upon running ```grunt build``` I see that the build system runs a rename of all the assets to help with browser caching here:

```
rev: {
      dist: {
        files: {
          src: [
            '<%= yeoman.dist %>/public/{,*/}*.js',
            '<%= yeoman.dist %>/public/{,*/}*.css',
            '<%= yeoman.dist %>/public/assets/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= yeoman.dist %>/public/assets/fonts/*'
          ]
        }
      }
  },
```
This causes my fonts to get renamed, but the usemin step doesn't seem to be handling fonts correctly. This causes my fonts to not get loaded in the final built version.

**Comment by Awk34** [comment]
Yeah, the minification process doesn't rename assets in css locations. This is also an issue if you try to use a background image in your css. The short-term solution is to just comment out the fonts line in your `rev` task.

**Comment by ashishbajaj99** [comment]
Thanks @Awk34. Do you guys plan to have a long term solution in place? What would be the tentative ETA for this?

**Comment by Awk34** [comment]
I haven't really looked into it, IDK if anyone else has either.

**Comment by ashishbajaj99** [comment]
Ok thanks, will see if I can get to it and submit it as a pull request at some point.

**Comment by tommybananas** [comment]
So if you need background-image url's in css, there is no way to do it unless you move those assets out of the minification phase?

**Comment by riderx** [comment]
you just need to update the grunt file like this in usemin declaration:
`        patterns: {
          js: [
            [/(assets\/images\/.*?\.(?:gif|jpeg|jpg|png|webp|svg))/gm, 'Update the JS to reference our revved images']
          ]
        }`
to ->
`        patterns: {
          css: [
            [/(assets\/images\/.*?\.(?:gif|jpeg|jpg|png|webp|svg))/gm, 'Update the CSS to reference our revved images']
          ],
          js: [
            [/(assets\/images\/.*?\.(?:gif|jpeg|jpg|png|webp|svg))/gm, 'Update the JS to reference our revved images']
          ]
        }`
it's fix the problem for including image in css, i will to see how to fix for font

**Comment by riderx** [comment]
for font i do this :
```javascript
        patterns: {
          css: [
            [/(assets\/images\/.*?\.(?:gif|jpeg|jpg|png|webp|svg))/gm, 'Update the CSS to reference our revved images'],
            [/(assets\/fonts\/.*?\.(?:woff|woff2|ttf))/gm, 'Update the CSS to reference our revved fonts']
          ],
          js: [
            [/(assets\/images\/.*?\.(?:gif|jpeg|jpg|png|webp|svg))/gm, 'Update the JS to reference our revved images']
          ]
        }
```
for make it work you need to put font in the right directory and not call them with relative path
