### ISSUE TITLE
Migrate to "Controller As" syntax

### ISSUE THREAD

**Issue by gad2103** [angular-fullstack/generator-angular-fullstack#984]
In anticipation of $scope going away in angular 2.0, and given that the old way of instantiating controllers in the view layer was an angular 1.2 thing (and considering we're on angular 1.3 heading to 1.4), it might be nice to move over to "Controller As" syntax. Thoughts?

**Comment by mitchellmorris** [comment]
+1 This is a feature that really needs implemented.  It's been a best practice for a while now.

**Comment by michaelpurnell** [comment]
+1 but its easy to change the application to "Controller As"
